agriculturegovau/agds-next

.storybook/main.js
.storybook/preview.tsx

Enable switching Brand colour palettes in Storybook

Add colour palettes to storybook

---

.github/workflows/deploy-docs.yml
.gitignore
docs/components/Navigation/index.tsx
docs/components/mdx/index.ts
docs/components/utils.tsx
docs/package.json
docs/playroom.config.js
docs/playroom/components.js
docs/playroom/frame.js
package.json
yarn.lock

Adds Playroom to the Docs site

Add Playroom

---

.changeset/clean-hats-drop.md
docs/components/PageLayout.tsx
docs/components/SiteFooter.tsx
docs/playroom/components.js
example-site/components/SiteFooter.tsx
packages/ag-branding/README.md
packages/footer/src/Footer.stories.tsx
packages/link-list/src/LinkList.stories.tsx
packages/link-list/src/LinkList.tsx
packages/link-list/src/LinkListGroup.tsx
packages/link-list/src/LinkListItem.tsx
packages/link-list/src/index.tsx

LinkList: Refactor and update spacing

---

.changeset/pink-forks-marry.md
README.md
packages/body/src/index.tsx

Ensure correct line height and spacing for Headings wrapped in Body component.

Body: Implement fontgrid and spacing for Headings

---

.changeset/twenty-clouds-look.md
CONTRIBUTING.md
docs/components/design-system-components.tsx
docs/components/utils.tsx
docs/pages/packages/index.tsx
packages/link-list/src/LinkList.stories.tsx
packages/link-list/src/LinkList.tsx
packages/link-list/src/LinkListItem.tsx

Added some notes on contributing to the repo.
- minor change to the internals of `LinkList`

Notes on Contribution

---

.changeset/clean-hats-drop.md

Update release type for LinkList

---

packages/side-nav/src/SideNav.stories.tsx

Fixes incorrect prop usage in SideNav examples.

Fix prop usage in story

---

.changeset/lazy-rocks-beg.md
packages/button/README.md
packages/button/src/Button.stories.tsx
packages/button/src/Button.tsx
packages/button/src/utils.tsx

Button: Add size prop

---

.changeset/sixty-games-build.md
packages/ag-branding/src/palette.ts
packages/core/src/colors.tsx

AgBranding: Update dark action color

---

.changeset/blue-panthers-look.md
packages/body/README.md
packages/body/src/Body.stories.tsx

Add more detailed examples to documentation.

Body: Add more detailed examples

---

.changeset/chatty-forks-guess.md
docs/components/design-system-components.tsx
docs/playroom/components.js
docs/playroom/snippets.js
packages/columns/CHANGELOG.md
packages/columns/README.md
packages/columns/package.json
packages/columns/src/Column.stories.tsx
packages/columns/src/Column.tsx
packages/columns/src/Columns.tsx
packages/columns/src/index.tsx

This PR adds 2 new components for handling grid layouts:`Columns` and `Column`

Add `Columns` component

---

docs/components/Code.tsx
docs/components/PkgCardList.tsx

docs: Fix broken image on `Cards` page

---

.changeset/mighty-ads-sell.md
docs/README.md
docs/components/PictogramCard.tsx
docs/components/PkgCardList.tsx
docs/components/pictograms/index.tsx
docs/components/pictograms/starter.svg
docs/pages/index.tsx
guides/getting-started.mdx

Updated the design and content of the home page as per designs.

docs: Update home page

---

.changeset/forty-dots-begin.md
packages/footer/README.md
packages/footer/src/Footer.stories.tsx

Footer: Use Columns in Footer examples

---

.changeset/big-fans-shave.md

This is stopping the releases script from finishing

Remove reference to text-link

---

docs/components/DocumentTitle.tsx
docs/pages/404.tsx
docs/pages/guides/[slug].tsx
docs/pages/guides/index.tsx
docs/pages/index.tsx
docs/pages/packages/[group]/[slug].tsx
docs/pages/packages/[group]/index.tsx
docs/pages/packages/index.tsx
docs/pages/releases/[slug].tsx
docs/pages/releases/index.tsx

Note: Please review this PR without whitespaces as I've added a new level of indentation to every page

docs: Add document title to each page

---

releases/2022-02-08.mdx

docs: Add release notes for 2022-02-08

---

.changeset/silent-pants-fly.md
packages/link-list/package.json
packages/link-list/src/LinkListItem.tsx

We can utilise `TextLink` here instead of having a bunch of custom styles.

LinkList: Use `TextLink` in `LinkListItem`

---

.changeset/lazy-pans-pull.md
packages/select/README.md
packages/select/src/Select.stories.tsx
packages/select/src/Select.tsx

Added option groups to `Select` component

Select: Add option groups

---

docs/components/design-system-components.tsx
docs/components/pictograms/index.tsx
docs/components/pictograms/progress-indicator.svg
docs/package.json
docs/playroom/components.js
docs/playroom/snippets.js
packages/progress-indicator/CHANGELOG.md
packages/progress-indicator/README.md
packages/progress-indicator/package.json
packages/progress-indicator/src/ProgressIndicator.stories.tsx
packages/progress-indicator/src/ProgressIndicator.tsx
packages/progress-indicator/src/ProgressIndicatorContainer.tsx
packages/progress-indicator/src/ProgressIndicatorItem.tsx
packages/progress-indicator/src/index.tsx

Add `progress-indicator` package

---

.changeset/tidy-crabs-grin.md
packages/progress-indicator/src/ProgressIndicatorItem.tsx

Fixed issue where border was being removed on hover

ProgressIndicator: Fix active border hover bug

---

.changeset/thin-bats-do.md
packages/main-nav/src/MainNav.tsx
packages/main-nav/src/NavList.tsx
packages/main-nav/src/utils.ts

Fixing an issue were an active secondary link also caused an item from the primary links to also appear active.

MainNav: Fix active secondary link causing active Home link

---

.github/pull_request_template.md

Include photos if necessary.
- For new components...
- - [ ] Add components to Playroom (docs/playroom/components.js)
- - [ ] Add snippits to Playroom (docs/playroom/snippits.js)
- - [ ] Add to Docs for jsx live (docs/components/utils.tsx)

Create Github PR template

---

.changeset/poor-eels-compare.md
packages/ag-branding/README.md

Correction for code snippets in ag-branding readme file.

ag-branding: Minor documentation correction

---

.changeset/dirty-jokes-allow.md
packages/accordion/src/Accordion.stories.tsx

Accordion: Add docs example for expand all

---

.changeset/flat-ravens-sneeze.md
.changeset/popular-deers-sell.md
.changeset/violet-files-kick.md
docs/playroom/snippets.js
example-site/components/SiteHeaderSearch.tsx
packages/breadcrumbs/src/Breadcrumbs.stories.tsx
packages/breadcrumbs/src/Breadcrumbs.tsx
packages/breadcrumbs/src/BreadcrumbsContainer.tsx
packages/breadcrumbs/src/BreadcrumbsItem.tsx
packages/footer/src/Footer.stories.tsx
packages/header/src/Header.stories.tsx
packages/main-nav/src/MainNav.tsx
packages/main-nav/src/NavContainer.tsx
packages/search-box/README.md
packages/search-box/src/SearchBox.tsx
packages/side-nav/src/SideNav.tsx
packages/side-nav/src/SideNavContainer.tsx
packages/skip-link/src/SkipLinkContainer.tsx
packages/skip-link/src/SkipLinks.stories.tsx
packages/skip-link/src/SkipLinks.tsx

- [] Add necessary tests
- [] Write documentation (README.md)
- [] Create stories for Storybook

Ensured consistent API of `aria-label`

---

.changeset/twenty-ads-design.md
packages/card/src/CardLink.tsx

Fixes an issue that was introduced accidentally in #158

CardLink: Fixed positioning bug

---

.changeset/violet-experts-repair.md
packages/progress-indicator/src/ProgressIndicatorItem.tsx

Updated border width of the active item as per design feedback.

ProgressIndicator: Updated border width of the active item

---

.changeset/sour-mirrors-guess.md
packages/body/src/Body.tsx

Body: Adjust margin for H3s

---

.changeset/wild-trains-hunt.md
packages/main-nav/src/MainNavLink.tsx

Fixes an inconstancy  between `MainNavButton` and `MainNavLInk`

MainNav: Added pointer cursor to `MainNavButton`

---

.changeset/odd-meals-sing.md
packages/main-nav/src/MainNavLink.tsx
packages/progress-indicator/src/ProgressIndicator.stories.tsx
packages/progress-indicator/src/ProgressIndicator.tsx
packages/progress-indicator/src/ProgressIndicatorItem.tsx

The `ProgressIndicator` component needs to work for both links and buttons.

ProgressIndicator: Allow `button` elements to be rendered

---

.github/workflows/deploy-docs.yml

Build example before building docs

Build example before building docs

---

.changeset/khaki-queens-hear.md
docs/components/design-system-components.tsx
docs/package.json
docs/playroom/components.js
docs/playroom/snippets.js
packages/fieldset/CHANGELOG.md
packages/fieldset/README.md
packages/fieldset/package.json
packages/fieldset/src/Fieldset.stories.tsx
packages/fieldset/src/Fieldset.tsx
packages/fieldset/src/FieldsetContainer.tsx
packages/fieldset/src/FieldsetLegend.tsx
packages/fieldset/src/index.tsx
packages/text/src/Text.tsx

Add new `fieldset` package

---

.changeset/ten-mangos-pay.md
packages/inpage-nav/src/InpageNav.tsx

This PR brings this component more inline with how other components handle aria-labels.

InpageNav: Add `aria label` prop

---

.changeset/bright-spiders-doubt.md
.changeset/popular-rice-serve.md
example-site/components/FormExampleMultiStep.tsx
example-site/components/FormExampleSinglePage.tsx
packages/fieldset/README.md
packages/fieldset/package.json
packages/fieldset/src/Fieldset.stories.tsx
packages/fieldset/src/Fieldset.tsx
packages/fieldset/src/FieldsetHint.tsx
packages/fieldset/src/FieldsetLegend.tsx
packages/fieldset/src/index.tsx

Improved modularity of API replacing the `legendAsPageHeading` prop with composable legends and hints.
New API
```tsx
<Fieldset
legend={<H1>What is your date of birth?</H1>}
hint={<Text fontSize="md" color="muted">We will only use this to respond to your requests</Text>}
/>
```

Fieldset: Improve API

---

.changeset/clean-suits-exist.md
packages/direction-link/src/DirectionLink.tsx
packages/main-nav/src/MainNavItem.tsx
packages/progress-indicator/src/ProgressIndicatorItem.tsx

We are currently using `forwardRefWithAs` incorrectly in a couple of comments, which is resulting in some error logs during development.

Update usage of `forwardRefWithAs`

---

.storybook/main.js
package.json
yarn.lock

Adds the ie11 storybook addon so that we can view our stories in ie11.

Add ie11 storybook addon

---

.changeset/tall-timers-applaud.md
packages/callout/README.md
packages/callout/src/Callout.stories.tsx

Using a P tag, rather than span, in our Callout component to match GOLD.

Callout: Use paragraphs tags in examples

---

.changeset/great-terms-exist.md
packages/main-nav/src/NavList.tsx

Added `aria-current="page"` to active nav item

MainNav: Add aria-current page

---

.changeset/orange-seahorses-behave.md
packages/keyword-list/src/KeywordListItem.tsx

Update color as per design feedback.

KeywordList: Update sub title color

---

.changeset/hip-berries-share.md
docs/components/PageLayout.tsx
example-site/pages/content.tsx
example-site/pages/form-multi-step.tsx

---------- | ----------- |
| <img width="497" alt="Screen Shot 2022-03-08 at 10 02 30 am" src="https://user-images.githubusercontent.com/6265154/157139265-f7c01c4c-e22c-4d29-9b85-972de6118b19.png"> |<img width="497" alt="Screen Shot 2022-03-08 at 10 03 06 am" src="https://user-images.githubusercontent.com/6265154/157139214-0e35d455-07be-400f-b251-f6e1f468f9d8.png">|

docs,example-site: Fixed layout issue on mobile

---

.changeset/sour-lions-buy.md
packages/accordion/src/Accordion.tsx
packages/accordion/src/AccordionItem.tsx
packages/accordion/src/AccordionTitle.tsx

Updated UI to reflect latest designs

Accordion: Update UI design

---

.changeset/old-pans-fail.md
.changeset/red-singers-jam.md
packages/core/src/utils/index.ts
packages/core/src/utils/useWindowSize.ts
packages/side-nav/src/SideNav.tsx

Added `aria-hidden` to collapsable content

SideNav: Added `aria-hidden` to collapsable content

---

.changeset/swift-ducks-shave.md
packages/tags/src/Tag.tsx

Added hover state to tags with links

Tags: Apply design feedback

---

.changeset/pretty-nails-peel.md
packages/accordion/README.md
packages/accordion/src/Accordion.stories.tsx
packages/accordion/src/AccordionItem.tsx
packages/accordion/src/AccordionTitle.tsx

- Added hover styles
- Increased content padding 
- Updated controlled documentation

Accordion: Apply design feedback

---

.changeset/lovely-crabs-add.md
.changeset/new-cycles-invent.md
.changeset/smart-dryers-teach.md
docs/components/PageLayout.tsx
docs/components/design-system-components.tsx
example-site/pages/index.tsx
packages/card/src/Card.tsx
packages/content/README.md
packages/content/package.json
packages/content/src/Content.tsx
packages/content/src/ContentBleed.tsx
packages/content/src/context.ts
packages/content/src/index.ts
packages/content/src/utils.ts
packages/core/src/boxPalette.ts
packages/core/src/goldTheme.ts
packages/core/src/theme.tsx
packages/core/src/tokens.ts
packages/side-nav/package.json
packages/side-nav/src/SideNav.tsx
packages/side-nav/src/SideNavCollapseButton.tsx
packages/side-nav/src/SideNavContainer.tsx
packages/side-nav/src/SideNavGroup.tsx
packages/side-nav/src/SideNavLink.tsx
packages/side-nav/src/SideNavTitle.tsx
packages/side-nav/src/utils.ts

SideNav: Apply new designs

---

.changeset/tame-weeks-return.md
packages/body/README.md
packages/body/src/Body.stories.tsx
packages/body/src/Body.tsx

Body: Removed margins from blockquote elements

---

.changeset/itchy-meals-visit.md
packages/icon/README.md

The current documentation refers the old API.

Icon: Update documentation

---

.changeset/khaki-schools-appear.md
packages/select/README.md

Currently the grouped example is disabled by default.

Select: Update documentation

---

guides/getting-started.mdx
guides/index.mdx

Update Content for Development Getting Started guide.

Add Getting Started guide

---

.changeset/early-dots-tie.md
.changeset/little-lobsters-flash.md
docs/components/design-system-components.tsx
docs/package.json
docs/playroom/components.js
docs/playroom/snippets.js
example-site/components/Divider.tsx
example-site/components/FormExampleMultiStep.tsx
example-site/components/FormExampleSignIn.tsx
example-site/components/FormExampleSinglePage.tsx
example-site/package.json
packages/form-stack/CHANGELOG.md
packages/form-stack/README.md
packages/form-stack/package.json
packages/form-stack/src/FormStack.tsx
packages/form-stack/src/index.tsx

Contains a single component `FormStack`

Create new `form-stack` package

---

.changeset/warm-buckets-begin.md
docs/components/SiteFooter.tsx
docs/pages/index.tsx

Docs: Add CTA link for Getting Started

---

.changeset/six-ducks-promise.md
packages/task-list/README.md
packages/task-list/src/TaskList.stories.tsx
packages/task-list/src/TaskListItem.tsx

TaskList: Updated styles based on design feedback

---

.changeset/ninety-dodos-remain.md
.changeset/orange-chicken-remain.md
docs/playroom/snippets.js
packages/fieldset/README.md
packages/fieldset/src/Fieldset.stories.tsx
packages/form-stack/src/FormStack.tsx

Changed default spacing between form elements from 1.5rem to 2rem

FormStack: Update spacing value

---

.changeset/nervous-poets-breathe.md
guides/getting-started.mdx

Add more information to getting started guide

Docs: Add more information to getting started guide

---

.changeset/mean-pets-film.md
packages/ag-branding/README.md
packages/core/README.md

Core, Branding: Update documentation

---

.changeset/smooth-zoos-camp.md
.storybook/main.js
package.json
yarn.lock

docs: Remove storybook ie11 addon

---

.storybook/preview.tsx

Default to `agriculture` instead of `gold`

Update storybook default theme

---

.changeset/moody-parents-eat.md
guides/forms.mdx
guides/index.mdx

docs: Add forms guide

---

.changeset/few-pandas-live.md
packages/side-nav/src/SideNav.tsx
packages/side-nav/src/SideNavCollapseButton.tsx
packages/side-nav/src/SideNavContainer.tsx
packages/side-nav/src/utils.ts

Updated hover state colours as per design feedback.

SideNav: Update hover state colours

---

.changeset/short-actors-argue.md
packages/footer/package.json
packages/header/package.json

Header,Footer: Removed unused dependencies

---

.changeset/moody-pandas-brush.md
packages/page-alert/src/PageAlert.tsx

PageAlert: Update PageAlert padding

---

.changeset/early-snakes-drop.md
example-site/components/FormExampleSinglePage.tsx
example-site/package.json

Example-site: Add PageAlert to form example

---

.changeset/kind-spoons-marry.md
packages/card/src/CardFooter.tsx
packages/card/src/CardHeader.tsx
packages/card/src/CardInner.tsx

Adjust CardInner, CardHeader and CardFooter spacing from 1em to 1.5em.

Card: Update inner padding

---

.changeset/tiny-cheetahs-travel.md
packages/progress-indicator/src/ProgressIndicatorItem.tsx

ProgressIndicator: Update `todo` status label

---

.changeset/shy-countries-prove.md
packages/select/src/Select.tsx

Updated icon size from `md` to `sm`

Select: Update icon size

---

.changeset/fast-steaks-accept.md
packages/card/README.md
packages/card/src/Card.stories.tsx

Card: document compositions

---

releases/2022-03-23.mdx

Release notes for 23rd March 2022 release

Add release notes

---

releases/2022-03-16.mdx
releases/2022-03-23.mdx

These release notes were included in the version packages PR, but were not included in the release notes

Release 2022-03-16: Add accordion release notes

---

.changeset/popular-bats-tap.md
packages/date-picker/src/CalendarContainer.tsx

Increased border radius for start and end dates

DatePicker: Update range styles

---

.changeset/proud-queens-sniff.md
packages/button/src/Button.stories.tsx
packages/icon/src/Icon.stories.tsx
packages/icon/src/example.tsx
packages/icon/src/index.ts
packages/icon/src/utils.tsx

Button: Show icons in stories

---

.changeset/green-donuts-sort.md
docs/components/design-system-components.tsx
docs/playroom/components.js
packages/modal/README.md
packages/modal/package.json
packages/modal/src/Modal.stories.tsx
packages/modal/src/Modal.tsx
packages/modal/src/ModalButtonGroup.tsx
packages/modal/src/ModalCover.tsx
packages/modal/src/ModalPanel.tsx
packages/modal/src/ModalTitle.tsx
packages/modal/src/index.tsx
packages/modal/src/utils.tsx

Add Modal component

---

.changeset/bright-dogs-sort.md
example-site/pages/form-multi-step.tsx
packages/progress-indicator/README.md
packages/progress-indicator/package.json
packages/progress-indicator/src/ProgressIndicator.stories.tsx
packages/progress-indicator/src/ProgressIndicator.tsx
packages/progress-indicator/src/ProgressIndicatorCollapseButton.tsx
packages/progress-indicator/src/ProgressIndicatorContainer.tsx
packages/progress-indicator/src/ProgressIndicatorHeading.tsx
packages/progress-indicator/src/ProgressIndicatorItem.tsx
packages/progress-indicator/src/ProgressIndicatorList.tsx
packages/progress-indicator/src/index.tsx

ProgressIndicator: Update mobile styles

---

.changeset/lazy-bears-smash.md
.changeset/swift-starfishes-work.md
packages/control-input/src/Checkbox.tsx
packages/control-input/src/CheckboxIndicator.tsx
packages/control-input/src/ControlContainer.tsx
packages/control-input/src/ControlInput.tsx
packages/control-input/src/Radio.tsx
packages/control-input/src/RadioIndicator.tsx
packages/core/src/packs.ts

Changes based off latest designs.

ControlInput: Update sizes and invalid/valid states

---

.changeset/silver-tables-promise.md
packages/select/src/Select.tsx

Updated the select indicator icon colour in dark mode as per latest designs.

Select: Update icon color 

---

.changeset/lucky-geckos-jog.md
example-site/components/FormExampleSinglePage.tsx
packages/control-input/src/ControlGroup.stories.tsx
packages/control-input/src/ControlGroup.tsx

- Updated spacing between each control
- Updating spacing between the set of controls and the label/hint/message
- Updated stories to show invalid states

ControlGroup: Update spacing of elements

---

.changeset/healthy-crews-smoke.md
packages/control-input/src/ControlGroup.tsx

ControlGroup: Increased gap between control group children and label

---

.changeset/cuddly-actors-speak.md
packages/main-nav/src/MenuButtons.tsx
packages/main-nav/src/NavContainer.tsx

Adding 'modal' treatment to mobile MainNav, to improve accessibility for screenreader users

MainNav: screenreader improvements

---

guides/getting-started.mdx

Updating Getting Started guide to guide users starting a new project to use the Starter kit.

Add Instructions for using starter kit to start a new project

---

guides/index.mdx
guides/responsive-props.mdx

Add responsive props guide

---

.changeset/gorgeous-items-study.md
packages/modal/src/Modal.tsx
packages/modal/src/ModalCover.tsx

Prevented the body from being scrollable while modal is open

Modal: Prevent body scrolling

---

.changeset/modern-badgers-whisper.md
packages/modal/src/Modal.stories.tsx
packages/modal/src/ModalCover.tsx
packages/modal/src/ModalPanel.tsx

Also includes some minor A11y improvements

Modal: Improve Mobile styles

---

.changeset/many-baboons-wave.md
packages/accordion/README.md
packages/accordion/src/Accordion.stories.tsx
packages/accordion/src/Accordion.tsx
packages/accordion/src/AccordionBody.tsx
packages/progress-indicator/src/ProgressIndicator.tsx
packages/side-nav/src/SideNav.tsx

Update animations to apply `display: none` or `display: hidden` which will improve the accessibility of these components.

Accordion,SideNav,ProgressIndicator: Updated height animation logic to improve accessibility

---

.changeset/healthy-crabs-tickle.md
packages/progress-indicator/src/ProgressIndicatorCollapseButton.tsx

Updated hover styles for mobile collapsible title

ProgressIndicator: Updated hover styles

---

.changeset/curvy-rabbits-invent.md
packages/date-picker/package.json
packages/date-picker/src/Calendar.tsx
packages/date-picker/src/DatePicker.stories.tsx
packages/date-picker/src/DatePicker.tsx
packages/date-picker/src/DateRangePicker.stories.tsx
packages/date-picker/src/DateRangePicker.tsx

- `DateRangePicker` only shows 1 month in mobile
- Calendar now closes when the escape key is pressed
- Improved focus management

DatePicker: Improve mobile UI and focus management

---

.changeset/spotty-cups-confess.md
packages/ag-branding/src/Logo.tsx

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/img_role#svg_and_roleimg

Branding: Add aria tags to `Logo`

---

.changeset/dry-oranges-jump.md
docs/components/SiteFooter.tsx

Docs: Add welcome to country

---

.changeset/funny-roses-fly.md
.changeset/honest-games-do.md
.changeset/pink-bikes-cheer.md
docs/components/design-system-components.tsx
docs/package.json
docs/playroom/components.js
docs/playroom/snippets.js
packages/button/README.md
packages/button/src/Button.stories.tsx
packages/button/src/Button.tsx
packages/button/src/styles.tsx
packages/loading/CHANGELOG.md
packages/loading/README.md
packages/loading/package.json
packages/loading/src/LoadingBlanket.stories.tsx
packages/loading/src/LoadingBlanket.tsx
packages/loading/src/LoadingDots.stories.tsx
packages/loading/src/LoadingDots.tsx
packages/loading/src/index.tsx
packages/skip-link/src/SkipLinkItem.tsx

Add new `loading` package

---

.changeset/eight-jars-design.md
packages/main-nav/src/NavContainer.tsx

MainNav: Remove data attributes for style overrides

---

.changeset/ninety-elephants-drop.md
packages/loading/src/LoadingBlanket.stories.tsx
packages/loading/src/LoadingBlanket.tsx
packages/loading/src/LoadingBlanketContainer.tsx
packages/loading/src/LoadingBlanketContent.tsx
packages/loading/src/LoadingBlanketLabel.tsx
packages/loading/src/LoadingDots.tsx
packages/loading/src/index.tsx

This PR makes it easier to compose the `LoadingBlanket` component, for example:
```tsx
<LoadingBlanketContainer fullScreen>
<LoadingBlanketContent>
<LoadingDots aria-label="loading" role="status" size="lg" />
<LoadingBlanketLabel>Loading</LoadingBlanketLabel>
</LoadingBlanketContent>
</LoadingBlanketContainer>
```

Loading: Improve modularity of `LoadingBlanket`

---

.changeset/moody-pants-doubt.md
packages/table/src/Table.tsx

Resolve warning from Emotion in development mode [215179](https://dev.azure.com.mcas.ms/agriculturegovau/Digital%20Services/_workitems/edit/215179)
Replace `nth-last-child` selector with `nth-last-of-type`

Table: Fix emotion warning

---

.changeset/silly-beans-glow.md
packages/hero-banner/src/HeroBanner.stories.tsx
packages/hero-banner/src/HeroBanner.tsx
packages/hero-banner/src/HeroBannerBackground.tsx
packages/hero-banner/src/HeroBannerContainer.tsx
packages/hero-banner/src/HeroBannerContent.tsx
packages/hero-banner/src/HeroBannerMobileImage.tsx
packages/hero-banner/src/HeroBannerTitle.tsx
packages/hero-banner/src/index.tsx
packages/hero-banner/src/utils.ts

- Updated padding of content
- Improved modularity of component

HeroBanner: Update padding and improve modularity

---

.changeset/khaki-balloons-fold.md
.changeset/long-cheetahs-appear.md
.changeset/seven-squids-approve.md
packages/box/src/styles.ts
packages/card/src/Card.tsx
packages/card/src/CardFooter.tsx
packages/card/src/CardHeader.tsx
packages/card/src/CardInner.tsx
packages/card/src/CardLink.tsx
packages/side-nav/src/SideNavGroup.tsx
packages/side-nav/src/SideNavLink.tsx
packages/table/src/TableCell.tsx
packages/table/src/TableHead.tsx
packages/table/src/TableHeader.tsx

Add `borderColor` prop to `Box`  and updated usage.

Box: Add `borderColor` and update usage

---

.changeset/khaki-months-sin.md
packages/accordion/package.json
packages/accordion/src/AccordionBody.tsx
packages/accordion/src/AccordionTitle.tsx
packages/call-to-action/package.json
packages/call-to-action/src/CallToAction.tsx
packages/loading/package.json
packages/loading/src/LoadingDots.tsx
packages/modal/package.json
packages/modal/src/ModalPanel.tsx
packages/progress-indicator/package.json
packages/progress-indicator/src/ProgressIndicator.tsx
packages/progress-indicator/src/ProgressIndicatorCollapseButton.tsx
packages/side-nav/package.json
packages/side-nav/src/SideNav.tsx
packages/side-nav/src/SideNavCollapseButton.tsx
yarn.lock

Reduces the amount of dependencies

Replace `react-spring` with `@react-spring/web`

---

.changeset/twelve-ducks-look.md
docs/lib/mdxUtils.ts
docs/pages/releases/[slug].tsx
releases/2022-01-05.mdx
releases/2022-01-07.mdx
releases/2022-01-24.mdx
releases/2022-02-08.mdx
releases/2022-02-23.mdx
releases/2022-03-02.mdx
releases/2022-03-03.mdx
releases/2022-03-16.mdx
releases/2022-03-23.mdx
releases/2022-04-01.mdx
releases/2022-04-28.mdx

Docs: Remove `type` from releases

---

.changeset/loud-needles-unite.md
docs/components/Code.tsx

Also removed the `reset` button

Docs: Add open in playroom link

---

.changeset/afraid-crabs-tease.md
packages/hero-banner/src/HeroBannerContent.tsx

Updated padding in `HeroBannerContent` to fix content alignment issue

HeroBanner: Update padding

---

docs/components/Code.tsx

docs: Update playroom URL

---

docs/components/Code.tsx

This should have been part of #320

docs: Update copy code button alignment

---

guides/getting-started.mdx

Reference example site in the Getting Started guide.

Getting started: Link to examples

---

.changeset/wise-goats-roll.md
docs/playroom/components.js

As it says on the tin.
```jsx
```

Docs: Add `mq` support to Playroom

---

.changeset/famous-pugs-hear.md
.changeset/fifty-planes-smell.md
example-site/components/FormExampleSinglePage.tsx
packages/page-alert/src/PageAlert.tsx

Improved a11y of single page form error state

PageAlert: Improve focus management

---

packages/file-upload/README.md
releases/2022-05-16.mdx

16th May, 2022 release

---

.changeset/friendly-clouds-talk.md
.changeset/nervous-experts-scream.md
packages/button/src/Button.tsx
packages/file-upload/src/FileUpload.tsx

- Fixes the file upload "select files" button from submitting the form
- Updated the `button` component so this doesn't happen again

Button,FileUpload: Add default `type`

---

.changeset/popular-planets-burn.md
packages/secondary-nav/src/SecondaryNavContainer.tsx
packages/secondary-nav/src/SecondaryNavList.tsx
packages/secondary-nav/src/SecondaryNavListItem.tsx

Fixes UI issue when last item is active. Screenshot of fix

SecondaryNav: Fix border issue

---

docs/components/Code.tsx

docs: fix flex wrapping of code example actions

---

.changeset/olive-hounds-rhyme.md
.changeset/thin-worms-notice.md
docs/components/TemplateLayout.tsx
example-site/components/FormExampleMultiStep/FormExampleMultiStep.tsx
example-site/components/FormExampleMultiStep/FormExampleMultiStep0.tsx
example-site/components/FormExampleMultiStep/FormExampleMultiStep1.tsx
example-site/components/FormExampleMultiStep/FormExampleMultiStep2.tsx
example-site/components/FormExampleMultiStep/FormExampleMultiStep3.tsx
example-site/components/FormExampleMultiStep/FormExampleMultiStep4.tsx
example-site/components/FormExampleMultiStep/FormExampleMultiStepActions.tsx
example-site/components/FormExampleMultiStep/FormExampleMultiStepContainer.tsx
example-site/components/FormExampleMultiStep/FormExampleMultiStepFieldset.tsx
example-site/pages/form-multi-step/form.tsx
example-site/pages/form-multi-step/index.tsx
packages/fieldset/README.md
packages/fieldset/src/Fieldset.tsx
packages/fieldset/src/FieldsetContainer.tsx
packages/fieldset/src/FieldsetContent.tsx
packages/fieldset/src/FieldsetHint.tsx
packages/fieldset/src/index.tsx

Aligned multi step form with latest designs
Updated fieldset component so `<legend>` is always the first child of `<fieldset>`

example-site: Improve multi page form

---

docs/components/TemplateLayout.tsx
docs/pages/packages/[group]/[slug].tsx

docs: Update page title component

---

.changeset/mean-files-vanish.md
packages/text/src/TextLinkExternal.tsx

Text: Fix wrapping of `TextLinkExternal`

---

.changeset/clean-papayas-bow.md
.changeset/mighty-hounds-check.md
docs/pages/404.tsx
docs/pages/index.tsx
example-site/pages/404.tsx
example-site/pages/index.tsx
packages/content/src/Content.tsx
packages/content/src/ContentBleed.tsx
packages/content/src/context.ts
packages/hero-banner/src/HeroBannerContent.tsx
packages/hero-banner/src/HeroBannerTitle.tsx

Reverts steelthreads/agds-next#355

Revert "Content: Remove `size` prop"

---

.changeset/fifty-tables-cheat.md
docs/pages/index.tsx

Use the design system `HeroBanner` component on the documentation website

docs: Use `HeroBanner` on home page

---

.changeset/nervous-boats-remain.md
example-site/components/FormDivider.tsx
example-site/components/FormExampleMultiStep/FormExampleMultiStepActions.tsx
example-site/components/FormExampleSinglePage.tsx
example-site/pages/form-single-page.tsx

Update design for single-page multi-question form

Example-site: New single-page form

---

.changeset/bright-gorillas-collect.md
packages/hero-banner/src/HeroBanner.stories.tsx
packages/hero-banner/src/HeroBannerContent.tsx
packages/hero-banner/src/HeroBannerImage.tsx
packages/hero-banner/src/HeroBannerTitle.tsx

- Updated gradient direction to `90deg` to ensure the gradient always covers the image
- Improved width of content when no image is supplied

HeroBanner: Update gradient and max width

---

.changeset/sixty-points-swim.md
packages/fieldset/src/FieldsetContent.tsx

Fieldset: Adjust FieldsetContent marginTop

---

.changeset/cuddly-pears-juggle.md
.storybook/stories/kitchenSink.tsx
docs/components/PageLayout.tsx
docs/components/PageTitle.tsx
docs/components/TemplateLayout.tsx
docs/pages/404.tsx
docs/pages/guides/[slug].tsx
docs/pages/index.tsx
docs/pages/packages/[group]/[slug].tsx
docs/pages/releases/[slug].tsx
docs/pages/releases/index.tsx
docs/pages/templates/index.tsx
docs/playroom/snippets.js
example-site/components/FormExampleMultiStep/FormExampleMultiStep.tsx
example-site/components/PageTitle.tsx
example-site/pages/404.tsx
example-site/pages/content.tsx
example-site/pages/form-multi-step/index.tsx
example-site/pages/form-sign-in.tsx
example-site/pages/form-single-page.tsx

Adjusted content spacing as per design feedback.

docs/example: update spacing 

---

.changeset/brown-clouds-sniff.md
packages/modal/src/ModalPanel.tsx

Modal: Add aria-label to close button

---

docs/pages/templates/[slug]/index.tsx
docs/pages/templates/index.tsx
example-site/components/AppLayout.tsx

**Waiting for content.**
Also, remove alt tags from presentation images.

Example-site: Activate template banners

---

packages/body/README.md
packages/body/src/Body.stories.tsx
packages/body/src/Body.tsx

Body: Adjust styles for blockquotes

---

example-site/components/ArticleCard.tsx

Example: Add presentation role to card images

---

.changeset/thirty-hotels-study.md
packages/content/src/utils.ts

Increase padding on mobile for `lg` variant

Content: Update padding on mobile for `lg` variant

---

packages/text/src/Text.stories.tsx
packages/text/src/TextLink.stories.tsx
packages/text/src/TextLinkExternal.stories.tsx

Add stories for TextLink and TextLinkExternal

Text: Add stories for `TextLink` and `TextLinkExternal`

---

example-site/components/FormExampleMultiStep/FormExampleMultiStep0.tsx
example-site/components/FormExampleSinglePage.tsx

example-site: Fix small typo and wrap footer divider

---

.changeset/cyan-meals-dress.md

Update core changeset 

---

example-site/components/FormExampleMultiStep/FormExampleMultiStep.tsx
example-site/components/FormExampleMultiStep/FormExampleMultiStepContainer.tsx
example-site/components/SiteHeader.tsx
example-site/pages/form-multi-step/index.tsx
example-site/pages/form-single-page.tsx
packages/field/README.md
templates/single-page-form/index.mdx

Ensured consistency of  of `Multi-step form` and `Single-page form`

docs/example: Fix single page and multi page typos

---

docs/components/SiteFooter.tsx
example-site/components/SiteFooter.tsx

Implement feedback from a11y audit.

docs/example: Add aria-label to footer nav

---

example-site/pages/index.tsx

Fixes home page wrapping weirdly on mobile.

example: Fix home page on mobile

---

templates/home/index.mdx
templates/single-page-form/index.mdx

- Remove references to .au-body css classes, which only exist in GOLD
- Add reference to 'multi-question' in single-page form

Template content tweak

---

.changeset/cool-cows-carry.md
packages/date-picker/src/Calendar.stories.tsx
packages/date-picker/src/Calendar.tsx
packages/date-picker/src/CalendarContainer.tsx
packages/date-picker/src/CalendarNavBar.tsx
packages/date-picker/src/DatePicker.stories.tsx
packages/date-picker/src/DatePicker.tsx
packages/date-picker/src/DatePickerInput.tsx
packages/date-picker/src/DateRangePicker.stories.tsx
packages/date-picker/src/DateRangePicker.tsx

Fixed bug where the text input would not reflect the `value` prop. Added some stories so that we can test this scenario in the future easier.

date-picker: Fix bug when `value` changes

---

packages/hero-banner/README.md
packages/hero-banner/src/HeroCategoryBanner/HeroCategoryBanner.stories.tsx

HeroBanner: Small storybook issues

---

.changeset/ten-baboons-join.md
packages/content/src/utils.ts

Adjust mobile padding values in `SectionContent`

Content: Adjust mobile padding

---

.changeset/ten-numbers-buy.md
packages/hero-banner/src/HeroBanner/HeroBannerContent.tsx
packages/hero-banner/src/HeroCategoryBanner/HeroCategoryBannerContent.tsx
packages/hero-banner/src/HeroSubcategoryBanner/HeroSubcategoryBannerContent.tsx

Adjust mobile padding values in `HeroBanner`, `HeroCategoryBanner` and `HeroSubcategoryBanner`

HeroBanner: Adjust mobile spacing

---

example-site/components/FormExampleMultiStep/FormExampleMultiStep.tsx
example-site/components/FormExampleMultiStep/FormExampleMultiStep0.tsx
example-site/components/FormExampleMultiStep/FormExampleMultiStep1.tsx
example-site/components/FormExampleMultiStep/FormExampleMultiStep2.tsx
example-site/components/FormExampleMultiStep/FormExampleMultiStep3.tsx
example-site/components/FormExampleMultiStep/FormExampleMultiStep4.tsx
example-site/components/FormExampleMultiStep/FormExampleMultiStepActions.tsx
example-site/components/FormExampleSinglePage.tsx
example-site/pages/category/subcategory/form-multi-step/index.tsx

Fixes some spacing issues in the single page and multi page form.

example-site: Update spacing in forms

---

example-site/components/DefinitionList.tsx
example-site/components/FormExampleMultiStep/FormExampleMultiStep4.tsx

example-site: Use DefinitionList in multi-step form summary

---

.changeset/six-drinks-pump.md
.eslintrc.js
.github/workflows/test.yml
package.json
packages/control-input/src/RadioIndicator.tsx
packages/core/src/utils/forwardRefWithAs.ts
packages/date-picker/src/DateRangePicker.tsx
packages/footer/src/FooterDivider.tsx
packages/header/src/Header.stories.tsx
packages/progress-indicator/src/ProgressIndicatorCollapseButton.tsx
packages/table/src/TableCell.tsx
yarn.lock

At the moment we are not performing any eslint checks to files inside the `packages` folder. This must have been missed early on. Luckily, we do not have many eslint warnings/errors inside this folder, mainly just unused vars.

Lint package files

---

.github/workflows/deploy-docs.yml
.github/workflows/release.yml
.github/workflows/test.yml

Upgrade our github actions from v2 to v3

Upgrade github actions to v3

---

.changeset/silent-pets-dress.md
packages/page-alert/src/PageAlertTitle.tsx

PageAlert: Update title font size

---

packages/body/src/Body.stories.tsx
packages/loading/src/LoadingBlanket.stories.tsx
packages/skip-link/src/SkipLinks.stories.tsx

Fixes an error `React is not defined` as we haven't specified fragments in storybook.

Fix storybook crashing when using fragments

---

.changeset/good-hairs-breathe.md
packages/accordion/package.json
packages/call-to-action/package.json
packages/loading/package.json
packages/modal/package.json
packages/progress-indicator/package.json
packages/side-nav/package.json
yarn.lock

Upgraded to version 9.4.5 of `@react-spring/web` as it oficially supports react 18 strict mode. [See react spring release notes here](https://github.com/pmndrs/react-spring/releases)

Upgrade react spring

---

.changeset/quiet-brooms-switch.md
packages/call-to-action/README.md
packages/call-to-action/src/CallToAction.stories.tsx

Moved group in documentation site / storybook from `content` to `navigation`

call-to-action: Update docs group

---

packages/call-to-action/README.md
packages/content/README.md

Fixes for `content` and `call-to-action` packages.

Update broken storybook path links

---

.changeset/loud-tigers-worry.md
packages/task-list/README.md
packages/task-list/src/TaskList.stories.tsx
packages/task-list/src/TaskList.tsx
packages/task-list/src/TaskListItem.tsx

Added the ability the forward refs and use the as prop

task-list: Use `forwardRefWithAs`

---

.changeset/dull-feet-burn.md
example-site/components/FormExampleMultiStep/FormExampleMultiStep1.tsx
packages/file-upload/README.md
packages/file-upload/package.json
packages/file-upload/src/FileUpload.stories.tsx
packages/file-upload/src/FileUpload.tsx
packages/file-upload/src/FileUploadFile.tsx
packages/file-upload/src/utils.tsx

- Support visual indication that a selected file is uploading
- Add Storybook for uploading a file on drop
- Add Storybook for uploading a single file on submit

FileUpload: Show files uploading and success

---

packages/secondary-nav/README.md

Updating to sentence case to be more consistent with our other packages.

Update side nav title

---

.changeset/gentle-llamas-turn.md
packages/progress-indicator/src/ProgressIndicator.tsx
packages/task-list/src/TaskList.tsx

progress-indicator/task-list: Improve list types

---

.changeset/four-jars-accept.md
packages/button/src/Button.tsx

Added abilty to pass refs to `ButtonLink`

button: Wrap `ButtonLink` in `forwardRef`

---

.changeset/empty-chicken-crash.md
.storybook/stories/kitchenSink.tsx
docs/components/TemplateLayout.tsx
docs/components/design-system-components.tsx
docs/pages/index.tsx
docs/playroom/components.js
docs/playroom/snippets.js
example-site/pages/index.tsx
packages/call-to-action/README.md
packages/call-to-action/src/CallToAction.stories.tsx
packages/call-to-action/src/CallToAction.tsx

This reverts commit 2dd2e3282596010b7b1bd645acd26348a539d182.

Revert "call-to-action: Use `forwardRefWithAs` (#434)"

---

.changeset/plenty-elephants-cover.md
docs/components/design-system-components.tsx
docs/playroom/components.js
example-site/components/FormExampleMultiStep/FormExampleMultiStep.tsx
packages/direction-link/README.md
packages/direction-link/src/DirectionLink.stories.tsx
packages/direction-link/src/DirectionLink.tsx

Revert "direction-link: Use `forwardRefWithAs` (#438)"
This reverts commit 8f4e3e00dc1037a8d910abd8982d994765bb91a9.

Revert "direction-link: Use `forwardRefWithAs` (#438)"

---

docs/components/design-system-components.tsx
docs/playroom/components.js
example-site/components/FormExampleMultiStep/FormExampleMultiStep4.tsx
packages/button/src/BaseButton.tsx
packages/text-link/README.md
packages/text-link/package.json
packages/text-link/src/TextLink.stories.tsx
packages/text-link/src/TextLink.tsx

text-link: Remove `forwardRefWithAs`

---

.changeset/cyan-avocados-kneel.md
packages/call-to-action/src/CallToAction.tsx
packages/main-nav/src/MainNavItem.tsx

Update link types after change in `Core`

call-to-action/main-nav: Update types

---

.changeset/silly-mugs-eat.md
example-site/components/FormExampleMultiStep/FormExampleMultiStep1.tsx
example-site/components/FormExampleMultiStep/FormExampleMultiStep4.tsx
packages/file-upload/src/FileUpload.tsx

- Add default value to `FileUpload`
- Fix multi step form example

example-site: Fix broken file upload step

---

docs/lib/mdx/templates.ts
templates/category/index.mdx
templates/content/index.mdx
templates/home/index.mdx
templates/index.mdx
templates/multi-page-form/index.mdx
templates/not-found/index.mdx
templates/sign-in/index.mdx
templates/single-page-form/index.mdx
templates/subcategory/index.mdx

At the moment templates are ordered alphabetically which is a bit problematic. This PR adds in an `order` key to each templates front-matter so we can group related templates.

docs: Update order of templates

---

.changeset/shy-doors-sit.md
docs/package.json
example-site/package.json
packages/breadcrumbs/package.json
packages/call-to-action/package.json
packages/direction-link/package.json
packages/inpage-nav/package.json
packages/keyword-list/package.json
packages/link-list/package.json
packages/progress-indicator/package.json
packages/tags/package.json
packages/task-list/package.json
packages/text-link/package.json
releases/2022-01-05.mdx

Bump package because `text-link` was already a package

text-link: Bump package

---

.changeset/eight-carrots-care.md
packages/secondary-nav/README.md

Updated documentation for the `secondary-nav` package.

secondary-nav: Update documentation

---

.changeset/quick-lemons-try.md
packages/file-upload/README.md

Improve documentation of FileUpload to ensure consumers consider loading states.

FileUpload: Document logic for loading states

---

packages/text/src/Text.stories.tsx

text: Fix storybook path

---

packages/core/src/tokens.stories.tsx

- [] Run `yarn changeset` to create a changeset file

core: Add stories to showcase color/space tokens

---

packages/core/src/tokens.stories.tsx

core: Add system colors to token story

---

.changeset/perfect-files-teach.md
packages/text-link/README.md

Update documentation for `TextLinkExternal` to include accessibility advice from W3C.

text-link: Update docs

---

.changeset/gold-bananas-relax.md
packages/text-link/README.md

Small documentation update, implementing feedback from Adrian.

text-link: update documentation

---

packages/core/src/tokens.stories.tsx

Implemented small design tweaks after feedback from the design team.

core: Update design of color tokens story

---

packages/text-link/src/TextLinkExternal.stories.tsx

Update the storybook path to be more consistent with other packages.

text-link: update `TextLinkExternal` storybook path

---

.changeset/dull-pears-run.md
packages/pagination/src/Pagination.tsx
packages/pagination/src/PaginationButtons.tsx
packages/pagination/src/PaginationContainer.tsx
packages/pagination/src/PaginationItemDirection.tsx
packages/pagination/src/PaginationItemPage.tsx
packages/pagination/src/usePagination.test.ts
packages/pagination/src/usePagination.ts

- Update spacing between list elements
- Apply bold font-weight to active element
- Improve rendering performance of back/next button

pagination: Apply design feedback

---

.changeset/slimy-humans-exercise.md
packages/pagination/src/PaginationItemDirection.tsx

Added aria label for prev/next buttons to improve screen reader experience

pagination: Improve screen reader experience

---

example-site/components/FormExampleMultiStep/FormExampleMultiStep4.tsx

Updates the error state in the finale step of the multi-step form.

example-site: Update multi-step declaration 

---

.changeset/unlucky-shrimps-bake.md
packages/file-upload/README.md

Ticket: [Product Backlog Item 252427](https://dev.azure.com.mcas.ms/agriculturegovau/Digital%20Services/_workitems/edit/252427?McasTsid=26110): File upload - documentation

FileUpload: Minor docs rewording

---

.changeset/hip-houses-admire.md
docs/components/ComponentPropsTable.tsx

| <img width="404" alt="Screen Shot 2022-06-30 at 1 36 26 pm" src="https://user-images.githubusercontent.com/6265154/176588117-e16d5164-ad4f-4cc5-b6c0-d6d09dad3bf6.png">      | <img width="403" alt="Screen Shot 2022-06-30 at 1 36 08 pm" src="https://user-images.githubusercontent.com/6265154/176588130-a7c5b5e5-7995-4ad4-bd3a-81708086002b.png">       |

docs: Fix props table on mobile

---

.changeset/slow-beds-hang.md
docs/package.json
example-site/package.json
yarn.lock

Upgraded to latest next version. Release notes for next can be found here https://nextjs.org/blog/next-12-2

doc: Upgrade next to v12.2.0

---

.changeset/seven-sloths-complain.md
packages/ag-branding/README.md
packages/ag-branding/docs/code.mdx
packages/ag-branding/docs/overview.mdx

ag-branding: Convert package to new documentation structure

---

.changeset/slow-beds-hang.md
docs/package.json
example-site/package.json
yarn.lock

Reverts steelthreads/agds-next#502

Revert "doc: Upgrade next to v12.2.0"

---

.changeset/tasty-geckos-join.md
packages/breadcrumbs/README.md
packages/breadcrumbs/docs/code.mdx
packages/breadcrumbs/docs/overview.mdx

breadcrumbs: Convert package to new documentation structure

---

.changeset/fuzzy-ways-doubt.md
.changeset/tame-cobras-grab.md
.changeset/warm-spiders-help.md
packages/button/src/BaseButton.tsx
packages/button/src/Button.tsx
packages/call-to-action/README.md
packages/call-to-action/docs/code.mdx
packages/call-to-action/docs/overview.mdx
packages/call-to-action/src/CallToAction.tsx
packages/progress-indicator/src/ProgressIndicatorCollapseButton.tsx
packages/side-nav/src/SideNavCollapseButton.tsx

call-to-action: Convert package to new documentation structure

---

.changeset/small-bees-compete.md
docs/components/SiteFooter.tsx
docs/playroom/snippets.js
example-site/components/SiteFooter.tsx
packages/footer/README.md
packages/footer/src/Footer.stories.tsx

Updated copyright from 'Commonwealth of Australia' to 'Department of Agriculture, Fisheries and Forestry'
This change include
- Docs site
- Example site (templates)
- Footer docs
- Footer storybook
- Footer playroom snippets

footer: update copyright

---

.changeset/clever-insects-roll.md
packages/field/src/FieldMessage.tsx

Adjusted font weight of `FieldMessage`

field: Update message font-weight

---

.changeset/few-seals-pull.md
packages/progress-indicator/src/ProgressIndicator.tsx
packages/side-nav/src/SideNav.stories.tsx
packages/side-nav/src/SideNav.tsx

Before
https://user-images.githubusercontent.com/6265154/177064599-35ae5039-35d6-4ab8-9646-a005c4132f90.mov
After
https://user-images.githubusercontent.com/6265154/177064550-defebe1f-0722-42c2-b3af-53bdc7b0e10a.mov

side-nav/progress-indicator: Fix mobile issues

---

.changeset/great-mugs-cover.md
packages/main-nav/README.md
packages/main-nav/docs/code.mdx
packages/main-nav/docs/overview.mdx

main-nav: Convert package to new documentation structure

---

.changeset/thin-actors-raise.md
packages/text-link/README.md
packages/text-link/docs/code.mdx
packages/text-link/docs/overview.mdx
packages/text-link/src/TextLink.tsx

text-link: Convert package to new documentation structure

---

packages/button/src/Button.tsx

As per title. No changeset as this in addition #512.
- [] Run `yarn changeset` to create a changeset file

button: Fix typo in prop types

---

.changeset/cold-coats-flash.md
packages/form-stack/README.md
packages/form-stack/docs/code.mdx
packages/form-stack/docs/overview.mdx

form-stack: Convert package to new documentation structure 

---

.changeset/polite-peaches-guess.md
packages/header/README.md
packages/header/docs/code.mdx
packages/header/docs/overview.mdx

header: Convert package to new documentation structure

---

.changeset/four-windows-relax.md
packages/icon/README.md
packages/icon/docs/code.mdx
packages/icon/docs/overview.mdx
packages/icon/src/Icon.tsx

icon: Convert package to new documentation structure 

---

.changeset/clean-cheetahs-dance.md
packages/inpage-nav/README.md
packages/inpage-nav/docs/code.mdx
packages/inpage-nav/docs/overview.mdx

inpage-nav: Convert package to new documentation structure

---

README.md
docs/components/mdxComponents.tsx

- Add some documentation in the repo README, to deter users from cloning the repo if they don't intend to contribute to it.

Guide users away from cloning AgDS monorepo.

---

.changeset/late-news-hope.md
packages/main-nav/docs/overview.mdx

Fixed broken link in documentation
- [] Add necessary tests

main-nav: Fixed broken link in documentation

---

.changeset/neat-tools-happen.md
packages/accordion/docs/accessibility.mdx
packages/accordion/docs/content.mdx
packages/accordion/docs/overview.mdx
packages/accordion/docs/rationale.mdx
packages/accordion/src/Accordion.stories.tsx
packages/button/docs/accessibility.mdx
packages/button/docs/content.mdx
packages/button/docs/overview.mdx
packages/button/docs/rationale.mdx

button/accordion: Update documentation

---

packages/button/docs/overview.mdx

Update documentation. Follow up to #558 

button: Update documentation

---

.changeset/mighty-nails-build.md
docs/components/Code.tsx
packages/accordion/docs/overview.mdx
packages/button/docs/overview.mdx

Add live code snippet to the very start of the overview content.

accordion/button: update documentation

---

.storybook/stories/kitchenSink.tsx

- Include 'on light bodyAlt' and 'on dark bodyAlt' stories
- Remove 'sideNavVariant' (Will fix sidenav in upcoming PR)
- Add DatePicker, FileUpload and StatusBadge components
- Update layout so it's "slightly more" realistic

Kitchen sink story updates

---

.storybook/stories/kitchenSink.tsx

Update layout for KitchenSink

---

.changeset/rotten-yaks-brake.md
packages/accordion/src/AccordionTitle.tsx

As found by Adham: 
Result of change:

Accordion: background should peek through

---

.changeset/late-dingos-taste.md
packages/callout/docs/overview.mdx
packages/callout/src/Callout.stories.tsx
packages/callout/src/Callout.tsx

Support case where a user places this on 'bodyAlt' background.

Callout: Add background prop

---

packages/badge/package.json

Fixes the following error when trying to generate a changeset.

badge: Fix dependencies 

---

packages/badge/docs/content.mdx
packages/badge/docs/overview.mdx
packages/badge/src/StatusBadge.stories.tsx
packages/badge/src/StatusBadge.tsx

Fixes this issue that is currently in the docs site and storybook.

badge: Fix incorrect wrapping in mobile

---

.changeset/tall-foxes-drum.md
.changeset/tidy-coats-turn.md
.storybook/stories/CardsWithRemoteData.tsx
.storybook/stories/TableWithRemoteData.tsx
docs/components/designSystemComponents.tsx
docs/package.json
docs/playroom/components.js
docs/playroom/snippets.js
packages/heading/src/Heading.tsx
packages/pagination/src/PaginationButtons.stories.tsx
packages/skeleton/CHANGELOG.md
packages/skeleton/README.md
packages/skeleton/docs/accessibility.mdx
packages/skeleton/docs/code.mdx
packages/skeleton/docs/overview.mdx
packages/skeleton/package.json
packages/skeleton/src/SkeletonBox.stories.tsx
packages/skeleton/src/SkeletonBox.tsx
packages/skeleton/src/SkeletonHeading.stories.tsx
packages/skeleton/src/SkeletonHeading.tsx
packages/skeleton/src/SkeletonText.stories.tsx
packages/skeleton/src/SkeletonText.tsx
packages/skeleton/src/index.tsx

Skeletons are visual placeholders for information while data is still loading.

Create new `skeleton` package

---

packages/core/src/tokens.ts

A t-shirt based spacing scale was explored in PR #472 and it was decided as a team that we will stick to the current spacing scale. As a result of that discussion, I'm removing this FIXME comment. No changeset required as not touching any bundled code.

core: Remove spacing FIXME 

---

.changeset/proud-falcons-juggle.md
packages/card/src/Card.tsx

Card: Add support for CSS prop

---

example-site/pages/index.tsx

Updated incorrect usage of `shade`.

example-site: Update home page row background from `shade` to `bodyAlt`

---

.changeset/bright-walls-pump.md
.storybook/stories/kitchenSink.tsx
docs/playroom/snippets.js
example-site/pages/category/subcategory/content.tsx
packages/inpage-nav/docs/overview.mdx
packages/inpage-nav/src/InpageNav.stories.tsx
packages/inpage-nav/src/InpageNav.tsx

- [Product backlog item 267332](https://dev.azure.com.mcas.ms/agriculturegovau/Digital%20Services/_boards/board/t/Design%20System/Backlog%20items/?workitem=267332)
- Replaced the title in all instances of `InpageNav` from "Contents" to "On this page"
- Added prop comments

inpage-nav: Update title in examples

---

packages/skeleton/src/SkeletonBox.tsx

Tweaking animation values after conversations with design team.

skeleton: Tweak animation values

---

package.json
yarn.lock

Upgrade `@changesets/cli` from `2.18.0` to `2.23.2`

---

docs/components/PageLayout.tsx
example-site/pages/category/subcategory/content.tsx

Increase the width of the left sidebar on `md` devices.

docs/example: Update left column width in page layout

---

docs/components/PkgLayout.tsx

- Show 'in Development' in header
- Show PageAlert in place of npm install instructions

Docs: Show if a component is not yet released

---

packages/file-upload/src/FileUploadFile.tsx

FileUpload: Ensure icon doesn't shrink

---

packages/core/src/tokens.stories.tsx

More Core stories to 'foundations'

---

packages/columns/docs/overview.mdx
packages/columns/src/Column.stories.tsx

Columns: Add documentation about prefering 1 and 2 column grids

---

docs/lib/mdx/guides.ts
docs/lib/mdx/packages.ts
docs/lib/mdx/templates.ts

Fixes an issue where some paths had double forward slashes.

docs: Update pkg paths

---

packages/callout/docs/overview.mdx

Updated example in documentation.

callout: Fix incorrect use of `dateTime`

---

docs/components/PkgCardList.tsx
docs/pages/index.tsx

This gap should be `1.5rem` not `1rem`.

docs: update gap in package card list

---

.changeset/stale-mails-enjoy.md
.changeset/strange-clouds-yell.md
docs/components/designSystemComponents.tsx
example-site/components/FormExampleMultiStep/FormExampleMultiStep4.tsx
packages/button/docs/overview.mdx
packages/button/src/Button.stories.tsx
packages/button/src/ButtonGroup.stories.tsx
packages/button/src/ButtonGroup.tsx
packages/button/src/styles.tsx
packages/text-link/docs/code.mdx
packages/text-link/docs/overview.mdx
packages/text-link/package.json
packages/text-link/src/TextLink.stories.tsx
packages/text-link/src/TextLink.tsx

- Add new `text` button new variant
- Removed `TextButton` component from our `text-link` package
- Updated vertical alignment in `ButtonGroup`

button: Add new `text` variant

---

docs/pages/index.tsx

eslint remove unused var

---

.changeset/friendly-poets-give.md
packages/date-picker/src/Calendar.tsx
packages/date-picker/src/CalendarContainer.tsx
packages/date-picker/src/reactDayPickerStyles.ts

Selected days in range mode now have more rounded borders. 
| <img width="735" alt="Screen Shot 2022-07-29 at 2 13 34 pm" src="https://user-images.githubusercontent.com/6265154/181682043-90518a0e-119b-4331-8741-69c8eb5ec7b2.png">      | <img width="722" alt="Screen Shot 2022-07-29 at 2 12 49 pm" src="https://user-images.githubusercontent.com/6265154/181682028-a27f77c8-541d-4536-9c92-eb6d5c89b76c.png">       |

date-picker: update range styles

---

.storybook/stories/kitchenSink.tsx

Added table and skeleton loaders to kitchen sink.

storybook: Add table and skeleton to kitchen sink

---

.storybook/stories/kitchenSink.tsx

- Add active state to `SubNav`
-  Add checked state to `Checkbox`

kitchen-sink: Update sub nav and checkbox

---

docs/lib/mdx/guides.ts
docs/lib/mdx/packages.ts
docs/lib/mdx/templates.ts
docs/lib/mdxUtils.ts
docs/pages/packages/[group]/[slug]/index.tsx
docs/pages/templates/[slug]/index.tsx

- Add `home` to all breadcrumbs
- Removed `Overview` from packages and templates

docs: update breadcrumbs

---

.changeset/loud-emus-guess.md
docs/components/SiteFooter.tsx
example-site/components/SiteFooter.tsx
packages/footer/docs/overview.mdx
packages/footer/src/Footer.stories.tsx
packages/footer/src/Footer.tsx

- Add `background` prop
- Add support for contextual palettes. Remove `variant` prop
- Use theme `accent` token for highlights

Footer: Add background prop. Remove variant prop.

---

.storybook/preview.tsx
.storybook/stories/CardsWithRemoteData.tsx
.storybook/stories/TableWithRemoteData.tsx
.storybook/stories/kitchenSink.tsx
tsconfig.json

Currently typescript is not checking any files in the `.storybook` folder.

Ensure typescript checks custom storybook files

---

packages/footer/docs/overview.mdx
packages/header/docs/overview.mdx
packages/main-nav/docs/overview.mdx
packages/main-nav/src/MainNav.stories.tsx

Fix broken storybook paths

---

packages/skip-link/README.md

This README is incorrect and doesn't match other packages. This was probably a result of a bad copy/paste.

skip-link: Fix README

---

packages/button/src/Button.stories.tsx

Loading should be `false` by default.

button: update basic stories

---

package.json

Small improvement to our prettier linting test. PR inspired by https://github.com/keystonejs/keystone/pull/7784

Use `prettier --check` instead of `prettier --list-different`

---

packages/skeleton/docs/overview.mdx

skeleton: Add xl variant to docs

---

packages/button/docs/overview.mdx

Added `href` to make button focusable.

button: improve a11y of docs

---

docs/playroom/snippets.js

Fix playroom snippets

---

.changeset/twenty-olives-prove.md
packages/badge/src/StatusBadge.tsx
packages/badge/src/utils.ts

Updated colour in `neutral` variants.

badge: Update colour in  `neutral` variants

---

.changeset/fair-pants-glow.md
packages/search-box/src/SearchBoxButton.tsx

Used `aria-label` on the button so the label is the same across all viewports regardless if text or an icon is visible.

search-box: added accessible name button

---

.changeset/shy-balloons-clap.md
packages/fieldset/docs/overview.mdx
packages/fieldset/src/Fieldset.stories.tsx
packages/text-input/src/TextInput.tsx

Add autoComplete support to TextInput. Prompted by [DAGR-76](https://dev.azure.com.mcas.ms/agriculturegovau/Digital%20Services/_workitems/edit/296691?McasTsid=26110)

text-input: Add autoComplete support

---

.changeset/heavy-falcons-move.md
packages/file-upload/package.json
packages/file-upload/src/FileUploadFile.tsx

FileUpload: Accessibility improvements

---

packages/date-picker/src/reactDayPickerStyles.ts

No changeset as this is a follow up to #671 after more testing on a windows machine.

date-picker: improve high contrast mode accessibility

---

.changeset/chatty-sloths-fetch.md
packages/fieldset/package.json
packages/fieldset/src/Fieldset.tsx
packages/fieldset/src/FieldsetContainer.tsx
packages/fieldset/src/FieldsetHint.tsx

This is the same as #675, but applied to the `fieldset` component.

fieldset: Improve a11y

---

.changeset/yellow-chairs-mix.md
.eslintrc.js
packages/file-upload/src/FileUpload.tsx

FileUpload: Remove button role from outer element

---

.changeset/breezy-cooks-protect.md
packages/search-box/src/SearchBoxInput.tsx

Searchbox: Use white background

---

.changeset/yellow-wasps-roll.md
packages/core/src/packs.ts

This was a typo - a mistake I missed in #648 😭

core: Change input height from `em` to `rem`

---

.changeset/honest-bottles-provide.md
packages/date-picker/src/DatePicker.tsx
packages/date-picker/src/DateRangePicker.tsx
packages/main-nav/src/NavContainer.tsx
packages/modal/src/Modal.tsx
packages/modal/src/ModalCover.tsx

Improved handling of pressing `Escape` to close components

Improved handling of pressing `Escape` to close components

---

docs/components/designSystemComponents.tsx
packages/badge/docs/overview.mdx
packages/badge/src/IndicatorDot.stories.tsx

- Add examples of IndicatorDot being used in an accessible manner (DAGR-69)

badge: Indicator dot example

---

.changeset/breezy-fireants-whisper.md
packages/control-input/src/CheckboxIndicator.tsx
packages/control-input/src/RadioIndicator.tsx

control-input: Improve a11y in high contrast mode

---

.changeset/rude-shrimps-crash.md
packages/switch/src/Switch.tsx

Improve accessibility of Switch component by adding `role='switch'` to the underlying checkbox

Switch: Add `role=switch` (DAGR-84)

---

packages/control-input/docs/overview.mdx

Make examples in documentation interactive (DAGR-67)

ControlInput: Make examples interactive

---

docs/package.json
example-site/package.json
yarn.lock

Upgrade to version 12.3 of next. https://nextjs.org/blog/next-12-3

Upgrade nextjs

---

packages/direction-link/docs/overview.mdx

Improve documentation to explain why DirectionButton exists
Prompted by DAGR-100

DirectionButton: Improve documentation

---

.changeset/beige-candles-hope.md
packages/task-list/src/TaskListItem.tsx

task-list: fix typo

---

docs/pages/_document.tsx
example-site/pages/_document.tsx

Add lang='en' to the docs site and example site, by creating _document.tsx files

Add lang=en to docs websites

---

.changeset/strong-apricots-act.md
packages/side-nav/src/SideNav.test.tsx
packages/side-nav/src/SideNav.tsx

- Added HTML validation tests
- Fixed minor HTML validation issue

side-nav: Added HTML validation tests

---

packages/card/src/Card.test.tsx

No changeset required as this doesn't touch any bundled code.

card: Added HTML validation tests 

---

packages/main-nav/src/MainNav.test.tsx

No changeset required as this doesn't touch any bundled code.

main-nav: Added HTML validation tests 

---

packages/main-nav/src/MainNav.test.tsx
packages/main-nav/src/__snapshots__/MainNav.test.tsx.snap

Add snapshot test to main-nav. Based off #705

main-nav: Add snapshot testing

---

.github/workflows/deploy-docs.yml

example-form: register a pet build

---

.changeset/four-kiwis-stare.md
packages/control-input/src/Checkbox.tsx
packages/control-input/src/Radio.tsx
packages/select/src/Select.tsx
packages/text-input/src/TextInput.tsx
packages/textarea/src/Textarea.tsx

Added support for https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autofocus prop.

form: Add `autoFocus` prop

---

.github/workflows/test.yml
example-form/components/FormRegisterPetDetails/FormRegisterPetDetailsStep0.tsx

- Fixed build
- Improved CI process to catch this in the future

Fix docs build error

---

example-form/components/FormRegisterPetDetails/FormRegisterPetDetails.tsx
example-form/pages/services/registrations/index.tsx

This PR fixes a bug where the user isn't shown the success page alert once submitting the form.

example-form: Update success page

---

.changeset/seven-mirrors-know.md
packages/side-nav/src/SideNav.test.tsx
packages/side-nav/src/SideNavTitle.tsx
packages/side-nav/src/__snapshots__/SideNav.test.tsx.snap

- Fixed bug where `titleLink` would not render an anchor tag
- Improved testing

side-nav: Fix `titleLink` bug

---

example-site/pages/category/subcategory/multi-page-form/success.tsx
example-site/pages/category/subcategory/single-page-form-success.tsx

Ensures the success page in our form examples have a unique page title.

example-site: Improve document title (DAGR-125)

---

example-form/components/FormRegisterPetDetails/FormRegisterPetDetailsContainer.tsx
example-form/components/FormRegisterPetDetails/FormRegisterPetDetailsStep0.tsx
example-form/components/FormRegisterPetDetails/FormRegisterPetDetailsStep1.tsx
example-form/components/FormRegisterPetDetails/FormRegisterPetDetailsStep2.tsx
example-form/components/FormRegisterPetDetails/FormRegisterPetDetailsStep3.tsx
example-form/components/FormRegisterPetPersonalDetails/FormRegisterPetPersonalDetailsStep0.tsx
example-form/components/FormRegisterPetPersonalDetails/FormRegisterPetPersonalDetailsStep1.tsx
example-form/components/FormRegisterPetPersonalDetails/FormRegisterPetPersonalDetailsStep2.tsx
example-form/components/FormRequiredFieldsMessage.tsx
example-form/components/RegistrationsCardList.tsx
example-form/components/ServicesCardList.tsx
example-form/components/ServicesRecentlyViewedCardList.tsx
example-form/pages/_document.tsx
example-form/pages/not-found.tsx
example-form/pages/services/registrations/index.tsx
example-form/pages/services/registrations/pet/index.tsx
example-form/pages/services/registrations/pet/task-1/form.tsx
example-form/pages/services/registrations/pet/task-1/index.tsx
example-form/pages/services/registrations/pet/task-2/form.tsx
example-form/pages/services/registrations/pet/task-2/index.tsx

Misc fixes to the example-form (copy, validation improvements etc)

example-form: Misc improvements

---

example-site/components/FormExampleMultiStep/FormExampleMultiStepContainer.tsx
example-site/pages/category/subcategory/single-page-form.tsx

Addressing accessibility review item DAGR-118 and DAGR-121

examples: Add text to state all fields are required

---

.changeset/funny-ears-trade.md
packages/combobox/src/Combobox.tsx
packages/date-picker/src/DatePickerInput.tsx
packages/field/src/Field.tsx
packages/file-upload/src/FileUpload.tsx
packages/select/src/Select.tsx
packages/text-input/src/TextInput.tsx
packages/textarea/src/Textarea.tsx

Fixed small typo in code
```diff
- allyProps
+ a11yProps
```

form: Fixed small typo in code 

---

example-form/components/FormRegisterPetDetails/FormRegisterPetDetailsActions.tsx
example-form/components/FormRegisterPetPersonalDetails/FormRegisterPetPersonalDetailsActions.tsx

Updated copy as per design feedback.

example-form: Update copy in cancellation modal

---

example-form/components/FormRegisterPetDetails/FormRegisterPetDetailsStep2.tsx
example-form/components/FormRegisterPetDetails/FormRegisterPetDetailsStep3.tsx

Small copy tweaks to fix a couple of typos.

example-form: Fix small typos

---

.changeset/fair-pumpkins-carry.md
packages/control-input/src/Checkbox.test.tsx
packages/control-input/src/CheckboxIndicator.tsx
packages/control-input/src/ControlInput.tsx
packages/control-input/src/Radio.test.tsx
packages/control-input/src/RadioIndicator.tsx
packages/control-input/src/__snapshots__/Checkbox.test.tsx.snap
packages/control-input/src/__snapshots__/Radio.test.tsx.snap

Partially resolve [Product Backlog Item 319535](https://dev.azure.com.mcas.ms/agriculturegovau/Digital%20Services/_workitems/edit/319535?McasTsid=26110) (DAGR-119).
- Add tests to ensure valid HTML for Checkbox and Radio components
- Fix invalid HTML errors

control-input: Fix invalid HTML errors

---

example-form/components/FormRegisterPetContext.tsx
example-form/components/FormRegisterPetDetails/FormRegisterPetDetails.tsx
example-form/components/FormRegisterPetDetails/FormRegisterPetDetailsContainer.tsx
example-form/components/FormRegisterPetDetails/FormRegisterPetDetailsStep0.tsx
example-form/components/FormRegisterPetDetails/FormRegisterPetDetailsStep1.tsx
example-form/components/FormRegisterPetDetails/FormRegisterPetDetailsStep2.tsx
example-form/components/FormRegisterPetDetails/FormRegisterPetDetailsStep3.tsx
example-form/components/FormRegisterPetPersonalDetails/FormRegisterPetPersonalDetails.tsx
example-form/components/FormRegisterPetPersonalDetails/FormRegisterPetPersonalDetailsContainer.tsx
example-form/components/FormRegisterPetPersonalDetails/FormRegisterPetPersonalDetailsStep0.tsx
example-form/components/FormRegisterPetPersonalDetails/FormRegisterPetPersonalDetailsStep1.tsx
example-form/components/FormRegisterPetPersonalDetails/FormRegisterPetPersonalDetailsStep2.tsx
example-form/components/ServicesCardList.tsx
example-form/components/SiteHeader.tsx
example-form/pages/services/registrations/pet/index.tsx
example-site/components/FormExampleMultiStep/FormExampleMultiStep.tsx
example-site/components/FormExampleMultiStep/FormExampleMultiStepContainer.tsx

This PR improves the form flow logic in the "register your pet" form. Some improvements include:
- Ensures you can complete task 1 or task 2 independently 
- Fixes a bug where the right status is set for each sub-task was not being defined correctly

example-form: Validation improvements

---

example-form/components/FormRegisterPetContext.tsx
example-form/components/FormRegisterPetPersonalDetails/FormRegisterPetPersonalDetailsStep0.tsx
example-form/pages/services/registrations/pet/index.tsx

example-form: Validation improvements 

---

example-form/components/FormRegisterPetDetails/FormRegisterPetDetailsStep4.tsx
example-form/components/FormRegisterPetPersonalDetails/FormRegisterPetPersonalDetailsStep0.tsx
example-form/components/FormRegisterPetPersonalDetails/FormRegisterPetPersonalDetailsStep2.tsx
example-form/components/FormRegisterPetPersonalDetails/FormRegisterPetPersonalDetailsStep3.tsx
example-site/components/FormExampleMultiStep/FormExampleMultiStep4.tsx

The `change` button at the end of each step needs to be at the bottom of the description list, not at the top. Also the label needs to be more descriptive than just "Change".

example-form: Move change button

---

example-form/components/FormRegisterPetDetails/FormRegisterPetDetailsStep1.tsx
example-form/components/FormRegisterPetDetails/FormRegisterPetDetailsStep3.tsx
example-form/components/FormRegisterPetPersonalDetails/FormRegisterPetPersonalDetailsStep0.tsx
example-site/components/FormExampleMultiStep/FormExampleMultiStep1.tsx
example-site/components/FormExampleMultiStep/FormExampleMultiStep2.tsx
packages/file-upload/src/FileUpload.stories.tsx

- Fix missing IDs
- Fix typo in multi step form

multi step forms: Update usage of `Controller`

---

example-form/components/FormRegisterPetDetails/FormRegisterPetDetailsStep4.tsx

Vaccination certificate is an optional field.

example-form: Fix error with uploaded file

---

.changeset/empty-coins-thank.md
.changeset/little-mirrors-speak.md
packages/button/src/Button.test.tsx
packages/button/src/Button.tsx
packages/date-picker/src/DatePickerInput.tsx
packages/date-picker/src/__snapshots__/DatePicker.test.tsx.snap
packages/date-picker/src/__snapshots__/DateRangePicker.test.tsx.snap
packages/loading/src/LoadingDots.test.tsx
packages/loading/src/LoadingDots.tsx

- Button: Add aria-live container for loading state
- Loading: make elements spans so they are valid children of button

Button: Add aria-live container for loading state

---

example-form/components/FormRegisterPetPersonalDetails/FormRegisterPetPersonalDetailsActions.tsx

example-form: update submit button text

---

example-form/components/FormRegisterPetContext.tsx

example-form: navigate user back to home page

---

example-form/components/FormRegisterPetPersonalDetails/FormRegisterPetPersonalDetailsStep0.tsx
example-form/components/FormRegisterPetPersonalDetails/FormRegisterPetPersonalDetailsStep1.tsx

Iterating on the example form flow to give users confidence they are correctly saving the information they've edited.

example-form: Update and save pre-filled information

---

docs/components/TokenColorTable.tsx
docs/pages/tokens/color.tsx
guides/theme.mdx

Iterating on the tokens page content
- Move colour token group descriptions to live near tables
- New UI design for switch
- Shuffle some content around

docs: Update tokens page

---

.changeset/witty-comics-call.md
.storybook/stories/TableWithRemoteData.tsx
packages/table/src/Table.tsx

table: Enable ref and tabIndex props

---

.changeset/thick-spies-report.md
packages/search-box/src/Search.test.tsx
packages/search-box/src/SearchBoxButton.tsx
packages/search-box/src/__snapshots__/Search.test.tsx.snap

- Fixed icon only version which was visually broken after recent button change
- Added tests

search-box: Fix icon only

---

docs/playroom/snippets.js
packages/details/docs/overview.mdx
packages/details/src/Details.stories.tsx
packages/details/src/Details.test.tsx
packages/details/src/__snapshots__/Details.test.tsx.snap

Fixed a small typo and added snapshot testing.

details: Fix typo

---

packages/accordion/src/Accordion.test.tsx
packages/accordion/src/__snapshots__/Accordion.test.tsx.snap

accordion: Add tests

---

packages/breadcrumbs/src/Breadcrumbs.test.tsx
packages/breadcrumbs/src/__snapshots__/Breadcrumbs.test.tsx.snap

As per title.
- [] Run `yarn changeset` to create a changeset file

breadcrumbs: Add tests

---

packages/modal/docs/overview.mdx
packages/modal/src/Modal.stories.tsx
packages/modal/src/Modal.test.tsx
packages/modal/src/__snapshots__/Modal.test.tsx.snap

Added basic tests for the `modal` package.

modal: Add tests

---

packages/text-link/src/TextLink.test.tsx
packages/text-link/src/TextLinkExternal.test.tsx
packages/text-link/src/__snapshots__/TextLink.test.tsx.snap
packages/text-link/src/__snapshots__/TextLinkExternal.test.tsx.snap

Added basic tests for the `text-link` package.

text-link: Add tests

---

packages/switch/src/Switch.test.tsx
packages/switch/src/Switch.tsx
packages/switch/src/SwitchTrack.tsx
packages/switch/src/__snapshots__/Switch.test.tsx.snap

- Added basic tests for `switch` package
- Fixed HTML validation error

switch: Add basic tests

---

packages/select/src/Select.test.tsx
packages/select/src/__snapshots__/Select.test.tsx.snap

Added basic tests for the `select` package

select: Add basic tests

---

packages/details/README.md
packages/details/docs/overview.mdx
packages/details/src/Details.stories.tsx
packages/details/src/Details.tsx

Updated the group the `details` package belongs to. 
No changeset required.

details: Update group from `layout` to `content`

---

plop-templates/component/README.md.hbs

Updated the plop file which generates the `README.md` file for new packages.

Update README in new package script

---

packages/table/src/__snapshots__/Table.test.tsx.snap

These tests were broken by #782

table: update snapshots

---

docs/playroom/snippets.js
packages/summary-list/docs/overview.mdx
packages/summary-list/src/SummaryList.stories.tsx
packages/summary-list/src/SummaryList.test.tsx
packages/summary-list/src/SummaryList.tsx
packages/summary-list/src/__snapshots__/SummaryList.test.tsx.snap

- Added font-size and line-height to our `dt` and `dd` elements so that they have the intended typography rhythm. 
- Updated examples to use a simple `<br />` tag instead of a `Stack` with `Text` elements. This has simplified our example code.

summary-list: Fix line-height issue

---

packages/page-alert/src/PageAlert.test.tsx
packages/page-alert/src/__snapshots__/PageAlert.test.tsx.snap

Added basic tests for the `page-alert` package

Add tests for the `page-alert` package

---

packages/badge/src/IndicatorDot.test.tsx
packages/badge/src/NotificationBadge.test.tsx
packages/badge/src/StatusBadge.test.tsx
packages/badge/src/__snapshots__/IndicatorDot.test.tsx.snap
packages/badge/src/__snapshots__/NotificationBadge.test.tsx.snap
packages/badge/src/__snapshots__/StatusBadge.test.tsx.snap

Added simple tests for the `badge` package.

Add tests for `badge` package

---

packages/call-to-action/src/CallToAction.test.tsx
packages/call-to-action/src/CallToAction.tsx
packages/call-to-action/src/__snapshots__/CallToAction.test.tsx.snap

Added basic tests for the `call-to-action` package.

Add tests for the `call-to-action` package

---

packages/pagination/src/Pagination.test.tsx
packages/pagination/src/Pagination.tsx
packages/pagination/src/PaginationButtons.test.tsx
packages/pagination/src/PaginationButtons.tsx
packages/pagination/src/__snapshots__/Pagination.test.tsx.snap
packages/pagination/src/__snapshots__/PaginationButtons.test.tsx.snap

Added basic tests for the `pagination` package.

Add tests for the `pagination` package

---

.changeset/five-spoons-bathe.md
packages/content/src/BaseContent.tsx

Fixed bug in `BaseContent` component where the `id` prop was not being rendered

content: Fix bug in `BaseContent` component

---

.storybook/stories/kitchenSink.tsx
README.md
docs/components/SiteFooter.tsx
docs/pages/index.tsx
example-site/components/SiteFooter.tsx
guides/getting-started.mdx

The name of the starter-kit repo has changed

Update links to starter kit

---

packages/README.md

docs: Rename "Package" to "Components"

---

docs/pages/tokens/spacing.tsx

Add updated content for Spacing

Tokens: Add content for Spacing

---

.changeset/brave-plums-cover.md
packages/box/src/styles.ts

Box: Enable responsive borders

---

docs/components/TokenLayout.tsx
docs/pages/tokens/color.tsx
docs/pages/tokens/colour.tsx

Small changes to colours page

---

guides/custom-theme.mdx

Minor typo fix

---

.changeset/pink-snakes-watch.md
packages/date-picker/src/__snapshots__/Calendar.test.tsx.snap
packages/date-picker/src/reactDayPickerStyles.ts

Improve accessibility by increasing font weight of selected dates.
[DAGR-73 Round 2 - Date picker selected state](https://dev.azure.com.mcas.ms/agriculturegovau/Digital%20Services/_workitems/edit/339960?McasTsid=26110):

DatePicker: Increasing font weight of selected dates

---

docs/components/pictograms/a11y.svg
docs/components/pictograms/details.svg
docs/components/pictograms/form-stack.svg
docs/components/pictograms/skeleton.svg
docs/components/pictograms/sub-nav.svg
docs/components/pictograms/summary-list.svg

Website Pictogram updates

---

example-form/components/FormRegisterPetDetails/FormRegisterPetDetailsActions.tsx
example-form/components/FormRegisterPetPersonalDetails/FormRegisterPetPersonalDetailsActions.tsx
example-site/components/FormExampleMultiStep/FormExampleMultiStepActions.tsx
example-site/components/FormExampleSinglePage.tsx

example-form: Update language in save buttons

---

packages/hero-banner/src/HeroCategoryBanner/HeroCategoryBanner.stories.tsx

Remove 'button' story from HeroCategoryBanner, as this component does not support buttons.
[Bug 298973](https://dev.azure.com.mcas.ms/agriculturegovau/Digital%20Services/_workitems/edit/298973?McasTsid=26110): Banner bugs

HeroCategoryBanner: Remove buttons story

---

.changeset/late-grapes-arrive.md
.changeset/nasty-pillows-hear.md
.changeset/slimy-schools-study.md
.changeset/spicy-paws-hide.md
.changeset/thirty-bobcats-wait.md
packages/progress-indicator/src/ProgressIndicatorItem.tsx
packages/task-list/src/TaskListItem.tsx
packages/task-list/src/__snapshots__/TaskList.test.tsx.snap

- Updated changesets
- Updated status maps
- Reverted task list font size changes

task-list/progress-indicator: Update icons and labels  PR suggestions

---

.changeset/clean-apples-vanish.md
packages/breadcrumbs/package.json
packages/breadcrumbs/src/Breadcrumbs.stories.tsx
packages/breadcrumbs/src/Breadcrumbs.test.tsx
packages/breadcrumbs/src/Breadcrumbs.tsx
packages/breadcrumbs/src/BreadcrumbsContainer.tsx
packages/breadcrumbs/src/BreadcrumbsItem.tsx
packages/breadcrumbs/src/BreadcrumbsToggle.tsx
packages/breadcrumbs/src/__snapshots__/Breadcrumbs.test.tsx.snap
packages/breadcrumbs/src/index.tsx
packages/hero-banner/src/HeroSubcategoryBanner/__snapshots__/HeroSubCategoryBanner.test.tsx.snap

Added collapsible behaviour to  mobile version
https://user-images.githubusercontent.com/6265154/204443287-68805c21-1918-4e69-adde-ef4d1f9b2fcc.mov

breadcrumbs: update mobile version

---

docs/.env.production
docs/.gitignore
docs/next-sitemap.config.js
docs/package.json
docs/public/google67c4a117546ddf5e.html
yarn.lock

This PR adds a sitemap to our website using [next-sitemap](https://www.npmjs.com/package/next-sitemap). The sitemap will be automatically generated on each build.

docs: Add sitemap

---

docs/pages/components/index.tsx

Updates as per design team feedback.

docs: update search components copy

---

packages/breadcrumbs/src/BreadcrumbsItem.tsx
packages/breadcrumbs/src/__snapshots__/Breadcrumbs.test.tsx.snap
packages/hero-banner/src/HeroSubcategoryBanner/__snapshots__/HeroSubCategoryBanner.test.tsx.snap

Fixed UI bug after design review.

breadcrumbs: Fix incorrect text color

---

packages/search-input/src/SearchInput.test.tsx
packages/search-input/src/SearchInputClearButton.tsx

Updated color, size and aria label of the clear button after a design review.

search-input: Update clear button UI

---

example-form/components/FormRegisterPetDetails/FormRegisterPetDetails.tsx
example-form/components/FormRegisterPetPersonalDetails/FormRegisterPetPersonalDetails.tsx
example-site/components/FormExampleMultiStep/FormExampleMultiStep.tsx
packages/progress-indicator/docs/overview.mdx

Add `blocked` state to docs, example site and example form.

progress-indicator: update docs/examples

---

packages/search-input/src/SearchInputClearButton.tsx

Increased clickable of the 'clear' button to 2rem (32px).

search-input: Increase clickable area of the clear button

---

docs/pages/tokens/breakpoints.tsx

Ticket: [Token docs: Breakpoints (351827)](https://dev.azure.com.mcas.ms/agriculturegovau/Digital%20Services/_workitems/edit/351827?McasTsid=26110)
Update content provided by Adham in ticket.

docs: Update breakpoint tokens content

---

docs/pages/tokens/border.tsx

Ticket: [Token docs: Border (351828)](https://dev.azure.com.mcas.ms/agriculturegovau/Digital%20Services/_workitems/edit/351828?McasTsid=26110): 
Update content provided by Adham in ticket.

docs: Update Border tokens content

---

docs/components/PageLayout.tsx
docs/components/SiteHeader.tsx
docs/components/TokenCharts.tsx
docs/components/TokenLayout.tsx
docs/content/tokens/index.ts
docs/pages/tokens/border.tsx
docs/pages/tokens/breakpoints.tsx
docs/pages/tokens/colour.tsx
docs/pages/tokens/index.tsx
docs/pages/tokens/max-width.tsx
docs/pages/tokens/spacing.tsx
docs/pages/tokens/typography.tsx

- Update content on the `typography` page
- Add breadcrumbs to each tokens page
- Update tokens index page design
- Add tokens to the site header main navigation

docs: Update tokens

---

docs/components/AppLayout.tsx
packages/global-alert/docs/overview.mdx
packages/global-alert/src/GlobalAlert.stories.tsx
packages/global-alert/src/GlobalAlert.test.tsx
packages/global-alert/src/GlobalAlert.tsx

improved docs, storybook stories and tests for the new `GlobalAlert` component.

global-alert: Update docs/stories

---

docs/pages/index.tsx

docs: add tokens to homepage

---

docs/pages/tokens/index.tsx

Move from 2 column to 3 column grid.

docs: update tokens grid

---

.changeset/spicy-rice-impress.md
packages/date-picker/docs/overview.mdx
packages/date-picker/src/Calendar.stories.tsx
packages/date-picker/src/Calendar.test.tsx
packages/date-picker/src/Calendar.tsx
packages/date-picker/src/CalendarContainer.tsx
packages/date-picker/src/DatePicker.tsx
packages/date-picker/src/DatePickerInput.tsx
packages/date-picker/src/DateRangePicker.tsx
packages/date-picker/src/__snapshots__/Calendar.test.tsx.snap
packages/date-picker/src/__snapshots__/DatePicker.test.tsx.snap
packages/date-picker/src/__snapshots__/DateRangePicker.test.tsx.snap
packages/date-picker/src/reactDayPickerStyles.ts

date-picker: Add year select to calendar

---

docs/package.json
yarn.lock

Upgrade playroom to `0.28.1` which includes react 18 support 🎉
https://github.com/seek-oss/playroom/releases/tag/v0.28.1

Upgrade playroom

---

docs/components/LinkComponent.tsx
docs/package.json
example-form/components/LinkComponent.tsx
example-form/package.json
example-site/components/LinkComponent.tsx
example-site/package.json
yarn.lock

Upgrade next

---

docs/package.json
yarn.lock

docs: remove unused dependency (yarn)

---

docs/components/SiteHeader.tsx

docs: Update header badge to Beta

---

docs/package.json
example-form/package.json
example-site/package.json
yarn.lock

Upgrade `next` to version `13.1.1`

Upgrade next to version 13.1

---

docs/content/guides/accessibility.mdx

Added accessibility guide to documentation website.

docs: add a11y guide

---

docs/components/SiteFooter.tsx

docs: add privacy link to footer

---

docs/content/guides/accessibility.mdx

docs: Update a11y guide

---

docs/components/CategoryPageTemplate.tsx
docs/pages/components/index.tsx
docs/pages/guides/index.tsx
docs/pages/templates/index.tsx
docs/pages/tokens/index.tsx
docs/pages/updates/[slug].tsx
docs/pages/updates/index.tsx

docs: Use category template for top-level pages

---

docs/components/SiteHeader.tsx
docs/components/SubcategoryPageTemplate.tsx
docs/content/foundations/accessibility.mdx
docs/content/foundations/design-principles.mdx
docs/content/foundations/icons.mdx
docs/content/foundations/technical-overview.mdx
docs/content/foundations/tokens.mdx
docs/content/guides/contribution.mdx
docs/content/guides/custom-theme.mdx
docs/content/tokens/index.ts
docs/content/updates/2023-01-09-beta.mdx
docs/lib/mdx/foundations.ts
docs/lib/mdx/templates.ts
docs/pages/foundations/[slug].tsx
docs/pages/foundations/icons.tsx
docs/pages/foundations/index.tsx
docs/pages/foundations/tokens/border.tsx
docs/pages/foundations/tokens/breakpoints.tsx
docs/pages/foundations/tokens/colour.tsx
docs/pages/foundations/tokens/index.tsx
docs/pages/foundations/tokens/max-width.tsx
docs/pages/foundations/tokens/spacing.tsx
docs/pages/foundations/tokens/typography.tsx
docs/pages/index.tsx
packages/react/src/core/docs/overview.mdx
packages/react/src/icon/docs/overview.mdx

docs: Add new 'foundations' section of the website

---

packages/react/src/icon/__snapshots__/Icon.test.tsx.snap

Updated jest snapshots after new icons were added in #918.

icon: update snapshots

---

docs/components/TokenLayout.tsx
docs/pages/foundations/icons.tsx

- Fix broken link missed in #926 
- Change default icon size from `lg` to `md`

docs: updates to foundations section

---

.changeset/fast-terms-boil.md
packages/react/src/tags/Tag.tsx
packages/react/src/tags/Tags.stories.tsx
packages/react/src/tags/Tags.test.tsx
packages/react/src/tags/Tags.tsx
packages/react/src/tags/__snapshots__/Tags.test.tsx.snap
packages/react/src/tags/docs/overview.mdx

Support removing Tags from a list

tags: Add removable functionality

---

packages/react/src/tags/Tag.tsx
packages/react/src/tags/__snapshots__/Tags.test.tsx.snap

Fix focus styling for Tag remove button.

Tags: Apply focus styling to remove button

---

.github/workflows/deploy-docs.yml
.github/workflows/preview.yml
.github/workflows/test.yml
docs/next.config.js
docs/pages/index.tsx
example-form/next.config.js
example-site/next.config.js

This PR adds pull request previews to our repo using the [PR Preview Github Action](https://github.com/rossjrw/pr-preview-action).
As the github deploy previews are deployed on a sub path (e.g. `https://steelthreads.github.io/agds-next/pr-preview/pr-938/`) we've had to make a slight tweak to our nextjs websites `basePath`.

Add PR previews

---

example-site/components/TemplateBanner.tsx

Update background colour from `shade` to `body`.
Preview available here https://design-system.agriculture.gov.au/pr-preview/pr-935/example-site/

example-site: update template banner background

---

docs/content/updates/2023-01-09-beta.mdx
docs/content/updates/2023-01-30.mdx
docs/lib/mdx/updates.ts
docs/pages/updates/[slug].tsx

Add 2023-01-30 release notes

---

docs/components/PkgLayout.tsx

Remove version number from base figma gallery url.

docs: update base figma gallery url

---

docs/components/designSystemComponents.tsx
docs/playroom/snippets.ts

Added more snippets to playroom after discussion with @danger17.
- Added snippet `Footer` to boilerplate
- Added snippet `Text` and `Heading`
- Add snippet for `ButtonGroup`
- Added snippet for `Tag`

playroom: Add more snippets

---

.changeset/proud-jars-rest.md
packages/react/src/pagination/PaginationItemDirection.tsx
packages/react/src/pagination/PaginationItemPage.tsx
packages/react/src/pagination/PaginationItemSeparator.tsx
packages/react/src/pagination/__snapshots__/Pagination.test.tsx.snap
packages/react/src/pagination/__snapshots__/PaginationButtons.test.tsx.snap
packages/react/src/pagination/utils.ts

Improved design for smaller devices.
| <img width="719" alt="Screen Shot 2023-02-07 at 10 07 21 am" src="https://user-images.githubusercontent.com/6265154/217114972-69d8998a-ae86-4bec-bceb-58ba54d71613.png">      | <img width="698" alt="Screen Shot 2023-02-07 at 10 07 09 am" src="https://user-images.githubusercontent.com/6265154/217114968-7624f725-1209-4d52-a018-8938034be658.png">       |

pagination: improved design for smaller devices

---

docs/components/mdxComponents.tsx
packages/react/src/progress-indicator/docs/overview.mdx
packages/react/src/task-list/docs/overview.mdx

Improve the documentation of each status type in ProgressIndicator.

progress-indicator,task-list: document each status type

---

docs/components/TokenCharts.tsx
docs/content/tokens/index.ts
docs/pages/foundations/tokens/max-width.tsx

Updated the max-width tokens page with a description about what each token is used for.

docs: update tokens max-width content

---

packages/react/README.md

If you take a look at the [`@ag.ds-next/react` package on NPM](https://www.npmjs.com/package/@ag.ds-next/react) we have an old README which needs to be updated.

Fix NPM readme

---

.changeset/short-shrimps-rest.md
packages/react/src/select/Select.stories.tsx
packages/react/src/select/Select.tsx
packages/react/src/select/docs/overview.mdx

Add support for small size to Select component, to support number lists like 'items per page'.

Select: Add support for small size

---

docs/content/updates/2023-02-17.mdx

AgDS Beta v1.2.0 release notes.

docs: 2023-02-17 release notes

---

.storybook/stories/KitchenSink.tsx

Added `Avatar`, `SummaryList`, `SearchInput` and `FileInput` to kitchen sink story.

Add more components to KitcheSink

---

.changeset/clever-boats-leave.md
packages/react/src/avatar/Avatar.tsx
packages/react/src/avatar/__snapshots__/Avatar.test.tsx.snap

Fix an issue where the Avatar component shrinks in tight containers like tables.

Avatar: Resolve shrinking bug

---

.github/workflows/preview.yml
.github/workflows/release.yml

Fix invalid yaml for node version definition

Fix Github Actions for PR previews

---

docs/content/updates/2023-02-23.mdx

Release notes for AgDS Beta v1.2.1.

AgDS Beta v1.2.1 release notes

---

README.md

This list is outdated. At the moment we have this information in our Github pull request template.

Remove "Adding new components" from README

---

.github/pull_request_template.md
docs/content/guides/change-management.mdx

Document the process for change management in AgDS
[Direct link to preview](https://design-system.agriculture.gov.au/pr-preview/pr-986/guides/change-management)

Document Change management

---

example-site/components/templates/SinglePageForm.tsx

Adds the `DatePicker` and `DateRangePicker` to the single page form template so we can test these components in a "real world" example form.

example-site: Add `DatePicker` and `DateRangePicker` to single page form

---

docs/package.json
yarn.lock

Upgraded to the latest version of playroom, which  Adds VSCode-style keybindings to the code editor. [See release note here](https://github.com/seek-oss/playroom/releases).
https://user-images.githubusercontent.com/6265154/223875475-0455cd4f-0851-456c-b072-fc8c604d3fe7.mov

Upgrade playroom to version `0.30.0`

---

.changeset/slimy-poets-move.md
packages/react/src/table/Table.test.tsx
packages/react/src/table/Table.tsx
packages/react/src/table/__snapshots__/Table.test.tsx.snap

Add support for ID prop to Table component

table: Add support for ID prop

---

example-site/components/templates/MultiPageFormSuccess.tsx
example-site/components/templates/SinglePageFormSuccess.tsx

This PR ensures that the conformational page alert element is focused after successfully completing a form in our Single-page and Multi-page form templates.
- [Single-page form preview](https://design-system.agriculture.gov.au/pr-preview/pr-1009/example-site/category/subcategory/single-page-form-success)
- [Multi-page form preview](https://design-system.agriculture.gov.au/pr-preview/pr-1009/example-site/category/subcategory/multi-page-form/success)

example-site: focus success page alert after submitting form

---

.changeset/curvy-ears-leave.md
.storybook/main.ts
.storybook/stories/TableFiltering/components/DashboardTable.stories.tsx
.storybook/stories/TableFiltering/components/DashboardTable.tsx
.storybook/stories/TableFiltering/components/DashboardTableHeader.tsx
.storybook/stories/TableFiltering/components/SortBySelect.tsx
.storybook/stories/TableFiltering/lib/generateBusinessData.ts
packages/react/src/table/Table.stories.tsx
packages/react/src/table/Table.test.tsx
packages/react/src/table/Table.tsx
packages/react/src/table/TableHeader.tsx
packages/react/src/table/__snapshots__/Table.test.tsx.snap
packages/react/src/table/docs/overview.mdx

- Add support for table-layout property
- Add support for more Table column width values
- Simplify basic Table Storybook. Expose filtering example table in Table stories as advanced example
- Remove numberOfEmployees from Table Filtering pattern code to simplify table
Prompted by feedback from @stowball in #942 
[Link to doc](https://csswizardry.com/2013/11/taming-data-tables/)

table: Add support for table-layout property

---

docs/content/foundations/design-principles.mdx
docs/content/foundations/icons.mdx
docs/pages/foundations/icons.tsx
packages/react/src/direction-link/docs/overview.mdx

Adding design guidelines to our existing Design Principles page
- [Design Principles](https://design-system.agriculture.gov.au/pr-preview/pr-1003/foundations/design-principles)
- [Icon page](https://design-system.agriculture.gov.au/pr-preview/pr-1003/foundations/icons)

docs: Add design guidelines

---

docs/content/templates/single-page-form/index.mdx

Exposing design principles for single-page forms from Figma on our website
[Preview webpage](https://design-system.agriculture.gov.au/pr-preview/pr-1004/templates/single-page-form)

Templates: Documentation for Single-page form

---

.changeset/great-ties-sing.md
.storybook/stories/TableFiltering/ExampleMedium.test.tsx
.storybook/stories/TableFiltering/ExampleSmall.test.tsx
.storybook/stories/TableFiltering/components/DashboardTable.stories.tsx
.storybook/stories/TableFiltering/components/DashboardTable.tsx
.storybook/stories/TableFiltering/index.tsx
.storybook/stories/TableFiltering/lib/utils.test.ts
.storybook/stories/TableFiltering/lib/utils.ts
packages/react/src/table/Table.stories.tsx
packages/react/src/table/Table.test.tsx
packages/react/src/table/TableCell.tsx
packages/react/src/table/__snapshots__/Table.test.tsx.snap
packages/react/src/table/docs/overview.mdx

- TableCell component supports usage as a row header (`<TableCell as='th' scope='row'>`)
- Add `1 - 10 of 128 items` caption to Table filtering example
- Add aria-hidden to Avatar in Table filtering example

table: Support `TableCell`usage as row header

---

.changeset/plenty-maps-know.md
docs/components/designSystemComponents.tsx
packages/react/src/side-nav/SideNav.stories.tsx
packages/react/src/side-nav/SideNav.test.tsx
packages/react/src/side-nav/SideNav.tsx
packages/react/src/side-nav/SideNavContainer.tsx
packages/react/src/side-nav/SideNavGroup.tsx
packages/react/src/side-nav/SideNavLink.tsx
packages/react/src/side-nav/SideNavLinkList.tsx
packages/react/src/side-nav/SideNavTitle.tsx
packages/react/src/side-nav/__snapshots__/SideNav.test.tsx.snap
packages/react/src/side-nav/docs/overview.mdx
packages/react/src/side-nav/index.ts
packages/react/src/side-nav/test-utils.ts
packages/react/src/side-nav/utils.test.ts
packages/react/src/side-nav/utils.ts

In this PR, I have updated the interface of link list items as per latest designs.
- [Preview changes on docs site](https://design-system.agriculture.gov.au/pr-preview/pr-1023/components/side-nav)
- [Preview changes in storybook](https://design-system.agriculture.gov.au/pr-preview/pr-1023/storybook/index.html?path=/story/navigation-sidenav--basic)
I have also removed exports of "primitive components" (like SideNavContainer) etc and the "modular" storybook example. This was a thing we did very early on but have since removed from `MainNav` and other components.

side-nav: Update UI as per latest designs

---

docs/content/updates/2023-03-20.mdx

Add AgDS Beta v1.3.0 release notes.

Add AgDS Beta v1.3.0 release notes

---

.changeset/chilly-shirts-hammer.md
packages/react/src/avatar/Avatar.tsx
packages/react/src/avatar/__snapshots__/Avatar.test.tsx.snap

A div is not a valid child of certain elements (such as Button)
[See in Storybook](https://design-system.agriculture.gov.au/pr-preview/pr-1026/storybook/index.html?path=/story/content-avatar--composite-names)

avatar: Render a span component

---

.storybook/stories/TableFiltering/components/ActiveFilters.tsx
.storybook/stories/TableFiltering/lib/getData.ts

This PR simplifies some filtering logic in the data filtering medium pattern.

data-filtering: Update filtering logic for date filters

---

.changeset/sour-wombats-double.md
packages/react/src/skip-link/SkipLinkItem.tsx
packages/react/src/skip-link/__snapshots__/SkipLinks.test.tsx.snap

Added high z-index to ensure the element is always placed above other elements on the page.

skip-links: Add z-index

---

docs/content/foundations/design-guidelines.mdx
docs/content/templates/multi-page-form/index.mdx
packages/react/src/button/docs/overview.mdx

Adding final bits of general guidance from [Product Backlog Item 395162](https://dev.azure.com.mcas.ms/agriculturegovau/Digital%20Services/_workitems/edit/395162?McasTsid=26110): Migrate general guidance from Mural into website

docs: Additional general guidance

---

.changeset/itchy-spoons-suffer.md
packages/react/src/select/Select.tsx
packages/react/src/select/__snapshots__/Select.test.tsx.snap

Updated styles for disabled state to fix default browser styles overrides.
[Preview changes here](https://design-system.agriculture.gov.au/pr-preview/pr-1039/storybook/index.html?path=/story/forms-all--disabled-fields)

select: Updated styles for disabled state to fix default browser styles overrides.

---

docs/content/updates/2023-03-30.mdx

AgDS Beta v1.3.1 release notes.

AgDS Beta v1.3.1 release notes

---

.changeset/rare-jeans-burn.md
packages/react/src/badge/NotificationBadge.tsx

Add support for `aria-hidden` to NotificationBadge component.

badge: Add aria-hidden to NotificationBadge

---

packages/react/src/combobox/__snapshots__/ComboboxAsyncMulti.test.tsx.snap
packages/react/src/combobox/__snapshots__/ComboboxMulti.test.tsx.snap

This needed to be done after merging #1027 and #1041.

combobox: Regenerate snapshots

---

.storybook/stories/TableFiltering/ExampleMedium.test.tsx
.storybook/stories/TableFiltering/ExampleMedium.tsx
.storybook/stories/TableFiltering/ExampleSmall.test.tsx
.storybook/stories/TableFiltering/ExampleSmall.tsx
.storybook/stories/TableFiltering/components/DashboardTable.stories.tsx
.storybook/stories/TableFiltering/components/DashboardTable.tsx
.storybook/stories/TableFiltering/components/FilterBar.tsx
.storybook/stories/TableFiltering/index.tsx
.storybook/stories/TableFiltering/lib/useSortAndFilter.ts

- Remove logic to focus table when a filter is changed
- Improve types for DashboardTableHeaders
- Remove focus order hack to place Sort-by select
- Remove draft banners
[Preview in Storybook](https://design-system.agriculture.gov.au/pr-preview/pr-1050/storybook/index.html?path=/story/patterns-data-filtering-wip--medium)

Table filtering: Improvements and remove draft banner

---

docs/components/SiteFooter.tsx

Cleaning up the footer by removing an unnecessary link

Remove home from SiteFooter

---

docs/content/patterns/selecting-multiple-options/index.mdx
docs/lib/mdx/patterns.ts
docs/pages/patterns/[slug]/index.tsx

This PR adds content to our new "Selecting multiple options" pattern.
[View preview here](https://design-system.agriculture.gov.au/pr-preview/pr-1057/patterns/selecting-multiple-options).

docs: Add content for "Selecting multiple options" pattern

---

package.json
yarn.lock

Upgrade `@preconstruct/cli`

---

README.md
docs/README.md
example-form/README.md
example-site/README.md

- Updated root README
- Added README to workspaces

Improve repo documentation 

---

.changeset/friendly-owls-decide.md
packages/react/src/page-alert/PageAlert.tsx
packages/react/src/page-alert/__snapshots__/PageAlert.test.tsx.snap

Added flex growing to the content area.

page-alert: Grow content area 

---

.changeset/breezy-hornets-smell.md
packages/react/src/date-picker/Calendar.tsx
packages/react/src/date-picker/__snapshots__/Calendar.test.tsx.snap
packages/react/src/table/TableHeaderSortable.tsx

date-picker: Fixed text colour bug when using in dark palette
table: Fixed text colour bug when using `TableHeaderSortable` dark palette

date-picker,table: Fix dark palette text colour bug

---

docs/content/updates/2023-04-19.mdx

docs: Release 2023-04-19 release notes

---

docs/pages/roadmap.tsx

Updated roadmap to reflect latest changes.
[View preview](https://steelthreads.github.io/agds-next/pr-preview/pr-1070/roadmap)

docs: Update roadmap

---

.changeset/little-lizards-brush.md
packages/react/src/file-upload/FileUpload.tsx
packages/react/src/file-upload/docs/overview.mdx
packages/react/src/file-upload/utils.tsx

Added support for `application/xml` and `text/xml` mime types.

file-upload: Added support for `application/xml` and `text/xml` mime types.

---

docs/content/updates/2023-04-21.mdx

docs: 2023-04-21 release notes

---

.changeset/polite-spoons-yawn.md
packages/react/src/combobox/ComboboxAsyncMulti.tsx

Fixed exhaustive deps warning for the `onClear` function in `ComboboxAsyncMulti`. This must have been missed in #1072 .

combobox: Fixed exhaustive deps warning for the `onClear` function in `ComboboxAsyncMulti`

---

docs/pages/patterns/index.tsx

Fixes the following issue on the patterns page.

docs: Fix broken images

---

docs/content/foundations/accessibility.mdx

[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1085/foundations/accessibility#browser-support)

docs: Add list of browser support

---

.changeset/five-ears-divide.md
.storybook/stories/DataFiltering/components/ActiveFilters.tsx
.storybook/stories/DataFiltering/components/FilterAccordion.tsx
.storybook/stories/DataFiltering/lib/getData.ts
example-site/components/templates/SinglePageForm.tsx
packages/react/src/date-picker/Calendar.stories.tsx
packages/react/src/date-picker/DatePicker.stories.tsx
packages/react/src/date-picker/DateRangePicker.stories.tsx
packages/react/src/date-picker/DateRangePicker.test.tsx
packages/react/src/date-picker/docs/overview.mdx

This PR fixes a few issues with our examples of `DateRangePicker` component. 
These bugs include:
- Not validating that the start date is always before the end date
- Not using `onFromInputChange` and `onToInputChange` which keeps track of the date range picker text inputs
I have also upgraded to the date picker stories to Storybook CSF3.

date-picker: Fix `DateRangePicker` documentation bugs

---

packages/react/src/inpage-nav/InpageNav.stories.tsx
packages/react/src/inpage-nav/docs/rationale.mdx

- Add rationale page to Inpage nav documentation
- Document rationale for lack of nesting support in Inpage nav

inpage-nav: Document rationale for nesting support

---

.storybook/stories/DataFiltering/TableFilteringMedium.stories.tsx
.storybook/stories/DataFiltering/TableFilteringSmall.stories.tsx
.storybook/stories/DataLoading/DataLoadingWithCards.stories.tsx
.storybook/stories/DataLoading/DataLoadingWithTables.stories.tsx
packages/react/src/box/Box.stories.tsx
packages/react/src/box/Flex.stories.tsx
packages/react/src/box/Stack.stories.tsx
plop-templates/component/{{componentName}}.stories.tsx.hbs

- Implement new Storybook CSF3 format in box components and the plop template
- Resolve warning for using deprecated 'storyName' attribute

Implement new Storybook CSF3 - 1

---

.storybook/stories/DataFiltering/components/ActiveFilters.tsx

Added formatting to applied tags in the "Medium" table filtering example.

Fix applied tags formatting data table filtering medium example

---

.changeset/silly-brooms-drop.md
packages/react/src/header/HeaderBrand.tsx
packages/react/src/header/__snapshots__/Header.test.tsx.snap

Updated header branding link size to match content.
| <img width="638" alt="Screenshot 2023-05-08 at 5 33 55 pm" src="https://user-images.githubusercontent.com/6265154/236763903-85190a19-2df5-49e8-beaa-e6bb8359315b.png"> | <img width="638" alt="Screenshot 2023-05-08 at 5 33 30 pm" src="https://user-images.githubusercontent.com/6265154/236763889-a2587536-7679-48f2-98e6-e3fa4ce8ef46.png"> |
| <img width="1438" alt="Screenshot 2023-05-08 at 5 34 02 pm" src="https://user-images.githubusercontent.com/6265154/236764033-e987bd14-d94a-4aba-9227-e2055ca74fa0.png"> | <img width="1438" alt="Screenshot 2023-05-08 at 5 34 12 pm" src="https://user-images.githubusercontent.com/6265154/236764042-630218ce-895e-435a-9df9-faf0559757b5.png"> |

header: Update header branding link size

---

packages/react/src/app-layout/AppLayout.tsx
packages/react/src/app-layout/docs/overview.mdx

- Remove references to hide/show menu toggle which has been removed
- Add link to notification badge component 
- Move second image to match original designs

app-layout: Improve documentation

---

docs/content/updates/2023-05-08.mdx
docs/content/updates/2023-05-09.mdx

Release notes for AgDS Beta v1.5.0.

AgDS Beta v1.5.0 release notes

---

.changeset/fuzzy-icons-learn.md
packages/react/src/app-layout/AppLayoutHeaderAccount.tsx
packages/react/src/app-layout/__snapshots__/AppLayout.test.tsx.snap

Reduce spacing between user avatar and user name in App layout header.

app-layout: Reduce spacing between user avatar and user name in App layout header

---

.changeset/stale-guests-glow.md
packages/react/src/app-layout/AppLayoutSidebarDialog.tsx
packages/react/src/core/utils/index.ts
packages/react/src/core/utils/useId/index.ts

Fixed bug when server side rendering `AppLayoutSidebarDialog`

app-layout: Fix SSR bug

---

docs/content/updates/2023-05-15.mdx

Added release notes for AgDS Beta v1.5.1 release.

AgDS Beta v1.5.1 release notes

---

docs/content/patterns/selecting-multiple-options/index.mdx

The live code example in the [Selecting multiple options](https://design-system.agriculture.gov.au/patterns/selecting-multiple-options) page is currently broken.

docs: Fix bug in "Selecting multiple options" patterns

---

packages/react/src/file-input/docs/overview.mdx

file-input: Add dos and don'ts documentation

---

docs/content/patterns/filtering-a-dataset/index.mdx

Update pattern component documentation based off latest feedback.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1120/patterns/filtering-a-dataset)

docs: Update "Filtering a dataset" pattern documentation

---

docs/pages/components/[slug]/index.tsx

Resolves  [455481](https://dev.azure.com.mcas.ms/agriculturegovau/Digital%20Services/_workitems/edit/455481)

Fix 'Edit this Page' link for Component overview

---

packages/react/src/footer/docs/overview.mdx

note about logo use added to DOn't content

footer: Update documentation

---

packages/react/src/app-layout/docs/overview.mdx

some suggested edits to introduce references to focus and remove references only to multi-page forms

app-layout: Update documentation

---

packages/react/src/header/docs/overview.mdx

change to intro para to remove AFF brand reference - we use the logo not the colours of AFF so we need to remove

header: Update documentation

---

packages/react/src/main-nav/docs/overview.mdx

main-nav: Update documentation

---

packages/react/src/side-nav/docs/overview.mdx

removed
- only expand active subsections to help emphasise which section the user is in and to reduce visual complexity because we dont have an expandable side nav menu

side-nav: update documentation

---

packages/react/src/call-to-action/docs/overview.mdx

[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1133/components/call-to-action)

call-to-action: Update documentation

---

packages/react/src/control-input/docs/overview.mdx

typo and language changed in don't for consistency

control-input: Update documentation

---

packages/react/src/date-picker/docs/overview.mdx

date-picker: Update documentation

---

packages/react/src/control-input/docs/overview.mdx

Fixed broken live code snippet on the Control input documentation page.

control-input: Fix broken documentation example

---

packages/react/src/table/docs/overview.mdx

Add example of TableHeaderSortable in the Table component docs page.

table: Document TableHeaderSortable

---

packages/react/src/details/docs/overview.mdx

details: Update documentation

---

packages/react/src/badge/docs/overview.mdx

badge: Update documentation

---

packages/react/src/heading/docs/overview.mdx

intro para changed and export specific heading examples in Dos and Donts removed

heading: Update documentation

---

packages/react/src/page-alert/docs/overview.mdx

structure of the 'do' sentences has been adjusted
Intro paras for Info and Error alerts adjusted

page-alert: Update documentation

---

packages/react/src/file-upload/docs/overview.mdx

file-upload: Update documentation

---

docs/pages/about.tsx
docs/pages/roadmap.tsx

"Edit this page" is missing from these pages.

docs: Add "Edit this page" to roadmap and about page

---

packages/react/src/combobox/utils.test.ts
packages/react/src/combobox/utils.ts

Updated logic in the `filterOptions` helper function so options from a different array but with the same value are filtered out correctly.
- [View bug in Playroom (live site)](https://design-system.agriculture.gov.au/playroom/index.html#?code=N4Igxg9gJgpiBcIA8AlGA7WAnAfAHXQAJDgAKASkIF4cSDjjJ0BnAF0IG0A3AQwBsArjAA0hZjFYA1fkIC61Qmh5hWAOgHiAyqx6sYpDsEK9BMeITwgARpdF8eVmH3OWAQpcIBfWeQDc9BiwJASwiUgCGQiQAYQgAWysIRIAPAFkBPlYASwjIwntHPipLTScYFUJIAXRWLABPS1zIgAssmuKQbR4sdlY6gAc2gHNCVggxGBhCIOYM1mZGojziEyEqYFWYTyaGCHRo5p50IZh18SkZLZ3iCH7sveZ1jmuGI02XEB5bfIcnD4BBDyeYQvYhvS4fGwgOy-ZwWEDuEBeEFLZZg4wQ%2BFgb4FP7w6JAlFowiybaohgAenw5L8AU8ZKQFLQmBguAIIE8QA)
- [View fixed bug in Playroom (PR Preview)](https://design-system.agriculture.gov.au/pr-preview/pr-1175/playroom/index.html#?code=N4Igxg9gJgpiBcIA8AlGA7WA …

combobox: Updated selected options equality check

---

.changeset/soft-suits-wait.md
packages/react/src/combobox/utils.test.ts
packages/react/src/combobox/utils.ts

Updated logic in the `splitLabel` helper function so options with special characters (brackets, slashes etc) are handled correctly.
- [View bug in Playroom (live site)](https://design-system.agriculture.gov.au/playroom/index.html#?code=N4Igxg9gJgpiBcIA8AlGA7WAnAfAHXQAJjDgAKASkIF4dSCTC8AXSdAZ2cIG0A3AQwA2AVxgAaQuxjMAakNEBdGoTT8wzAHTCpAZWb9mMMumGDBFANwMSLLNOFYiZa8RYskAQWHMIkALYADoLSMC5MzG7MgvwARjCC1HggAGIAlpiEAJ4QDoSQwujMWJlJYZEsABbpzIkgevxYXMyZAekA5oQ%2BkjAwhHbspszspUQ2EeMCIjDUwJOiAL5l4ywQ6ADCFfzobdPAUrLyMIujrstREPxQAPIBzKmr7DP87JnoYIQAZgXq90SCF9dbr92GR0gFvHIplRgEtyswAPTwwg6VJ%2BUwGXr8ST-ADuhHQ0hxECwAGs8kJBLCzvwcfxUlwCXiAApYCB%2BVJSMhkfoQQS8GBUWjdZgAFVRMByzG5MHYvP5EgAjABWAAMKoolipkTszAcRG4s0O8EIAHJ%2BCaJNE4oJjSaABKpQhkHH0iqEGJYNQk6TsCgm%2BYKKwncKRebHRiReH4YMsTXBsMEJDwtCYGC4EDzIA)
- [View …

combobox: Fix filtering bug with special characters

---

packages/react/src/pagination/docs/overview.mdx

Updated do's and dont's content.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1179/components/pagination)

pagination: Update documentation

---

.changeset/seven-emus-hang.md
packages/react/src/app-layout/AppLayoutFooter.tsx
packages/react/src/app-layout/__snapshots__/AppLayout.test.tsx.snap

Updated `AppLayoutFooterDivider` border color from `border` to `borderMuted`.
[View preview]()

app-layout: Update footer divider color

---

docs/content/updates/2023-06-12.mdx

Add AgDS Beta v1.6.0 release notes

---

packages/react/src/divider/docs/overview.mdx

divider: Update documentation

---

docs/content/patterns/accessible-form-validation-and-recovery/index.mdx

Created new pattern "Accessible form validation and error recovery"
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1184/patterns/accessible-form-validation-and-recovery)

docs: Create new pattern "Accessible form validation and error recovery"

---

docs/content/about.mdx
docs/content/roadmap.mdx
docs/pages/about.tsx
docs/pages/roadmap.tsx

- Migrate [About page](https://design-system.agriculture.gov.au/pr-preview/pr-1199/about) to MDX
- Migrate [Roadmap page](https://design-system.agriculture.gov.au/pr-preview/pr-1199/roadmap) to MDX

docs: Migrate to mdx files

---

packages/react/src/divider/Divider.stories.tsx
packages/react/src/divider/docs/overview.mdx
packages/react/src/filter-drawer/FilterDrawer.stories.tsx
packages/react/src/filter-drawer/docs/overview.mdx

- Move `FilterDrawer` to `Layout` group
- Move `Divider` to `Content` group

docs: Update group for `Divider` and `FilterDrawer`

---

docs/pages/about.tsx
docs/pages/roadmap.tsx

docs: Migrate to mdx files 

---

.github/workflows/test.yml
.storybook/stories/KitchenSink.tsx

- Added step to our "Test" Github action to ensure storybook files are tested for correct linting
- Fixed errors in our Kitchen sink storybook file that were accidentally introduced in#1196 
- Added step to our "Test" Github action to ensure files in our "example-form" app  are tested for correct linting

Add storybook and example-form linting to test github action

---

docs/.env.development
docs/.env.production
packages/react/src/divider/docs/overview.mdx
packages/react/src/filter-drawer/docs/overview.mdx
packages/react/src/notification-badge/docs/overview.mdx
packages/react/src/status-badge/docs/overview.mdx

Updated all Figma lins to use the new gallery file.

Update Figma URL

---

packages/react/src/radio/docs/overview.mdx

radio: Update documentation

---

packages/react/src/date-range-picker/docs/overview.mdx

date-range-picker: Update documenttion

---

docs/components/TokenCharts.tsx

| <img width="514" alt="Screenshot 2023-06-27 at 8 37 04 am" src="https://github.com/steelthreads/agds-next/assets/6265154/4706fdf7-d49f-4d83-bf4d-f9cbb80ef7e8"> | <img width="522" alt="Screenshot 2023-06-27 at 8 36 58 am" src="https://github.com/steelthreads/agds-next/assets/6265154/3d4caa6e-c642-4f44-b614-2e459f602439"> |

docs: Center align Border width values in tokens section

---

packages/react/src/checkbox/docs/overview.mdx
packages/react/src/date-range-picker/docs/overview.mdx

- [Updated Checkbox](https://design-system.agriculture.gov.au/pr-preview/pr-1224/components/checkbox)
- [Updated Date picker](https://design-system.agriculture.gov.au/pr-preview/pr-1224/components/date-picker)
- [Updated Date range picker](https://design-system.agriculture.gov.au/pr-preview/pr-1224/components/date-picker)
- [Updated Radio](https://design-system.agriculture.gov.au/pr-preview/pr-1224/components/radio)

docs: Update figma gallery urls

---

docs/package.json
yarn.lock

Upgrade next-mdx-remote

---

packages/react/src/status-badge/docs/overview.mdx

I have added a 'dont' point to emphasise the use case in an attempt to stop this being used incorrectly. If this is too repetitive or inconsistent with guidance else where we need to strengthen the language of the original dot point to say 'only use the 'subtle'...

status-badge: Update documentation

---

.changeset/breezy-suits-drum.md
packages/react/src/app-layout/AppLayout.stories.tsx
packages/react/src/app-layout/AppLayout.tsx
packages/react/src/app-layout/AppLayoutHeader.tsx
packages/react/src/app-layout/AppLayoutHeaderNav.tsx
packages/react/src/app-layout/AppLayoutSidebar.tsx
packages/react/src/app-layout/AppLayoutSidebarDialog.tsx
packages/react/src/app-layout/__snapshots__/AppLayout.test.tsx.snap
packages/react/src/app-layout/docs/overview.mdx
packages/react/src/app-layout/utils.ts

Change responsive behaviour, so that the two column layout is visible in the extra large breakpoint. This ensures devices between 996px and 1200px aren't too tight.
[Link to preview](https://design-system.agriculture.gov.au/pr-preview/pr-1213/storybook/index.html?path=/story/templates-single-page-form--in-app-form-page)

app-layout: Change responsive behaviour

---

packages/react/src/field/docs/overview.mdx

reference to input format added

field: Update documentation

---

docs/content/patterns/accessible-form-validation-and-recovery/index.mdx

added specific position Do content

Update "Accessible form validation and error recovery" pattern

---

.changeset/young-rivers-behave.md
packages/react/src/combobox/ComboboxBase/ComboboxListItem.tsx
packages/react/src/combobox/defaultRenderItem.tsx

- Ensured text is black and underlined when hovered or 'active'

combobox: Improved hover styles

---

.changeset/few-jobs-tie.md
packages/react/src/table/Table.stories.tsx
packages/react/src/table/TableCell.tsx
packages/react/src/table/docs/overview.mdx

Added example with table actions.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1238/components/table)

table: Add `actions` docs example

---

docs/content/updates/2023-07-11.mdx

AgDS Beta v1.7.0 release notes.

AgDS Beta v1.7.0 release notes

---

docs/next-sitemap.config.js

Ensure all pages under `/pr-preview/` are not crawled by google.

Disallow crawling of PR preview

---

.github/workflows/preview.yml
docs/components/PullRequestPreviewBanner.tsx
docs/components/SiteLayout.tsx
docs/next.config.js

Add PR Preview banner

---

.changeset/tricky-peas-hug.md
packages/react/src/app-layout/AppLayout.stories.tsx
packages/react/src/app-layout/AppLayout.test.tsx
packages/react/src/app-layout/AppLayoutSidebar.tsx
packages/react/src/app-layout/__snapshots__/AppLayout.test.tsx.snap
packages/react/src/app-layout/test-utils.tsx
packages/react/src/core/utils/findBestMatch.test.ts
packages/react/src/core/utils/findBestMatch.ts
packages/react/src/core/utils/index.ts
packages/react/src/main-nav/MainNav.test.tsx
packages/react/src/main-nav/MainNav.tsx
packages/react/src/main-nav/__snapshots__/MainNav.test.tsx.snap
packages/react/src/main-nav/utils.ts
packages/react/src/sub-nav/SubNav.stories.tsx
packages/react/src/sub-nav/SubNav.test.tsx
packages/react/src/sub-nav/SubNav.tsx
packages/react/src/sub-nav/__snapshots__/SubNav.test.tsx.snap

- Deduplicated use of `findBestMatch` from navigational components and moved into the `core` entrypoint.
- Used `findBestMatch` utility function to ensure nav items are highlighted correctly based on the `activePath`.
- Used `findBestMatch` utility function to ensure nav items are highlighted correctly based on the `activePath`.

Add `findBestMatch` utility and update nav components

---

docs/content/updates/2023-07-12.mdx

AgDS Beta v1.7.1 release notes.

AgDS Beta v1.7.1 release notes

---

.changeset/blue-knives-change.md
.changeset/selfish-spoons-tan.md
.storybook/stories/KitchenSink.tsx
docs/components/designSystemComponents.tsx
docs/playroom/snippets.ts
packages/react/package.json
packages/react/src/accordion/docs/overview.mdx
packages/react/src/button/BaseButton.tsx
packages/react/src/details/docs/overview.mdx
packages/react/src/sub-nav/docs/overview.mdx
packages/react/src/tabs/Tab.tsx
packages/react/src/tabs/TabButton.tsx
packages/react/src/tabs/TabList.tsx
packages/react/src/tabs/TabListContext.tsx
packages/react/src/tabs/TabPanel.tsx
packages/react/src/tabs/TabPanels.tsx
packages/react/src/tabs/TabPanelsContext.tsx
packages/react/src/tabs/Tabs.stories.tsx
packages/react/src/tabs/Tabs.test.tsx
packages/react/src/tabs/Tabs.tsx
packages/react/src/tabs/TabsContext.tsx
packages/react/src/tabs/__snapshots__/Tabs.test.tsx.snap
packages/react/src/tabs/docs/accessibility.mdx
packages/react/src/tabs/docs/code.mdx
packages/react/src/tabs/docs/overview.mdx
packages/react/src/tabs/index.ts
packages/react/src/tabs/localPalette.ts
packages/react/src/tabs/utils.ts
packages/react/tabs/package.json
yarn.lock

Created new `Tabs` component.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1232/components/tabs)

Create new `Tabs` component

---

packages/react/src/tabs/docs/overview.mdx

Hi @jordanoverbye can you sense check and edit this if you feel it needs improvement?

tabs: Update documentation

---

packages/react/src/direction-link/docs/overview.mdx

direction-link: Update documenation

---

.changeset/smooth-eels-dress.md
.storybook/stories/KitchenSink.tsx
packages/react/src/global-alert/GlobalAlert.stories.tsx
packages/react/src/global-alert/GlobalAlert.test.tsx
packages/react/src/global-alert/GlobalAlert.tsx
packages/react/src/global-alert/GlobalAlertCloseButton.tsx
packages/react/src/global-alert/__snapshots__/GlobalAlert.test.tsx.snap
packages/react/src/global-alert/docs/overview.mdx

- Visual refresh of GlobalAlert component
- Add support for 'info' tone
- Anchor dismiss button to top-right for mobile devices.
- Relabel 'Dismiss' button to 'Close'
- [Storybook](https://design-system.agriculture.gov.au/pr-preview/pr-1256/storybook/index.html?path=/story/content-globalalert--basic)
- [Docs](https://design-system.agriculture.gov.au/pr-preview/pr-1256/components/global-alert)

global-alert: Visual refresh

---

.changeset/nasty-sloths-teach.md
packages/react/src/core/utils/useClickOutside.ts
packages/react/src/date-picker/DatePicker.tsx
packages/react/src/date-range-picker/DateRangePicker.tsx

core: Extended utility function `useClickOutside` to accept multiple refs.
This is required for #1236

core: Extended utility function `useClickOutside` to accept multiple refs

---

packages/react/src/checkbox/docs/overview.mdx

checkbox: Update documentation

---

packages/react/src/page-alert/docs/overview.mdx

Add examples of a dismissable Page alert to documentation.
[Preview link](https://design-system.agriculture.gov.au/pr-preview/pr-1274/components/page-alert#dismissable)

page-alert: Add example for dismissing

---

.changeset/dirty-houses-mix.md
packages/react/src/app-layout/AppLayoutHeader.tsx
packages/react/src/app-layout/__snapshots__/AppLayout.test.tsx.snap
packages/react/src/box/styles.ts
packages/react/src/footer/Footer.tsx
packages/react/src/footer/FooterDivider.tsx
packages/react/src/footer/__snapshots__/Footer.test.tsx.snap
packages/react/src/footer/localPalette.ts
packages/react/src/main-nav/MainNavBottomBar.tsx
packages/react/src/main-nav/NavContainer.tsx
packages/react/src/main-nav/__snapshots__/MainNav.test.tsx.snap
packages/react/src/main-nav/utils.ts
packages/react/src/sub-nav/utils.ts

This PR extends the `Box` component so borders can be applied with the `accent` colour. For example:
```tsx
<Box borderBottom borderBottomWidth="xxl" borderColor="accent">
Hello world
</Box>
```
[Preview Box in Playroom](https://design-system.agriculture.gov.au/pr-preview/pr-1185/playroom/index.html#?code=N4Igxg9gJgpiBcIA8AFAhgcxgYQgOwBcZCA%2BAHTwAJKkAhCAD0oCMIAnWN%2BggiAWxbtO3XnwDqASygEAFgF4yIBgwA2iwRxhtcK9gpBowYYgXUAHNFCgS8GOcACMAX3JVqlABIwVuygHd2FSgKaiQAenoGV3D0LFxCE1cQJyA)
- [Preview App layout](https://design-system.agriculture.gov.au/pr-preview/pr-1185/storybook/index.html?path=/story/layout-applayout--default)
- [Preview Footer](https://design-system.agriculture.gov.au/pr-preview/pr-1185/storybook/index.html?path=/story/layout-footer--body-background)
- [Preview Main …

box: Add `accent` to border color prop

---

.changeset/silent-eagles-press.md
packages/react/src/app-layout/AppLayoutSidebarDialog.tsx
packages/react/src/filter-drawer/FilterDrawer.tsx

app-layout: Fixed usage of `useTransition` by `@react-spring/web` to ensure compatibility with latest version.
filter-drawer: Fixed usage of `useTransition` by `@react-spring/web` to ensure compatibility with latest version.
- [ x Run `yarn lint` in the root of the repository to ensure linting tests are passing

Fixed usage of `useTransition` by `@react-spring/web` 

---

docs/content/updates/2023-07-14.mdx
docs/content/updates/2023-07-24.mdx

AgDS Beta v1.9.0 release notes.

AgDS Beta v1.9.0 release notes

---

RELEASE.md
docs/components/PkgLayout.tsx
docs/lib/mdx/packages.ts
plop-templates/component/docs/overview.mdx.hbs

docs: Show unreleased components

---

packages/react/src/side-nav/SideNav.test.tsx

Add a test which ensures that the nav is labelled with the title.
Doing before: #1273

side-nav: Add test to ensure accessible title on nav

---

.storybook/stories/DataFiltering/lib/getData.ts
.storybook/stories/DataFiltering/lib/useSortAndFilter.ts

In the table filtering examples, we are consolidating multiple useState hooks into one useReducer.

Filter pattern: Consolidate states into a reducer

---

packages/react/src/dropdown-menu/docs/overview.mdx

change to first Do point added

dropdown-menu: Update documentation

---

.storybook/stories/DataFiltering/TableFilteringLarge.tsx
.storybook/stories/DataFiltering/TableFilteringLargeExample.tsx
.storybook/stories/DataFiltering/TableFilteringMedium.test.tsx
.storybook/stories/DataFiltering/TableFilteringMedium.tsx
.storybook/stories/DataFiltering/TableFilteringMediumExample.tsx
.storybook/stories/DataFiltering/TableFilteringSmall.test.tsx
.storybook/stories/DataFiltering/TableFilteringSmall.tsx
.storybook/stories/DataFiltering/TableFilteringSmallExample.tsx
.storybook/stories/DataFiltering/components/ActiveFilters.tsx
.storybook/stories/DataFiltering/components/DashboardFilterDrawer.tsx
.storybook/stories/DataFiltering/components/DashboardPagination.tsx
.storybook/stories/DataFiltering/components/DashboardTable.stories.tsx
.storybook/stories/DataFiltering/components/DashboardTable.tsx
.storybook/stories/DataFiltering/components/FilterAccordion.tsx
.storybook/stories/DataFiltering/components/FilterAssigneeSelect.tsx
.storybook/stories/DataFiltering/components/FilterSearchInput.tsx
.storybook/stories/DataFiltering/components/FilterStateSelect.tsx
.storybook/stories/DataFiltering/components/FilterStatusSelect.tsx
.storybook/stories/DataFiltering/components/SortBySelect.tsx
.storybook/stories/DataFiltering/lib/SortAndFilterContext.tsx
.storybook/stories/DataFiltering/lib/contexts.tsx
.storybook/stories/DataFiltering/lib/getData.ts
.storybook/stories/DataFiltering/lib/useSortAndFilter.ts
.storybook/stories/DataFiltering/lib/utils.ts

Implementing contexts in the table filtering examples, to eliminate prop-drilling.
- SortAndFilterProvider: for sort, filter and pagination state
- DataProvider: for data, and whether data is loading

Refactor Filter pattern examples to use context

---

docs/content/about.mdx

LICENSE does not have an `.md` extension

docs: Update link to license

---

.changeset/quiet-students-hammer.md
packages/react/src/tabs/TabPanel.tsx
packages/react/src/tabs/__snapshots__/Tabs.test.tsx.snap

Increased vertical padding in the tab panel on mobile devices.

tabs: Update panel padding

---

docs/components/designSystemComponents.tsx
docs/playroom/snippets.ts

Add boilerplate snippet for App layout.

app-layout: Add playroom snippet

---

.storybook/stories/KitchenSink.tsx
packages/react/src/dropdown-menu/DropdownMenuGroup.tsx
packages/react/src/dropdown-menu/DropdownMenuItem.tsx
packages/react/src/dropdown-menu/DropdownMenuItemRadio.tsx
packages/react/src/dropdown-menu/__snapshots__/DropdownMenu.test.tsx.snap

Small pull request to address some design feedback from @adhamdannawayaff 
- Group headings should be bold
- Menu items shouldn't be underlined (only on hover)
- Icons in dropdown menu items should change colour to match the text

dropdown-menu: Update styles

---

.changeset/early-ladybugs-fold.md
packages/react/src/date-picker/__snapshots__/Calendar.test.tsx.snap
packages/react/src/date-picker/reactDayPickerStyles.ts

Adjust the hover state of the Calendar component to ensure we aren't using (background) colour alone to communicate the interaction
- Add an underline
- Change text colour to black

date-picker: Update hover state styles in Calendar

---

docs/components/TokenCharts.tsx
docs/components/mdxComponents.tsx
docs/content/foundations/tokens/spacing.mdx
docs/pages/foundations/tokens/spacing.tsx

- Added documentation for when to use 12px spacing
- Converted spacing document to MDX for easier future editing
[View changes](https://design-system.agriculture.gov.au/pr-preview/pr-1304/foundations/tokens/spacing)

docs: Spacing documentation update

---

docs/playroom/snippets.ts
packages/react/src/heading/docs/overview.mdx
packages/react/src/link-list/docs/overview.mdx
packages/react/src/list/OrderedList.stories.tsx
packages/react/src/list/UnorderedList.stories.tsx
packages/react/src/list/docs/overview.mdx
packages/react/src/prose/docs/overview.mdx
packages/react/src/text/docs/overview.mdx

Lists feedback

---

.changeset/spotty-hairs-kiss.md
packages/react/src/app-layout/AppLayoutSidebarNav.tsx
packages/react/src/app-layout/__snapshots__/AppLayout.test.tsx.snap

Decreased border left width of active item in sidebar from 8px to 4px.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1309/storybook/index.html?path=/story/layout-applayout--default)

app-layout: Update border width of active item

---

package.json
yarn.lock

Upgrade `html-validate` from version 7 to 8.

Upgrade `html-validate`

---

packages/react/src/file-input/docs/overview.mdx

Mentioned by Ryan during Office Hours.

file-input: Remove double-negative from docs

---

.storybook/stories/DataFiltering/TableFilteringMedium.test.tsx
.storybook/stories/DataFiltering/TableFilteringSmall.test.tsx

Updated table filtering tests in an attempt to improve the performance of these tests. While this is an improvement, this pull request hasn't changed anything dramatically.

Update table filtering tests

---

packages/react/src/progress-indicator/docs/overview.mdx

@jordanoverbye can you please review and commit this change if you agree.

progress-indicator: Update documentation

---

packages/react/src/autocomplete/Autocomplete.test.tsx
packages/react/src/combobox/ComboboxBase/ComboboxButtons.tsx
packages/react/src/combobox/__snapshots__/Combobox.test.tsx.snap
packages/react/src/combobox/__snapshots__/ComboboxAsync.test.tsx.snap
packages/react/src/combobox/__snapshots__/ComboboxAsyncMulti.test.tsx.snap
packages/react/src/combobox/__snapshots__/ComboboxMulti.test.tsx.snap
packages/react/src/combobox/useAsync.ts

- Fixed console.log which was accidentally merged in #PR 1327
- Fixed icon position that was changed in #1318 
[View preview](https://design-system.agriculture.gov.au/pr-preview/PR-1339/components/combobox)

combobox: Revert icon position change

---

.changeset/sixty-files-rest.md
docs/components/designSystemComponents.tsx
packages/react/src/checkbox/CheckboxIndicator.tsx
packages/react/src/checkbox/__snapshots__/Checkbox.test.tsx.snap
packages/react/src/control-group/__snapshots__/ControlGroup.test.tsx.snap
packages/react/src/icon/__snapshots__/Icon.test.tsx.snap
packages/react/src/icon/icons/CheckIcon.tsx
packages/react/src/icon/index.ts
packages/react/src/icon/utils.tsx
packages/react/src/switch/SwitchTrack.tsx

- Added new `CheckIcon` to the icon library. 
- Replaced custom icon in `Checkbox` and `Switch` with new icon
| Component | Before | After |
|--------|--------|--------|
| Checkbox | [View before](https://design-system.agriculture.gov.au/components/checkbox) | [View after](https://design-system.agriculture.gov.au/pr-preview/pr-1277/components/checkbox) |
| Switch | [View before](https://design-system.agriculture.gov.au/components/switch) | [View after](https://design-system.agriculture.gov.au/pr-preview/pr-1277/components/switch)

icon: Add new `Check` icon

---

.github/pull_request_template.md
docs/content/patterns/accessible-form-validation-and-recovery/index.mdx
docs/content/patterns/conditional-reveal/index.mdx
docs/content/patterns/filtering-a-dataset/index.mdx
docs/content/patterns/loading-error-empty-states/index.mdx
docs/content/patterns/selecting-multiple-options/index.mdx
docs/lib/mdx/packages.ts
docs/lib/mdx/patterns.ts
docs/pages/components/[slug]/index.tsx
docs/pages/patterns/[slug].tsx
packages/react/src/checkbox/docs/overview.mdx
packages/react/src/combobox/docs/overview.mdx
packages/react/src/filter-drawer/docs/overview.mdx
packages/react/src/loading/docs/overview.mdx
packages/react/src/page-alert/docs/overview.mdx
packages/react/src/pagination/docs/overview.mdx
packages/react/src/radio/docs/overview.mdx
packages/react/src/skeleton/docs/overview.mdx

[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1341/components/page-alert)
**Preflight**
**Testing**

docs: Add related patterns

---

.storybook/stories/DataFiltering/TableFilteringLarge.tsx
.storybook/stories/DataFiltering/TableFilteringMedium.tsx
.storybook/stories/DataFiltering/TableFilteringSmall.tsx
.storybook/stories/DataFiltering/components/ActiveFilters.tsx
.storybook/stories/DataFiltering/components/DashboardFilterDrawer.tsx
.storybook/stories/DataFiltering/components/DataTable.stories.tsx
.storybook/stories/DataFiltering/components/DataTable.tsx
.storybook/stories/DataFiltering/components/FilterAssigneeSelect.tsx
.storybook/stories/DataFiltering/components/FilterDestinationsSelect.tsx
.storybook/stories/DataFiltering/components/FilterSearchInput.tsx
.storybook/stories/DataFiltering/components/FilterServicesSelect.tsx
.storybook/stories/DataFiltering/components/FilterStateSelect.tsx
.storybook/stories/DataFiltering/components/FilterStatusSelect.tsx
.storybook/stories/DataFiltering/components/SortBySelect.tsx
.storybook/stories/DataFiltering/lib/generateBusinessData.ts
.storybook/stories/DataFiltering/lib/getData.ts
.storybook/stories/DataFiltering/lib/useSortAndFilter.ts
.storybook/stories/DataFiltering/lib/utils.test.ts
.storybook/stories/DataFiltering/lib/utils.ts

Made some minor improvements to the table filtering code, to prepare for (and decrease the diff in) #1146 
- Add Destination and Service fields to generated data (multi-select)
- Rename DashboardTable to DataTable (to compliment DataList in #1146)
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1357/storybook)
**Preflight**
**Testing**

Table filtering: Add multi-select filters

---

docs/playroom/snippets.ts

Duplicating existing snippets for Checkbox and Radio, so they are searchable by the word 'Control group'
[View Playroom](https://design-system.agriculture.gov.au/pr-preview/pr-1358/playroom)
**Preflight**
**Testing**

Playroom: Create snippets for Control group

---

.changeset/sixty-files-rest.md
docs/components/designSystemComponents.tsx
docs/content/content/content-patterns.mdx
docs/content/foundations/design-principles.mdx
docs/content/patterns/loading-error-empty-states/index.mdx
docs/pages/foundations/tokens/typography.tsx
packages/react/src/accordion/docs/content.mdx
packages/react/src/button/docs/content.mdx
packages/react/src/card/docs/content.mdx
packages/react/src/card/docs/overview.mdx
packages/react/src/checkbox/CheckboxIndicator.tsx
packages/react/src/checkbox/__snapshots__/Checkbox.test.tsx.snap
packages/react/src/combobox/docs/overview.mdx
packages/react/src/control-group/__snapshots__/ControlGroup.test.tsx.snap
packages/react/src/details/docs/accessibility.mdx
packages/react/src/details/docs/content.mdx
packages/react/src/details/docs/overview.mdx
packages/react/src/file-upload/docs/overview.mdx
packages/react/src/icon/__snapshots__/Icon.test.tsx.snap
packages/react/src/icon/icons/CheckIcon.tsx
packages/react/src/icon/index.ts
packages/react/src/icon/utils.tsx
packages/react/src/status-badge/docs/content.mdx
packages/react/src/switch/SwitchTrack.tsx

Implementing some documentation which Sarah and Yvette prepared a while ago, in the following components:
- Card
- Combobox
- Details
- FileUpload
- Status badge
- Typography
Also added some documentation to Loading/Error pattern page, content patterns, design principles

docs: General component documentation improvements (2)

---

docs/content/content/content-principles.mdx
docs/content/guides/how-to-write-guidance/about-this-guide.mdx
docs/content/guides/how-to-write-guidance/types-of-content.mdx
packages/react/src/accordion/docs/content.mdx
packages/react/src/button/docs/content.mdx
packages/react/src/status-badge/docs/content.mdx

[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1363)
**Preflight**
**Testing**

Documentation change

---

.changeset/slimy-baboons-tap.md
packages/react/src/autocomplete/__snapshots__/Autocomplete.test.tsx.snap
packages/react/src/combobox/Combobox.tsx
packages/react/src/combobox/ComboboxAsync.tsx
packages/react/src/combobox/ComboboxBase/ComboboxBase.tsx
packages/react/src/combobox/ComboboxBase/ComboboxSearchIcon.tsx
packages/react/src/search-input/__snapshots__/SearchInput.test.tsx.snap

autocomplete: Add search icon

---

packages/react/src/modal/Modal.stories.tsx

Added two more Storybook examples for the Modal component. 
- [View Confirming Form Cancellation](https://design-system.agriculture.gov.au/pr-preview/pr-1371/storybook/?path=/story/content-modal--confirming-form-cancellation)
- [View Confirming Destructive Action](https://design-system.agriculture.gov.au/pr-preview/pr-1371/storybook/?path=/story/content-modal--confirming-destructive-action)

modal: Add more stories

---

packages/react/src/accordion/docs/content.mdx
plop-templates/component/docs/accessibility.mdx.hbs
plop-templates/component/docs/content.mdx.hbs
plop-templates/component/docs/overview.mdx.hbs
plop-templates/component/docs/rationale.mdx.hbs

Creating some guidance and boilerplate content to help write better and more consistent component documentation.

Templates for generating component docs

---

.storybook/stories/KitchenSink.tsx

Small change to the kitchen-sink, to make the background control actually change the background
[View storybook](https://design-system.agriculture.gov.au/pr-preview/pr-1377/storybook/index.html?path=/story/testing-kitchen-sink--wesbsite-layout&args=background:bodyAlt&globals=palette:dark)

kitchen-sink: Implement page bg and onBodyAlt prop

---

.storybook/stories/DataFiltering/ListFiltering.tsx
docs/pages/components/index.tsx
packages/react/src/_collapsing-side-bar/CollapsingSideBar.tsx
packages/react/src/filter-sidebar/FilterSidebar.tsx
packages/react/src/filter-sidebar/__snapshots__/FilterSidebar.test.tsx.snap
packages/react/src/filter-sidebar/docs/overview.mdx
packages/react/src/progress-indicator/ProgressIndicator.tsx

Clear filters button in Filter sidebar

---

packages/react/src/callout/docs/overview.mdx

content edits to reduce confusion with section alert
**Preflight**
**Testing**

callout: Update documentation

---

packages/react/src/page-alert/docs/overview.mdx

Typo in page-alert docs

---

.changeset/plop-create-section-alert.md
.storybook/stories/KitchenSink.tsx
docs/components/designSystemComponents.tsx
docs/components/pictograms/index.tsx
docs/playroom/snippets.ts
packages/react/section-alert/package.json
packages/react/src/global-alert/docs/overview.mdx
packages/react/src/page-alert/docs/overview.mdx
packages/react/src/section-alert/SectionAlert.stories.tsx
packages/react/src/section-alert/SectionAlert.test.tsx
packages/react/src/section-alert/SectionAlert.tsx
packages/react/src/section-alert/SectionAlertDismissButton.tsx
packages/react/src/section-alert/__snapshots__/SectionAlert.test.tsx.snap
packages/react/src/section-alert/docs/code.mdx
packages/react/src/section-alert/docs/content.mdx
packages/react/src/section-alert/docs/overview.mdx
packages/react/src/section-alert/index.ts
packages/react/src/section-alert/utils.tsx
scripts/plopfile.mjs

Create a new Section-alert component - an alternative to Page-alert that can be use in sections of pages.
- [Storybook](https://design-system.agriculture.gov.au/pr-preview/pr-1167/storybook/index.html?path=/story/content-sectionalert--success)
- [Documentation page](https://design-system.agriculture.gov.au/pr-preview/pr-1167/components/section-alert)

section-alert: Create new component

---

docs/content/updates/2023-09-22.mdx
packages/react/CHANGELOG.md

Added release notes to the website

Release notes for September 22 2023

---

packages/react/src/filter-sidebar/docs/overview.mdx

This was left in after the last release

filter-sidebar: Remove unreleased flag

---

.changeset/eighty-colts-beam.md
packages/react/src/app-layout/AppLayout.stories.tsx
packages/react/src/app-layout/AppLayout.test.tsx
packages/react/src/app-layout/AppLayoutSidebar.stories.tsx
packages/react/src/app-layout/AppLayoutSidebarNav.tsx
packages/react/src/app-layout/__snapshots__/AppLayout.test.tsx.snap
packages/react/src/app-layout/test-utils.tsx
packages/react/src/app-layout/utils.ts

This PR adds support for displaying the active business name and ABN by allowing text-only sidebar navigation items in `AppLayoutSidebar`. This can be achieved by not passing a `href` OR an `onClick` to a navigation list item. 
This change is backwards compatible, plus allows other text based list items in other areas of the sidebar that haven't been thought of yet.
Since the next version of App layout will be released very shortly, I feel that this is a good time to re-apply the changes that were reverted recently. The changes that have been reverted are: 
- Decreased the width of the `AppLayoutSidebar` from `17.5rem` to `16rem` (re-apply PR #1319)
- Decreased the gap between icons and labels in `AppLayoutSidebar` from `1rem` to `0.75rem` (re-apply PR #1348 )
- Decreased border left …

app-layout: Add support for business name in sidebar

---

.changeset/early-hounds-fix.md
packages/react/src/file-upload/utils.tsx

Add support for the `application/vnd.ms-outlook` MIME type
[View storybook preview]
**Preflight**
**Testing**

file-upload: Add support for `application/vnd.ms-outlook` MIME type

---

docs/content/updates/2023-09-22.mdx
docs/content/updates/2023-09-27.mdx

AgDS Beta v1.12.0 release notes
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1401/updates)

AgDS Beta v1.12.0 release notes

---

.changeset/gentle-zebras-chew.md
.changeset/plop-create-FileIcon.md
docs/components/designSystemComponents.tsx
packages/react/src/file-upload/FileUpload.stories.tsx
packages/react/src/file-upload/FileUpload.test.tsx
packages/react/src/file-upload/FileUpload.tsx
packages/react/src/file-upload/FileUploadFile.stories.tsx
packages/react/src/file-upload/FileUploadFile.tsx
packages/react/src/file-upload/FileUploadFileList.stories.tsx
packages/react/src/file-upload/FileUploadFileList.tsx
packages/react/src/file-upload/FileUploadFileThumbnail.tsx
packages/react/src/file-upload/FileUploadRejectedFile.stories.tsx
packages/react/src/file-upload/FileUploadRejectedFile.tsx
packages/react/src/file-upload/FileUploadRejectedFileList.stories.tsx
packages/react/src/file-upload/FileUploadRejectedFileList.tsx
packages/react/src/file-upload/__snapshots__/FileUpload.test.tsx.snap
packages/react/src/file-upload/test-utils.ts
packages/react/src/file-upload/utils.test.tsx
packages/react/src/file-upload/utils.tsx
packages/react/src/icon/__snapshots__/Icon.test.tsx.snap
packages/react/src/icon/icons/FileIcon.tsx
packages/react/src/icon/index.ts
packages/react/src/icon/utils.tsx

- Add support for image thumbnails in FileUploadFile and FileUploadRejectedFile
- Refactored FileUpload to pass `File[]` to FileUploadFile and FileUploadRejectedFile
- Added `FileIcon` to Icon set
[View Storybook](https://design-system.agriculture.gov.au/pr-preview/pr-1399/storybook/?path=/story/forms-fileupload-primitives-fileuploadfile--basic)
**Preflight**
**Testing**

file-upload: Add thumbnails for image files.

---

docs/components/designSystemComponents.tsx
packages/react/src/file-upload/docs/overview.mdx

Fix missing documentation for `hideThumbnails` prop

file-upload: Update docs

---

docs/content/updates/2023-10-04.mdx

AgDS Beta v1.13.0 release notes

AgDS Beta v1.13.0 release notes

---

yarn.lock

Upgraded PostCSS to version `8.4.31` which should resolve Security Issue https://github.com/steelthreads/agds-next/security/dependabot/55
This PR is based off PR #1417

Upgrade PostCSS

---

.changeset/nervous-scissors-flash.md
packages/react/src/app-layout/AppLayoutHeaderNav.tsx

[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1423)
**Preflight**
**Testing**

app-layout: Focus mode menu button

---

.changeset/two-roses-reply.md
packages/react/src/app-layout/__snapshots__/AppLayout.test.tsx.snap
packages/react/src/dropdown-menu/DropdownMenu.tsx
packages/react/src/dropdown-menu/DropdownMenuButton.tsx
packages/react/src/dropdown-menu/DropdownMenuContext.tsx
packages/react/src/dropdown-menu/DropdownMenuPanel.tsx
packages/react/src/dropdown-menu/reducer.tsx

Thanks to @lukebennett88 for providing these changes!
- Improved accessibility by ensuring that the `DropdownMenuButton` component always has a valid `aria-controls` attribute
- Improved accessibility by allowing users to press `Enter`, `Space`, `ArrowDown` or `ArrowUp` keys to open up the dropdown menu and activate a child descendant
- Fixed a bug where keyboard shortcuts couldn't be used when the dropdown menu was open - e.g. refresh the page using cmd + r.
- Improved accessibility by significantly improving the logic for searching for a child descendant
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1409/components/dropdown-menu)
**Preflight**
**Testing**

dropdown-menu: Small a11y improvements

---

.storybook/stories/DataFiltering/TableFiltering.stories.tsx
.storybook/stories/DataFiltering/components/DataTable.tsx
.storybook/stories/DataFiltering/lib/getData.ts
.storybook/stories/DataFiltering/lib/useFetchData.ts

- Implement an empty state in the DataTable component, which follows our patterns
- Implement an error state in the DataTable component, which follows our patterns. This is triggered by a `throwError` boolean in the Storybook controls
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1427/storybook/index.html?path=/story/patterns-tables--filter-medium)
**Preflight**
**Testing**

table-filtering: Implement error and empty states

---

.changeset/four-elephants-share.md
packages/react/src/_popover/Popover.tsx
packages/react/src/autocomplete/__snapshots__/Autocomplete.test.tsx.snap
packages/react/src/combobox/Combobox.tsx
packages/react/src/combobox/ComboboxBase/ComboboxBase.tsx
packages/react/src/combobox/ComboboxBase/ComboboxMultiBase.tsx
packages/react/src/combobox/__snapshots__/Combobox.test.tsx.snap
packages/react/src/combobox/__snapshots__/ComboboxAsync.test.tsx.snap
packages/react/src/combobox/__snapshots__/ComboboxAsyncMulti.test.tsx.snap
packages/react/src/combobox/__snapshots__/ComboboxMulti.test.tsx.snap

Improved internal positioning of Combobox component.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1428/components/combobox)
https://github.com/steelthreads/agds-next/assets/6265154/2210d8a4-19bc-40e5-ace3-368cabb5f94c
https://github.com/steelthreads/agds-next/assets/6265154/3d2edde1-68b5-4234-a216-73d4127a6c32
**Preflight**
**Testing**

combobox: Improve internal positioning engine

---

packages/react/src/progress-indicator/docs/overview.mdx

added points to reinforce that steps should be navigable and not disabled
**Preflight**
**Testing**

progress-indicator: Add documentation for disabling behaviour

---

docs/content/updates/2023-10-17.mdx

AgDS Beta v1.14.0 release notes
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1438)

AgDS Beta v1.14.0 release notes

---

.changeset/few-lies-shave.md
packages/react/src/text-input/TextInput.tsx

Add Typescript support for the maxLength property in text-input
**Preflight**
**Testing**

text-input: Add support for max-length

---

docs/content/updates/2023-10-17.mdx

Fix typo in latest release notes

---

packages/react/src/form-stack/docs/overview.mdx
packages/react/src/stack/docs/overview.mdx
packages/react/src/text-input/docs/overview.mdx

[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1445/components/form-stack)
**Preflight**

form-stack: Improve documentation

---

packages/react/src/fieldset/docs/accessibility.mdx
packages/react/src/fieldset/docs/overview.mdx

[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1446/components/fieldset)
**Preflight**

fieldset: Improve documentation

---

.changeset/lemon-buckets-hear.md
packages/react/src/pagination/usePagination.test.ts
packages/react/src/pagination/usePagination.ts

Fixed small bug where separators were sometimes being displayed unnecessarily
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1452/components/pagination)
| [Before Playroom](https://design-system.agriculture.gov.au/playroom/index.html#?code=N4Igxg9gJgpiBcIA8BlALgQzAawAQHMMAHAXmAGYBfAPgB0A7XXJABQ3wEt6M0OJ6GTJmACuAJzEx6aNvhhkArJUFC0ETABtZMAM5kAjAAZljIXPowxPGAAlJAMzIAKAJS4S1XLRABibyaFcUQkpGXZ5YAAWANwAejpTVnYuHj4BU2FxSWltRRimNU1tPWAFYxUmc0trOxhHYFd3T28-EHygrNDcqIB2GPiVJM5uXn4KjpCc8LzxwowtcJKjdqqrNFsHZzcPL19-ceDssLkyPpUB9KYhlNHLoUOu6dL2uYW5ErKVqWr12vrGnYtfYZCZHbrRc4JJCxdBYbAJEAAGhAAHcOFA0AALHQIADa%2BgATIZDABdShAA) | [After playroom](https://design-system.agriculture.gov.au/pr-preview/pr-1452/playroom/index.html#?code=N4Igxg9gJgpiBcIA8 …

pagination: Improve divider logic

---

packages/react/src/file-upload/docs/overview.mdx

file-upload: Fix typo in docs

---

docs/content/patterns/loading-error-empty-states/index.mdx
docs/content/templates/error-page/ErrorPage.stories.tsx
docs/content/templates/error-page/ErrorPage.tsx
docs/content/templates/error-page/index.mdx

- add support for optional 'action' button in error page template, inspired by the error state patterns.
- improve documentation for the error page template, to reference content guidance published elsewhere.
- rename 'page level error state' to 'section level error state', added link to error page template.
- [DOCS Error page template](https://design-system.agriculture.gov.au/pr-preview/pr-1456/templates/error-page)
- [STORYBOOK Error page template in website layout](https://design-system.agriculture.gov.au/pr-preview/pr-1456/storybook/index.html?path=/story/templates-error-page--template)
- [STORYBOOK Error page template in app layout](https://design-system.agriculture.gov.au/pr-preview/pr-1456/storybook/index.html?path=/story/templates-error-page--application-template)
- [DOCS Loading …

error-page-template: Add support for button (optional). Improve docs. Rename 'page level error'

---

docs/content/patterns/selectable-table-with-batch-actions/index.mdx
packages/react/src/table/docs/overview.mdx

Fix usage of `useState` in our Table component documentation. This should be `React.useState` as `useState` is not available to use directly inside of Playroom.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1464)

docs: fix `useState` usage

---

docs/content/patterns/messaging/index.mdx
packages/react/src/callout/docs/overview.mdx
packages/react/src/field/docs/overview.mdx
packages/react/src/file-upload/docs/overview.mdx
packages/react/src/global-alert/docs/overview.mdx
packages/react/src/page-alert/docs/overview.mdx
packages/react/src/section-alert/docs/overview.mdx

Created new messaging patterns document.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1453/patterns/messaging)

patterns: Create messaging pattern page

---

docs/content/guides/change-management.mdx

I have read through this change management content and saw some issues
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1465)

docs: Update change management

---

docs/content/updates/2023-10-31.mdx

AgDS Beta v1.15.0 release notes

AgDS Beta v1.15.0 release notes

---

packages/react/src/accordion/docs/overview.mdx

accordion: Update documentation

---

.changeset/silver-parents-scream.md
packages/react/src/ag-branding/theme.ts

Updated `darkBackgroundShade` and `darkBackgroundBodyAlt` color.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1458)

ag-branding: Tweak navy values

---

packages/react/src/inpage-nav/docs/overview.mdx

Improved documentation for the Inpage nav component by adding a 'back to top' link at the bottom of every content section in the live code example.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1477/components/inpage-nav)
**Preflight**

inpage-nav: Improve documentation

---

packages/react/src/date-picker/docs/overview.mdx
packages/react/src/date-range-picker/docs/overview.mdx

docs: Fix incorrect group date-picker and date-range-picker

---

.changeset/tender-dodos-trade.md
packages/react/src/date-picker/__snapshots__/Calendar.test.tsx.snap
packages/react/src/date-picker/reactDayPickerStyles.ts

Used fixed height in calendar to prevent navigation controls from moving when switching between months.
- [View date picker](https://design-system.agriculture.gov.au/pr-preview/pr-1491/components/date-picker)
- [View date range picker](https://design-system.agriculture.gov.au/pr-preview/pr-1491/components/date-range-picker)
**Preflight**
**Testing**

date-picker: Use fixed height

---

yourgov/components/HelpCallout.tsx
yourgov/components/Layout/AppLayout.tsx
yourgov/data/mockLicencesAndPermits.ts
yourgov/lib/useLinkedBusinesses.tsx
yourgov/pages/app/dashboard/index.tsx
yourgov/pages/app/licences-and-permits/apply/index.tsx
yourgov/pages/app/licences-and-permits/apply/mobile-food-vendor-permit/index.tsx
yourgov/pages/app/licences-and-permits/index.tsx
yourgov/pages/services/food-drink-hospitality/operate-a-food-truck-van-or-stall-on-public-areas/index.tsx

Similar to #1488, but this time for the authed space.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1490/yourgov)

yourgov: Improve authed experience

---

.changeset/tender-dodos-trade.md
docs/content/updates/2023-11-14.mdx

Initial release of Password input, improvements to Combobox, plus various minor bug fixes and improvements.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1493)

AgDS Beta v1.16.0 release notes

---

.changeset/dull-houses-return.md

Fixes a mistake I accidentally made in #1498

Fix typo in changeset file

---

docs/content/updates/2023-11-30.mdx

AgDS Beta v1.17.0 release notes.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1509)

AgDS Beta v1.17.0 release notes

---

docs/content/updates/2023-11-30.mdx

Fixed error in Release 1.17.0 notes

Fixed error in Release 1.17.0 notes

---

.changeset/gold-squids-kiss.md
.storybook/stories/DataFiltering/components/DataList.tsx
.storybook/stories/DataLoading/DataLoadingWithCards.tsx
packages/react/src/file-upload/FileUploadExistingFile.stories.tsx
packages/react/src/file-upload/FileUploadFile.stories.tsx
packages/react/src/file-upload/FileUploadRejectedFile.stories.tsx
packages/react/src/indicator-dot/IndicatorDot.stories.tsx
packages/react/src/textarea/Textarea.stories.tsx

Fix various accessibility issues in Storybook stories
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1519)
**Preflight**
**Testing**

storybook: Fix various accessibility issues in Storybook stories

---

packages/react/src/checkbox/docs/overview.mdx

Removed word checkboxes from h2 Small

checkbox: Text edit to be consistent with radio page

---

.changeset/pink-ants-tickle.md
packages/react/src/core/Core.tsx

https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-gutter
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1521)
**Preflight**
**Testing**

core: Add scrollbar-gutter to prevent layout shift between short & long pages

---

.changeset/swift-countries-juggle.md
packages/react/src/table/TableCell.tsx
packages/react/src/table/TableHeader.tsx
packages/react/src/table/docs/overview.mdx

table: Add `colSpan` and `rowSpan` support to `TableCell` and `TableHeader`
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1527)
**Preflight**
**Testing**
- [] Add any necessary unit tests (HTML validation, snapshots etc)

table: Add colSpan and rowSpan support to TableCell and TableHeader

---

.changeset/six-cows-act.md
packages/react/src/file-upload/FileUpload.tsx
packages/react/src/file-upload/utils.tsx

Before:
After:
**Preflight**
**Testing**

file-upload: Set maxFiles to have a default of 1 and fix too-many-files error message

---

.changeset/empty-mangos-cross.md
packages/react/src/app-layout/AppLayoutSidebarDialog.tsx

https://design-system.agriculture.gov.au/storybook/iframe.html?args=&id=layout-applayout-applayoutsidebar--without-icons&viewMode=story
Total Issues: 1
ARIA dialog and alertdialog nodes should have an accessible name
https://design-system.agriculture.gov.au/pr-preview/pr-1530/storybook/iframe.html?args=&id=layout-applayout-applayoutsidebar--basic&viewMode=story
Total Issues: 0
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1530)
**Preflight**
**Testing**

app-layout: Fix a11y of AppLayoutSidebarDialog by giving it a Menu label

---

.storybook/stories/DataFiltering/lib/utils.test.ts
LICENSE
RELEASE.md
docs/content/patterns/selectable-table-with-batch-actions/index.mdx
docs/playroom/snippets.ts
packages/react/src/app-layout/AppLayout.test.tsx
packages/react/src/app-layout/__snapshots__/AppLayout.test.tsx.snap
packages/react/src/date-picker/Calendar.test.tsx
packages/react/src/date-picker/DatePicker.test.tsx
packages/react/src/date-picker/__snapshots__/Calendar.test.tsx.snap
packages/react/src/date-range-picker/DateRangePicker.test.tsx
packages/react/src/footer/Footer.test.tsx
packages/react/src/footer/__snapshots__/Footer.test.tsx.snap
packages/react/src/footer/docs/overview.mdx
packages/react/src/indicator-dot/IndicatorDot.stories.tsx
packages/react/src/indicator-dot/docs/overview.mdx
packages/react/src/table/Table.stories.tsx
packages/react/src/table/docs/overview.mdx
yourgov/data/mockLicencesAndPermits.ts

Updates any references throughout the documentation from 2022 or 2023 to 2024.

Update dates from 2022/2023 to 2024

---

docs/content/foundations/icons.mdx
packages/react/src/button/docs/overview.mdx

Update copy provided by @danger17 .
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1543).

icon: Improve documentation

---

.changeset/brave-ducks-draw.md
packages/react/package.json
packages/react/src/date-picker/Calendar.tsx
packages/react/src/date-picker/CalendarContainer.tsx
packages/react/src/date-picker/DatePicker.test.tsx
packages/react/src/date-picker/DatePicker.tsx
packages/react/src/date-picker/DatePickerInput.tsx
packages/react/src/date-picker/__snapshots__/Calendar.test.tsx.snap
packages/react/src/date-picker/__snapshots__/DatePicker.test.tsx.snap
packages/react/src/date-picker/reactDayPickerStyles.ts
packages/react/src/date-picker/utils.test.ts
packages/react/src/date-picker/utils.ts
packages/react/src/date-range-picker/DateRangePicker.test.tsx
packages/react/src/date-range-picker/DateRangePicker.tsx
packages/react/src/date-range-picker/__snapshots__/DateRangePicker.test.tsx.snap
packages/react/src/date-range-picker/utils.test.ts
packages/react/src/date-range-picker/utils.ts
yarn.lock

Folllow up to #1536 
- Upgraded internal dependency of `react-day-picker`
- Improved the ARIA label of the button that opens the calendar picker
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1544/components/date-picker)
- Upgraded internal dependency of `react-day-picker`
- Improved the ARIA labels of the buttons that opens the calendar picker
- Improved range styles inside of the calendar picker
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1544/components/date-range-picker)
**Preflight**
**Testing**

date-picker: Upgrade `react-day-picker`

---

packages/react/src/button/docs/overview.mdx

button: Update documentation 

---

.storybook/stories/DataFiltering/ListFiltering.tsx
docs/content/patterns/search-filters/index.mdx
docs/content/templates/sign-in/SignInForm.tsx
docs/pages/components/index.tsx
example-site/pages/sign-in-form.tsx
packages/react/src/filter-sidebar/FilterSidebar.stories.tsx
yourgov/pages/sign-in.tsx
yourgov/pages/sign-out.tsx

There were some differences between the design of filter sidebar and what was delivered in code. This PR aims to align design and code.
Key differences:
- column sizes (should be 3col/8col with a 1 col gap)
- results header and it's alignment to left-col
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1540)
**Preflight**
**Testing**

filter-sidebar: Align code to design

---

.changeset/twenty-penguins-fetch.md
packages/react/package.json
yarn.lock

Upgraded internal dependency of `react-focus-lock`. This effects the following packages:
- [App Layout](https://design-system.agriculture.gov.au/pr-preview/pr-1546/components/app-layout)
- [Date Picker](https://design-system.agriculture.gov.au/pr-preview/pr-1546/components/date-picker)
- [Date Range Picker](https://design-system.agriculture.gov.au/pr-preview/pr-1546/components/date-picker)
- [Drawer](https://design-system.agriculture.gov.au/pr-preview/pr-1546/components/drawer)
- [Main Nav](https://design-system.agriculture.gov.au/pr-preview/pr-1546/components/main-nav)
- [Modal](https://design-system.agriculture.gov.au/pr-preview/pr-1546/components/modal)
**Preflight**
**Testing**

Upgrade `react-focus-lock`

---

RELEASE.md
docs/content/updates/2023-11-30.mdx
docs/content/updates/2024-01-16.mdx

AgDS Beta v1.18.0 release notes.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1552)

Release notes v1.18.0

---

.changeset/funny-boxes-repeat.md
packages/react/src/date-picker/__snapshots__/Calendar.test.tsx.snap
packages/react/src/date-picker/reactDayPickerStyles.ts

[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1541/components/date-picker)
**Preflight**
**Testing**

date-picker: Add indicator dot under current date

---

.changeset/nice-bees-sleep.md
packages/react/src/date-picker/DatePicker.stories.tsx
packages/react/src/date-picker/DatePicker.test.tsx
packages/react/src/date-picker/DatePicker.tsx
packages/react/src/date-picker/DatePickerInput.tsx
packages/react/src/date-picker/__snapshots__/DatePicker.test.tsx.snap
packages/react/src/date-picker/docs/overview.mdx
packages/react/src/date-picker/utils.test.ts
packages/react/src/date-picker/utils.ts
packages/react/src/date-range-picker/DateRangePicker.stories.tsx
packages/react/src/date-range-picker/DateRangePicker.test.tsx
packages/react/src/date-range-picker/DateRangePicker.tsx
packages/react/src/date-range-picker/__snapshots__/DateRangePicker.test.tsx.snap
packages/react/src/date-range-picker/docs/overview.mdx

This is a duplicate of https://github.com/agriculturegovau/agds-next/pull/1561 except that it makes date formatting happen `onBlur` to fix loads of UX bugs
Follow up to #1555
---
Add new prop `dateFormat`, which can be used to adjust the date format displayed in the text input and secondary label. Format dates on blur
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1563/components/date-picker)
Add new prop `dateFormat`, which can be used to adjust the date format displayed in the text input and secondary label. Format dates on blur
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1563/components/date-range-picker)
**Preflight**
**Testing**

date-picker: Format dates on blur. Add new dateFormat prop

---

packages/react/src/drawer/docs/overview.mdx

@stowball some proposed updates to encourage correct use of side drawer
**Preflight**
**Testing**

drawer: Update Do and Don't content

---

docs/content/updates/2024-02-27.mdx
packages/react/src/grouped-fields/docs/overview.mdx

AgDS Beta v1.19.0 release notes.
**Preflight**
**Testing**

Release notes v1.19.0

---

.changeset/serious-lobsters-lay.md
.changeset/wise-zebras-sleep.md
docs/content/patterns/conditional-reveal/index.mdx

Pattern name change and content type of information added
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1576)
**Preflight**

docs: Patterns: update conditionally revealed content

---

packages/react/src/global-alert/docs/overview.mdx

docs: global-alert - Fix typo

---

packages/react/src/filter-sidebar/docs/overview.mdx

The Filter Sidebar docs had react errors
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1600)
**Preflight**
**Testing**

filter-sidebar docs: Fix React console errors

---

.changeset/happy-items-clap.md
docs/content/patterns/selectable-table-with-batch-actions/index.mdx

added content to emphasise that batch actions must be applicable to every row of a table
**Preflight**
**Testing**

Table with batch actions content changes

---

packages/react/src/accordion/docs/overview.mdx

Fixed figma link
**Preflight**
**Testing**

Fixed figma link on accordion page

---

packages/react/src/accordion/docs/overview.mdx

This reverts commit 3bbcf0394e659ba52fa21b302eeb83abc33052aa.

Revert "Fixed figma link on accordion page (#1608)"

---

docs/content/updates/2024-05-02.mdx
packages/react/src/time-input/docs/overview.mdx
packages/react/src/time-picker/docs/overview.mdx

Release notes v1.21.0
**Preflight**

Release notes v1.21.0

---

.changeset/friendly-islands-punch.md
docs/content/updates/2024-05-02.mdx

`CornerDownRightIcon` was incorrectly listed as `CornerRightDownIcon` in the release notes.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1667)
**Preflight**

Fix release notes typo

---

packages/react/src/table/docs/overview.mdx

I have added do's and dont's to include dropdown menu use
**Preflight**
**Testing**

Table doco - improve rules on drop down menu use for actions

---

packages/react/src/file-upload/FileUpload.test.tsx
packages/react/src/file-upload/test-utils.ts

New unit tests for `FileUpload`:

Add unit tests

---

.changeset/orange-ligers-boil.md
packages/react/src/header/docs/overview.mdx

[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1692)
**Preflight**
**Testing**

header: docs updates

---

docs/content/updates/2024-06-06.mdx
docs/content/updates/2024-07-10.mdx

Release notes v1.23.0

---

.changeset/dirty-parents-do.md
packages/react/src/tags/Tag.tsx
packages/react/src/tags/__snapshots__/Tags.test.tsx.snap
packages/react/src/tags/docs/overview.mdx

tags: Update appearance of tags to be smaller and pill-shaped.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1713)
**Preflight**
**Testing**

tags: Update appearance of tags to be smaller and pill-shaped.

---

docs/content/updates/2024-07-10.mdx

typo fix 'suppport'

---

.changeset/clever-mugs-invent.md
packages/react/src/app-layout/AppLayoutSidebarNav.test.tsx
packages/react/src/app-layout/AppLayoutSidebarNav.tsx

Fixes the level two items not receiving `body` background:
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1714)
Before: 
After:
**Preflight**
**Testing**

app-layout-sidebar: Fix level two nav items not receiving body background

---

example-site/components/SiteHeader.tsx
example-site/pages/audit/audit-1-1.tsx
example-site/pages/audit/audit-1-2.tsx
example-site/pages/audit/audit-1-3.tsx
example-site/pages/audit/audit-2-1.tsx
example-site/pages/audit/audit-2-2.tsx
example-site/pages/audit/audit-2-3.tsx
example-site/pages/audit/audit-3-1.tsx
example-site/pages/audit/audit-3-2.tsx
example-site/pages/audit/audit-3-3.tsx

We need multiple pages to test the side nav for the audit.
See https://design-system.agriculture.gov.au/pr-preview/pr-1725/example-site/audit/audit-1-1
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1725)
**Preflight**
**Testing**

Audit: nested side nav examples

---

.storybook/stories/DataFiltering/ListFiltering.tsx
.storybook/stories/SelectableTableBatchActions/SelectableTableBatchActions.tsx
packages/react/src/filter-sidebar/FilterSidebar.stories.tsx
packages/react/src/table/Table.stories.tsx

A few components for testing in Storybook needed to be wrapped in the page SiteLayout:
* Checkbox Indeterminate: https://design-system.agriculture.gov.au/pr-preview/pr-1724/storybook/iframe.html?args=&id=content-table--selectable-basic&viewMode=story
* Filter sidebar: https://design-system.agriculture.gov.au/pr-preview/pr-1724/storybook/iframe.html?args=&id=layout-filtersidebar--full&viewMode=story
* Pagination: https://design-system.agriculture.gov.au/pr-preview/pr-1724/storybook/iframe.html?args=&id=layout-filtersidebar--full&viewMode=story
* Table with batch actions: https://design-system.agriculture.gov.au/pr-preview/pr-1724/storybook/iframe.html?args=&id=content-table--selectable-with-batch-actions&viewMode=story
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-17 …

audit: Add SiteLayout to various stories

---

yourgov/components/FormMobileFoodVendorPermit/FormContainer.tsx
yourgov/components/FormMobileFoodVendorPermit/FormTask1Container.tsx
yourgov/components/FormMobileFoodVendorPermit/FormTask1FormState.ts
yourgov/components/FormMobileFoodVendorPermit/FormTask1Provider.tsx
yourgov/components/FormMobileFoodVendorPermit/FormTask1Step1.tsx
yourgov/components/FormMobileFoodVendorPermit/FormTask1Step1ChangeDetails.tsx
yourgov/components/FormMobileFoodVendorPermit/FormTask1Step4.tsx
yourgov/components/FormMobileFoodVendorPermit/FormTask1Step5.tsx
yourgov/components/FormRegisterPetDetails/FormRegisterPetDetails.tsx
yourgov/components/FormRegisterPetDetails/FormRegisterPetDetailsStep2.tsx
yourgov/components/Layout/AppLayout.tsx
yourgov/data/mockBusinesses.ts
yourgov/data/mockUsers.ts
yourgov/lib/useAuth.tsx
yourgov/lib/useLinkedBusinesses.tsx
yourgov/lib/useSessionFormState.ts
yourgov/pages/app/licences-and-permits/apply/mobile-food-vendor-permit/form/index.tsx
yourgov/pages/app/licences-and-permits/apply/mobile-food-vendor-permit/form/task-1/step-1/change-details.tsx
yourgov/pages/app/licences-and-permits/apply/mobile-food-vendor-permit/index.tsx
yourgov/pages/app/licences-and-permits/apply/who-can-apply.tsx

To test various components, we need to use existing yourgov pages, but without the sign in restriction and without saving the form state.
* Date picker: https://design-system.agriculture.gov.au/pr-preview/pr-1723/yourgov/app/licences-and-permits/apply/mobile-food-vendor-permit/form/task-1/step-4
* Date range picker: https://design-system.agriculture.gov.au/pr-preview/pr-1723/yourgov/app/licences-and-permits/apply/mobile-food-vendor-permit/form/task-1/step-5
* Details to Drawer help content: https://design-system.agriculture.gov.au/pr-preview/pr-1723/yourgov/app/licences-and-permits/apply/mobile-food-vendor-permit/form?type=food+van
* Progress Indicator L2: https://design-system.agriculture.gov.au/pr-preview/pr-1723/yourgov/app/licences-and-permits/apply/mobile-food-vendor-permit/form/task- …

audit: Necessary changes to yourgov

---

.storybook/stories/DataFiltering/SearchFilters.stories.tsx
.storybook/stories/DataFiltering/TableFilteringMedium.tsx
.storybook/stories/DataFiltering/components/ActiveFilters.tsx
.storybook/stories/DataFiltering/components/DataTable.tsx
.storybook/stories/DataFiltering/components/DataTableBatchActionsBar.tsx
.storybook/stories/DataFiltering/components/DataTableRow.tsx
.storybook/stories/DataFiltering/components/DataTableSelectAllCheckbox.tsx
.storybook/stories/DataFiltering/components/FilterAccordion.tsx
.storybook/stories/DataFiltering/lib/getData.ts
.storybook/stories/DataFiltering/lib/useFetchData.ts

Adds the following to the medium filter table:
- dropdown in last cell
- drawer triggered on dropdown's first item click ("Change status")
- drawer with form + radio group for statuses
- change of status + press "Save changes" updates table data
- immediate table data change on press of dropdown's second item
- confirm modal shows on press of dropdown's third item
- data persists across filters
- data resets on page refresh
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1727)
**Preflight**
**Testing**

audit-2024: complex table

---

.storybook/stories/DataFiltering/TableFilteringMedium.tsx
.storybook/stories/DataFiltering/components/DataTable.tsx
.storybook/stories/DataFiltering/components/FilterDestinationsSelect.tsx
packages/react/src/app-layout/__snapshots__/AppLayout.test.tsx.snap
packages/react/src/dropdown-menu/DropdownMenuPanel.tsx

[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1728)
**Preflight**
**Testing**

Audit: Fix table dropdown size and storybook HMR

---

.storybook/stories/DataFiltering/TableFilteringMedium.tsx
.storybook/stories/DataFiltering/components/ActiveFilters.tsx
.storybook/stories/DataFiltering/components/DashboardPagination.tsx
.storybook/stories/DataFiltering/components/DataTable.tsx

Adds table settings
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1729)
**Preflight**
**Testing**

Audit: Table settings

---

README.md

Updating the README.md to include an important message about not using agency data when contributing to the repository.
[View preview of README as it is rendered in Github](https://github.com/agriculturegovau/agds-next/blob/9a3d06f360b7b294c865bf714a5a8411383202e8/README.md#contributing)
**Preflight**
**Testing**

readme: Update to include message about agency data

---

.changeset/healthy-apples-buy.md
.storybook/stories/DataFiltering/components/FilterDestinationsSelect.tsx
packages/react/src/app-layout/__snapshots__/AppLayout.test.tsx.snap
packages/react/src/dropdown-menu/DropdownMenuPanel.tsx

dropdown-menu: Fix closed dropdowns from creating horizontal scroll.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1731)
**Preflight**
**Testing**

dropdown-menu: Horizontal scroll fix

---

.changeset/ninety-ravens-decide.md
packages/react/src/task-list/TaskList.tsx
packages/react/src/task-list/TaskListHeading.tsx
packages/react/src/task-list/__snapshots__/TaskList.test.tsx.snap

Updated wording from "steps" to "tasks".
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1741)
**Preflight**
**Testing**

task-list: Update steps to tasks wording

---

.changeset/tough-balloons-give.md
packages/react/src/table/TableScroller.tsx
packages/react/src/table/__snapshots__/Table.test.tsx.snap

table: Add edge shadows to scrollable tables when appropriate.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1733)
**Preflight**
**Testing**

table: Add edge shadows to scrollable tables when appropriate.

---

.changeset/sweet-peas-exist.md
docs/pages/foundations/tokens/colour.tsx

Fixes a broken link to editing the colour tokens page in Github from colour tokens pattern page.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1767)
**Preflight**
**Testing**

docs: Fix broken edit-this-page link

---

docs/content/updates/2024-09-12.mdx

Release notes page for v1.24.0.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1774)
**Preflight**

Release notes v1.24.0

---

.github/workflows/deploy-develop-docs.yml
README.md
docs/pages/index.tsx

This PR introduces an extension to the repo's workflow whereby we have an integration branch for features before those features are released to consumers. It will create a persistent docs build at https://design-system.agriculture.gov.au/develop and all feature branches will be created from here. The benefits will be:
1. The [docs site](https://design-system.agriculture.gov.au) will no longer show features that are yet to be released to NPM. This has been a source of confusion for consumers.
2. It's easier to create hot-fixes.
3. It's easier to create beta releases.
TODO before merging:
TODO after merging:
[View preview](https://design-system.agriculture.gov.au/develop)
**Preflight**
**Testing**

Create develop branch and CI

---

.changeset/config.json
.github/workflows/release.yml

Tell changesets to base from develop.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1777)
**Preflight**
**Testing**

ci: Update release and changeset configs

---

.changeset/config.json
.github/workflows/release.yml

This is basically the same as #1777, but we are merging into main instead now
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1778)

ci: Update release and changeset configs (to main) (#1777)

---

.changeset/smart-rockets-press.md
docs/components/Code.tsx

Removed _all_ `aria-label`s from the code snippet buttons (only two were flagged) as this creates consistency in the button group.
These are the buttons:
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1775)
**Preflight**
**Testing**

docs: use visible name of live code snippet buttons as accessible name

---

.changeset/smart-rockets-press.md
docs/components/Code.tsx

Testing release of #1775
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1779)

Docs Release (#1775)

---

.changeset/wet-keys-fix.md
packages/react/src/details/Details.tsx

Adds accessible name of "Information" to (i) icon in Details component.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1772)
**Preflight**
**Testing**

details: Make (i) icon available to screen readers and update accessible name

---

.changeset/chatty-days-complain.md
packages/react/src/breadcrumbs/BreadcrumbsToggle.tsx
packages/react/src/breadcrumbs/__snapshots__/Breadcrumbs.test.tsx.snap
packages/react/src/hero-banner/HeroSubcategoryBanner/__snapshots__/HeroSubCategoryBanner.test.tsx.snap

Swapping the generic accessible name for a more descriptive one.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1766)
**Preflight**
**Testing**

breadcrumbs: Update accessible name for  collapsed button to be more descriptive

---

.changeset/fluffy-bikes-repeat.md
.storybook/stories/DataFiltering/components/DataTableSelectAllCheckbox.tsx
.storybook/stories/SelectableTableBatchActions/useRowSelection.ts
packages/react/src/table/Table.stories.tsx

Changes all functional storybook examples of toggling the indeterminate select-all checkbox to toggle to all-selected from indeterminate in order to match screen reader announcements.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1769)
**Preflight**
**Testing**

table: Change examples of indeterminate select-all checkbox to toggle to all-selected on press, rather than all-deselected

---

.storybook/stories/DataFiltering/components/DataTable.tsx

Related to https://github.com/agriculturegovau/agds-next/pull/1787, our audit-specific branch needs to have unique table action dropdowns with `aria-describedby`
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1788)
**Preflight**
**Testing**

audit-2024: Give storybook dropdown actions unique descriptions

---

.changeset/chilly-dogs-care.md
packages/react/src/app-layout/AppLayoutHeaderNav.tsx
packages/react/src/app-layout/__snapshots__/AppLayout.test.tsx.snap
packages/react/src/main-nav/MainNavMenuButtons.tsx
packages/react/src/main-nav/__snapshots__/MainNav.test.tsx.snap

Adds `aria-haspopup` and `aria-expanded` attributes to the menu button for app and website layouts to announce state of main menu button.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1789)
**Preflight**
**Testing**

app-layout: Add aria attributes to menu button

---

.changeset/rich-swans-join.md
packages/react/src/dropdown-menu/DropdownMenu.stories.tsx
packages/react/src/dropdown-menu/DropdownMenu.test.tsx
packages/react/src/dropdown-menu/__snapshots__/DropdownMenu.test.tsx.snap

Just changing the storybook examples that use the NotificationBadge so that visual and announced text match.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1790)
**Preflight**
**Testing**

dropdown-menu: Update badge story announcement

---

.changeset/twenty-shrimps-push.md
packages/react/src/date-range-picker/docs/overview.mdx

Accurately describe date-range-picker error states
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1796)
**Preflight**
**Testing**

date-range-picker: Update example errors in docs to be specific

---

.changeset/cuddly-wasps-trade.md
packages/react/src/table/TableScroller.tsx
packages/react/src/table/docs/overview.mdx

The a11y audit said that our actions in tables should be unique, so Edit <ID> etc and to achieve this with `aria-describedby`. Annoyingly, VoiceOver on desktop doesn't pick these up on links (but does on buttons), but VO on iOS and TalkBack on Android does work as expected.
I have also added a Dropdown actions example since we can now popularise it.
My a11y testing of the table docs page also showed that we had multiple identical sections. Some of this was due to the captions being identical, and others because we allow headings to be used in captions, but it was not picking those up. One benefit is that I have added a heading to the wide tables example as one way of not having the "caption" scroll away with the table.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1 …

table: Make actions unique & fix table wrapper labelling

---

.changeset/purple-actors-compare.md
docs/content/content/content-structure.mdx

add detail to content about heading levels
**Preflight**
**Testing**

DAFF-143 a11y audit

---

.changeset/little-rockets-heal.md
packages/react/src/details/docs/overview.mdx

DAFF-42 expert observation edits

---

.changeset/rude-squids-admire.md
packages/react/src/combobox/docs/overview.mdx

and add required vs optional reference
**Preflight**
**Testing**

DAFF-28 remove optional label

---

.changeset/giant-needles-cheat.md
docs/content/foundations/icons.mdx

add detail about button/link icons being decorative
**Preflight**
**Testing**

DAFF-68 icon doco

---

.changeset/two-shoes-fix.md
packages/react/src/password-input/docs/overview.mdx

DAFF-77 Password input Do's and Don'ts

---

.changeset/brown-days-do.md
packages/react/src/table/docs/overview.mdx

DAFF-111 table content changes

---

.changeset/pretty-phones-jog.md
packages/react/src/autocomplete/docs/overview.mdx

DAFF-25 autocomplete content edit

---

.changeset/three-kings-add.md
packages/react/src/autocomplete/docs/overview.mdx

DAFF-10 - remove optional from autocomplete

---

.changeset/seven-dots-tickle.md
packages/react/src/app-layout/docs/overview.mdx

DAFF-4 sub-level content edits

---

.changeset/cyan-horses-help.md
docs/content/content/content-structure.mdx

not skipping heading level guidance added

---

.changeset/popular-beans-sin.md
packages/react/src/pagination/docs/overview.mdx

The audit wanted to the items per page dropdown to function
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1799)
**Preflight**
**Testing**

pagination: Update Items per page to a working example.

---

.changeset/fast-suns-agree.md
packages/react/package.json
packages/react/src/combobox/ComboboxBase/ComboboxTag.tsx
packages/react/src/combobox/ComboboxMulti.tsx
yarn.lock

This PR fixes the following bugs surfaced in the audit and from our subsequent testing:
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1786)
**Preflight**
**Testing**

combobox: ios voiceover issues

---

.changeset/funny-wasps-complain.md
docs/playroom/snippets.ts
packages/react/src/summary-list/SummaryList.stories.tsx
packages/react/src/summary-list/docs/code.mdx
packages/react/src/summary-list/docs/overview.mdx

The a11y audit found that our summary list actions didn't have unique content, so this updates guidance and examples.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1803)
**Preflight**
**Testing**

summary-list: Update docs & examples to have unique Action content

---

.changeset/blue-walls-trade.md
docs/content/patterns/focus-mode/index.mdx

[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1805)
**Preflight**
**Testing**

docs: Fix typo in focus mode docs

---

.changeset/cyan-horses-help.md
docs/content/content/content-structure.mdx

This reverts commit b2fbe78163a8e256e1643375989b5840fda15a3e.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1798)
**Preflight**
**Testing**

Revert "not skipping heading level guidance added (#1794)"

---

.changeset/real-lemons-rest.md
docs/content/content/content-principles.mdx

The a11y audit wanted our "1" link to be more accessible
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1802)
**Preflight**
**Testing**

content-principles: Improve accessibility of link to footnote

---

.changeset/smooth-coats-film.md
.storybook/stories/DataFiltering/components/DataTable.tsx
packages/react/src/table/docs/overview.mdx

Our table examples weren't following the the ARIA pattern exactly https://www.w3.org/WAI/ARIA/apg/patterns/table/examples/sortable-table/
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1801)
**Preflight**
**Testing**

table: Update guidance & examples of sortable tables to match ARIA pattern

---

.changeset/plenty-geese-travel.md
packages/react/src/app-layout/AppLayoutHeader.tsx
packages/react/src/app-layout/AppLayoutHeaderAccount.tsx
packages/react/src/app-layout/AppLayoutHeaderAccountDropdown.tsx
packages/react/src/app-layout/AppLayoutHeaderNav.tsx
packages/react/src/app-layout/__snapshots__/AppLayout.test.tsx.snap
packages/react/src/main-nav/MainNavContainer.tsx
packages/react/src/main-nav/MainNavDialog.tsx
packages/react/src/main-nav/MainNavList.tsx
packages/react/src/main-nav/MainNavListItem.tsx
packages/react/src/main-nav/MainNavListItemDropdown.tsx
packages/react/src/main-nav/MainNavMenuButtons.tsx
packages/react/src/main-nav/__snapshots__/MainNav.test.tsx.snap
packages/react/src/main-nav/docs/overview.mdx
packages/react/src/main-nav/utils.ts

The a11y audit found that the man nav menu button didn't fit on small screen. As a quick fix we are going to wrap them underneath with a further enhancement to come in future to possibly improve the desktop experience.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1795)
[Playrooom main nav](https://design-system.agriculture.gov.au/pr-preview/pr-1795/playroom/#?code=N4Igxg9gJgpiBcIA8AlGA7WAnAfAHXQAJDgAKASkIF4cSDjjJ0BnAF0IG1mYAbGMVjCgAhAK7MAluhjNmAGkLdWAZV79BI8VJnMAutUJoAhgIB04mMtZHBpPCACC6VgDMJAD3vkA3PQZYYVlEsIjsiBmIkYQh3QgAHIz5WQSp7KCMsAGt7fHCIyIBZIykAOSMANz98hhNWCXKYAAUbAAtUkABiFogAWxh7KurCCUEe5ipgDkGhkkIWgJd4Qnsu3v6QBR4jACNeJfsACTX7QgBfOWmh4DmF-c6XCFFMGwkIFntNnb3lkAAxR%2BedTezBO50u1Wu8xgix%2BHUgPTibwwrBBG0IW12PDuAGFeojpM5UWcLnkZrMoTCVglkjAQqjPpi7s0aXTQSSyQxIbdYaM4 …

Wrap accountDetails/secondaryItems when space is limited.

---

.changeset/good-chicken-allow.md
packages/react/src/page-alert/docs/overview.mdx

[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1807)
**Preflight**
**Testing**

Page alert - headings link added to page.mdx

---

.changeset/shiny-eels-develop.md
packages/react/src/breadcrumbs/docs/overview.mdx

Updated the first 3 points in the 'Do' section to align with audit suggestions
**Preflight**
**Testing**

breadcrumbs: Improve guidance around correct usage

---

.changeset/good-chicken-allow.md
packages/react/src/page-alert/docs/overview.mdx

Reverts agriculturegovau/agds-next#1807

Revert "Page alert - headings link added to page.mdx"

---

.changeset/mighty-tomatoes-divide.md
docs/components/EditPage.tsx

Sets the "Edit this page" link's branch dynamically, primarily targeting `develop`, and `main` will only be on `main`'s deployment.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1818)
**Preflight**
**Testing**

docs: Set edit-this-page link to dynamically select a branch

---

.changeset/shiny-eels-develop.md
packages/react/src/breadcrumbs/docs/overview.mdx

Redo of https://github.com/agriculturegovau/agds-next/pull/1791
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1816)
**Preflight**
**Testing**

breadcrumbs: Improve guidance around correct usage (To Develop)

---

.changeset/giant-moose-grin.md
docs/components/Code.tsx
docs/components/mdxComponents.tsx
docs/content/content/content-styles.mdx

In the docs page for content style, update heading text in examples to be unique.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1806)
**Preflight**
**Testing**

docs: content-styles unique example headings

---

.changeset/tiny-radios-fry.md
packages/react/src/card/docs/overview.mdx

Make lists of card semantic lists, add colour section in docs.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1817)
**Preflight**
**Testing**

card: Make list semantic, add colour section to docs

---

.changeset/unlucky-feet-obey.md
packages/react/src/file-upload/FileUpload.tsx
packages/react/src/file-upload/__snapshots__/FileUpload.test.tsx.snap

Associates the descriptions of accepted files and max file size with the `Select files` button.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1823)
**Preflight**
**Testing**

file-upload: Announce descriptions of file size and accepted files

---

.changeset/beige-comics-walk.md
docs/content/foundations/icons.mdx

Make the use of icons clearer
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1827)
**Preflight**

foundations: Improve icon usage clarity

---

.changeset/green-carpets-wash.md
packages/react/src/file-upload/FileUpload.tsx
packages/react/src/file-upload/__snapshots__/FileUpload.test.tsx.snap
packages/react/src/file-upload/docs/overview.mdx

Adds a visually hidden status that updates with added and removed files as the user interacts with these features of the component.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1821)
**Preflight**
**Testing**

file-upload: Announce adding and removing files

---

.changeset/clean-eels-warn.md
.storybook/stories/DataFiltering/TableFilteringMedium.test.tsx
.storybook/stories/DataFiltering/TableFilteringSmall.test.tsx
packages/react/src/button/Button.tsx
packages/react/src/combobox/ComboboxAsyncMulti.test.tsx
packages/react/src/file-upload/__snapshots__/FileUpload.test.tsx.snap
packages/react/src/pagination/Pagination.test.tsx
packages/react/src/pagination/Pagination.tsx
packages/react/src/pagination/PaginationButtons.test.tsx
packages/react/src/pagination/PaginationButtons.tsx
packages/react/src/pagination/PaginationItemSeparator.tsx
packages/react/src/pagination/__snapshots__/Pagination.test.tsx.snap
packages/react/src/pagination/__snapshots__/PaginationButtons.test.tsx.snap
packages/react/src/pagination/usePagination.test.ts
packages/react/src/pagination/usePagination.ts

The audit found that the hidden pages ellipsis buttons should be announced better
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1826)
**Preflight**
**Testing**

pagination: Announce the hidden pages represented by ellipses

---

.changeset/rich-seahorses-care.md
packages/react/src/file-input/FileInput.tsx
packages/react/src/file-input/docs/overview.mdx
packages/react/src/file-upload/__snapshots__/FileUpload.test.tsx.snap

Adds accept example and more guidance on hint regarding file size.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1822)
**Preflight**
**Testing**

file-input: Add accept example and enhance hint guidance

---

.changeset/plenty-avocados-share.md
packages/react/src/avatar/docs/overview.mdx

Adds a colour section with light and dark palette variants to the docs.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1830)
**Preflight**
**Testing**

avatar: add colour section to docs

---

.changeset/few-bags-kiss.md
packages/react/src/side-nav/docs/overview.mdx

Adds responsive columns to the docs example so that chevrons are closer to their context.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1831)
**Preflight**
**Testing**

side-nav: add responsive columns to contain example in docs

---

.changeset/green-timers-thank.md
packages/react/src/date-range-picker/docs/overview.mdx

Noticed that the `toInvalid`checks have been incorrect since June 2023 at least… https://github.com/agriculturegovau/agds-next/commit/0942aab35d15a19625d8e7bf3b8700a64eb6ece9#diff-435af9b4eacc1d56d598abc8d9b535c987bc616b67f6882195add24a964ef058R70
And I broke the input change events in July https://github.com/agriculturegovau/agds-next/commit/b12ac2c265850568c255491f3e9b2f01ad915a93#diff-435af9b4eacc1d56d598abc8d9b535c987bc616b67f6882195add24a964ef058R74
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1834)
**Preflight**
**Testing**

date-range-picker: Fix toInvalid checks & inputChange events

---

.changeset/sharp-items-sit.md
yourgov/components/FormMobileFoodVendorPermit/steps/FormState.ts
yourgov/components/FormMobileFoodVendorPermit/steps/FormStep1.tsx
yourgov/components/FormMobileFoodVendorPermit/steps/FormStep10Review.tsx
yourgov/components/FormMobileFoodVendorPermit/steps/FormStep1ChangeDetails.tsx
yourgov/components/FormMobileFoodVendorPermit/steps/FormStep7.tsx
yourgov/components/FormMobileFoodVendorPermit/steps/FormStep8.tsx
yourgov/lib/useSessionFormState.ts

Adds the food safety supervisor steps and changes necessary to step 7 - employees
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1841)
**Preflight**
**Testing**

yourgov: Add food safety supervisor step

---

.changeset/fresh-lions-sleep.md
yourgov/components/FormMobileFoodVendorPermit/FormContainer.tsx
yourgov/components/FormMobileFoodVendorPermit/FormState.ts
yourgov/components/FormMobileFoodVendorPermit/GlobalFormProvider.tsx
yourgov/components/FormMobileFoodVendorPermit/utils.ts
yourgov/lib/useSessionFormState.ts
yourgov/pages/app/licences-and-permits/apply/mobile-food-vendor-permit/success/index.tsx

[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1844)
**Preflight**
**Testing**

yourgov: Add application success page

---

.changeset/tasty-sloths-pull.md
yourgov/components/FormMobileFoodVendorPermit/steps/FormState.ts
yourgov/components/FormMobileFoodVendorPermit/steps/FormStep10Review.tsx
yourgov/components/FormMobileFoodVendorPermit/steps/FormStep6.tsx

[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1845)
**Preflight**
**Testing**

yourgov: Update food served types

---

.changeset/cuddly-cows-sparkle.md
.changeset/wicked-hotels-wonder.md
packages/react/src/table/docs/overview.mdx
yourgov/components/FormMobileFoodVendorPermit/ApplicationHistory.tsx
yourgov/components/FormMobileFoodVendorPermit/GettingStartedForm.tsx
yourgov/components/Layout/AppLayout.tsx
yourgov/data/mockLicencesAndPermits.ts
yourgov/pages/app/dashboard/index.tsx
yourgov/pages/app/licences-and-permits/apply-for-new-permit/index.tsx
yourgov/pages/app/licences-and-permits/apply/index.tsx
yourgov/pages/app/licences-and-permits/apply/mobile-food-vendor-permit/index.tsx
yourgov/pages/app/licences-and-permits/index.tsx
yourgov/pages/app/licences-and-permits/manage-existing/index.tsx
yourgov/pages/app/staff/index.tsx

[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1848)
**Preflight**
**Testing**

yourgov: Add working application history and related pages

---

.changeset/gold-moons-whisper.md
.changeset/plenty-bikes-end.md
yourgov/components/FormMobileFoodVendorPermit/ApplicationHistory.tsx
yourgov/components/FormMobileFoodVendorPermit/steps/FormState.ts
yourgov/components/FormMobileFoodVendorPermit/steps/FormStep10.tsx
yourgov/components/FormMobileFoodVendorPermit/steps/FormStep10Review.tsx
yourgov/pages/app/licences-and-permits/[slug].tsx
yourgov/pages/app/licences-and-permits/apply/mobile-food-vendor-permit/success/index.tsx

yourgov: Add declaration and employee table to review step
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1849)
**Preflight**
**Testing**

yourgov: Add declaration to review step

---

.changeset/tall-poems-clean.md
packages/react/src/date-picker/Calendar.tsx
packages/react/src/date-picker/__snapshots__/Calendar.test.tsx.snap
packages/react/src/date-picker/reactDayPickerStyles.ts

[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1851)
**Preflight**
**Testing**

date-range-picker: Fix layout squishing & superfluous <> buttons

---

.changeset/perfect-singers-deliver.md
yourgov/components/FormMobileFoodVendorPermit/steps/FormStep1.tsx
yourgov/pages/app/dashboard/index.tsx
yourgov/pages/app/index.tsx
yourgov/pages/app/licences-and-permits/[slug].tsx
yourgov/pages/sign-in.tsx

Various tweaks fixes to the UI: spacing, icon sizes, etc
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1853)
**Preflight**
**Testing**

yourgov: Various UI tweaks and fixes

---

yourgov/components/Staff/DashboardPagination.tsx
yourgov/components/Staff/lib/useSortAndFilter.ts

[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1854)
**Preflight**
**Testing**

Yourgov staff members pagination

---

.changeset/tender-ads-sin.md
packages/react/src/date-picker/Calendar.tsx
packages/react/src/date-picker/__snapshots__/Calendar.test.tsx.snap
packages/react/src/select/Select.tsx
yourgov/components/FormMobileFoodVendorPermit/GettingStartedForm.tsx
yourgov/components/FormMobileFoodVendorPermit/steps/FormStep1.tsx
yourgov/components/FormMobileFoodVendorPermit/steps/FormStep2.tsx
yourgov/components/FormMobileFoodVendorPermit/steps/FormStep3.tsx
yourgov/components/FormMobileFoodVendorPermit/steps/FormStep4.tsx
yourgov/components/FormMobileFoodVendorPermit/steps/FormStep5.tsx
yourgov/pages/index.tsx
yourgov/pages/services/food-drink-hospitality/operate-a-food-truck-van-or-stall-on-public-areas/index.tsx
yourgov/pages/sign-in.tsx

ARC Toolkit found a number of validation and markup issues. This fixes them in the main pages and form flow. Staff flow will be done separately
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1856)
**Preflight**
**Testing**

yourgov: Fix markup validation bugs. Add autocomplete attrs

---

.changeset/old-hairs-carry.md
.changeset/pink-pants-wait.md
packages/react/src/combobox/ComboboxBase/ComboboxTag.tsx
packages/react/src/switch/Switch.tsx
packages/react/src/switch/__snapshots__/Switch.test.tsx.snap
packages/react/src/table/TableScroller.tsx
yourgov/components/FormMobileFoodVendorPermit/steps/FormState.ts
yourgov/components/FormMobileFoodVendorPermit/steps/FormStep10Review.tsx
yourgov/components/FormMobileFoodVendorPermit/steps/FormStep6.tsx
yourgov/components/Layout/AppLayout.tsx
yourgov/components/Staff/AccessRequestsTable/ModalUnavailableFeature.tsx
yourgov/components/Staff/DashboardFilterDrawer.tsx
yourgov/components/Staff/DataTable.tsx
yourgov/components/Staff/StaffMembersTable.tsx
yourgov/components/Staff/lib/useSortAndFilter.ts
yourgov/lib/zodUtils.ts
yourgov/pages/app/index.tsx
yourgov/pages/app/licences-and-permits/[slug].tsx
yourgov/pages/app/licences-and-permits/apply/mobile-food-vendor-permit/index.tsx
yourgov/pages/app/staff/[slug].tsx
yourgov/pages/app/staff/invite-staff-member/index.tsx

These are all issues found by ARC Toolkit and manual testing.
switch: Add required `aria-checked` attribute and add support for `aria-controls`.
table: Fix scrolling shadows not responding to changes in table heights.
yourgov: Various bug fixes and enhancements based on our testing.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1859)
**Preflight**
**Testing**

yourgov: Various bug fixes and enhancements based on our testing

---

.changeset/lemon-suits-rush.md
packages/react/src/file-upload/FileUpload.tsx
packages/react/src/file-upload/__snapshots__/FileUpload.test.tsx.snap
yourgov/components/FormDefinitionList.tsx
yourgov/components/FormMobileFoodVendorPermit/UploadFileTable.tsx
yourgov/components/FormMobileFoodVendorPermit/steps/FormState.ts
yourgov/components/FormMobileFoodVendorPermit/steps/FormStep10Review.tsx
yourgov/components/FormMobileFoodVendorPermit/steps/FormStep9.tsx
yourgov/components/LinkComponent.tsx
yourgov/lib/useSessionFormState.ts
yourgov/pages/app/licences-and-permits/[slug].tsx
yourgov/pages/app/staff/[slug].tsx
yourgov/pages/app/staff/invite-staff-member/index.tsx

[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1857)
**Preflight**
**Testing**

Yourgov upload documents step

---

.changeset/short-balloons-rest.md
.changeset/smart-cars-watch.md
packages/react/src/core/utils/useFocus.ts
packages/react/src/date-range-picker/DateRangePicker.tsx
packages/react/src/date-range-picker/__snapshots__/DateRangePicker.test.tsx.snap
yourgov/components/FormMobileFoodVendorPermit/ApplicationHistory.tsx
yourgov/components/FormMobileFoodVendorPermit/steps/FormState.ts
yourgov/components/FormMobileFoodVendorPermit/steps/FormStep5.tsx
yourgov/components/FormMobileFoodVendorPermit/steps/FormStep7.tsx
yourgov/components/FormMobileFoodVendorPermit/steps/FormStep7AddEmployee.tsx
yourgov/components/FormMobileFoodVendorPermit/utils.ts
yourgov/lib/zodUtils.ts

Fix validation issues
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1860)
**Preflight**
**Testing**

yourgov: Fix date and time validation

---

.changeset/wild-parents-press.md
packages/react/src/dropdown-menu/docs/overview.mdx

Announce "99+" since it's the displayed value rather than 100 in the docs when an item is using the NotificationBadge.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1863)
**Preflight**
**Testing**

dropdown-menu: Announce displayed value in docs examples with 99+ badges

---

.changeset/spicy-rockets-fly.md
packages/react/src/card/docs/overview.mdx

Adding guideline about wrapping cards in a list as per accessibility audit.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1862)
**Preflight**
**Testing**

card: Add Do list item regarding wrapping cards in a list.

---

.changeset/brave-planets-joke.md
yourgov/components/FormMobileFoodVendorPermit/steps/FormStep10Review.tsx
yourgov/components/FormMobileFoodVendorPermit/steps/FormStep9.tsx
yourgov/pages/app/licences-and-permits/[slug].tsx

Use a table instead of bulleted list for the review steps of Upload documents to match the input step.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1866)
**Preflight**
**Testing**

yourgov: Use a table for Upload documents on review steps.

---

.changeset/smart-beds-fail.md
yourgov/components/FormMobileFoodVendorPermit/steps/FormStep7.tsx

yourgov: Fix alert focus management in add and remove employees.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1867/yourgov)
**Preflight**
**Testing**

yourgov: Fix alert focus management in add and remove employees

---

.changeset/thick-sheep-occur.md
yourgov/components/FormMobileFoodVendorPermit/steps/FormStep7.tsx

Use en effect & delay to always focus
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1871)
**Preflight**
**Testing**

yourgov: Fix Add/Remove employee focus management… again

---

.changeset/tiny-rockets-pump.md
yourgov/components/FormMobileFoodVendorPermit/steps/FormStep9.tsx

Focus the success message after a file has been removed and after the table updates.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1869)
**Preflight**
**Testing**

yourgov: Focus success message after removing file

---

.changeset/brown-rockets-count.md
yourgov/components/FormMobileFoodVendorPermit/steps/FormState.ts
yourgov/pages/app/staff/invite-staff-member/index.tsx

Use phone validation pattern when inviting a staff member rather than just required.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1873)
**Preflight**
**Testing**

yourgov: Use phone validation for inviting a staff member

---

.changeset/nine-apples-dream.md
packages/react/src/modal/ModalDialog.tsx
packages/react/src/modal/__snapshots__/Modal.test.tsx.snap

On mobile, modals incorrectly had rounded corners and they often didn't fit because of the brower toolbar disappearing etc.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1872)
**Preflight**
**Testing**

modal: Fix appearance on small screens

---

.changeset/fifty-gorillas-worry.md
packages/react/src/summary-list/SummaryList.tsx
packages/react/src/summary-list/__snapshots__/SummaryList.test.tsx.snap

This fixes when summary lists contain long content and 2+ word action text, the action text incorrectly wraps
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1883)
[Before](https://design-system.agriculture.gov.au/playroom/#?code=N4Igxg9gJgpiBcIA8BlArgWwwQwE4E8AZASwGcAXAPgB0A7AAntUxwJIoElyYMaHGm6LHiJlyXHgBUYuXgDFiuCvVrYMMJAHohrUZ24ZpsvgMEsR7cQYAiMUmFzEADuWIRaJ0-UIRcPes6kmPRQEAA2vvSkxOT0ajDkADT0kLSkMGDc5Gi4cVDOZGDEtADm9DBhMQB09AByaGFhairu5bTEGHReAbTcuFDBOCWq9DgAHh1opPQAZo6lxI3YNfW0YPTcjVOjCVPJOGF2aNhQ2PQAbjAAFsRgDdhdXpUARjIQLbTJp07Ez9szMDQJWI2FiviKKzQayi4UqRWy%2BQY5zwxG2OFIpDO0XIj1M8Viz1%2BMFoAwwNQAoq5mjgcmQNhUwnsomAKjIyABHNAwOL0Sole4qDJfYjDMjRTr8UwNJoYSC4JwyelbUhVXFMbTmNhiCQYWz2RwuNweNXMYRa-Q8ACCmSNnlMSGkY3IJFoAGt6Fc-DMALzUEAAYj9lAAwldsKVuTNFMpVOotI7ncVXXb1ToLNqDNbXO5 …

summary-list: Prevent action column from shrinking

---

.changeset/beige-nails-shave.md
.storybook/stories/DataFiltering/components/DataList.tsx
.storybook/stories/DataFiltering/components/DataTable.tsx
docs/content/patterns/loading-error-empty-states/index.mdx
docs/content/patterns/messaging/index.mdx
docs/content/patterns/search-filters/index.mdx
yourgov/components/Staff/DataTable.tsx

Only update the content of the live region, rather than conditionally render the whole thing. This way the "No results found" status is announced when rendered.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1880)
**Preflight**
**Testing**

filter-sidebar: announce empty state

---

.changeset/few-pears-crash.md
yourgov/components/FormMobileFoodVendorPermit/steps/FormStep7.tsx
yourgov/components/FormMobileFoodVendorPermit/steps/FormStep9.tsx
yourgov/components/Staff/DashboardFilterDrawer.tsx
yourgov/pages/app/index.tsx

While observing user testing, we saw some simple, low-hanging fruit improvements
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1898)
**Preflight**
**Testing**

yourgov: Simple markup and UI fixes

---

.github/dependabot.yml

We need to add this to add dependabot weekly PRs again https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1900)
**Preflight**

Add dependabot update yml

---

.changeset/odd-ants-push.md
packages/react/src/callout/Callout.stories.tsx

Remove conditional reveal story for Callout component as we no longer support this pattern.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1910)
**Preflight**
**Testing**

callout: Remove conditional reveal story

---

.changeset/plop-create-ProgressNotRequired.md
docs/components/designSystemComponents.tsx
packages/react/src/icon/__snapshots__/Icon.test.tsx.snap
packages/react/src/icon/icons/ProgressNotRequiredIcon.tsx
packages/react/src/icon/index.ts
packages/react/src/icon/utils.tsx

New icon for an upcoming Progress Indicator status
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1919)
**Preflight**
**Testing**

icon: Created new icon, ProgressNotRequiredIcon

---

.changeset/polite-bulldogs-do.md
packages/react/src/status-badge/StatusBadge.tsx
packages/react/src/status-badge/__snapshots__/StatusBadge.test.tsx.snap

Removes the various emphasis announcements from the icon in StatusBadge, e.g. `high emphasis`, which was causing confusion during usability testing.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1928)
**Preflight**
**Testing**

status-badge: Remove emphasis from icon announcement

---

.changeset/happy-glasses-act.md
yourgov/components/FormMobileFoodVendorPermit/steps/FormStep2.tsx
yourgov/components/FormMobileFoodVendorPermit/steps/FormStep3.tsx

Changes the conditional reveal pattern in the yourGov app from injecting newly rendered input between radio buttons in a radio group to after the entire group.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1927)
**Preflight**
**Testing**

yourgov: New conditional reveal pattern

---

.changeset/serious-pillows-repair.md
yourgov/pages/app/dashboard/index.tsx

[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1936)
**Preflight**
**Testing**

yourgov: Change to use FeatureLinkList for Popular Links

---

.changeset/good-points-type.md
yourgov/components/FormMobileFoodVendorPermit/steps/FormState.ts
yourgov/components/FormMobileFoodVendorPermit/steps/ReviewAndSubmitStepsSummary.tsx
yourgov/components/FormMobileFoodVendorPermit/steps/StepBusinessDetailsForm.tsx
yourgov/pages/app/permits/[slug].tsx

Sole trader also needs to have ABN and hint text added to let users know about conditional fields
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1946)
**Preflight**
**Testing**

yourgov: Update Business structure to have ABN for sole trader

---

.changeset/grumpy-cars-scream.md
yourgov/components/FormMobileFoodVendorPermit/steps/ReviewAndSubmitStepsSummary.tsx
yourgov/components/FormMobileFoodVendorPermit/steps/StepReviewAndSubmitForm.tsx
yourgov/components/FormMobileFoodVendorPermit/utils.ts

When you save after editing from a review step, we now display and focus a SectionAlert.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1947)
**Preflight**
**Testing**

yourgov: Add success message when saving from review edit

---

.changeset/kind-turtles-provide.md
packages/react/src/list/docs/overview.mdx

The list examples were found to have incorrect and confusing examples.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1941)
**Preflight**
**Testing**

list: Fix docs examples

---

.changeset/calm-wolves-cross.md
yourgov/components/FormMobileFoodVendorPermit/steps/StepEmployeesForm.tsx
yourgov/components/FormMobileFoodVendorPermit/utils.ts
yourgov/components/HelpReference.tsx
yourgov/components/Staff/DataTable.tsx

Some small issues were found in UT and by SonarCloud
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1960)
**Preflight**
**Testing**

yourgov: Various fixes to error handling, icons & table cells

---

.changeset/clean-timers-eat.md
docs/components/designSystemComponents.tsx
packages/react/src/icon/__snapshots__/Icon.test.tsx.snap
packages/react/src/icon/icons/DrawerIcon.tsx
packages/react/src/icon/index.ts
packages/react/src/icon/utils.tsx
yourgov/pages/_app.tsx

We tested a `DrawerIcon` before settling on `MoveLeft/Right`. Removing this as it's not needed
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1975)
**Preflight**
**Testing**

icon: Remove unused DrawerIcon

---

.changeset/moody-lemons-wave.md
docs/content/updates/2025-03-20.mdx
docs/content/updates/2025-03-21.mdx
packages/react/src/date-picker-next/docs/overview.mdx
packages/react/src/date-range-picker-next/docs/overview.mdx
packages/react/src/toggle-button/docs/overview.mdx

Release notes v1.26.0
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1982)
**Preflight**
**Testing**

Release notes v1.26.0

---

.changeset/gold-ways-sparkle.md
docs/package.json
example-site/package.json
yarn.lock
yourgov/package.json

Upgrade Next to fix CVE: https://github.com/advisories/GHSA-f82v-jwr5-mffw
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1985)
**Preflight**

build(deps): bump next from 14.2.21 to 14.2.25

---

.changeset/odd-kids-sparkle.md
docs/content/guides/getting-started.mdx
packages/react/package.json

`facepaint` doesn't need to be a peer dependency since unlike React and Emotion, it wouldn't have a problem if it were to be duplicated
**Preflight**
**Testing**

deps: Move `facepaint` to a normal dependency

---

.changeset/brave-dots-heal.md
packages/react/src/table/Table.tsx
packages/react/src/table/TableRow.tsx
packages/react/src/table/docs/overview.mdx

Teams need to be able to apply background colours to table rows. Adding support for all of the ones Box supports.
Also noticed that invalid rows weren't showing when on a striped row.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-2001)
* [Playroom of main showing broken behaviour of invalid](https://design-system.agriculture.gov.au/playroom/#?code=N4Igxg9gJgpiBcIA8AhCAPABABwIZSgEsA7AcwF5gAmAXwD4AdYzTJAJRmNgCdHmXMwABQBKTOTqCmAgZGIBnAC6YA2vJgAbGGEUwobCAHd5AGkzrFAZU3bd%2Bo-IC64zB1w6AdAFd1lxbl0hFUcRAG4maRlMADMvYh1CCGZFCFJSLQNDay0EpKFuIwBJLhh0MWBIqMxCaMwhdRy7TPkPEjANL1h5fKKSsvLKqvMYKxsdPWahfLEJTG4PaMINXW4p%2BRnJeUwAQnJyOd7YfvD%2BKppMTXUpU6GLbNsJhynuDdUPd%2B4zAsNio5CToaYGiDFjA4ggzByJSYXDEACezQAwgALbQAaz0LgaD3sxg8WjIimRmEkAAYAVEocpcBoNEjUWAMVAsWMmg58ZxSETxHtMABmE4Q2LxRSJZK …

table: Add background prop to <TableRow>. Fix invalid not overriding striped background

---

.changeset/plop-create-CodeIcon.md
docs/components/designSystemComponents.tsx
packages/react/src/icon/__snapshots__/Icon.test.tsx.snap
packages/react/src/icon/icons/CodeIcon.tsx
packages/react/src/icon/index.ts
packages/react/src/icon/utils.tsx
scripts/new-icon/script.mjs

Adds a new code icon.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-2027)
**Preflight**
**Testing**

icon: Add new CodeIcon

---

.changeset/happy-carpets-bathe.md
docs/content/updates/2025-05-13.mdx
packages/react/src/conditional-field-container/docs/overview.mdx

Release notes v1.28.0
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-2033)
**Preflight**
**Testing**

Release notes v1.28.0

---

.changeset/stale-pots-travel.md
packages/react/src/file-upload/FileUpload.stories.tsx
packages/react/src/file-upload/FileUpload.test.tsx
packages/react/src/file-upload/FileUploadExistingFile.stories.tsx
packages/react/src/file-upload/FileUploadExistingFile.tsx
packages/react/src/file-upload/FileUploadExistingFileList.stories.tsx
packages/react/src/file-upload/__snapshots__/FileUpload.test.tsx.snap
packages/react/src/file-upload/docs/overview.mdx
packages/react/src/file-upload/utils.tsx

Added support for an `onClick` event on the ExistingFile type - utilised by FileUpload.
This will allow users to implement a custom onClick handler for downloading files if the file isn't publically accessible via an href, or if they need to add interceptors/enrichment such as analytics.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-2045)
**Preflight**
**Testing**

file-upload: Add onClick support for ExistingFile

---

.changeset/funny-beers-give.md
docs/content/updates/2025-06-03.mdx

Release notes v1.29.0
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-2054)
**Preflight**

Release notes v1.29.0

---

.changeset/happy-beers-sell.md
docs/content/patterns/ask-users-for-dates-and-times/index.mdx

Add new pattern page `Ask users for dates and times`.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-2080)
[Ask users for dates and times pattern preview](https://design-system.agriculture.gov.au/pr-preview/pr-2080/patterns/ask-users-for-dates-and-times)
**Preflight**

docs: add 'Ask users for dates and times' pattern page

---

.changeset/gentle-mice-compete.md
docs/content/guides/getting-started.mdx

Update getting started for the way of using it with next
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-2089)
**Preflight**
**Testing**

docs: Update Getting Started guide to support Next.js
