README.md, docs/README.md, docs/pages/index.tsx
- Adds minimal "getting started" docs to the main Readme
- changes the Docs homepage content to use the `docs/README.md` file instead of the repo root Readme.
=> repo docs: Getting started guide

packages/box/src/Flex.tsx, packages/box/src/styles.ts, packages/core/src/tokens.ts
- use fontGrid in primitive components
- allow passing `display` to `Flex` component
- apply common resets to primitives - eg.  `box-sizing: border-box, margin: 0, list-style: none`.
- new maxWidth Token for mobilemenu
=> Updates to Box and Core

.changeset/empty-tables-travel.md, docs/components/LinkComponent.tsx, docs/pages/_app.tsx, packages/header/src/HeaderBrand.tsx, packages/header/src/HeaderContainer.tsx
The alignment of the Site Header was incorrect when there was no subline.
| Before  | After  |
|:----|:-----|
|  ![image](https://user-images.githubusercontent.com/814227/149721178-db6c1de7-6f91-4429-b077-8f586016d24c.png) | ![image](https://user-images.githubusercontent.com/814227/149721093-3341f6e9-c441-482f-9149-cf89c6ab4b45.png) |
=> Header: Fix alignment and useLinkComponent

.storybook/main.js, package.json, yarn.lock
Add `@storybook/addon-a11y` to enable accessibility checks in Storybook.
Can't do a Changeset as we're only changing top-level files
=> Storybook: Add a11y tools

.storybook/preview.tsx, docs/components/ReactLive/index.tsx, docs/components/prism-theme.ts, packages/body/src/Body.tsx, packages/box/src/Divider.tsx, packages/box/src/styles.ts, packages/core/src/colors.tsx, packages/link-list/src/LinkListItem.tsx, packages/main-nav/src/MainNav.stories.tsx, packages/main-nav/src/MenuButtons.tsx, packages/main-nav/src/NavContainer.tsx, packages/main-nav/src/NavItem.tsx, packages/main-nav/src/NavList.tsx, packages/main-nav/src/utils.ts, packages/text-link/src/index.tsx
Somewhere along the way we broke the color variant for this.
Before:
After:
Also, in a bid for consistency of naming, I've renamed `themeVars` to `themeValues`. The convention I'm creating here is as follows:
`...Vars` is the css variable name. `--agds-foreground-text`.
`...Values` is the css variable as a value. `var(--agds-foreground-text)`.
So `vars` are for setting, `values` are for getting.
This still needs to be changed for `GlobalVars`.
=> Fix: MainNav color variants 

docs/components/PkgCard.tsx
Fixed: In the Docs, links to packages were not working from the packages/index page.
=> Docs: Fix links to packages

.changeset/light-actors-rush.md, packages/link-list/src/LinkListContainer.tsx
For horizontal link lists, we want to enable wrapping so they layout doesn't break.
=> LinkList: Enable wrapping for longer lists

.changeset/blue-toes-raise.md, .changeset/kind-vans-cheat.md, docs/playroom/snippets.js, packages/content/src/Content.tsx, packages/core/src/tokens.ts, packages/footer/src/Footer.tsx, packages/header/README.md, packages/header/src/Header.stories.tsx, packages/header/src/Header.tsx, packages/header/src/HeaderBrand.tsx, packages/header/src/HeaderContainer.tsx
- Recompose Header with Columns component
- Change HeaderBrand title line height
- Add changeset, including a recent change to add the rightContent prop (which was recently merged in)
Pictured: New Header with placeholder SearchBox component
=> Header: Compose with Columns. Add rightContent slot.

.changeset/wicked-cougars-shout.md, docs/components/SiteHeader.tsx, docs/lib/mdxUtils.ts, packages/ag-branding/README.md
- Rename Agriculture group to Brand
- Sort package groups: 'Foundations' first, than alphabetically (approved by Adrian)
- Update Site heading
=> Docs: Improve information architecture

.changeset/funny-panthers-brush.md, docs/components/prism-theme.ts, packages/box/src/styles.ts, packages/core/src/colors.tsx
We (Adrian and I) identified that our system doesn't currently use hint text anywhere consistently, and that it does not have sufficient contrast with all backgrounds. We therefore move to use the foregroundMuted color for each palette instead.
=> Core: Remove `hint` and `hintAlt` color tokens

.changeset/ten-humans-compete.md, .eslintrc.js, docs/components/Code.tsx, docs/components/PkgCardList.tsx, example-site/pages/index.tsx, packages/card/README.md
Next's Image component is incompatible with Github Pages, so we need to take it out in order to get the website to build again.
=> Docs: Remove next image

docs/components/Code.tsx
Demote buttons in CodePreview component to secondary and tertiary.
=> Docs: Apply button weights to code preview

docs/components/Code.tsx
Replace `0.5rem` padding with `1rem` padding
The default padding for [react-simple-code-editor](https://www.npmjs.com/package/react-simple-code-editor) is 10px. They do not offer a very nice way to override this value, which is why I had to use `!important`).
=> docs: Update padding in code examples

.changeset/mighty-seals-flash.md, .changeset/silent-items-protect.md, packages/footer/src/Footer.stories.tsx, packages/header/src/HeaderBrand.tsx
Update responsive logic in Header, so larger font size is shown for tablet viewport.
Also, make some updates to Footer's stories
=> Header: Tweak responsive logic for text sizes

.changeset/wise-terms-guess.md, docs/pages/packages/index.tsx, packages/box/src/styles.ts
This change enables us to use text components (such as `H1`, `H2` etc) inside of `TextLink` and have the colours from all states (hover/focus etc) applied.
=> Box: Add `inherit` to foreground color map

docs/components/Code.tsx
=> Docs: Show secondary button in CodePreview

.changeset/tame-tables-attack.md, packages/header/src/HeaderBrand.tsx
Logo now has a smaller size for mobile viewports
=> Header: Adjust logo sizing for small breakpoints

docs/lib/mdxUtils.ts, docs/pages/guides/[slug].tsx, docs/pages/releases/[slug].tsx
=> docs: Add breadcrumbs to guides and releases

docs/lib/mdxUtils.ts, docs/pages/releases/index.tsx, releases/2022-01-05.mdx, releases/2022-01-07.mdx, releases/2022-01-24.mdx, releases/2022-02-08.mdx, releases/index.mdx
=> docs: Automatically generate release notes page content

.changeset/mighty-files-suffer.md, packages/breadcrumbs/src/BreadcrumbsItem.tsx
We don't need these as they are applied from the `TextLink`
=> Breadcrumbs: Remove typographic props from `BreadcrumbsItem`

.changeset/serious-poets-fetch.md, docs/components/PageLayout.tsx, docs/components/PkgCardList.tsx, docs/pages/index.tsx, packages/columns/README.md, packages/columns/src/Column.stories.tsx, packages/columns/src/Column.tsx, packages/columns/src/Columns.tsx, packages/header/src/HeaderContainer.tsx
As discussed with @mikehazell , we don't really want to be supporting all of the box props in components.
Also I've moved the component into the `Layout` group, as it appears in Gold.
=> Columns: Remove `BoxProps` from `Column` and `Columns`

.changeset/kind-guests-move.md, docs/components/design-system-components.tsx, packages/a11y/CHANGELOG.md, packages/a11y/README.md, packages/a11y/package.json, packages/a11y/src/VisuallyHidden.stories.tsx, packages/a11y/src/VisuallyHidden.tsx, packages/a11y/src/index.ts, packages/search-box/package.json, packages/search-box/src/SearchLabel.tsx, packages/side-nav/package.json, packages/side-nav/src/SideNavLink.tsx, packages/side-nav/src/SideNavTitle.tsx, packages/side-nav/src/utils.ts
Created new package where our a11y utils can live. `side-nav` and `search-box` now make use the `VisuallyHidden` component
=> Add new `a11y` package

.changeset/thirty-emus-sniff.md, packages/button/src/Button.tsx, packages/button/src/utils.tsx
Fixes #121
- Updated horizontal padding for the `sm` variant in the `Button` component
- Added `size` prop to `ButtonLink`
- Refactored how disabled styles are applied
=> Update `Button` padding styles

.changeset/calm-clouds-search.md, packages/button/src/utils.tsx, packages/select/src/Select.tsx, packages/text-input/src/TextInput.tsx
In some browsers these elements have some default margins which need to be reset. If you open up the `SearchBox` component in safari you will see this issue.
=> Button/Textinput/Textarea: Removed default browser margins

.changeset/fast-sheep-unite.md, packages/box/src/styles.ts
Fixed bug in `Box` where border top styles were not being applied when using the `borderTop` prop
=> Box: Fix bug with `borderTop`

.changeset/calm-brooms-sneeze.md, packages/ag-branding/src/theme.ts
Our current alt dark background colours are shades of grey, which don't match the navy tones of our dark backgrounds.
When these colours are mixed, the results can be quite ugly.
This PR replaces the grey alt backgrounds with tones of navy that sit well alongside our existing shades.
=> ag-branding: New alt colours

.changeset/odd-moose-tie.md, packages/core/src/utils/useElementSize.ts
Replaced usage of `useLayoutEffect` with `useEffect` in our custom hook `useElementSize`. This is because it gives us an ugly warning message when server rendering and since the effect isn't important for first render, we can use `useEffect` instead.
For more information please see https://gist.github.com/gaearon/e7d97cdf38a2907924ea12e4ebdf3c85
- [] Add necessary tests
- [] Write documentation (README.md)
- [] Create stories for Storybook
- [] Add components to Playroom (docs/playroom/components.js)
- [] Add snippets to Playroom (docs/playroom/snippets.js)
- [] Add to Docs for jsx live (docs/components/utils.tsx)
- [] Add pictogram to Docs (docs/components/pictograms/index.tsx)
=> Core: Update `useElementSize` hook

.changeset/cyan-spies-kick.md, packages/side-nav/src/SideNavContainer.tsx, packages/side-nav/src/SideNavTitle.tsx
Removed overflow to improve focus state and applied focus ring to side nav collapse button.
=> SideNav: Improve focus state

.changeset/tiny-lions-count.md, packages/a11y/src/VisuallyHidden.tsx, packages/accordion/src/AccordionItem.tsx, packages/columns/src/Columns.tsx, packages/control-input/src/Checkbox.tsx, packages/control-input/src/ControlContainer.tsx, packages/control-input/src/ControlGroup.tsx, packages/control-input/src/ControlInput.tsx, packages/control-input/src/ControlLabel.tsx, packages/control-input/src/Radio.tsx, packages/field/src/FieldContainer.tsx, packages/field/src/FieldLabel.tsx, packages/header/src/HeaderBrand.tsx, packages/icon/src/Icon.tsx, packages/link-list/src/LinkListContainer.tsx, packages/main-nav/src/NavItem.tsx, packages/search-box/src/SearchBox.tsx, packages/search-box/src/SearchBoxButton.tsx, packages/search-box/src/SearchBoxInput.tsx, packages/select/src/Select.tsx, packages/side-nav/src/SideNavGroup.tsx, packages/text-input/src/TextInput.tsx, packages/textarea/src/Textarea.tsx
Improved the typescript types of components with children or extend default HTML elements
- Replaced `children: React.ReactNode` with `PropsWithChildren<{...}>` where possible
- Removed usage of `React.DetailedHTMLProps<{...}>`
=> Improve types of components with children or extend default HTML elements

.changeset/eleven-shrimps-bathe.md, packages/breadcrumbs/src/Breadcrumbs.tsx, packages/link-list/src/LinkList.tsx
Fixes a small typescript bug when combing `Omit` and an array type.
=> Breadcrumbs, LinkList: Fix small typescript bug in main component types

.changeset/silly-rockets-lie.md, packages/header/src/HeaderBrand.tsx
Improve visual appearance of HeaderBadge, to match GOLD
=> Header: HeaderBadge visual tweaks

.changeset/honest-rings-tell.md, packages/search-box/src/SearchBoxButton.tsx
Updated horizontal padding of `SearchBoxButton`. This change is to bring this component more inline with GOLD.
=> SearchBox: Updated horizontal padding of `SearchBoxButton`

.changeset/cuddly-pumpkins-camp.md, packages/select/src/Select.tsx
Added an empty value to the select placeholder. This bug was discovered after I tried to integrate out select component into a form with `react-hook-form`
=> Select: Fix placeholder issue

.changeset/lemon-hotels-hear.md, packages/control-input/src/CheckboxIndicator.tsx, packages/control-input/src/RadioIndicator.tsx
Fixes an issue where checkbox and radio indicators were rendering at 34x34, not 32x32 as intended.
=> Checkbox/Radio: Update size of indicators

.changeset/fair-cycles-attend.md, packages/text-input/src/TextInput.tsx
Rename `InputProps` to `TextInputProps`
=> TextInput: Rename type

.github/workflows/test.yml
- Rename `Preconstruct` to `Build packages` . I think this name is a bit easier to understand.
- run `yarn build` which is defined in our root package.json. This is more consistent with our other scripts in this file.
=> Update test github action

.changeset/thin-pumas-appear.md, packages/field/src/Field.tsx, packages/select/src/Select.tsx, packages/text-input/src/TextInput.tsx, packages/textarea/src/Textarea.tsx
After researching the differences between `required` and `aria-required`, we have reached a conclusion that `aria-required` is better suited for our needs.
- We can't control the message
-  They’re not always announced properly when focusing a field (looking at you Firefox)
- They can’t cater for all the scenarios that we actually need, so you have to implement custom errors anyway, thus giving users inconsistent experiences
=> Replace usage of `required` with `aria-required`

.changeset/flat-bikes-prove.md, packages/breadcrumbs/README.md, packages/link-list/README.md
Remove useless `Box` from documentation
=> LinkList, Breadcrumbs: Update docs

.changeset/fair-shoes-flash.md, packages/field/src/Field.tsx, packages/search-box/src/SearchBoxInput.tsx, packages/select/src/Select.tsx, packages/text-input/src/TextInput.tsx, packages/textarea/src/Textarea.tsx
Fixed a bug in `Field` and updated usage so if an `id` prop is supplied, that value will be used instead of the auto generated ID. This fixes a bug where if you pass an ID into `TextInput`, `Textarea` or `Select, the labels and inputs will not be connected correctly via ids.
=> Field: Update Ids

.changeset/wild-dogs-greet.md, packages/accordion/src/AccordionItem.tsx
- Removed `id` prop from `AccordionItem`.
- Updated format of auto generate IDs.
=> Accordion: Update ID format

.changeset/rude-pants-share.md, docs/playroom/snippets.js, packages/side-nav/src/SideNav.stories.tsx, packages/side-nav/src/SideNav.tsx, packages/side-nav/src/SideNavCollapseButton.tsx, packages/side-nav/src/SideNavContainer.tsx, packages/side-nav/src/SideNavGroup.tsx, packages/side-nav/src/SideNavLink.tsx, packages/side-nav/src/SideNavTitle.tsx, packages/side-nav/src/utils.ts
Improves accessibility of SideNav components, with assistance from @stowball. We did this by ensuring the right aria attributes were applied.
While doing this work, we realised that SideNavContainer was doing too much work, so the logic responsible for collapsing the nav in mobile viewports was uplifted to the core SideNav component.
=> SideNav: Accessibility improvements. Move collapse logic out of container.

.changeset/wild-coats-sneeze.md, packages/inpage-nav/src/InpageNav.tsx, packages/skip-link/src/SkipLinks.tsx
Updated the default aria label to be more consistent with other default aria labels in the system.
=> InpageNav, SkipLinks: Update default aria-label

.changeset/light-taxis-grow.md, packages/box/src/styles.ts, packages/button/src/styles.tsx, packages/core/src/packs.ts, packages/header/src/HeaderBrand.tsx, packages/main-nav/src/NavListItem.tsx, packages/progress-indicator/src/ProgressIndicatorItem.tsx, packages/side-nav/src/SideNavLink.tsx, packages/side-nav/src/SideNavTitle.tsx
Added new underline pack since we use 2 properties for underlines. Fixed some usage where `textDecorationSkipInk` wasn't being used.
=> Core: Add new `underline` pack

.changeset/kind-trees-smile.md, .changeset/polite-seahorses-unite.md, packages/button/README.md, packages/button/src/Button.stories.tsx, packages/button/src/Button.tsx, packages/button/src/styles.tsx, packages/icon/src/index.tsx
=> Button: Add `iconBefore` and `iconAfter` props

.changeset/tender-laws-warn.md, packages/control-input/src/ControlGroup.stories.tsx, packages/control-input/src/ControlGroup.tsx, packages/field/README.md, packages/field/src/Field.stories.tsx, packages/field/src/Field.tsx, packages/select/src/Select.stories.tsx, packages/select/src/Select.tsx, packages/text-input/src/TextInput.stories.tsx, packages/text-input/src/TextInput.tsx, packages/textarea/src/Textarea.stories.tsx, packages/textarea/src/Textarea.tsx
By default, "(optional)" or "(required)" is appended to all form labels. To disable this, you will now be able to set the new `requiredLabel` prop to `false`.
=> Field: Add `requiredLabel` prop

.changeset/two-garlics-agree.md, packages/main-nav/package.json, packages/main-nav/src/NavContainer.tsx, yarn.lock
`react-focus-lock` is a lot more popular then `focus-trap-react`. Also `focus-trap-react` requires `prop-types` as a peer dependency.
=> MainNav: Change focus lock libraries

.changeset/fifty-doors-fail.md, packages/card/src/Card.tsx
Remove the pointer cursor from Card when clickable is true. Why? Because the pointer appears over CardLink which wraps Card anyway.
=> Card: Remove cursor pointer

.changeset/olive-files-rhyme.md, packages/icon/src/Icon.tsx
Our Icon components are currently invalid because they use rem units in the width/height attribute. Setting the width/height in CSS fixes this issue.
=> Icon: Move width/height attributes to CSS

.changeset/dry-bugs-cover.md, .changeset/gold-steaks-travel.md, .changeset/heavy-donkeys-unite.md, example-site/components/FormExampleSinglePage.tsx, packages/control-input/src/ControlGroup.tsx, packages/field/README.md, packages/field/src/FieldContainer.tsx, packages/field/src/index.tsx, packages/field/src/useScrollToField.ts
By default, the browser will scroll the target into view. Because our labels or legends appear above the input, this means the user will be presented with an input without any context, as the label or legend will be off the top of
the screen.
Manually handling the click event, scrolling the question into view and then focussing the element solves this.
=> Field: Add `useScrollToField` hook

.changeset/dry-olives-argue.md, packages/call-to-action/src/CallToAction.tsx
Reduced icon size from 1.5rem to 1rem
=> CallToAction: Reduced icon size from 1.5rem to 1rem

.changeset/sixty-cherries-fix.md, .changeset/ten-hounds-pump.md, packages/body/README.md, packages/modal/src/Modal.stories.tsx, packages/modal/src/ModalPanel.tsx, packages/modal/src/ModalTitle.tsx
- ModalTitle is now a h2 element
- Modal close button is now medium size (from small)
- The maximum width of the Modal now comes from a token value
- Stories for Modal no longer use the Body component.
- Body: Add documentation to explain where Body usage is appropriate.
=> Modal: Design and documentation improvements

.changeset/hungry-beers-design.md, packages/main-nav/src/NavContainer.tsx
Return focus to the Menu button when the MainNav modal is closed in mobile viewports
=> MainNav: Return focus when modal is closed

.changeset/lucky-cooks-rest.md, docs/components/design-system-components.tsx, docs/playroom/components.js, packages/modal/src/Modal.stories.tsx, packages/modal/src/ModalPanel.tsx, packages/modal/src/index.tsx
In Apple VoiceOver and Chrome, the Modal title was not being read out when modal is opened. We discovered this was because the title was not the first child of the Modal.
=> Modal: Make Title required. Resolve issue with Chrome not reading title in VoiceOver

.changeset/weak-icons-share.md, packages/modal/README.md, packages/modal/src/Modal.stories.tsx, packages/modal/src/Modal.tsx, packages/modal/src/ModalButtonGroup.tsx, packages/modal/src/ModalPanel.tsx
We've added an 'actions' prop to Modal, which is the new place where Buttons are added to a Modal.
=> Modal: Buttons appear at bottom of screen in Mobile view

.changeset/little-jeans-brake.md, packages/footer/src/FooterDivider.tsx
From https://www.sarasoueidan.com/blog/horizontal-rules/
> Since horizontal rules are semantic elements announced by screen readers, then unless you’re using a horizontal rule to semantically divide content, you should hide it from screen readers using aria-hidden="true". In other words: use aria-hidden="true" to hide decorational horizontal lines. Do not hide them if they are providing semantic, thematic content breaks.
=> Footer: Hide `FooterDivider` from screen readers

.changeset/pretty-elephants-tan.md, packages/main-nav/src/MainNav.stories.tsx, packages/main-nav/src/MainNav.tsx, packages/main-nav/src/NavContainer.tsx, packages/main-nav/src/NavList.tsx, packages/main-nav/src/utils.ts
Hide mobile toggle button if no links are supplied. Fixes an issue that can be seen here `https://steelthreads.github.io/export-landing/`
=> MainNav: Hide mobile toggle button if no links are supplied

.changeset/blue-moles-prove.md, .changeset/chilly-chefs-remember.md, .changeset/metal-eels-argue.md, packages/control-input/src/ControlGroup.stories.tsx, packages/control-input/src/ControlGroup.tsx, packages/date-picker/README.md, packages/date-picker/src/DatePicker.stories.tsx, packages/date-picker/src/DatePickerInput.tsx, packages/date-picker/src/DateRangePicker.stories.tsx, packages/date-picker/src/DateRangePicker.tsx, packages/field/README.md, packages/field/src/Field.stories.tsx, packages/field/src/Field.tsx, packages/field/src/FieldLabel.tsx, packages/select/README.md, packages/select/src/Select.stories.tsx, packages/select/src/Select.tsx, packages/text-input/README.md, packages/text-input/src/TextInput.stories.tsx, packages/text-input/src/TextInput.tsx, packages/textarea/README.md, packages/textarea/src/Textarea.stories.tsx, packages/textarea/src/Textarea.tsx
- Only append `(optional)` to field labels
- Allow the secondary label to be overridden, for components like the date picker
- Show date format in the date picker component label
=> Remove `(required)` from field labels

.changeset/lucky-moose-flow.md, packages/hero-banner/src/HeroBannerBackground.tsx
Fixes an issue where the image does not get covered by the gradient, as pictured in the screenshot below.
=> HeroBanner: Reverse gradient direction

docs/components/Code.tsx, docs/pages/packages/[group]/[slug].tsx
Keeps the behaviour and UI consistent with the new `Open in Storybook` button
=> Docs: Open in playroom should open in a new tab 

.changeset/hot-pugs-remain.md, packages/breadcrumbs/src/BreadcrumbsDivider.tsx
Updated size from `16px` to `10px` as per design feedback. We have decided not to add this new size to the design system `Icon` component, but instead just inline this size for now.
=> Breadcrumbs: Update size of `BreadcrumbsDivider`

.changeset/afraid-bulldogs-enjoy.md, .changeset/fluffy-hornets-greet.md, .changeset/warm-days-bow.md, docs/components/Code.tsx, docs/components/design-system-components.tsx, docs/components/prism-theme.ts, docs/components/utils.tsx, docs/pages/packages/[group]/[slug].tsx, packages/body/README.md, packages/body/src/Body.stories.tsx, packages/body/src/Body.tsx
At the moment all MDX content on our component pages (i.e https://steelthreads.github.io/agds-next/packages/navigation/main-nav) is wrapped a `Body` component which provides default styles to all child HTML elements. 
This works well, but is causing issue in our live code previews as unwanted body styles are being inherited. This PR fixes this by having a configurable `notSelector`, so the documentation can unset body styles for live code examples.
=> Docs/Body: Prevent body styles from being inherited in live code examples

.changeset/gold-bears-invent.md, packages/modal/src/Modal.stories.tsx, packages/modal/src/ModalButtonGroup.tsx, packages/modal/src/ModalPanel.tsx, packages/modal/src/ModalTitle.tsx
There have been some bugs while testing VoiceOver with Safari and Chrome, which stop a user from being able to navigate the contents of the modal. We found the issue was due to the ModalPanel being focused. Shifting focus to the ModalTitle instead seems to have solved the problem.
=> Modal: Fix bug with Voiceover. ModalTitle is auto-focused

.changeset/twenty-ravens-exercise.md, packages/main-nav/src/MenuButtons.tsx, packages/main-nav/src/NavContainer.tsx
Adding enhancements to the open/close buttons in the MainNav, to improve how the screen reader reads out the page.
**Open button**
Before: "Menu, button, main, navigation"
After: "Open main navigation, collapsed, button, main, navigation"
**Close button**
Before:"Close, button, group, main navigation, dialog"
After: "Close main navigation, expanded, button, main navigation, dialog."
=> MainNav: Add aria labels to MainNav buttons

.changeset/witty-penguins-itch.md, packages/breadcrumbs/src/BreadcrumbsDivider.tsx
Currently the `BreadcrumbsDivider` and `BreadcrumbsItem` are slightly misaligned due to the line height of our links and the bounding box of the chevron icon. We can fix this by nudging the divider icon down by 1px.
=> Breadcrumbs: Improve center alignment of breadcrumbs

.changeset/cyan-meals-dress.md, packages/core/src/packs.ts
Increased control (checkboxes, radio buttons) border widths from `2px` to `3px`.
=> Core: Update control border size

.changeset/red-phones-end.md, packages/secondary-nav/src/SecondaryNav.stories.tsx, packages/secondary-nav/src/SecondaryNavContainer.tsx, packages/secondary-nav/src/SecondaryNavList.tsx
This PR replaces horizontal scrolling with flex wrapping, as discussed with the design team.
Screenshot
=> secondary-nav: Updating wrapping behaviour 

.changeset/neat-kings-learn.md, packages/breadcrumbs/package.json, packages/breadcrumbs/src/Breadcrumbs.tsx
In Voiceover, the active page will be read out as 'Page title (current page)', thanks to our VisuallyHidden component
=> Breadcumbs: Read out 'current page' in active item

.changeset/lemon-planes-report.md, .changeset/three-bees-listen.md, docs/components/Code.tsx, docs/components/EditPage.tsx, docs/components/SiteHeader.tsx, docs/components/design-system-components.tsx, docs/components/utils.tsx, docs/pages/index.tsx, docs/pages/packages/[group]/[slug].tsx, docs/playroom/components.js, packages/a11y/README.md, packages/a11y/src/ExternalLinkCallout.stories.tsx, packages/a11y/src/ExternalLinkCallout.tsx, packages/a11y/src/VisuallyHidden.stories.tsx, packages/a11y/src/index.ts, packages/text/README.md, packages/text/package.json, packages/text/src/Text.tsx, packages/text/src/TextLink.tsx, packages/text/src/TextLinkExternal.tsx, packages/text/src/index.tsx
- Create ExternalLinkCallout component, to consistently announce to a screenreader that a link that will open in a new tab
- Create TextLinkExternal for body links that open in a new tab.
- Use TextLinkExternal and ExternalLinkCallout within the documentation website
- Move TextLink to own files
=> Text: Create TextLinkExternal and ExternalLinkCallout

example-site/components/FormExampleMultiStep/FormExampleMultiStep1.tsx, example-site/components/FormExampleMultiStep/FormExampleMultiStepActions.tsx
On step 3, the divider is not inside of the `FormStack` which causes incorrect spacing of elements
=> example-site: Fix multi step form stack

.changeset/mighty-berries-wash.md, docs/components/PageTitle.tsx, docs/components/TemplateLayout.tsx, docs/pages/packages/[group]/[slug].tsx, example-site/components/FormExampleMultiStep/FormExampleMultiStep0.tsx, example-site/components/FormExampleMultiStep/FormExampleMultiStep1.tsx, example-site/components/FormExampleMultiStep/FormExampleMultiStep2.tsx, example-site/components/FormExampleMultiStep/FormExampleMultiStep3.tsx, example-site/components/FormExampleMultiStep/FormExampleMultiStep4.tsx, example-site/components/FormExampleMultiStep/FormExampleMultiStepContainer.tsx, example-site/components/PageTitle.tsx, example-site/pages/form-multi-step/index.tsx, example-site/pages/form-sign-in.tsx, example-site/pages/form-single-page.tsx
Created a `PageTitle` component which is composed of a pretext, title and introduction paragraph. This has been moved into a component as it repeated on almost every page of docs website and example website.
=> docs/example: Add `PageTitle` component

.changeset/hot-pears-rest.md, packages/breadcrumbs/src/BreadcrumbsContainer.tsx
In [this example from W3](https://www.w3.org/TR/wai-aria-practices/examples/breadcrumb/index.html), the Breadcrumbs examples uses an OL html element. I've updated ours to do the same.
=> Breadcrumbs: Use ordered list

.changeset/wicked-tools-sneeze.md, example-site/components/FormExampleMultiStep/FormExampleMultiStep3.tsx, example-site/components/FormExampleMultiStep/utils.ts
In this PR, we have improved the form validation for the 'conditional' step in the multi-step for, by showing validation messages onChange.
We've also changed the state-management logic, so each checkbox is treated as a value for the 'checkbox' field, rather than each being treated as seperate values.
=> Examples: Improve validation in mutli-step form conditional step

.changeset/selfish-socks-hide.md, packages/body/src/Body.tsx
- Updated color of `hr` elements
- Removed margin top for first of type blockquotes and figures
Screenshot of fixed issue
=> Body: Adjust styles for blockquotes and hr

.changeset/pretty-parents-complain.md, packages/link-list/README.md, packages/link-list/src/LinkListItem.tsx
Links that open in a new tab will use show the external link indicator.
=> LinkList: Use external link indicator

.changeset/rare-avocados-develop.md, docs/components/Code.tsx, docs/components/SiteFooter.tsx, packages/text/src/TextLinkExternal.tsx
Update `TextLinkExternal` to use the link component from context.
=> TextLinkExternal: Use global link component

.changeset/cool-buttons-press.md, .storybook/stories/kitchenSink.tsx, docs/playroom/snippets.js, packages/accordion/README.md, packages/accordion/src/Accordion.stories.tsx
This PR fixes a typography bug in the accordion package documentation.
- One of the examples has a `p` tag not wrapped in a `Body` tag which causes incorrect styling. 
- Lots of the examples use `span` tags instead of `p` tags
=> accordion: Update documentation

.changeset/popular-ligers-pay.md, packages/breadcrumbs/src/BreadcrumbsContainer.tsx
Fix breadcrumb items shrinking smaller devices.
| <img width="375" alt="Screen Shot 2022-06-03 at 2 19 30 pm" src="https://user-images.githubusercontent.com/6265154/171785537-1be91273-e694-47f1-be6a-f6743031df79.png">      | <img width="376" alt="Screen Shot 2022-06-03 at 2 19 43 pm" src="https://user-images.githubusercontent.com/6265154/171785530-c0b890ea-b279-40e1-8cea-821fa8820931.png">       |
=> breadcrumbs: Fix items shrinking smaller devices

.changeset/orange-mice-cheer.md, .changeset/shy-buckets-sleep.md, packages/file-upload/src/FileUpload.tsx
- Fix Select button in Safari, which did not add the file to the 'value' of the input.
- Fix bug that caused the red tint to not be applied in 'internal validation'.
- Indent file validation messages to sit within the red border.
=> FileUpload: Fix Select button in Safari. Styling improvements

example-site/pages/category/subcategory/content.tsx
The links on the `content` example site page are currently broken. They should just be "fake" links as they don't go anywhere.
=> example-site: Fix broken links on content page

.changeset/dirty-guests-deny.md, docs/components/Code.tsx, docs/components/design-system-components.tsx, docs/pages/packages/[group]/[slug].tsx, docs/playroom/components.js, example-site/pages/category/subcategory/multi-page-form/index.tsx, example-site/pages/index.tsx, packages/button/README.md, packages/button/src/BaseButton.tsx, packages/button/src/Button.stories.tsx, packages/button/src/Button.tsx
- Added the ability the forward refs and use the as prop
- Removed `ButtonLink` component. Usage of this component can be replaced with:
```jsx
const Link = useLinkComponent();
return (
<Button as={LinkComponent} href="/sign-in">
Sign in
</Button>
);
```
=> button: use `forwardRefWithAs`

.changeset/plenty-elephants-cover.md, docs/components/design-system-components.tsx, docs/playroom/components.js, example-site/components/FormExampleMultiStep/FormExampleMultiStep.tsx, packages/direction-link/README.md, packages/direction-link/src/DirectionLink.stories.tsx, packages/direction-link/src/DirectionLink.tsx
- Added the ability the forward refs and use the as prop
- Removed `DirectionButton` component. Usage of this component can be replaced with `<DirectionLink as={BaseButton} {...} />`
=> direction-link: Use `forwardRefWithAs`

.changeset/gold-pants-provide.md, packages/call-to-action/src/CallToAction.tsx, packages/direction-link/src/DirectionLink.tsx, packages/progress-indicator/src/ProgressIndicator.stories.tsx, packages/progress-indicator/src/ProgressIndicator.tsx, packages/progress-indicator/src/ProgressIndicatorCollapseButton.tsx, packages/progress-indicator/src/ProgressIndicatorItem.tsx
- Added the ability the forward refs and use the as prop
- Removed `ProgressIndicatorItemLink` and `ProgressIndicatorItemButton`. Usage of these components can be replaced with:
```jsx
const Link = useLinkComponent();
return <ProgressIndicatorItem as={LinkComponent} {...} />
```
=> progress-indicator: Use `forwardRefWithAs`

.changeset/cool-adults-relax.md, .changeset/sweet-actors-hammer.md, packages/core/src/CoreProvider.tsx, packages/side-nav/src/SideNavTitle.tsx, packages/tags/src/Tag.tsx, packages/text-link/src/TextLink.tsx
Updated `TextLink` to internally render a `Box` instead of `Text`. This is so font size is inherited from the parent.
=> TextLink: Inherit font size

.changeset/flat-teachers-smile.md, packages/call-to-action/README.md, packages/control-input/README.md, packages/direction-link/README.md, packages/file-upload/README.md, packages/inpage-nav/README.md, packages/link-list/README.md, packages/main-nav/README.md, packages/page-alert/README.md, packages/progress-indicator/README.md, packages/secondary-nav/README.md, packages/side-nav/README.md, packages/skip-link/README.md, packages/task-list/README.md, packages/text-link/README.md
This PR makes sure every component uses title case. Right now, this is a bit inconsistent.
=> docs: Update component names to title case

docs/playroom.config.js
We need to include ur typescript types in our playroom config, otherwise we don't get the nice autocomplete!
=> Add typescript types to playroom

docs/playroom/components.js
The `Button` component doesn't work in playroom, I believe this was just the result of a bad merge.
=> playroom: Add button component

.changeset/six-sheep-itch.md, docs/components/Code.tsx, docs/components/EditPage.tsx, docs/components/PkgLayout.tsx, docs/components/SiteFooter.tsx, docs/components/SiteHeader.tsx, docs/components/utils.tsx, docs/pages/index.tsx, example-site/components/SiteFooter.tsx, example-site/pages/category/subcategory/multi-page-form/index.tsx, packages/breadcrumbs/src/Breadcrumbs.stories.tsx, packages/button/docs/overview.mdx, packages/button/src/Button.stories.tsx, packages/link-list/README.md, packages/main-nav/src/MainNav.stories.tsx
Removed `target="_blank"` from all links as per accessibility recommendations.
=> docs/example: Remove links that open up new tabs

packages/control-input/src/Checkbox.stories.tsx
I was referencing Checkbox while building Switch, and the storybook UI didn't let me set a disabled state
=> Checkbox: Preset disabled states in storybook examples

.changeset/chilly-dolphins-flash.md, packages/switch/src/Switch.tsx
Prevent hover styles from being applied when element is focused. 
https://user-images.githubusercontent.com/6265154/175463490-a75593b7-aaa7-4fa6-ae32-329dfa8d4c3b.mov
=> switch: Prevent hover styles from being applied when element is focused

.changeset/honest-sloths-shave.md, docs/components/PkgLayout.tsx, docs/components/TemplateLayout.tsx, docs/lib/mdx/packages.ts
Next allows us to prevent scrolling to the top of the page when using their `Link` component. More information  about this can be found here: https://nextjs.org/docs/api-reference/next/link#disable-scrolling-to-the-top-of-the-page
This PR disabled automatic scrolling to top of page for the `SubNav` component on our templates and packages page.
=> docs: Disable scrolling to the top of the page when using `SubNav`

example-site/components/FormExampleMultiStep/FormExampleMultiStep0.tsx, example-site/components/FormExampleMultiStep/FormExampleMultiStep1.tsx, example-site/components/FormExampleMultiStep/FormExampleMultiStep2.tsx, example-site/components/FormExampleMultiStep/FormExampleMultiStep3.tsx, example-site/components/FormExampleMultiStep/FormExampleMultiStep4.tsx, example-site/components/FormExampleSignIn.tsx, example-site/components/FormExampleSinglePage.tsx, guides/forms.mdx, packages/file-upload/src/FileUpload.stories.tsx
This PR adds [`noValidate`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form#attr-novalidate)  to all of our forms which use `react-hook-form`. This built-in browser validation isn't necessary since we're already doing extensive client side validation using `yup`.
=> examples: Disable native HTML5 validation

docs/lib/mdx/packages.ts
Prevents the `rationale` page appearing on documentation pages where we don't have content.
=> docs: Fix rationale page showing incorrectly

.changeset/new-err-token.md, packages/ag-branding/src/theme.ts
Add an "ag overwrite" for the system error token colour.
The result is a much more vibrant red which improves contrast on dark mode:
=> ag-branding: New error token

.changeset/long-chairs-know.md, packages/field/src/FieldMessage.tsx
Prevent flex shrinking of field message alert icon
| <img width="330" alt="Screen Shot 2022-07-05 at 11 29 47 am" src="https://user-images.githubusercontent.com/6265154/177234101-76a4216e-e0e7-4bf1-b832-ef372970e8f0.png">      | <img width="330" alt="Screen Shot 2022-07-05 at 11 29 26 am" src="https://user-images.githubusercontent.com/6265154/177234095-0e591cd3-e948-48ae-acc7-ca96a14ae7f8.png">       |
=> field: add flex shrink to message error icon

.changeset/small-toys-visit.md, docs/components/ComponentPropsTable.tsx, packages/table/src/Table.tsx, packages/table/src/TableCell.tsx, packages/table/src/TableHeader.tsx
Adjust widths to improve content in the component props table
=> docs: Adjust widths in props table

.changeset/grumpy-stingrays-repeat.md, packages/button/src/BaseButton.tsx
All buttons in the design system are routed through our `BaseButton` component which provides us with a blank slate for styling, as well as a centralised place to fixing any global a11y issues. This PR adds the `type="button` to button components by default, which will prevent various components from accidentally submitting forms.
=> button: Add default `type` to `BaseButton`

packages/core/src/tokens.stories.tsx
Add a backgrounds story to the Core/Tokens group. This is a visualisation of how backgrounds work together.
Please note that colours in screenshot do not match live tokens.
=> Story: Visualisation of background tokens

.changeset/mean-cherries-sniff.md, packages/sub-nav/docs/overview.mdx, packages/sub-nav/src/SubNav.stories.tsx, packages/sub-nav/src/SubNav.tsx, packages/sub-nav/src/SubNavContainer.tsx
- Replace 'variant' with 'background' prop
- Remove parent definition, so the colours change with parent context
=> SubNav: Add background prop

.changeset/nine-experts-help.md, docs/components/PageLayout.tsx, example-site/pages/category/subcategory/content.tsx, packages/side-nav/docs/overview.mdx, packages/side-nav/src/SideNav.stories.tsx, packages/side-nav/src/SideNav.tsx, packages/side-nav/src/SideNavContainer.tsx, packages/side-nav/src/utils.ts
Our `SideNav` component internally sets its palette. That means that if it's parent changes palette from light to dark, the SideNav does not change (pictured)
This PR changes the props to remove palette setting.
**Before:** `variant: 'light' | 'lightAlt' | 'dark' | 'darkAlt`
**After:** `background: 'body' | 'bodyAlt`
=> SideNav: Add background prop

.changeset/quick-ravens-sparkle.md, docs/pages/index.tsx, example-site/pages/category/index.tsx, example-site/pages/category/subcategory/index.tsx, example-site/pages/index.tsx, packages/hero-banner/docs/overview.mdx, packages/hero-banner/src/HeroBanner/HeroBanner.stories.tsx, packages/hero-banner/src/HeroBanner/HeroBanner.tsx, packages/hero-banner/src/HeroBanner/HeroBannerContainer.tsx, packages/hero-banner/src/HeroBanner/HeroBannerContent.tsx, packages/hero-banner/src/HeroBanner/HeroBannerImage.tsx, packages/hero-banner/src/HeroCategoryBanner/HeroCategoryBanner.stories.tsx, packages/hero-banner/src/HeroCategoryBanner/HeroCategoryBanner.tsx, packages/hero-banner/src/HeroCategoryBanner/HeroCategoryBannerContainer.tsx, packages/hero-banner/src/HeroCategoryBanner/HeroCategoryBannerContent.tsx, packages/hero-banner/src/HeroCategoryBanner/HeroCategoryBannerImage.tsx, packages/hero-banner/src/HeroSubcategoryBanner/HeroSubcategoryBanner.stories.tsx, packages/hero-banner/src/HeroSubcategoryBanner/HeroSubcategoryBanner.tsx, packages/hero-banner/src/HeroSubcategoryBanner/HeroSubcategoryBannerContainer.tsx, packages/hero-banner/src/utils.ts
Our HeroBanner components internally sets palette. That means that if it's parent changes palette from light to dark, the HeroBanner does not change (pictured)
We've replaced `variant` props (light, lightAlt, dark, darkAlt) with `background` (body, bodyAlt)
=> HeroBanner: Add background prop

.changeset/moody-games-sort.md, docs/components/Code.tsx, packages/body/src/Body.tsx
This PR exports a new variable `bodyBlockClassname`.
=> body: Allow consumers to keep vertical rhythm on specific elements

.storybook/stories/kitchenSink.tsx
Add a variant of the kitchen sink story that showcases components with their alternate backgrounds set.
=> Storybook: Add alt backgrounds example to kitchen sink story

.changeset/loud-lions-cheat.md, packages/file-upload/src/FileRejection.stories.tsx, packages/file-upload/src/FileRejection.tsx, packages/file-upload/src/FileUpload.stories.tsx, packages/file-upload/src/FileUpload.tsx, packages/file-upload/src/FileUploadFile.stories.tsx, packages/file-upload/src/FileUploadFile.tsx, packages/file-upload/src/utils.tsx
- New UI for rejected files ([Product Backlog Item 261307](https://dev.azure.com.mcas.ms/agriculturegovau/Digital%20Services/_workitems/edit/261307?McasTsid=26110))
- Increase spacing between drop zone and file list ([Product Backlog Item 262389](https://dev.azure.com.mcas.ms/agriculturegovau/Digital%20Services/_workitems/edit/262389?McasTsid=26110))
- Enable removal (hiding) of errors
- Improve props for FileUploadFile component
I recommend opening the "multiple images" Story for FileUpload in Storybook, and attempting to drag in a .pages file (or other) that is too large for the max size.
=> FileUpload: New rejected file UI

.changeset/real-pugs-share.md, packages/box/src/styles.ts
Add `columnGap` and `rowGap` props to Box component. Useful for both flexBox and grid.
=> Box: Add `columnGap` and `rowGap` props

.changeset/silent-swans-visit.md, packages/side-nav/docs/overview.mdx, packages/side-nav/src/SideNav.stories.tsx, packages/side-nav/src/SideNav.tsx, packages/side-nav/src/SideNavTitle.tsx
Converted `titleLink` into an optional prop. This removes an old `TODO` that has been there since this component was created.
=> side-nav: Make `titleLink` optional

packages/badge/src/StatusBadge.stories.tsx, packages/badge/src/StatusBadge.tsx, packages/card/src/Card.stories.tsx
Original goal was to publish some examples where StatusBadge is used effectively in context - both in Cards and in a Table.
I got a bit side-tracked by doing some testing and [research on building accessible cards](https://inclusive-components.design/cards/). This thinking was captured in this Story but I can't say it's perfect. Would be great for someone to test further.
Happy to discuss this further
=> Storybook: Add examples of Cards, and Table with StatusBadge

.changeset/spicy-pillows-stare.md, packages/core/src/Core.tsx, packages/core/src/theme.tsx
Fixed bug in the `Core` component where if no theme was supplied, the default theme (GOLD) was not being applied.
=> core: Fix bug where default theme is not applied

.changeset/happy-yaks-crash.md, packages/prose/src/Prose.tsx
Added horizontal scrolling to `pre` tags to prevent page overflow
| <img width="321" alt="Screen Shot 2022-07-28 at 10 51 08 am" src="https://user-images.githubusercontent.com/6265154/181400381-cceec95a-dc2f-4318-9de5-a26b3d55cd81.png">      | <img width="319" alt="Screen Shot 2022-07-28 at 10 57 41 am" src="https://user-images.githubusercontent.com/6265154/181400390-b7f0a020-700c-4be2-9573-83961b892a48.png">       |
=> prose: add horizontal scrolling to `pre` tags

.changeset/gentle-eggs-cough.md, packages/sub-nav/src/SubNavContainer.tsx, packages/sub-nav/src/SubNavListItem.tsx
Updated bottom bar colour to `borderMuted`
=> SubNav: Update bottom bar colour

.changeset/nine-zoos-shop.md, packages/breadcrumbs/src/Breadcrumbs.stories.tsx, packages/breadcrumbs/src/Breadcrumbs.tsx, packages/breadcrumbs/src/BreadcrumbsContainer.tsx, packages/breadcrumbs/src/BreadcrumbsItem.tsx
Added mobile variant which shows a link to the immediate parent.
=> breadcrumbs: Add mobile version

docs/lib/mdx/guides.ts, docs/pages/guides/index.tsx, guides/index.mdx
Automatically populate the `guides` home page with the the list of guides.
=> docs: Add card list to guides page

packages/loading/src/LoadingBlanketContainer.tsx, packages/loading/src/LoadingDots.tsx
- Rollback recent change that forces text color in loading dots
- Ensure loading blanket applies text color
=> Rollback recent change that forces text color to LoadingDots

.changeset/fifty-carrots-yawn.md, packages/header/src/Header.stories.tsx, packages/header/src/Header.tsx, packages/header/src/HeaderBrand.tsx, packages/header/src/HeaderContainer.tsx
Enable a more compact header component, primarily for internal applications.
=> Header: Add 'small' size

packages/header/src/Header.stories.tsx, packages/header/src/Header.tsx, packages/header/src/HeaderBrand.tsx, packages/header/src/HeaderContainer.tsx
Follow up of #638 
Renames the options in the `size` prop from `small | medium` to `sm | md` for consistency.
=> Header: Rename `size` prop options

.changeset/early-carpets-clap.md, packages/a11y/docs/overview.mdx, packages/a11y/src/ExternalLinkCallout.tsx
Some screen readers will announce the parenthesis as “left parenthesis” “right parenthesis” adding unneeded verbosity to the link text which may confuse some users.
=> a11y: update external link callout screen reader text

.changeset/pretty-bottles-call.md, docs/pages/templates/[slug]/index.tsx, docs/pages/templates/index.tsx, docs/playroom/snippets.js, example-site/pages/category/index.tsx, example-site/pages/index.tsx, packages/hero-banner/docs/overview.mdx, packages/hero-banner/src/HeroBanner/HeroBanner.stories.tsx, packages/hero-banner/src/HeroCategoryBanner/HeroCategoryBanner.stories.tsx
Improved a11y in examples by setting example image to be decorative. This can be done by setting `alt=""` and `role="presentation`. https://www.w3.org/WAI/tutorials/images/decorative/
=> hero-banner: a11y fix

.changeset/tame-beans-build.md, packages/control-input/src/Checkbox.tsx, packages/control-input/src/CheckboxIndicator.tsx, packages/control-input/src/ControlContainer.tsx, packages/control-input/src/ControlLabel.tsx, packages/control-input/src/Radio.tsx, packages/control-input/src/RadioIndicator.tsx
- Prevented the checkbox and radio indicator for shrinking
- Updated alignment of labels to ensure multi-line labels are aligned vertically
=> control-input: fix indicator shrinking and label alignment

.changeset/pretty-shoes-move.md, .changeset/rich-experts-refuse.md, .changeset/shy-camels-allow.md, packages/button/src/styles.tsx, packages/core/src/packs.ts, packages/text-input/src/TextInput.tsx
- Adjusted height and line-height of buttons and text inputs to align better to an 8px baseline grid.
- Adjusted `sm` button font size
- Adjusted text button styles
=> Align buttons and inputs to 8px baseline grid

.changeset/ninety-mayflies-brake.md, packages/side-nav/src/SideNavCollapseButton.tsx, packages/side-nav/src/SideNavGroup.tsx
- Removed `aria-haspopup="menu"`  to convert the ARIA Menu Button to a simple [disclosure widget](https://www.w3.org/WAI/ARIA/apg/patterns/disclosure/).
- Removed `role="menu"` from the `<ul>` as this was only partially implemented.
=> side-nav: improve a11y

.changeset/many-rice-sin.md, packages/main-nav/src/MenuButtons.tsx
On the main navigation the visible label for the hamburger menu is different from its label in code. 
Speech recognition software users may not be able to reference the element directly because its visible label doesn’t match its code label.
=> main-nav: update open and close button aria label

.changeset/neat-bobcats-think.md, .changeset/short-deers-smile.md, packages/badge/src/IndicatorDot.tsx, packages/box/src/styles.ts, packages/call-to-action/src/CallToAction.tsx, packages/callout/src/Callout.tsx, packages/date-picker/src/reactDayPickerStyles.ts, packages/loading/src/LoadingDots.tsx, packages/page-alert/src/PageAlert.tsx, packages/skeleton/src/SkeletonBox.tsx
- Added new `highContrastOutline` prop to our box component. This applies a transparent outline which will be visible in windows high contrast mode.
- Applied new prop to a few components which need to be improved in high contrast mode
=> Improve windows high contrast mode a11y

.changeset/giant-beds-push.md, packages/control-input/docs/overview.mdx, packages/control-input/package.json, packages/control-input/src/ControlGroup.tsx
Improve accessibilty of our control group component by connecting the "hint" and "message" field to the `fieldset` element.
An example of this pattern can be found on the gov uk website: https://design-system.service.gov.uk/components/error-message/
=> control-group: Improve a11y

docs/components/PictogramCard.tsx
The pictogram alt text seen in our packages list are more irritating than helpful when using a screenreader
before:
```
heading level 2, forms
pictogram of button
button, link
pictogram of control input
control input, link
```
after:
```
heading level 2, forms
button, link
control input, link
date picker, link
```
=> Hide pictograms from screenreaders

.changeset/tiny-rockets-tap.md, packages/modal/src/Modal.tsx, packages/modal/src/ModalCover.tsx
For VoiceOver on iOS when the modal is open, focus is not trapped inside of the modal. A screen-reader user can navigate away from the modal content and continue to navigate the parent page.
In this PR I have added `aria-hidden="true"` to every direct child of the `body` element when the modal is opened.  This is because `aria-modal` is not yet supported by [all browsers](https://a11ysupport.io/tech/aria/aria-modal_attribute).
=> modal: fixed accessibilty bug in VoiceOver iOS

.changeset/serious-vans-decide.md, packages/main-nav/src/MainNav.tsx, packages/main-nav/src/NavContainer.tsx, packages/main-nav/src/NavList.tsx
Address issues with invalid HTML picked up in an accessibility audit. (DAGR-95)
- Ensure the role="dialog" and aria-modal="true" is completely removed on viewport sizes where it does not apply
- Avoid using aria-label on generic elements like a `<div/>`
- Remove role="none" on the `<div/>`
- Moved the parent <nav> element found higher up in the DOM to instead be a child of the dialog/main navigation container rather than a parent.
[Product Backlog Item 296763](https://dev.azure.com.mcas.ms/agriculturegovau/Digital%20Services/_workitems/edit/296763?McasTsid=26110): DAGR 95 - parsing errors may effect assistive tech in MainNav
=> MainNav: Address invalid HTML (DAGR-95)

.changeset/eleven-stingrays-refuse.md, .changeset/sharp-bobcats-deny.md, .changeset/tiny-ads-enjoy.md, .changeset/tiny-eagles-learn.md, packages/field/src/FieldMessage.tsx, packages/file-upload/src/FileRejection.tsx, packages/file-upload/src/FileUploadFile.tsx, packages/icon/src/Icon.tsx, packages/page-alert/src/PageAlert.tsx
- Icon: Add support for `aria-label` and `aria-hidden`
- Field: Add aria-label to icon (DAGR-72)
- FileUpload: Add aria-label to icon (DAGR-81)
=> Add aria-label to Icons (DAGR-72/DAGR-81/DAGR-88)

.changeset/fair-pens-talk.md, .changeset/nervous-months-suffer.md, packages/button/src/Button.tsx, packages/file-upload/src/FileUploadFile.tsx, packages/loading/docs/overview.mdx, packages/loading/package.json, packages/loading/src/LoadingBlanket.stories.tsx, packages/loading/src/LoadingBlanket.tsx, packages/loading/src/LoadingBlanketLabel.tsx, packages/loading/src/LoadingDots.stories.tsx, packages/loading/src/LoadingDots.tsx
- Loading Dots: Replace aria-label with visually hidden text (DAGR-70). This prop is optional as there could be better ways to show a composition is loading (like the text inside of a loading blanket)
=> Loading: Improve accessibility for screenreader users (DAGR-70)

.changeset/tender-cows-think.md, packages/pagination/src/PaginationItemPage.tsx, packages/pagination/src/PaginationItemSeparator.tsx
Accessibility improvements
- Read out 'current page' in `PaginationItemPageButton` (DAGR-102)
- Read out 'ellipsis' in `PaginationItemSeperator`
=> Pagination: Read out current page for PaginationButtons (DAGR-102)

docs/playroom/snippets.js, packages/footer/docs/overview.mdx, packages/footer/src/Footer.stories.tsx
While the heading elements are nested inside of a `<footer>` the heading level assignment of `H3` may impact the page's heading hierarchy for screen reader users. If there are `H2` elements higher up in the page, screen reader users may think this content is a child of that content from a document structure perspective.
No changeset required as not making any changes to code.
=> footer: update headings in examples (DAGR93)

.changeset/slow-gorillas-tan.md, packages/field/src/FieldLabel.tsx
There is currently an issue when using voice over on macos in safari. When interacting with form fields that have secondary text, such as required, optional, dd/mm/yyyy etc, safari doesn't read out the secondary label. For example:
- Code: `<TextInput label="Name" />`
- Rendered Label: `Name (Optional)`
- Safari VO: `Name, and 1 other item,  edit text`
- Chrome VO: `Name, optional,  edit text`
With the proposed changes, safari will read out the secondary label text as expected.
=> field: improve screen reader experience when using secondary label (DAGR-71)

docs/components/mdxComponents.tsx, packages/a11y/docs/overview.mdx
- Update documentation of ExternalLinkCallout to discourage usage. [Old version here](https://steelthreads.github.io/agds-next/packages/foundations/a11y)
- Add 'PageAlert' component to docs site
=> ExternalLinkCallout: Update docs to discourage usage (DAGR-87)

.changeset/quiet-ways-complain.md, packages/card/src/Card.stories.tsx, packages/card/src/Card.tsx, packages/card/src/CardLink.tsx
his PR ensures that when `CardLink` is used, the text within the card is selectable and the entire card is clickable. Please read more about this technique here: https://inclusive-components.design/cards/#theredundantclickevent
=> card: Improve a11y when using `CardLink` (DAGR91)

scripts/plopfile.mjs
Automatically add a component to the `designSystemComponents.tsx` file when running `yarn new:package`.
There is a minor formatting issue with the extra new line above
=> Plop script: Add component to Docs site

example-form/pages/not-found.tsx
Updated the copy on the not found (fake 404) page for the `example-form`
=> example-form: Improve 404 page

docs/pages/index.tsx
Adds `main` tag to home page to fix broken skip links.
=> docs: Add `main` tag to home page (DAGR-111, DAGR-110)

.changeset/slow-moose-rest.md, packages/field/src/Field.test.tsx, packages/field/src/Field.tsx, packages/field/src/__snapshots__/Field.test.tsx.snap
Improved accessibility by ensuring `aria-describedby` is only rendered when there is a value
=> field: Improve a11y (DAGR-119)

docs/components/Code.tsx, docs/components/prism-theme.ts
Retheme the website code block to increase accessibility, use more of our tokens, and generally improve its appearance.
The theme was inspired by the Github VSCode theme.
=> docs: Retheme code block

.changeset/polite-books-guess.md, .changeset/swift-bears-cover.md, packages/core/src/boxPalette.ts, packages/main-nav/package.json, packages/main-nav/src/NavContainer.tsx, packages/main-nav/src/__snapshots__/MainNav.test.tsx.snap
- Added new hook `useBoxPalette` which returns the current palette for a specific DOM element
- Improved accessibility of `main-nav` component
=> main-nav: Improve focus trapping for screen readers (DAGR-109)

.changeset/lucky-balloons-hang.md, example-site/components/FormExampleMultiStep/FormExampleMultiStep2.tsx, packages/date-picker/src/DatePicker.test.tsx, packages/date-picker/src/DatePicker.tsx, packages/date-picker/src/DateRangePicker.test.tsx, packages/date-picker/src/DateRangePicker.tsx, packages/date-picker/src/__snapshots__/DatePicker.test.tsx.snap, packages/date-picker/src/__snapshots__/DateRangePicker.test.tsx.snap
Added ability to pass ref to the input elements which makes it possible to automatically focus the field when an error occurs.  This fixes DAGR-124. 
More specifically: 
- DatePicker: Added new prop `inputRef`
- DateRangePicker: Added new props `fromInputRef` and `toInputRef`
- Added tests
=> date-picker: add ability to pass refs to the input element

docs/components/Code.tsx
The component used for our 'non-live' static code blocks was rendering a disabled TextArea. This was captured by the accessibility review as the text area did not have a label.
We've fixed the issue by replacing it with a component that renders a `<pre>` tag instead.
=> Docs: Code block does not use pre-tag (DAGR-115)

example-form/components/FormRegisterPetDetails/FormRegisterPetDetails.tsx, example-form/components/FormRegisterPetDetails/FormRegisterPetDetailsActions.tsx, example-form/components/FormRegisterPetDetails/FormRegisterPetDetailsContainer.tsx, example-form/components/FormRegisterPetDetails/FormRegisterPetDetailsStep0.tsx, example-form/components/FormRegisterPetDetails/FormRegisterPetDetailsStep1.tsx, example-form/components/FormRegisterPetDetails/FormRegisterPetDetailsStep2.tsx, example-form/components/FormRegisterPetDetails/FormRegisterPetDetailsStep3.tsx, example-form/components/FormRegisterPetDetails/FormRegisterPetDetailsStep4.tsx, example-form/components/FormRegisterPetPersonalDetails/FormRegisterPetPersonalDetailsContainer.tsx, example-form/components/FormRegisterPetPersonalDetails/FormRegisterPetPersonalDetailsStep0.tsx, example-form/components/PageTitle.tsx, example-site/components/FormExampleMultiStep/FormExampleMultiStep2.tsx, example-site/components/FormExampleMultiStep/FormExampleMultiStepContainer.tsx, example-site/components/PageTitle.tsx
Improve focus management of multi-step form (both the register your pet form and multi-page form in our examples). This has included
- Focus the title of the current step as the user navigates between form steps
- Fixed a bug where the invalid state for the date picker is sometimes not shown
- [] Write documentation (README.md)
=> Improve focus management of multi-step form

guides/getting-started.mdx
Fix issue from a11y audit:
[Product Backlog Item 319337](https://dev.azure.com.mcas.ms/agriculturegovau/Digital%20Services/_workitems/edit/319337?McasTsid=26110): DAGR-116: Link text is not descriptive
=> docs: Rewrite links to be more unique in Getting Started

.changeset/tasty-sheep-smoke.md, packages/side-nav/src/SideNav.stories.tsx, packages/side-nav/src/SideNav.tsx, packages/side-nav/src/SideNavContainer.tsx, packages/side-nav/src/__snapshots__/SideNav.test.tsx.snap
From [DAGR-112: Section element name could be improved (319203)](https://dev.azure.com.mcas.ms/agriculturegovau/Digital%20Services/_workitems/edit/319203?McasTsid=26110): 
The SideNav has an aria-label of "side navigation". This name is not applicable when the sectioning element owns 100% of the viewport's width.
=> side-nav: Remove `aria-label`

packages/core/src/boxPalette.ts, packages/core/src/responsive.test.ts
Added tests for  the`mq` and `mapResponsiveProp` functions in `core`, which are responsible for responsive style generation.
=> core: Add tests for responsive style generation

.changeset/silver-games-wash.md, packages/progress-indicator/src/ProgressIndicator.test.tsx, packages/progress-indicator/src/ProgressIndicator.tsx, packages/progress-indicator/src/ProgressIndicatorItem.tsx, packages/progress-indicator/src/__snapshots__/ProgressIndicator.test.tsx.snap
Similar to #746, but for the `progress-indicator` package. 
- Added missing role attribute to the side nav body element.
- Removed `role` and `aria-labelledby` on larger screens as the accordion widget is not visible.
Also added some tests.
=> progress-indicator: Improved HTML for larger screen sizes

.github/pull_request_template.md
Now that our tests are getting more useful, we should be running `yarn test` to ensure snapshots are still passing.
=> PR checklist: Add run test and update snapshots as a checklist item

.changeset/nine-spies-design.md, .changeset/ninety-pumas-cry.md, packages/date-picker/src/DatePicker.test.tsx, packages/date-picker/src/DatePickerInput.tsx, packages/date-picker/src/DateRangePicker.test.tsx, packages/date-picker/src/__snapshots__/DatePicker.test.tsx.snap, packages/date-picker/src/__snapshots__/DateRangePicker.test.tsx.snap, packages/details/src/Details.test.tsx, packages/field/src/Field.test.tsx, packages/field/src/__snapshots__/Field.test.tsx.snap, packages/search-box/src/Search.test.tsx, packages/text-input/src/TextInput.test.tsx, packages/text-input/src/TextInput.tsx, packages/text-input/src/__snapshots__/TextInput.test.tsx.snap, packages/textarea/src/Textarea.test.tsx, packages/textarea/src/__snapshots__/Textarea.test.tsx.snap, plop-templates/component/src/{{componentName}}.test.tsx.hbs
- Add tests to `field`, `textinput` and `textarea`
- Restructure some tests to get accurate HTML validation tests
- DatePicker: Set a default value of the `type` prop to `text`
- TextInput: Set a default value of the `type` prop to `text`
=> Add more tests for form fields

.changeset/selfish-hornets-scream.md, packages/file-upload/package.json, packages/file-upload/src/FileUpload.tsx
Merge consumer ref with dropzone ref before forwarding to input and use `visuallyHiddenStyles` instead of `display: none`
=> file-upload: Merge refs and use visuallyHiddenStyles

.changeset/rude-poems-confess.md, packages/accordion/src/Accordion.test.tsx, packages/accordion/src/__snapshots__/Accordion.test.tsx.snap, packages/core/package.json, packages/core/src/CoreProvider.tsx, packages/core/src/utils/index.ts, packages/core/src/utils/useId.ts, packages/date-picker/src/DatePicker.test.tsx, packages/date-picker/src/DateRangePicker.test.tsx, packages/date-picker/src/__snapshots__/DatePicker.test.tsx.snap, packages/date-picker/src/__snapshots__/DateRangePicker.test.tsx.snap, packages/field/src/Field.test.tsx, packages/field/src/__snapshots__/Field.test.tsx.snap, packages/progress-indicator/src/ProgressIndicator.test.tsx, packages/progress-indicator/src/__snapshots__/ProgressIndicator.test.tsx.snap, packages/search-box/src/Search.test.tsx, packages/search-box/src/__snapshots__/Search.test.tsx.snap, packages/side-nav/src/SideNav.test.tsx, packages/side-nav/src/__snapshots__/SideNav.test.tsx.snap, packages/text-input/src/TextInput.test.tsx, packages/text-input/src/__snapshots__/TextInput.test.tsx.snap, packages/textarea/src/Textarea.test.tsx, packages/textarea/src/__snapshots__/Textarea.test.tsx.snap, yarn.lock
Rollback PR #749 but....
- Export `useId` from Core
- Use the latest version of `@reach/auto-id` which uses reacts internal `useId` function if available.
=> Rollback "Replace useId from @reach/auto-id with @react-aria/utils"

.changeset/blue-suns-live.md, .changeset/rich-meals-applaud.md, packages/box/src/styles.ts, packages/table/src/Table.tsx, packages/table/src/TableBody.tsx, packages/table/src/TableCaption.tsx, packages/table/src/TableHead.tsx
Recently realised that display='table' was missing as an option in the box styles. I've added it here along with grid and inline grid, and also updated usage of display properties in some of our components
=> Box: Add display: table to Box styles. Add to missing components

.changeset/violet-worms-itch.md, packages/button/src/Button.test.tsx, packages/button/src/Button.tsx, packages/button/src/__snapshots__/Button.test.tsx.snap
- Removed `loading` and `loadingLabel` prop from `ButtonLink`. If you are using these props, you should be using `Button` instead.
- Added more tests
=> button: Removed loading props from `ButtonLink`

docs/components/Code.tsx
- Ensure when the use presses `Esc`, we hide the editor and focus the "Hide live code" button
- Announce to screen reader users that the escape button can be pressed
- Improve focus styles
=> docs: improve a11y of live code editor

docs/components/Code.tsx, docs/components/mdxComponents.tsx, docs/lib/mdxUtils.ts, docs/package.json, packages/a11y/docs/overview.mdx, yarn.lock
- Upgraded `next-mdx-remote` from version 3 to 4. This fixes the issue with the mailto links, but meant we had to tweak how the `pre/code` mdx tags were working.
- Replaced `@untitled-docs/live-code/rehype` for `remark-mdx-code-meta` as untitled docs wasn't passing in the `live` attribute. Also this is the plugin MDX recommend on [their website](https://mdxjs.com/guides/syntax-highlighting/#syntax-highlighting-with-the-meta-field).
=> docs: Fix package name/versions becoming mailto links

guides/figma.mdx
MDX version 2 (bumped in #812 ) caused this issue. MDX was wrapping "Go to figma" in a `p` tag 🤔.
| <img width="349" alt="Screen Shot 2022-10-27 at 2 09 12 pm" src="https://user-images.githubusercontent.com/6265154/198189625-0aac5a51-c20d-42c0-a56c-6cf6bfa6cc42.png">      | <img width="347" alt="Screen Shot 2022-10-27 at 2 09 01 pm" src="https://user-images.githubusercontent.com/6265154/198189638-59d848f3-967b-49ee-b5e6-1b9e348e4cdb.png">       |
=> docs: Fix broken figma button

packages/date-picker/src/Calendar.test.tsx, packages/date-picker/src/__snapshots__/Calendar.test.tsx.snap
This one is a little embarrassing....
Our snapshot tests were created with values that were in the future....
When the future was the present, the classes in the HTML output changed, and we updated the snapshot
Now that the present is now the past, the classes are different again, which caused the snapshot tests to fail
This update now ensures those values are treated as 'past', so this won't happen again
=> DatePicker: Fix time-based bug in snapshot test

docs/pages/tokens/colour.tsx, guides/custom-theme.mdx
- Added general tips for picking colours to the 'theming' guide
- Renamed 'color' page to 'colour'
- Renamed 'theming' guide page to 'custom-theme'
=> Custom theme guide: Add general tips for picking colours

.changeset/tiny-pigs-worry.md, .storybook/stories/kitchenSink.tsx, packages/badge/docs/overview.mdx, packages/badge/src/IndicatorDot.stories.tsx, packages/badge/src/IndicatorDot.test.tsx, packages/badge/src/IndicatorDot.tsx, packages/badge/src/StatusBadge.tsx, packages/badge/src/__snapshots__/IndicatorDot.test.tsx.snap, packages/badge/src/__snapshots__/StatusBadge.test.tsx.snap
Remove the neutral tone from IndicatorDot as suggested in DAGR-69 Round 2.
Also removed tone as a prop as now only the 'action' tone exists
=> IndicatorDot: Retire neutral tone

.changeset/eighty-cars-knock.md, packages/header/src/Header.stories.tsx, packages/header/src/Header.tsx, packages/header/src/__snapshots__/Header.test.tsx.snap
We recently found a visual bug in Header when composed with SearchBox, which is visible in 'tablet' viewports. In this view, the space isn't used as effectively as it could be. [View in Playroom](https://steelthreads.github.io/agds-next/playroom/index.html#?code=N4Igxg9gJgpiBcIA8AhCAPABFAhgJwGsA%2BAHQDtNMkAJGHWPcyygZwEsAvGAXhJAFsofJswBGOMAQDmeCAFcyUXiFHQAngEEANgBdhFZlohSI3YEgAyxiJgD0RAL4jKACzpQ2ZKcoCi6AA4QeDqYAMoweABubGAw%2BsyYLHKiWp48fAAqLmwsmDmYOAWJyan8MMUpafFi9FIwFjiiMFrKTTo41ZR4bFIuOgDCEGQ6MMNmzsxI4fhgLmhYQ6HJ-Gw6ZpBkLBBaMAB0RlIOpAYJlFN0eLPzAJJk-nIhWo3NytOXLpg62bkA7jCi7BGfDsx1OkzeVwwKAeOiGeQ2AHkyFo1GZgJh0Cx4J88HIYAAaTCCbEAMxwWhY5QcRwmYIhLlpk1s9Pm0J0sLIoNOSGZF0h6C5lCcBns5BESAAsjhPAA5HCRPIjfgsMwAbXRTyaWmxfFoWiMfEJLjwMBJOpAAGJgQ4ALoOEHkHnzY5IAAKODqg2GoxCOBVfH40rIfC5btklMFVBcAEYiO66pg3PRPF …
=> header: Adjust responsive behaviour

docs/.env.development, docs/.env.production, docs/components/Code.tsx, docs/components/PkgLayout.tsx, docs/components/SiteFooter.tsx
Improves the experience of working with Storybook and Playroom locally by using environment variables to link to URLs based on whether the docs site is running in a development or production environment.
In seperate processes run:
```sh
yarn docs:dev
yarn playroom:build
yarn storybook:build
```
```sh
yarn docs:build && yarn playroom:build && yarn storybook:build && cd docs && yarn next start
```
=> docs: Add env vars for Playroom and Storybook links

.changeset/nine-poets-chew.md, packages/summary-list/src/SummaryList.tsx, packages/summary-list/src/__snapshots__/SummaryList.test.tsx.snap
Prevented flex shrinking of `SummaryListItemTerm` to ensure the width of this element is always the same.
| <img width="837" alt="Screen Shot 2022-11-15 at 1 24 49 pm" src="https://user-images.githubusercontent.com/6265154/201819824-d87edad4-606c-4e6f-9bb9-5906cfb668b2.png"> | <img width="838" alt="Screen Shot 2022-11-15 at 1 24 33 pm" src="https://user-images.githubusercontent.com/6265154/201819818-05b2cc2a-4201-4c2e-9092-0b991ba7a608.png"> |
=> summary-list: Prevent term from shrinking

.changeset/wild-goats-marry.md, packages/page-alert/src/PageAlert.stories.tsx, packages/page-alert/src/__snapshots__/PageAlert.test.tsx.snap, packages/prose/src/Prose.tsx
Requested in a comment in [Product Backlog Item 277300](https://dev.azure.com.mcas.ms/agriculturegovau/Digital%20Services/_workitems/edit/277300?McasTsid=26110)
Subtle improvement to increase spacing before elements with the proseBlockClassname, from 1.5rem to 2rem.
Before: 
After: 
Also added a Storybook example for a PageAlert with Prose. While this is not related, I was prompted to add it by the regenerated snapshot.
=> Prose: Increase spacing before block elements

.changeset/big-lemons-bow.md, .changeset/spotty-teachers-matter.md, docs/components/PageLayout.tsx, docs/pages/404.tsx, docs/pages/index.tsx, example-form/components/AppLayout.tsx, example-form/pages/not-found.tsx, example-site/components/AppLayout.tsx, example-site/pages/404.tsx, packages/content/src/BaseContent.tsx, packages/main-nav/src/NavContainer.tsx, packages/main-nav/src/__snapshots__/MainNav.test.tsx.snap, packages/skip-link/docs/overview.mdx, packages/skip-link/src/SkipLinks.stories.tsx
Alternative to #835 
This PR improves the accessibility of our skip links across all of our websites, by adding `tabIndex={-1}` to all elements which are targets of skip links. No focus ring is shown which keeps the visual behaviour the same as what we currently have.
=> DAGR-111: Add tabIndex to skip links targets

example-form/components/FormRegisterPetContext.tsx, example-form/components/FormRegisterPetDetails/FormRegisterPetDetails.tsx, example-form/components/FormRegisterPetPersonalDetails/FormRegisterPetPersonalDetails.tsx, example-form/pages/services/registrations/pet/index.tsx
For every list item in the register your pet "task list" we use the combination of an anchor tag + an `onClick` event to set some state of the "active task". In some instances, the state update causes a small re-render of the current page BEFORE navigation to the next page. 
This is causing an issue in NVDA where the focused element doesn't get moved to the body, as expected when performing a route change.
To fix this, we have removed the `onClick` from each task list item to make them just regular anchor tags. The functionality that was in the `onClick` event has now been moved into a `useEffect` on each task page.
=> example-form: Fix bug in NVDA by moving call to `startTask`

.changeset/brave-days-sin.md, packages/accordion/src/__snapshots__/Accordion.test.tsx.snap, packages/call-to-action/src/__snapshots__/CallToAction.test.tsx.snap, packages/card/src/__snapshots__/Card.test.tsx.snap, packages/details/src/__snapshots__/Details.test.tsx.snap, packages/icon/src/Icon.tsx, packages/progress-indicator/src/__snapshots__/ProgressIndicator.test.tsx.snap, packages/select/src/__snapshots__/Select.test.tsx.snap, packages/side-nav/src/__snapshots__/SideNav.test.tsx.snap
We noticed that small icons that portray a link (bold) aren't prominent enough.
In this PR, Icons with small sizes and bold weights will use 4px stroke weight instead of 3px
Examples below are before vs after
=> icon: Use 4px stroke width for small bold icons

docs/lib/mdx/packages.ts, docs/pages/components/index.tsx, packages/switch/docs/overview.mdx
Components are grouped
Components are a flat list
=> docs: Add component search

.changeset/soft-berries-taste.md, .changeset/sour-emus-study.md, docs/components/TokenCharts.tsx, docs/components/TokenLayout.tsx, docs/pages/tokens/index.tsx, docs/pages/tokens/max-width.tsx, packages/combobox/src/Combobox.tsx, packages/core/src/tokens.ts, packages/date-picker/src/DatePickerInput.tsx, packages/date-picker/src/__snapshots__/DatePicker.test.tsx.snap, packages/date-picker/src/__snapshots__/DateRangePicker.test.tsx.snap, packages/field/src/fieldMaxWidth.tsx, packages/field/src/index.tsx, packages/fieldset/src/__snapshots__/Fieldset.test.tsx.snap, packages/search-box/src/__snapshots__/Search.test.tsx.snap, packages/search-input/src/SearchInput.tsx, packages/search-input/src/SearchInputContainer.tsx, packages/search-input/src/__snapshots__/SearchInput.test.tsx.snap, packages/select/docs/overview.mdx, packages/select/src/Select.stories.tsx, packages/select/src/Select.tsx, packages/select/src/__snapshots__/Select.test.tsx.snap, packages/text-input/src/TextInput.tsx, packages/text-input/src/__snapshots__/TextInput.test.tsx.snap, packages/textarea/docs/overview.mdx, packages/textarea/src/Textarea.stories.tsx, packages/textarea/src/Textarea.tsx, packages/textarea/src/__snapshots__/Textarea.test.tsx.snap
This PR adjusts the maximum widths of our form fields. 
The values we initially used were taken from GOLD and are a bit odd. For example the `xs` form field was `4.3rem (68.8px)` wide which can be. Also if no max width was supplied `12.8125rem` was used.  Now, the default max width is `md`.
```diff
- xs: '4.3rem',
+ xs: '5rem',
- sm: '6.3rem',
+ sm: '8rem',
- md: '10rem',
+ md: '13rem',
- lg: '18rem',
+ lg: '18rem',
- xl: '24rem',
+ xl: '24rem',
```
| <img width="815" alt="Screen Shot 2022-12-01 at 2 55 38 pm" src="https://user-images.githubusercontent.com/6265154/204968858-ffa3536f-eca0-4c36-be02-bd382ac98354.png"> | <img width="817" alt="Screen Shot 2022-12-01 at 2 55 04 pm" …
=> field: Adjust max widths

packages/task-list/package.json, packages/task-list/src/TaskList.test.tsx, packages/task-list/src/TaskListItem.tsx, packages/task-list/src/__snapshots__/TaskList.test.tsx.snap
Use visuallyHidden to add a full stop after the spans in TaskListItem, rather than an aria-label on the span
=> task-list: Use visuallyHidden to add fullstop

.changeset/gorgeous-rules-cry.md, packages/search-box/src/SearchBoxInput.tsx, packages/search-box/src/__snapshots__/Search.test.tsx.snap
Removed browser autocomplete from the search box input component.
=> search-box: remove autocomplete

.storybook/preview.tsx
Fixes the following warning from storybook
```
715.manager.bundle.js:10292 `showName` is deprecated as `name` will stop having dual purposes in the future. Please specify a `title` in `globalTypes` instead.
```
=> docs: fix storybook global types

docs/content/updates/2022-01-07.mdx, docs/content/updates/2022-01-24.mdx, docs/content/updates/2022-02-08.mdx, docs/content/updates/2022-02-23.mdx, docs/content/updates/2022-03-02.mdx, docs/content/updates/2022-03-03.mdx, docs/content/updates/2022-03-16.mdx, docs/content/updates/2022-03-23.mdx, docs/content/updates/2022-04-01.mdx, docs/content/updates/2022-04-28.mdx, docs/content/updates/2022-05-16.mdx, docs/content/updates/2022-05-30.mdx, docs/content/updates/2022-06-15.mdx, docs/content/updates/2022-06-28.mdx, docs/content/updates/2022-07-27.mdx
Removed the first `/` from some links that start with `https://`. This was a mistake which probably happened when we moved domains and updated some content with find & replace.
```diff
- /https://design-system.agriculture.gov.au/...
+ https://design-system.agriculture.gov.au/...
```
=> docs: fix broken links

packages/date-picker/src/Calendar.test.tsx
These tests were causing failures as the year range in the calendar component is dynamically generated. To fix this, we have set an explicit date range using a fixed date.
Note: Snapshots do not need to be generated again as the tests update yield the same output.
=> date-picker: Fix calendar tests

yarn.lock
Currently when you are running tests you see the following warning:
```
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
```
After running this command, our dependency on `caniuse-lite` has been updated which results in the following target browser changes:
```diff
- and_chr 101
+ and_chr 108
- and_ff 100
+ and_ff 107
- and_qq 10.4
+ and_qq 13.1
- and_uc 12.12
+ and_uc 13.4
- android 101
+ android 108
- baidu 7.12
+ baidu 13.18
- chrome 101
- chrome 100
- chrome 99
+ chrome 108
+ chrome 107
+ chrome 106
- edge 101
- edge 100
- edge 99
+ edge 108
+ edge 107
- firefox 101
- firefox 100
- firefox 99
- firefox 98
+ firefox 107
+ firefox 106
- ios_saf 15.4 …
```
=> Upgraded browserslist

.storybook/stories/CardsWithRemoteData.tsx, .storybook/stories/KitchenSink.tsx, .storybook/stories/TableWithRemoteData.tsx, packages/react/src/ag-branding/Logo.stories.tsx, packages/react/src/ag-branding/docs/overview.mdx, packages/react/src/call-to-action/docs/overview.mdx, packages/react/src/control-input/docs/overview.mdx, packages/react/src/date-picker/docs/overview.mdx, packages/react/src/direction-link/docs/overview.mdx, packages/react/src/file-upload/docs/overview.mdx, packages/react/src/form-stack/docs/overview.mdx, packages/react/src/global-alert/docs/overview.mdx, packages/react/src/hero-banner/docs/overview.mdx, packages/react/src/inpage-nav/docs/overview.mdx, packages/react/src/link-list/docs/overview.mdx, packages/react/src/main-nav/docs/overview.mdx, packages/react/src/page-alert/PageAlert.stories.tsx, packages/react/src/page-alert/docs/overview.mdx, packages/react/src/progress-indicator/docs/overview.mdx, packages/react/src/search-box/docs/overview.mdx, packages/react/src/search-input/docs/overview.mdx, packages/react/src/side-nav/docs/overview.mdx, packages/react/src/skip-link/docs/overview.mdx, packages/react/src/sub-nav/docs/overview.mdx, packages/react/src/summary-list/docs/overview.mdx, packages/react/src/task-list/docs/overview.mdx, packages/react/src/text-input/docs/overview.mdx, packages/react/src/text-link/docs/overview.mdx
This PR updates our component names on the documentation site from Title case (e.g. Page Alert) to sentence case (e.g. Page alert). This fixes an inconsistency in naming between our figma Gallery and documentation site.
=> docs: Update component names to sentence case

example-site/components/SiteFooter.tsx
Adds the privacy link to the example-site footer. This is a follow up to #919.
=> example-site: add privacy link to footer

.changeset/dry-rules-bathe.md, packages/react/src/combobox/Combobox.tsx, packages/react/src/combobox/ComboboxAsync.tsx
fixed a bug where the input element became non-interactive after blur
=> combobox: fix bugs when input is blurred

packages/react/src/field/Field.test.tsx, packages/react/src/field/__snapshots__/Field.test.tsx.snap
This PR improves the test coverage of the `Field` component. Improvements include:
- Checking that the a11y props are provided correctly when the field is both valid and invalid 
- Removing default props to better replicate the out of the box experience with the component
- Removing a bit of duplicate code
=> field: Improve test coverage

.changeset/blue-masks-mix.md, packages/react/src/combobox/ComboboxAsync.tsx
Fixed bug in `ComboboxAsync` where options would be loaded on initial render incorrectly.
=> combobox: fix issue with async tests

.changeset/cold-baboons-add.md, packages/react/src/card/Card.tsx
Our `Card` component uses the technique from https://inclusive-components.design/cards/#theredundantclickevent for handling links. This PR fixes a bug with this technique where command clicking a link can cause the event to trigger twice.
To replicate the current issue:
1. Go to the home page
2. In the list of cards, click the text element that says 'Foundations' while holding the command key
3. The link should open in a new tab (which is expected), but the current tab should also change to the updated to the new url which is incorrect.
=> card: prevent link event from firing twice

packages/react/src/search-box/SearchBoxInput.tsx, packages/react/src/search-box/__snapshots__/Search.test.tsx.snap
In #925, we changed the background colours of all of our inputs to 'body' from transparent. I mistakingly applied this change to SearchBox, which is supposed to have a white background.
No need for a changeset
=> Searchbox: Revert styling change

packages/react/src/file-input/docs/overview.mdx
This PR adds a link from the `FileInput` component to the figma gallery.
=> file-input: add figma gallery link

.changeset/odd-boxes-complain.md, packages/react/src/date-picker/DatePicker.test.tsx, packages/react/src/date-picker/DatePicker.tsx, packages/react/src/date-picker/DateRangePicker.test.tsx, packages/react/src/date-picker/DateRangePicker.tsx
This PR fixes a bug in our `DatePicker` and `DateRangePicker` components. This bug is pretty visible in the following stories:
- https://design-system.agriculture.gov.au/storybook/index.html?path=/story/forms-datepicker-datepicker--controlled-example
- https://design-system.agriculture.gov.au/storybook/index.html?path=/story/forms-datepicker-daterangepicker--controlled-example
In both of these stories, if you click 'Set pre-defined range' followed by the 'Clear' button, you'll notice that the text inputs do not update as expected.
Using our deploy previews, you can see this issue has been fixed:
- https://design-system.agriculture.gov.au/pr-preview/pr-946/storybook/index.html?path=/story/forms-datepicker-datepicker--controlled-example
- …
=> date-picker: fix inputs not updating when value changes

.changeset/tasty-oranges-fold.md, packages/react/src/autocomplete/__snapshots__/Autocomplete.test.tsx.snap, packages/react/src/combobox/ComboboxBase/ComboboxBase.tsx, packages/react/src/combobox/__snapshots__/Combobox.test.tsx.snap, packages/react/src/combobox/__snapshots__/ComboboxAsync.test.tsx.snap
This PR fixes an inconsistency in hint text max widths for our form components.
**Before**
Notice in the `Combobox` component how the hint text has the same max-width as the input element. This behaviour is inconsistent with other form components. [See playroom link](https://design-system.agriculture.gov.au/playroom/index.html#?code=N4Igxg9gJgpiBcIA8AhCAPABABwIZSgEsA7AcwF5gAmAXwD4AdYzTJAMQgCcBbAZQBdcYANaNmLVm0IAbGAEli2AK78mEidNwAjGNPIMQAUXS5u2WQbXrMACxL99IADJcY3TIWwBnJe6gRpLkwvQn5MUxh%2BABpMSGIvGDB%2BSKVOcKJsQi8wElJMXVCAOkwABU4IEkwuHPzyrxiANxgvfkItJWlffNJI-Kwm6UaAlTwwuKJuGGJ%2BLu5CQstxFgB6MSsWJAAVGHRBThhcdY1tXUdjU3MYRetbe0cXffdPHz8AoJCwiOjYiHjE5JmaXwniyOTI%2BWkRVK5Uq1UItQg9UwTRabQ6XRgPTCO2RuiGnX4ox%2BxAmUxm7jmCxAR1WRyQvF0-yOLE0Oj0BnOZgs1KWEjs03urie3i6-kCaQ%2B4Um3ziCSSKSBGVBuQhULKFWYcIRSJRr …
=> autocomplete, combobox: fix hint max width bug

.changeset/calm-cycles-itch.md, packages/react/src/card/Card.tsx, packages/react/src/card/CardLink.tsx, packages/react/src/card/__snapshots__/Card.test.tsx.snap
This PR reverts #689.
The reason for this is that we found an issue in the [redundant click event pattern](https://inclusive-components.design/cards/#theredundantclickevent). If the user is holding down the `meta` key, links will sometimes not open in a new tab - depending on where the user clicks within the `Card`. We have been in touch with Heydon Pickering to alert them of this bug.
We believe that the pseudo-content trick is a much more accessible solution for AgDS. While it does not allow the user to select text, this technique requires no javascript and users can open links in a new tabs.
=> card: revert back to pseudo-content trick

docs/content/guides/contribution.mdx, docs/content/guides/custom-theme.mdx, docs/content/guides/figma.mdx, docs/content/guides/forms.mdx, docs/content/guides/getting-started.mdx, docs/content/guides/responsive-props.mdx, docs/lib/mdx/guides.ts, docs/pages/guides/[slug].tsx, docs/pages/guides/index.tsx
- Remove side nav from guide page, to add focus on the content
- Shorten paragraphs under cards in the guide list page, via a new 'overview' field in Markdown
- Rename 'description' Markdown field to 'opener' to reflect its purpose.
=> docs: guides design improvements

example-form/components/FormRegisterPetDetails/FormRegisterPetDetails.tsx, example-form/components/FormRegisterPetDetails/FormRegisterPetDetailsStep4.tsx, example-form/components/FormRegisterPetPersonalDetails/FormRegisterPetPersonalDetails.tsx, example-form/components/FormRegisterPetPersonalDetails/FormRegisterPetPersonalDetailsStep0.tsx, example-form/components/FormRegisterPetPersonalDetails/FormRegisterPetPersonalDetailsStep3.tsx
This pull request fixes a small issue our the [example-form](https://design-system.agriculture.gov.au/example-form/) application. 
If you are on step 1 and move to another step, the progress indicator for step 1 will be shown as `blocked` when it should be `todo`.
I've also made a couple of small improvements while I was here, by fixing a react hydrating error that first popped up when we introduced the 'side flow' in step 1.
=> example-form: fixed incorrect step status

.changeset/giant-emus-build.md, docs/pages/foundations/tokens/max-width.tsx, packages/react/src/core/tokens.ts, packages/react/src/modal/Modal.tsx, packages/react/src/modal/ModalDialog.tsx, packages/react/src/modal/ModalPanel.tsx, packages/react/src/modal/__snapshots__/Modal.test.tsx.snap
Added new `modalPanel` max-width token which has a value of 45rem. This value has been calculated by taking the `bodyText` max-width and adding 3rem which is the horizontal padding inside of the modal.
- Updated max-width of modal dialog
- Renamed `ModalPanel` to `ModalDialog` (internal use only)
=> Add new `modalDialog` max-width token

docs/components/TemplateLayout.tsx
We accidentally removed the "View template preview" call to action link from the templates page. This PR adds that link back in.
=> docs: Add template preview link

docs/components/TokenLayout.tsx
This PR fixes  a small issue in our `TokenLayout` component.
```
Warning: React does not recognize the `pageTitle` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `pagetitle` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```
This issue was happening as we were spreading invalid anchor attributes into each item in the `SideNav`
=> docs: fix sidebar warning in `TokenLayout`

.storybook/preview.tsx, .storybook/stories/CardsWithRemoteData.tsx, .storybook/stories/KitchenSink.tsx, .storybook/stories/TableWithRemoteData.tsx, example-site/components/templates/Category.stories.tsx, example-site/components/templates/Content.stories.tsx, example-site/components/templates/Home.stories.tsx, example-site/components/templates/MultiPageForm.stories.tsx, example-site/components/templates/NotFound.stories.tsx, example-site/components/templates/SignInForm.stories.tsx, example-site/components/templates/SinglePageForm.stories.tsx, example-site/components/templates/Subcategory.stories.tsx
In storybook, individual stories can have one of the following [layout options](https://storybook.js.org/docs/react/configure/story-layout):
- `centered`: center the component horizontally and vertically in the Canvas
- `fullscreen`: allow the component to expand to the full width and height of the Canvas
- `padded`: (default) Add extra padding around the component
We currently use `fullscreen` for everything but add our own padding. I believe this is incorrect as we now have stories where we don't want padding applied, for example in the kitchen sink or in the template stories.
In this PR, I have defaulted back to the `padded` layout param and explicitly added `fullscreen` to the kitchen sink and template stories.
=> storybook: Remove padding from fullscreen layouts

.github/workflows/deploy-docs.yml, .github/workflows/preview.yml
This PR ensures all of our Github actions always use Node 16. Currently, only 2 of 4 actions explicitly require Node 16.
This fixes an issue first noticed in PR #974
=> Setup node in github actions

packages/react/src/control-input/docs/overview.mdx, packages/react/src/field/docs/overview.mdx, packages/react/src/file-input/docs/overview.mdx, packages/react/src/search-input/docs/overview.mdx, packages/react/src/select/docs/overview.mdx, packages/react/src/text-input/docs/overview.mdx, packages/react/src/textarea/docs/overview.mdx
- Added a section about hint text to form component documentation pages
- Where applicable, moved the `block` prop documentation section to the bottom of the page. This prop isnt very widely used, so having it first on the page doesn't really make sense.
- Improved `ControlInput` documentation while I was there, as it was a bit outdated.
=> docs: Add hint text to form components

.changeset/nervous-days-provide.md, packages/react/src/button/styles.tsx, packages/react/src/date-picker/__snapshots__/DatePicker.test.tsx.snap, packages/react/src/date-picker/__snapshots__/DateRangePicker.test.tsx.snap, packages/react/src/file-input/__snapshots__/FileInput.test.tsx.snap, packages/react/src/file-upload/__snapshots__/FileUpload.test.tsx.snap
Replaced transparent background in the `secondary` variant from `transparent` with body background colour. This update has a flow-on effect for `FileInput`, `FileUpload` and `DatePicker`.
The reason for this change is that our form input component (`Autocomplete ,`TextInput`, `Select` etc) all have a `body` background colour set, so this change brings more consistency to our form components.
=> button: add body background to secondary variant

.changeset/clever-zoos-wash.md, packages/react/src/file-input/FileInput.tsx, packages/react/src/file-input/__snapshots__/FileInput.test.tsx.snap
Updated the "Upload file" button size from `sm` to `md` as per design review session.
=> file-input: Update button size

docs/package.json, package.json, yarn.lock
🧹 Housekeeping 🧹 
Removing some unused dependencies in the repo.
- Removed `parse-numeric-range`. This was included in the initial creation of this file so I believe this was a copy/paste error.
- Removed `ts-jest`. This is not needed as we use babel to transform our typescript files for jest.
=> Remove unused dependencies

.changeset/pink-cats-kneel.md, packages/react/src/field/Field.test.tsx, packages/react/src/field/FieldContainer.tsx, packages/react/src/field/FieldHint.tsx, packages/react/src/field/FieldLabel.tsx, packages/react/src/field/FieldMessage.tsx, packages/react/src/field/useScrollToField.ts
This PR has come from the work that I have been doing over in PR #997. We need to be able to able to add a `className` to the `FieldLabel` element so I have done this as as a seperate PR. While I was touching these files, I made a few minor improvements which have included:
- Fixed typos in hook `useScrollToField`
- Exported component types and added prop comments
- Improved tests
=> field: Added `className` prop to `FieldLabel`

.changeset/grumpy-news-happen.md, packages/react/package.json, packages/react/src/core/utils/useId.ts, packages/react/src/core/utils/useId/canUseDom.ts, packages/react/src/core/utils/useId/index.ts, packages/react/src/core/utils/useId/useId.test.tsx, packages/react/src/core/utils/useId/useId.ts, packages/react/src/core/utils/useId/useIsomorphicLayoutEffect.ts, yarn.lock
We use `@reach/auto-id` to autogenerate IDs to facilitate WAI-ARIA and server rendering. We can not just use `useId` from React as we need to provide support for React 16, 17 and 18.
Reach UI is no longer being maintained and does not fully support React 18. See https://github.com/reach/reach-ui/issues/972 for more details.
In this PR, I have removed the dependency to Reach UI and the logic from `@reach/auto-id` has been forked and copied into the repo.
=> Remove dependency to `reach-ui`

.github/pull_request_template.md, .storybook/stories/KitchenSink.tsx
- Use the page template component which is defined in the .storybook directory
- Make Storybook controls for the background colours
- Have a single 'default' story for Kitchen sink (no more child stories)
=> Kitchen sink: Use page-template. Add background control

.changeset/sixty-pants-flow.md, packages/react/src/date-picker/DatePicker.tsx, packages/react/src/date-picker/DatePickerInput.tsx
- Removed unused prop `placeholder` 
- Removed options `xs` and `sm` from `maxWidth` prop. These widths were too small to be used in this component.
=> date-picker: Removed `placeholder` prop, updated `maxWidth` options

.changeset/poor-bees-obey.md, packages/react/src/summary-list/SummaryList.tsx, packages/react/src/summary-list/__snapshots__/SummaryList.test.tsx.snap
Fixed a text colour bug when this component was placed inside dark palette. 
This was done by adding an explicit colour to `SummaryListItemTerm` and `SummaryListItemDescription`.
| Before | After | 
|--------|-------|
| <img width="827" alt="Screen Shot 2023-03-16 at 10 48 34 am" src="https://user-images.githubusercontent.com/6265154/225481726-53b9a5ef-5591-4ddc-9161-31fa6ad94cbe.png">       |  <img width="840" alt="Screen Shot 2023-03-16 at 10 48 23 am" src="https://user-images.githubusercontent.com/6265154/225481650-3bd1822a-6075-4f34-856f-b4d90ebc1137.png">      |
=> summary-list: Fix text colour bug in dark palette

.changeset/lovely-gorillas-care.md, packages/react/src/box/styles.ts, packages/react/src/core/responsive.ts
Updated the `palette` prop to accept responsive value. [View changes in this Playroom example](https://design-system.agriculture.gov.au/pr-preview/pr-1021/playroom/index.html#?code=N4Igxg9gJgpiBcIA8AhCAPAOgOwAS4AcBDAGxgBdyYBeYAbUxCiICcBrRgGl0ZIEsA5gAtyXHk1YcQAXQC%2BOfACMiYNgJYQArtijVGi6AE9GC3JBIQWekFXSiQp4lCh9sA2gEZ52AHymAEjAkFrgA6pYkUDhIAPRo6H7YILJAA).
- [] Document the component for the website (`docs/overview.mdx` and `docs/code.mdx` at a minimum)
- [] Create stories for Storybook
- [] Add necessary unit tests (HTML validation, snapshots etc)
- [] Manually test component in various modern browsers
- [] Manually test component using a screen reader
=> box: Updated `palette` prop to accept responsive values

docs/content/templates/single-page-form/index.mdx
=> docs: Add guidance about focusing the error summary and success messaging

packages/react/src/control-input/docs/overview.mdx
Our control-group examples conflict with our guidance, which says to not use horizontal lists. This is a bit of a band-aid fix while we contemplate removing the block prop and defaulting to vertical lists
=> control-group: Show vertical examples to follow guidance

packages/react/src/field/docs/overview.mdx
In the following screenshot, the heading `useScrollToField` is the wrong heading type (level 2 instead of level 3). Also, as it's using a `<code />` component the associated heading ID is `object-object` and the font size is incorrect.
In the following screenshot, the heading "useScrollToField" contains the backticks.
[Preview changes here](https://design-system.agriculture.gov.au/pr-preview/pr-1037/components/field)
=> docs: Update `Field` documentation

.changeset/heavy-apes-tickle.md, packages/react/src/field/docs/overview.mdx, packages/react/src/field/useScrollToField.ts
Extended the function returned from from `useScrollToField` to accept either a mouse event or an ID of a form field element. This change makes it easier for consumers to scroll and focus a form field on the same page in situations such as when a form first renders.
I've added an example of this use case to our documentation site, but we currently do not have any living examples of where this hook would be useful. It would have useful to have have had this in PR #980.
[Preview changes in single page form](https://design-system.agriculture.gov.au/pr-preview/pr-1038/example-site/category/subcategory/single-page-form).
=> field: Update `useScrollToField`

.changeset/shy-bottles-float.md, packages/react/src/autocomplete/__snapshots__/Autocomplete.test.tsx.snap, packages/react/src/combobox/__snapshots__/Combobox.test.tsx.snap, packages/react/src/combobox/__snapshots__/ComboboxAsync.test.tsx.snap, packages/react/src/control-input/__snapshots__/ControlGroup.test.tsx.snap, packages/react/src/date-picker/DateRangePicker.test.tsx, packages/react/src/date-picker/__snapshots__/DatePicker.test.tsx.snap, packages/react/src/date-picker/__snapshots__/DateRangePicker.test.tsx.snap, packages/react/src/field/Field.test.tsx, packages/react/src/field/FieldLabel.tsx, packages/react/src/field/__snapshots__/Field.test.tsx.snap, packages/react/src/fieldset/__snapshots__/Fieldset.test.tsx.snap, packages/react/src/file-input/__snapshots__/FileInput.test.tsx.snap, packages/react/src/file-upload/__snapshots__/FileUpload.test.tsx.snap, packages/react/src/search-input/__snapshots__/SearchInput.test.tsx.snap, packages/react/src/select/__snapshots__/Select.test.tsx.snap, packages/react/src/text-input/__snapshots__/TextInput.test.tsx.snap, packages/react/src/textarea/__snapshots__/Textarea.test.tsx.snap
This PR updates the wrapping behaviour of the `FieldLabel` component. Currently we use flexbox for our label component and the space between the primary and secondary label is added via a flex gap. But this has a few issues such as:
1. Labels that span multiple lines do not behave nicely
2. The text content of the node does not contain a space 
I have removed flexbox from the `FieldLabel` component and replaced that flex gap with a space character (`" "`).
[Test in Playroom](https://design-system.agriculture.gov.au/pr-preview/pr-1041/playroom/index.html#?code=N4Igxg9gJgpiBcIA8AxCAnAtgZQC4EMwBrAPgB0A7AAiqQBUYAPXASQoAcBXXKgG3wBGMXgF4yIOgAsAlgGcqcqviroY%2BXrwCefCBQDmVAO4ywkqrnTSY83BCqz2%2Bapk69c09rxh9pFa%2BbtYTF1ZC3xcb0N0fHZ2XwMhSXwAN2kITnRxKgB6cmpaABFwmAAFaWIYTPyafiFRcWxhGDAeZShio2lcM2Va4XMk …
=> field: Update wrapping behaviour of label

package.json, yarn.lock
This dependency  upgrade will contribute to the to the resolution of [security alert CVE-2022-46175](https://github.com/steelthreads/agds-next/security/dependabot/41).
=> Upgrade dependency `babel-loader`

.changeset/ninety-crabs-sniff.md, packages/react/src/progress-indicator/ProgressIndicator.stories.tsx, packages/react/src/progress-indicator/ProgressIndicatorItem.tsx, packages/react/src/progress-indicator/docs/overview.mdx
Added new status `started` which can be used to indicate that the step has been partially completed but is not active or selected.
[View preview here](https://design-system.agriculture.gov.au/pr-preview/pr-1068/components/progress-indicator)
=> progress-indicator: Add new status `started` status

.eslintrc.js, docs/next.config.js, docs/scripts/generateComponentProps.js, docs/scripts/generateGuideImages.js, docs/scripts/generateTemplateImages.js, example-form/next.config.js, example-site/next.config.js
Updated our ESLint config to disable the `typescript-eslint/no-var-requires` rule in our plain Javascript files. This change means we can stop manually disabling this rule in every JS file.
=> Update eslintconfig for JS scripts

.changeset/chilly-fireants-move.md, packages/react/src/main-nav/MainNav.tsx, packages/react/src/main-nav/MenuButtons.tsx, packages/react/src/main-nav/__snapshots__/MainNav.test.tsx.snap
Replaced custom inline icons with design system icons `MenuIcon` and `CloseIcon`. I noticed these while doing the App shell work.
I believe this happened because this component was one of the first that was built, before the icon library began to take shape. When `MenuIcon` and `CloseIcon` were added - we didn't update this component.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1080/) (ust shrink your browser until you see the main nav mobile version appear)
=> main-nav: Remove custom icons

docs/components/Code.tsx, docs/components/mdxComponents.tsx, docs/lib/img.ts, docs/next.config.js, docs/pages/foundations/tokens/colour.tsx, docs/pages/index.tsx, docs/pages/patterns/[slug]/index.tsx, docs/pages/patterns/index.tsx
We use a Github action for pull requests deploy preview. As the deploy previews get published on a sub-path, we need to prefix the paths of links and images with this sub-path. 
NextJS automatically prefixes links for us but our images do not contain the prefix. This means that at the moment any new images that are added in PR are not available to preview in the PR is merged.
This PR fixes this issue by ensuring local image paths are prefixed with the base path.
=> docs: Add base path to images

docs/components/TokenColorTable.tsx
I think I got these values around the wrong way when I initially developed this page.
This change accurately documents the purpose of the shade and shadeAlt tokens
=> docs: Update mismatched documentation for background tokens

packages/react/src/accordion/AccordionTitle.tsx, packages/react/src/core/tokens.ts, packages/react/src/modal/ModalCover.tsx, packages/react/src/modal/ModalDialog.tsx, packages/react/src/modal/__snapshots__/Modal.test.tsx.snap, packages/react/src/progress-indicator/ProgressIndicatorCollapseButton.tsx, packages/react/src/side-nav/SideNavCollapseButton.tsx, packages/react/src/switch/SwitchTrack.tsx
Follow up to https://github.com/steelthreads/agds-next/pull/1088
This PR updates our `transition.duration` token to be a number which is more consistent with our other tokens. For example, we define `borderRadius` as `4`, not `4px` and we define `fontSize` as `16`, not `16rem`,
This change means we can also use this token in Javascript easily, for example with react-spring:
```
useSpring({ ..., config: { duration: tokens.transition.duration })
```
=> core: Update `transition` token

docs/content/patterns/single-page-form/index.mdx
- Fixed small typo
- Renamed `PageAlert` to `Page alert`
=> docs: fix typo in single page form template

packages/react/src/app-layout/AppLayoutSidebar.tsx, packages/react/src/app-layout/AppLayoutSidebarNav.tsx, packages/react/src/app-layout/__snapshots__/AppLayout.test.tsx.snap
Change on-top of AppLayout PR to propose a change in component usage.
- AppLayoutSidebar now uses 'bodyAlt' background as it should be considered a body area for content
- the active/hover state should use 'shadeAlt' as we use shades to tint content. shadeAlt sits within a bodyAlt area.
=> app-layout: Use `bodyAlt` for AppLayoutSidebar

.changeset/many-knives-confess.md, packages/react/src/core/tokens.ts, packages/react/src/main-nav/MainNav.stories.tsx, packages/react/src/main-nav/MainNavBottomBar.tsx, packages/react/src/main-nav/NavContainer.tsx, packages/react/src/main-nav/__snapshots__/MainNav.test.tsx.snap, packages/react/src/main-nav/utils.ts
Currently we have 4 border tokens: `sm (1px)`, `md (2px)`, `lg (3px)` and `xl (4px)`.
However, in the Main nav component we have a custom border value of 8px. I think this has been fine, but we have re-used this custom border in the App layout header component, so I feel like this is the right time to "tokenise" this new border value.
In the following PR, I have added a new `xxl` border token of `8px` so that it can be used across Main nav and App layout Header.
=> tokens: Add `xxl` border token

packages/react/src/app-layout/AppLayoutHeader.stories.tsx, packages/react/src/app-layout/AppLayoutHeaderBrand.tsx, packages/react/src/app-layout/__snapshots__/AppLayout.test.tsx.snap
Update hover state of our `AppLayoutHeader` component to match `Header`.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1098/storybook/index.html?path=/story/layout-applayout--basic)
=> app-layout: Update  header branding hover state

packages/react/src/app-layout/AppLayoutHeader.stories.tsx, packages/react/src/app-layout/AppLayoutHeaderAccount.tsx, packages/react/src/app-layout/AppLayoutHeaderBrand.tsx, packages/react/src/app-layout/__snapshots__/AppLayout.test.tsx.snap
Follow up to PR #1098  and PR #1059.
- Prevent coat of arms logo from shrinking when title or sub line is really long
- Prevent user account avatar from shrinking when title or sub line is really long
- Added max-width of `16rem` to user account which will wrap long names at a sensible width.
-  Added story to show what a really long name could look like. [Preview here ](https://design-system.agriculture.gov.au/pr-preview/pr-1100/storybook/index.html?path=/story/layout-applayout-applayoutheader--with-long-user-name)
=> app-layout: Fix shrinking/wrapping in `AppLayoutHeader`

packages/react/src/app-layout/AppLayoutHeaderBrand.tsx, packages/react/src/app-layout/__snapshots__/AppLayout.test.tsx.snap
With long subline
With long title and subline
=> app-layout: Add max-width to header title and subline

.storybook/stories/DataFiltering/components/ActiveFilters.tsx, .storybook/stories/DataFiltering/components/DashboardTable.tsx, .storybook/stories/DataFiltering/components/FilterStateSelect.tsx
In the medium table filtering example, the value displayed in the tag has incorrect formatting. Some examples of this incorrect formatting are `Status: notBooked` and `State: act`.
In the following screenshot, you can see the formatting of the tags underneath "Active filters" has been fixed.
=> Improve active filter tag formatting in medium table filtering example

.changeset/metal-rivers-dance.md, packages/react/src/tags/Tags.stories.tsx, packages/react/src/tags/TagsList.tsx, packages/react/src/tags/__snapshots__/Tags.test.tsx.snap
Updated wrapping behaviour the flowing of tags across multiple lines.
In this [this playroom example](https://design-system.agriculture.gov.au/playroom/index.html#?code=N4Igxg9gJgpiBcIA8AVAhgcwM4B0B2ABAQBYxpQCWeGAvMPkUajAB4AuBaWNOIxATLwIAzCHjYB1GBQzE2PEACMIAGyi8AfA0ZF02eNqYB6FKzZbCBAL7aKbGAFtuwANqGCwEgCcYw%2BAV4AYl4AGgIVNEUYFX9eADEICCErEPdPYh8-AJBgkDCIqJjsgCE0L2TUyyJ0zNic0PDI6LrSgC8KtO9fOtz8pqL4xI6qjy6soIaC5pKy4Z0a7uzexsKWtHaQa0r5sZ7J-rqEpM2UzozFibyV6d5S8pPtxgXx%2BqupgZA2uYIAXRs8IwWPIgADuFCgbGIWAQLj%2BQA), you can see how tags currently do not wrap correctly.
Using our deploy preview, you can see the new behaviour in [this playroom example](https://design-system.agriculture.gov.au/pr-preview/pr-1116/playroom/index.html#?code=N4Igxg9gJgpiBcIA8AVAhgcwM4B0B2ABAQBYxpQCWeGAvMPkUajAB4AuBaWNOIxAT …
=> tags: Update wrapping behaviour

.changeset/orange-vans-tap.md, .changeset/sharp-pigs-shave.md, packages/react/src/app-layout/AppLayoutSidebarDialog.tsx, packages/react/src/core/utils/index.ts, packages/react/src/core/utils/useAriaModalPolyfill.ts, packages/react/src/main-nav/NavContainer.tsx, packages/react/src/modal/Modal.tsx
Created new hook `useAriaModalPolyfill` which adds `aria-hidden="true"` to every direct child of the `body` element when a modal is opened. This hook consolidates code that was previously copied/pasted across Modal, App layout and Main nav.
- [View app layout preview in storybook](https://design-system.agriculture.gov.au/pr-preview/pr-1119/storybook/index.html?path=/story/layout-applayout--basic)
- [View modal preview in storybook](https://design-system.agriculture.gov.au/pr-preview/pr-1119/storybook/index.html?path=/story/content-modal--basic)
- [View main nav preview in storybook](https://design-system.agriculture.gov.au/pr-preview/pr-1119/storybook/index.html?path=/story/navigation-mainnav--body)
Adding missing aria dialog tags to mobile version of App layout sidebar. I noticed this …
=> core: Create new hook `useAriaModalPolyfill`

.eslintrc.js, package.json, yarn.lock
We currently do not use this dependency in our eslint config. We do not need this as we write all of our content in MDX.
=> Remove dependency "eslint-plugin-markdown"

.storybook/stories/DataFiltering/components/ActiveFilters.tsx, .storybook/stories/DataFiltering/components/FilterBar.tsx, .storybook/stories/DataFiltering/components/FilterSearchInput.tsx
Updated wrapping behaviour of two elements in the "medium" table filtering example.
| <img width="670" alt="Screenshot 2023-05-17 at 10 33 10 am" src="https://github.com/steelthreads/agds-next/assets/6265154/44ee3bb4-d7cd-48a0-93d6-93c7f657113f"> | <img width="670" alt="Screenshot 2023-05-17 at 10 32 56 am" src="https://github.com/steelthreads/agds-next/assets/6265154/2e4df144-5535-412c-841e-116a6ded8fc8"> | 
| <img width="794" alt="Screenshot 2023-05-17 at 10 35 15 am" src="https://github.com/steelthreads/agds-next/assets/6265154/4959f42b-df47-4669-8191-2679a46b9b96">| <img width="792" alt="Screenshot 2023-05-17 at 10 35 09 am" src="https://github.com/steelthreads/agds-next/assets/6265154/79c1a2ce-b8ea-4a8c-bc66-5b12818faf69"> |
=> Improve mobile experience of table filtering examples

.changeset/honest-ties-develop.md, packages/react/package.json, packages/react/src/combobox/ComboboxAsync.tsx, packages/react/src/combobox/ComboboxAsyncMulti.tsx, packages/react/src/combobox/useDebounceValue.test.ts, packages/react/src/combobox/useDebounceValue.ts
As a general rule we always want to reduce our reliance on 3rd party code where possible. The `use-debounce` package is only being used within the `ComboboxAsync` and `ComboboxAsyncMulti` components.
This library was being used to prevent "thrashing" network requests while a user is typing in a combobox. No library options or functionality were exposed as public API.
- removed the dependency `use-debounce`
- created a replacement hook targeted to our use case `useDebounceValue`
- added unit tests
- updated usage in `ComboboxAsync` and `ComboboxAsyncMulti`
> **Note** This is a less sophisticated method of debounce but is one which I believe is appropriate for this use case.
> Specifically this debounce does not support a "maximum wait time". The component will always wait at least 300ms …
=> combobox: Remove use-debounce dependency

docs/components/Code.tsx, docs/components/mdxComponents.tsx, docs/components/prism-theme.ts, docs/content/guides/responsive-props.mdx, docs/package.json, yarn.lock
In some of our documentation examples, we want to show an example of using a prop or attribute and also show a live preview of the result.
Currently we can show either static code OR a live preview with the code hidden behind an expandable toggle. The main reason this is the case was the that code block had an accessibility issue where by it would become a tab trap.
This PR adds an attribute to the live code block component which will allow us to have the code view open by default when we want that behaviour.
It also updates the underlying libraries for the live editing view which now support a tab mode which resolves the accessibility issue.
The updated behaviour can be seen on the [Responsive Props page in Guides](https://design-system.agriculture.gov.au/pr-preview/pr-1157/guides/respons …
=> docs: Enable showing code by default in live code block

packages/react/src/badge/index.ts
This PR is a follow up up to #1162. 
As well as re-exporting and marking components as deprecated, we should also do this for the component prop type definitions.
No changeset required as PR #1162 contains that.
=> badge: Re-export and deprecate types

.changeset/slimy-drinks-rest.md, docs/components/Code.tsx, docs/components/ConditionalFieldContainer.tsx, docs/components/designSystemComponents.tsx, example-form/components/ConditionalFieldContainer.tsx, example-form/components/FormRegisterPetPersonalDetails/FormRegisterPetPersonalDetailsStep2.tsx, example-site/components/ConditionalFieldContainer.tsx, example-site/components/FormExampleMultiStep/FormExampleMultiStep3.tsx, packages/react/src/control-input/docs/code.mdx, packages/react/src/control-input/index.ts
Follow up to #1148.
In this PR, I have moved the `ConditionalFieldContainer` component from the `control-input` entrypoint into the docs, example site and example form components directory.
It has also been added to the Live code editor context, so it can be used in the "conditionally revealed questions" pattern, which can be previewed here https://design-system.agriculture.gov.au/pr-preview/pr-1165/patterns/conditional-reveal.
The reason for this change is that we are most likely going to split up control-input into several small components. Until that work has been resolved, it doesn't make any sense to be altering that package right now.
=> control-input: Move conditional field container

packages/react/src/pagination/docs/overview.mdx
Storybook link for pagination was broken. Updated to the first pagination story.
=> docs: Fix pagination storybook link

.changeset/shaggy-waves-exercise.md, example-site/components/templates/MultiPageFormSuccess.tsx, example-site/components/templates/SinglePageFormSuccess.tsx, packages/react/src/page-alert/PageAlert.stories.tsx, packages/react/src/page-alert/PageAlert.test.tsx, packages/react/src/page-alert/PageAlert.tsx, packages/react/src/page-alert/PageAlertTitle.tsx, packages/react/src/page-alert/docs/overview.mdx
This PR adds support for placing a PageAlertTitle component in the PageAlert's `title` prop, as opposed to a string. This is to support an upcoming change which will introduce a Dismiss button to PageAlert.
=> page-alert: Add support for React element in title

packages/react/src/flex/Flex.tsx, packages/react/src/stack/Stack.tsx
This PR is a follow up to #1168 
This fixes up a circular dependency issue we have with the `Box`, `Flex` and `Stack` component.
=> box: Fix circular dependency 

.changeset/hip-maps-breathe.md, packages/react/src/date-range-picker/DateRangePicker.tsx, packages/react/src/date-range-picker/__snapshots__/DateRangePicker.test.tsx.snap
Updated container wrapping behaviour to allow the component to be placed in tight areas such as sidebars.
The grey box represents a parent container changing it's width. You can see clearly in this video, that the date range picker doesn't respond well when placed in a tight area.
https://github.com/steelthreads/agds-next/assets/6265154/8fd1b095-360e-4d82-9638-db8c68a9061c
After flex wrapping has been added, the two inputs flow nicely in tight areas.
https://github.com/steelthreads/agds-next/assets/6265154/78dd90ee-c66c-42e9-9422-f51e71b8023e
=>  date-range-picker: Add flex wrapping

docs/content/patterns/selecting-multiple-options/index.mdx, docs/pages/patterns/[slug].tsx
In this PR I have added our table of contents to the "Patterns" section of the docs website. We do this in other parts of the website, but we never added to Patterns section.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1187/patterns/filtering-a-dataset)
=> docs: Add table of contents to patterns

.changeset/two-icons-joke.md, packages/react/src/file-input/FileInput.test.tsx, packages/react/src/file-input/FileInput.tsx, packages/react/src/file-input/__snapshots__/FileInput.test.tsx.snap
Removing the red tint and text colour from the button region of the FileInput component.
=> file-input: Removed red tint background from invalid state

docs/components/PatternLayout.tsx, docs/components/PkgLayout.tsx, docs/components/TemplateLayout.tsx, docs/content/patterns/conditional-reveal/index.mdx, docs/content/patterns/filtering-a-dataset/index.mdx, docs/content/patterns/selecting-multiple-options/index.mdx, docs/content/templates/category/index.mdx, docs/content/templates/content/index.mdx, docs/content/templates/error-page/index.mdx, docs/content/templates/home/index.mdx, docs/content/templates/multi-page-form/index.mdx, docs/content/templates/sign-in/index.mdx, docs/content/templates/single-page-form/index.mdx, docs/content/templates/subcategory/index.mdx, docs/lib/mdx/packages.ts, docs/lib/mdx/patterns.ts, docs/lib/mdx/templates.ts
Remove version number from components, patterns and templates.
- [View components preview](https://design-system.agriculture.gov.au/pr-preview/pr-1186/components/avatar)
- [View patterns preview](https://design-system.agriculture.gov.au/pr-preview/pr-1186/patterns/conditional-reveal)
- [View templates preview](https://design-system.agriculture.gov.au/pr-preview/pr-1186/templates/category)
=> docs: Remove version number from components, patterns and templates

docs/content/templates/error-page/ThirdParty.tsx
Fix a typo in #1174 which showed the error code twice in the `Third party outage` template.
=> docs: Error page template - remove duplicate error code

packages/react/src/filter-drawer/FilterDrawer.tsx, packages/react/src/filter-drawer/FilterDrawerDialog.tsx, packages/react/src/filter-drawer/__snapshots__/FilterDrawer.test.tsx.snap, packages/react/src/filter-drawer/docs/overview.mdx
Follow up to PR #1099.
- Close the Filter drawer when the user clicks the overlay
- Updated padding in `FilterDialog` to match the padding of page content
- Update documentation
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1203/components/filter-drawer)
=> filter-drawer: Close drawer clicking the overlay

yarn.lock
Similar to PR #909. Currently when you are running tests you see the following warning:
```
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
```
=> Upgraded browserslist 

docs/components/Code.tsx, docs/components/mdxComponents.tsx, docs/content/templates/single-page-form/index.mdx, packages/react/src/accordion/docs/overview.mdx, packages/react/src/page-alert/docs/overview.mdx, packages/react/src/prose/docs/overview.mdx
In our docs site live code previews, we disable the page's Prose styles to ensure they don't modify the appearance of examples not related to body content. However, we do want to enable this in some examples.
This PR introduces a flag on the live code snippet declarations to opt-in to use Prose styles.
=> docs: `enableProse` flag on `Code` previews

.storybook/stories/DataFiltering/TableFilteringMedium.tsx, .storybook/stories/DataFiltering/components/FilterAccordion.tsx
During a recent design review for the upcoming vertical filters pattern, Paul noticed this inconsistency with Figma.
This 'Reset filters' button is redundant, as a 'Clear filters' button appears with the active filter tags when at least one filters has been applied.
=> Table filtering: Remove redundant "Reset Filters" button

.storybook/stories/KitchenSink.tsx, packages/react/src/app-layout/AppLayout.stories.tsx
- Add example with Global alert to App Layout stories
- Added Global-alert above kitchen sink, and replaced the 'PageTemplate' with a specified Header and Footer.
=> Added more storybook examples of Global alert

packages/react/src/date-range-picker/DateRangePicker.tsx, packages/react/src/filter-drawer/FilterDrawerDialog.tsx, packages/react/src/filter-drawer/__snapshots__/FilterDrawer.test.tsx.snap
Follow up to PR #1203.
This updates the "stickyness" of the Filter drawer component on mobile devices only. With this update, the Filter drawer footer component will no longer be stuck to the bottom of the scree which provides much more space for the main content area.
https://github.com/steelthreads/agds-next/assets/6265154/602e320a-e9d6-4e06-a38c-ce95cd4c100d
=> filter-drawer: Update mobile "stickyness" behaviour

.changeset/mighty-carrots-battle.md, packages/react/src/modal/ModalDialog.tsx, packages/react/src/modal/ModalTitle.tsx, packages/react/src/modal/__snapshots__/Modal.test.tsx.snap
Updated modal padding on mobile as it is inconsistent with Filter dialog and other components.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1205/storybook/iframe.html?id=content-modal--basic&viewMode=story)
| <img width="373" alt="Screenshot 2023-06-20 at 10 55 07 am" src="https://github.com/steelthreads/agds-next/assets/6265154/13b186a4-433a-4520-aa9f-af40f1644422"> | <img width="373" alt="Screenshot 2023-06-20 at 10 54 54 am" src="https://github.com/steelthreads/agds-next/assets/6265154/a9286d04-0df5-454a-8dbb-86a577a9c9bf"> |
=> modal: Fix inconsistent padding on mobile

.changeset/moody-shrimps-pull.md, .storybook/stories/DataFiltering/components/DashboardTable.tsx, .storybook/stories/KitchenSink.tsx, packages/react/src/status-badge/StatusBadge.stories.tsx, packages/react/src/status-badge/StatusBadge.test.tsx, packages/react/src/status-badge/StatusBadge.tsx, packages/react/src/status-badge/__snapshots__/StatusBadge.test.tsx.snap, packages/react/src/status-badge/docs/overview.mdx
Added new `weight` prop which can be used to set the visual weight of the badge. The two accepted values are `subtle` and `regular` (default).
- [View docs preview](https://design-system.agriculture.gov.au/pr-preview/pr-1218/components/status-badge)
- [View storybook preview](https://design-system.agriculture.gov.au/pr-preview/pr-1218/storybook/index.html?path=/story/content-statusbadge--info)
=> status-badge: Add new `weight` prop

docs/components/Code.tsx, docs/package.json, yarn.lock
Added support for `diff` syntax highlighting. This was done via the recommended way mentioned on the documentation page which can be found here https://github.com/FormidableLabs/prism-react-renderer#custom-language-support
This was accidecanlly removed in PR #1157 where we upgraded `prism-react-renderer` to version 2.
| <img width="828" alt="Screenshot 2023-06-29 at 11 05 14 am" src="https://github.com/steelthreads/agds-next/assets/6265154/416b1ed5-799d-437d-844d-8b63ff401d39"> | <img width="824" alt="Screenshot 2023-06-29 at 11 05 19 am" src="https://github.com/steelthreads/agds-next/assets/6265154/bdaaba3c-ed6f-486c-8398-191b5076d295"> |
=> docs: Add support for `diff` syntax highlighting

.changeset/thick-bees-scream.md, docs/components/mdxComponents.tsx, docs/content/content/content-principles.mdx, docs/content/content/content-styles.mdx, packages/react/src/page-alert/__snapshots__/PageAlert.test.tsx.snap, packages/react/src/prose/Prose.tsx
- Apply muted colour to footnote in content principles page
- Replace hyphen with en-dash in en-dash example
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1233/content/content-principles)
=> docs: Restyle footnote in content principles

.changeset/tall-islands-rhyme.md, packages/react/src/app-layout/AppLayout.stories.tsx, packages/react/src/app-layout/AppLayout.test.tsx, packages/react/src/app-layout/AppLayoutHeader.stories.tsx, packages/react/src/app-layout/AppLayoutHeader.tsx, packages/react/src/app-layout/AppLayoutHeaderBrand.tsx, packages/react/src/app-layout/__snapshots__/AppLayout.test.tsx.snap
Added new prop `badgeLabel` to `AppLayoutHeader` which can be used to indicate if an application is in a prerelease state.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1241/storybook/index.html?path=/story/layout-applayout--default)
=> app-layout: Add `badgeLabel` prop

packages/react/src/_popover/Popover.tsx, packages/react/src/autocomplete/__snapshots__/Autocomplete.test.tsx.snap, packages/react/src/combobox/__snapshots__/Combobox.test.tsx.snap, packages/react/src/combobox/__snapshots__/ComboboxAsync.test.tsx.snap, packages/react/src/combobox/__snapshots__/ComboboxAsyncMulti.test.tsx.snap, packages/react/src/combobox/__snapshots__/ComboboxMulti.test.tsx.snap, packages/react/src/filter-drawer/FilterDrawerDialog.tsx, packages/react/src/filter-drawer/__snapshots__/FilterDrawer.test.tsx.snap
Follow up to PRs #1206 and #1207. 
This PR replaces `overflowY: scroll` with `overflowY: auto` to remove the scrollbars on windows when they are not required.
No changeset required as these components have not been released yet.
| <img width="416" alt="Screenshot 2023-07-07 at 3 08 21 pm" src="https://github.com/steelthreads/agds-next/assets/6265154/7baaf078-0d80-4ff8-b99e-2a2bb576128e"> | <img width="397" alt="Screenshot 2023-07-07 at 3 08 07 pm" src="https://github.com/steelthreads/agds-next/assets/6265154/a2f5cda1-b253-49d1-a5ec-4d342d8ab729"> |
=> popover/filter-drawer: Use overflow auto

.changeset/rich-shirts-eat.md, docs/pages/foundations/tokens/max-width.tsx, packages/react/src/app-layout/AppLayout.tsx, packages/react/src/app-layout/AppLayoutSidebar.tsx, packages/react/src/app-layout/AppLayoutSidebarDialog.tsx, packages/react/src/app-layout/utils.ts, packages/react/src/core/tokens.ts, packages/react/src/main-nav/NavContainer.tsx, packages/react/src/modal/ModalDialog.tsx
In hindsight, these maxWidth tokens are coupled to specific components, and should not have been brought into the global tokens.
=> core: Remove modalDialog and mobileMenu tokens

docs/content/updates/2023-07-14.mdx
AgDS Beta v1.8.0 release notes
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1262/updates/2023-07-14)
=> AgDS Beta v1.8.0 release notes

packages/react/src/_popover/Popover.tsx
- Updated our `usePopover` hook to accept a `placement` option
- Updated our `usePopover` hook to accept a generic type, which is passed to `useFloating`, which will give us more specific types for our reference elements
This is required for #1236
=> popover: Make popover placement configurable

docs/components/Code.tsx, docs/components/mdxComponents.tsx, docs/content/content/content-patterns.mdx, docs/content/content/content-styles.mdx, docs/content/content/voice-and-tone.mdx, docs/content/guides/how-to-write-guidance/how-to-present-guidance.mdx
Unify appearance of example content and code blocks across the Content and Content Guides sections.
Each 'example' is treated as a seperate card with the heading 'Example'. This is the case for any 'ContentExample', or Code example which exists on the same page as a ContentExample.
Please see the PR preview deployment for [Content](https://design-system.agriculture.gov.au/pr-preview/pr-1239/content) and [How to present guidance](https://design-system.agriculture.gov.au/pr-preview/pr-1239/guides/how-to-write-guidance/how-to-present-guidance).
=> docs: Consistent styling to Content examples

.changeset/sixty-melons-shake.md, packages/react/src/date-picker/Calendar.tsx, packages/react/src/date-picker/DatePicker.tsx, packages/react/src/date-picker/DatePickerInput.tsx, packages/react/src/date-range-picker/DateRangePicker.tsx
This is based off PR #1266
Clicking the calendar button trigger while the calendar popover is open will now close the calendar popover.
https://github.com/steelthreads/agds-next/assets/6265154/5f9606d6-9a6f-441b-a3f3-b70d2159374e
https://github.com/steelthreads/agds-next/assets/6265154/6ab85730-8acd-475e-9864-a99d062e5d84
=> date-picker: Fix click outside issue

docs/components/Code.tsx
This PR fixes bug that was introduced in #1239.
| <img width="821" alt="Screenshot 2023-07-21 at 10 44 22 am" src="https://github.com/steelthreads/agds-next/assets/6265154/216417cd-74da-4490-9b15-03b2e4ecdbe3"> | <img width="814" alt="Screenshot 2023-07-21 at 10 47 25 am" src="https://github.com/steelthreads/agds-next/assets/6265154/183d2112-28cf-4af9-8b55-b8ea3befd8a3"> |
=> docs: Enable overflow in live code snippets

.changeset/loud-keys-begin.md, packages/react/src/box/styles.ts
'Focus' is the name of our system focus ring colour. It should not be exposed as a value for text elements.
Remove focus from foregroundColorMap to avoid it used for text elements
=> Box: Remove 'focus' from supported text styles

packages/react/src/app-layout/__snapshots__/AppLayout.test.tsx.snap, packages/react/src/app-layout/test-utils.tsx, packages/react/src/main-nav/MainNav.stories.tsx, packages/react/src/sub-nav/SubNav.stories.tsx, packages/react/src/tabs/Tabs.stories.tsx
Updated usage of `NotificationBadge` to include an accessible label when used in components as the `endElement` . This update will provides a better experience for screen readers.
An example of this update is the "App layout" example, which has the menu item "Messages" with a Notification badge. Instead of announcing "Messages 6", it will now announce "Messages, 6 unread".
[View preview (App layout)](https://design-system.agriculture.gov.au/pr-preview/pr-1290/storybook/index.html?path=/story/layout-applayout--default)
I have also done this in Ag Common https://github.com/steelthreads/ag-common/pull/67
=> notification-badge: Update usage

.changeset/bright-pillows-shout.md, packages/react/src/checkbox/CheckboxIndicator.tsx, packages/react/src/checkbox/CheckboxInput.tsx, packages/react/src/checkbox/__snapshots__/Checkbox.test.tsx.snap, packages/react/src/control-group/__snapshots__/ControlGroup.test.tsx.snap, packages/react/src/radio/RadioIndicator.tsx, packages/react/src/radio/RadioInput.tsx, packages/react/src/radio/__snapshots__/Radio.test.tsx.snap
**Checkbox**
Updated CSS for toggling the display of the checkbox indicator which stops the checkbox from shifting slightly in certain browsers.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1291/components/checkbox)
**Radio** 
Updated CSS for toggling the display of the radio indicator for consistency with the `Checkbox` component.
**Note These changes have no effect on the accessibility of either of these components as the elements taht are being toggled on/off are already hidden from the accessibility tree.**
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1291/components/radio)
https://github.com/steelthreads/agds-next/assets/6265154/8c8b23b0-347b-480a-a2c4-b06800e4f878
https://github.com/steelthreads/agds-next/assets/6265154/d4cf8e3b-6ee3- …
=> checkbox/radio: Fix indicator bug

.changeset/fast-pans-flow.md, packages/react/src/autocomplete/Autocomplete.test.tsx, packages/react/src/combobox/Combobox.test.tsx, packages/react/src/combobox/Combobox.tsx, packages/react/src/combobox/ComboboxAsync.test.tsx, packages/react/src/combobox/ComboboxAsync.tsx, packages/react/src/combobox/ComboboxAsyncMulti.test.tsx, packages/react/src/combobox/ComboboxAsyncMulti.tsx, packages/react/src/combobox/ComboboxBase/ComboboxBase.tsx, packages/react/src/combobox/ComboboxBase/ComboboxMultiBase.tsx, packages/react/src/combobox/ComboboxMulti.test.tsx, packages/react/src/combobox/ComboboxMulti.tsx, packages/react/src/combobox/test-utils.ts
Added new `inputRef` prop to Autocomplete and Combobox components. This allows consumers to pass refs to the underlying HTML input element, which is consistent  with our Date picker and Date range picker component.
As part of this PR, I have improved some of the test files by consolidating some duplicated code.
=> combobox: Add new `inputRef` prop

.changeset/four-parents-repeat.md, packages/react/src/filter-drawer/FilterDrawer.tsx, packages/react/src/modal/Modal.tsx
Currently if you attempt to server side render the Filter drawer or Modal components, they will crash. This is due to the fact that they use react portals, which can not be rendered on the server.
Since these components are always closed by default, they don't need to be server side rendered. We can do this by making use  of the `canUseDOM` helper function we created for App layout.
=> Update usage of `createPortal` to fix SSR issues

.changeset/twelve-crabs-worry.md, packages/react/src/app-layout/AppLayout.tsx
Consumers of AppLayout must set focusMode to false, which seems unnecessary to me
=> app-layout: Made focusMode prop optional

packages/react/src/dropdown-menu/DropdownMenuItem.tsx, packages/react/src/dropdown-menu/__snapshots__/DropdownMenu.test.tsx.snap
Decreased the gap between icons and labels in the Dropdown Menu component from `1rem` to `0.75rem`.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1301/storybook/index.html?path=/story/layout-dropdownmenu--icons-and-badges)
> No changeset required as this component has not been released yet
=> dropdown-menu: Decrease gap between icon and label

.changeset/purple-ravens-grow.md, packages/react/src/app-layout/AppLayoutSidebarNav.tsx, packages/react/src/app-layout/__snapshots__/AppLayout.test.tsx.snap
Decreased the gap between icons and labels in the app layout sidebar from `1rem` to `0.75rem`.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1302/storybook/index.html?path=/story/layout-applayout--default)
=> app-layout: Decrease gap between icon and label

.changeset/lovely-phones-grow.md, packages/react/src/icon/__snapshots__/Icon.test.tsx.snap, packages/react/src/icon/icons/ArrowUpDownIcon.tsx, packages/react/src/icon/icons/ChevronsUpDownIcon.tsx, packages/react/src/icon/index.ts, packages/react/src/icon/utils.tsx, packages/react/src/table/TableHeaderSortable.stories.tsx, packages/react/src/table/TableHeaderSortable.test.tsx, packages/react/src/table/TableHeaderSortable.tsx, packages/react/src/table/__snapshots__/TableHeaderSortable.test.tsx.snap
- Add ArrowUpDownIcon
- Changed TableHeaderSortable to show ArrowUpDownIcon if the column is not the active sort
- Change icon size to 24px
- Icon no longer changes direction while being hovered
[Link to preview](https://design-system.agriculture.gov.au/pr-preview/pr-1321/storybook/iframe.html?args=&id=patterns-data-filtering-and-sorting--medium&viewMode=story)
=> TableHeaderSortable: Show icons persistently

packages/react/src/autocomplete/Autocomplete.test.tsx
Follow up to #1322  - forgot to wrap the `Autocomplete` component tests in `act`.
=> autocomplete: Wrap tests in act

.github/workflows/deploy-docs.yml, .github/workflows/preview.yml, .github/workflows/test.yml, jest.config.js
[GitHub Actions is showing warnings](https://github.com/steelthreads/agds-next/actions/runs/5804406765) regarding the usage of 'set-output' in CI scripts.
I have followed [this blog post](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) which details how to upgrade.
```
Linting (18)The following actions uses node12 which is deprecated and will be forced to run on node16: actions/setup-node@v1. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
--
Linting (18)The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecati …
```
=> Remove usages of set-output in CI

.changeset/twenty-donuts-smoke.md, packages/react/package.json, packages/react/src/autocomplete/Autocomplete.test.tsx, packages/react/src/autocomplete/__snapshots__/Autocomplete.test.tsx.snap, packages/react/src/combobox/Combobox.test.tsx, packages/react/src/combobox/ComboboxAsync.test.tsx, packages/react/src/combobox/ComboboxAsync.tsx, packages/react/src/combobox/ComboboxAsyncMulti.test.tsx, packages/react/src/combobox/ComboboxAsyncMulti.tsx, packages/react/src/combobox/ComboboxBase/ComboboxBase.tsx, packages/react/src/combobox/ComboboxBase/ComboboxMultiBase.tsx, packages/react/src/combobox/ComboboxMulti.test.tsx, packages/react/src/combobox/ComboboxMulti.tsx, packages/react/src/combobox/__snapshots__/Combobox.test.tsx.snap, packages/react/src/combobox/__snapshots__/ComboboxAsync.test.tsx.snap, packages/react/src/combobox/__snapshots__/ComboboxAsyncMulti.test.tsx.snap, packages/react/src/combobox/__snapshots__/ComboboxMulti.test.tsx.snap, yarn.lock
Upgraded dependency on `downshift` to version 8 – [View release notes](https://github.com/downshift-js/downshift/releases).
In version 8, downshift has implemented ARIA version 1.2. In this update, the combobox will opened when the input is *clicked* and not when the input is *focused*. This is why we've had to make a few changes to the component + tests.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1343/components/combobox)
**Preflight**
**Testing**
=> combobox: Upgrade to version 8 of downshift

.changeset/purple-ravens-grow.md, .changeset/spotty-hairs-kiss.md, packages/react/src/app-layout/AppLayoutSidebarNav.tsx, packages/react/src/app-layout/__snapshots__/AppLayout.test.tsx.snap
This reverts PR #1302 and PR #1309.
The reason for this is because if teams do not upgrade all at once, there will be layouts fits between the micro-frontends.
We will re-apply these changes when PR #1261 is merged and ready to be deployed.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1348)
**Preflight**
=> app-layout: Revert recent UI changes

.changeset/stale-bees-fail.md, docs/components/designSystemComponents.tsx, docs/playroom/snippets.ts, packages/react/src/checkbox/Checkbox.stories.tsx, packages/react/src/checkbox/Checkbox.test.tsx, packages/react/src/checkbox/Checkbox.tsx, packages/react/src/checkbox/CheckboxIndicator.tsx, packages/react/src/checkbox/CheckboxInput.tsx, packages/react/src/checkbox/__snapshots__/Checkbox.test.tsx.snap, packages/react/src/checkbox/docs/overview.mdx, packages/react/src/control-group/__snapshots__/ControlGroup.test.tsx.snap, packages/react/src/icon/__snapshots__/Icon.test.tsx.snap, packages/react/src/icon/icons/MinusIcon.tsx, packages/react/src/icon/index.ts, packages/react/src/icon/utils.tsx
Added support for indeterminate checkboxes via a new `indeterminate` prop
An [indeterminate checkbox](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#indeterminate_state_checkboxes) is used to represent a group of checkboxes that has a mix of selected and unselected values.
When a checkbox is indeterminate, it overrides the checked state.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1351/components/checkbox)
**Preflight**
**Testing**
=> checkbox: Add indeterminate state

.changeset/purple-glasses-switch.md, packages/react/src/prose/Prose.stories.tsx, packages/react/src/prose/Prose.tsx
When using a `<mark>` element inside of our `Prose` component, we apply the `foregroundAction` token as the background color, and the `bodyBackground` token as the text color. These styles were taken from GOLD, but it does seem very odd.
- [Body](https://mcas-proxyweb.mcas.ms/certificate-checker?login=false&originalUrl=https%3A%2F%2Fdesign-system.agriculture.gov.au.mcas.ms%2Fpr-preview%2Fpr-1355%2Fstorybook%2Findex.html%3Fpath%3D%2Fstory%2Fcontent-prose--basic%26McasTsid%3D26110&McasCSRF=d716213ed644f002dc8ebd0b01d84b6957b9d0a27ce51d704f7db71633b34098)
- [Body Alt](https://mcas-proxyweb.mcas.ms/certificate-checker?login=false&originalUrl=https%3A%2F%2Fdesign-system.agriculture.gov.au.mcas.ms%2Fpr-preview%2Fpr-1355%2Fstorybook%2Findex.html%3Fpath%3D%2Fstory%2Fcontent-prose--body-alt%26McasT …
=> prose: Update `mark` styles

.changeset/four-coats-invite.md, packages/react/src/core/responsive.ts, packages/react/src/core/tokens.ts
Created an xxl breakpoint to enable different layouts for wide screens - intended to enable more dense screens where needed.
There isn't any science behind the 1800px number (apart from it being a few hundred px larger than 1200), so it can be changed if needed.
- [Breakpoint docs](https://design-system.agriculture.gov.au/pr-preview/pr-1359/foundations/tokens/breakpoints)
- [Playroom with working xxl token](https://design-system.agriculture.gov.au/pr-preview/pr-1359/playroom/index.html#?code=N4Igxg9gJgpiBcIA8AhCAPAOgOwAS8gBsIAnAXmGB333QGd5dMQBDMAFwEsJtmAaajXTpCjZnQCuYMDDp1%2BggL6KcAPkEBhHuxjZ2OJAHo06ddhCKgA)
**Preflight**
**Testing**
=> core: Added xxl breakpoint token

.changeset/perfect-terms-lay.md, packages/react/src/control-group/ControlGroup.tsx, packages/react/src/control-group/__snapshots__/ControlGroup.test.tsx.snap
Added flex wrapping so horizontal options can break into multiple lines if required.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1366/components/control-group)
| <img width="418" alt="Screenshot 2023-09-11 at 12 01 14 pm" src="https://github.com/steelthreads/agds-next/assets/6265154/f78fa9ee-934f-4beb-b8bd-58737ce174fd"> | <img width="423" alt="Screenshot 2023-09-11 at 12 01 02 pm" src="https://github.com/steelthreads/agds-next/assets/6265154/3caec3ef-0306-4a8a-90a0-1a9443faeaaf"> |
| <img width="424" alt="Screenshot 2023-09-11 at 12 01 49 pm" src="https://github.com/steelthreads/agds-next/assets/6265154/7b32b3c1-2af0-41bc-88e3-ebaeffbddbae"> | <img width="420" alt="Screenshot 2023-09-11 at 12 02 01 pm" …
=> control-group: Add wrapping

.changeset/brown-islands-sip.md, packages/react/src/details/Details.stories.tsx, packages/react/src/details/Details.tsx, packages/react/src/details/docs/overview.mdx
Added new prop `onBodyAlt` to the Details component. If the Details component is placed on a page with `bodyAlt` background, set the `onBodyAlt` prop to `true`.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1370/components/details)
**Preflight**
**Testing**
=> details: Add new `onBodyAlt` prop

.changeset/twenty-falcons-dance.md, packages/react/src/_popover/Popover.tsx, packages/react/src/dropdown-menu/DropdownMenu.stories.tsx, packages/react/src/dropdown-menu/DropdownMenu.test.tsx, packages/react/src/dropdown-menu/DropdownMenu.tsx, packages/react/src/dropdown-menu/DropdownMenuGroup.tsx, packages/react/src/dropdown-menu/DropdownMenuPanel.tsx, packages/react/src/dropdown-menu/__snapshots__/DropdownMenu.test.tsx.snap, packages/react/src/dropdown-menu/docs/overview.mdx
This is required for PR #1261
- Added new prop `popoverOffset` which can be used to control the distance between the button and panel.
- Updated padding of label element in `DropdownMenuGroup`, as requested by @adhamdannawayaff 
- Swapped from display style to conditional rendering to improve panel element anchoring as recommend by [Floating UI](https://floating-ui.com/docs/react#anchoring)
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1367/components/dropdown-menu)
**Preflight**
**Testing**
=> dropdown-menu: Add `popoverOffset` prop

packages/react/src/dropdown-menu/docs/overview.mdx, packages/react/src/list/docs/overview.mdx
We forgot to do this as part of the last release.
=> docs: Remove unreleased from `list` and `dropdown-menu`

.changeset/kind-monkeys-vanish.md, packages/react/src/dropdown-menu/DropdownMenu.stories.tsx, packages/react/src/dropdown-menu/DropdownMenuItem.tsx, packages/react/src/dropdown-menu/DropdownMenuItemRadio.tsx, packages/react/src/dropdown-menu/DropdownMenuPanel.tsx, packages/react/src/dropdown-menu/__snapshots__/DropdownMenu.test.tsx.snap
Improve handling of menu items with long labels. This is required for PR #1261.
| <img width="1394" alt="Screenshot 2023-09-15 at 12 31 56 pm" src="https://github.com/steelthreads/agds-next/assets/6265154/5be04058-7744-4d04-b00e-5d30b9b515f5"> | <img width="1406" alt="Screenshot 2023-09-15 at 12 31 02 pm" src="https://github.com/steelthreads/agds-next/assets/6265154/2a37fb85-d042-4977-b1cb-142bfc3d1cdd"> |
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1372/storybook/index.html?path=/story/layout-dropdownmenu--long-labels)
**Preflight**
**Testing**
=> dropdown-menu: Improve handling of long labels

.github/workflows/test.yml, jest.config.js
After reading [Tests are Extremely Slow on Docker and/or Continuous Integration (CI) server](https://jestjs.io/docs/next/troubleshooting#tests-are-extremely-slow-on-docker-andor-continuous-integration-ci-server) on the Jest docs, I've implemented [`maxWorkers`](https://jestjs.io/docs/next/cli#--maxworkersnumstring) option.
Excerpt the Jest docs
> If you use GitHub Actions, you can use [github-actions-cpu-cores](https://github.com/SimenB/github-actions-cpu-cores) to detect number of CPUs, and pass that to Jest.
This change seems to improve our CI time by approx 60 seconds. The "Unit Tests" on this branch runs in 2 minutes, but on the main branch it takes around 3 minutes.
=> Add max workers to jest tests

.storybook/main.ts, .storybook/preview.tsx, docs/next.config.js, docs/package.json, example-form/next.config.js, example-form/package.json, example-site/next.config.js, example-site/package.json, package.json, yarn.lock
- Upgraded Next to version `13.15.0`
- Fixed deprecation warning about using [next export] by using ` output: 'export'` as mentioned [in the next docs](https://nextjs.org/docs/pages/building-your-application/deploying/static-exports#configuration)
- Removed usage of `storybook-addon-next-router` as we get deprecation warnings about this plugin, and it doesn't work very well with the next version of Next. This has been replaced by `next-router-mock`.
=> Upgrade NextJS

packages/react/src/callout/Callout.tsx, packages/react/src/callout/__snapshots__/Callout.test.tsx.snap, packages/react/src/callout/utils.tsx
Adjusted the gap in regular Callout between the icon and the text stack to be consistent with designs.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1385/components/callout)
**Preflight**
**Testing**
=> callout: Adjusted icon gap

.changeset/happy-meals-watch.md, packages/react/src/app-layout/AppLayoutContent.tsx, packages/react/src/app-layout/AppLayoutSidebar.tsx, packages/react/src/app-layout/__snapshots__/AppLayout.test.tsx.snap
Removed `overflow: hidden` from `AppLayoutContent` to support sticky elements. This is required in order for PR #1345.
I've also added `min-width: 0` to fix large tables and potentially other wide elements breaking the page layout on smaller devices. This was being achieved by `overflow-hidden` previously.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1388/playroom/index.html#?code=N4Igxg9gJgpiBcIA8BBADmgMgQwJ4QFcAXAPgB0A7AAitQx32IAkZtYAnSmmgC1agCWFAOYBeMiADKMdgDcBYGFQrYAtjAlduAZwIAjTEJjipM%2BYqqxtYdgLREBEakR7YiVSAQA2UKnqXYVF4CREReSl5OwjKa1NyRwhCiwEiYEIlUAPQkAL5avOwwAGYmAMSxNNladFh4hESSArB62JxxNCEwqtrJANr53P3t3DTAQdj%2BXvBUEjiTEgA0VDyFRdMS5SBLCk7TAOowetqdAJKQ1DkLAyNjXhMwUzMgcw%2BLy6vrIJvb5-uHx0QYGcnFRLtcqABdK7DGi9W73R6zBFvHYUaYAUQAHiFgRcoQMIXk4lU4jUGPUAMJOQEUUgDJCqb …
=> app-layout: Fix large tables breaking layout

.changeset/green-radios-decide.md, packages/react/src/details/Details.tsx, packages/react/src/details/__snapshots__/Details.test.tsx.snap, packages/react/src/switch/Switch.tsx, packages/react/src/switch/__snapshots__/Switch.test.tsx.snap, packages/react/src/switch/docs/overview.mdx
details: Updated width of interactive element to match content
switch: Updated width of interactive element to match content
[View Switch preview](https://design-system.agriculture.gov.au/pr-preview/pr-1382/components/switch)
[View Details preview](https://design-system.agriculture.gov.au/pr-preview/pr-1382/components/switch)
**Preflight**
**Testing**
=> switch/details: Update width of interactive element to match content

.changeset/few-days-behave.md, .changeset/tiny-chairs-enjoy.md, packages/react/src/autocomplete/__snapshots__/Autocomplete.test.tsx.snap, packages/react/src/combobox/Combobox.test.tsx, packages/react/src/combobox/ComboboxBase/ComboboxBase.tsx, packages/react/src/combobox/ComboboxBase/ComboboxMultiBase.tsx, packages/react/src/combobox/ComboboxMulti.test.tsx, packages/react/src/combobox/__snapshots__/Combobox.test.tsx.snap, packages/react/src/combobox/__snapshots__/ComboboxAsync.test.tsx.snap, packages/react/src/combobox/__snapshots__/ComboboxAsyncMulti.test.tsx.snap, packages/react/src/combobox/__snapshots__/ComboboxMulti.test.tsx.snap, packages/react/src/field/Field.stories.tsx, packages/react/src/field/Field.test.tsx, packages/react/src/field/Field.tsx, packages/react/src/field/FieldLabel.tsx
Improved accessibility by ensuring that the popover listbox element is described correctly by the field label. This is currently a bug, and it's due to the fact that we don't pass the `labelId` supplied from downshift correctly.
This bug was actually picked up by testing the component using the [IBM Equal Access Accessibility Checker](https://chrome.google.com/webstore/detail/ibm-equal-access-accessib/lkcagbfjnkomcinoddgooolagloogehp) chrome plugin.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1396/components/combobox)
---
Added new `labelId` prop so field labels can be given IDs
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1396/components/field)
---
**Preflight**
**Testing**
=> combobox: Improve a11y by fixing incorrect usage of `aria-describedby`

docs/content/templates/multi-page-form/MultiPageFormStep.tsx
Resolve a layout bug in the multi-step form template example on mobile, which was constricting form contents.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1391/storybook/index.html?path=/story/templates-multi-page-form--form-page)
| <img width="452" alt="image" src="https://github.com/steelthreads/agds-next/assets/12689383/b6ca33d3-c626-485d-ba99-b91bc394460d"> | <img width="453" alt="image" src="https://github.com/steelthreads/agds-next/assets/12689383/32e3d8da-5700-47df-a0df-c3a3acd1d949"> | 
**Preflight**
**Testing**
=> multi-step-form example: Resolve layout bug

.storybook/stories/DataFiltering/ListFiltering.stories.tsx, .storybook/stories/DataFiltering/TableFiltering.stories.tsx, .storybook/stories/DataFiltering/components/DataTable.stories.tsx, .storybook/stories/DataFiltering/lib/contexts.tsx, .storybook/stories/DataFiltering/lib/useFetchData.ts, .storybook/stories/DataFiltering/lib/utils.ts, packages/react/src/filter-sidebar/FilterSidebar.stories.tsx
While working with the table filtering code to build more examples, I found the name useData confusing. So I've renamed it to `useFetchData` and moved it to it's own file, in the same folder as `useSortAndFilter`
I did this in #1405 but thought making a seperate PR would be a good way to reduce the diff
=> table-filtering: Rename useData to useFetchData and move to own file

packages/react/src/table/Table.tsx, packages/react/src/table/TableContext.tsx, packages/react/src/table/TableRow.tsx, packages/react/src/table/__snapshots__/Table.test.tsx.snap, packages/react/src/table/__snapshots__/TableHeaderSortable.test.tsx.snap
We have encountered an issue with our new `<TableRow />` selectable styles when using the `<Table />` component with `tableLayout="fixed"`. You can preview this bug [here](https://design-system.agriculture.gov.au/storybook/index.html?path=/story/content-table--selectable-basic&args=tableLayout:fixed).
To resolve this, I implemented an alternative selectable style logic based on the `tableLayout` prop. To achieve this, a new `TableContext` was introduced so that the `<TableRow />` component has access to the `tableLayout` prop.
No changeset is required at this time since `TableRow` hasn't been released.
[View preview of bug fixed](https://design-system.agriculture.gov.au/pr-preview/pr-1407/storybook/index.html?path=/story/content-table--selectable-basic&args=tableLayout:fixed) …
=> table: Fix selectable rows when using fixed table layout

.changeset/quick-papayas-collect.md, .github/pull_request_template.md, .storybook/stories/KitchenSink.tsx, packages/react/src/app-layout/AppLayoutSidebarNav.tsx, packages/react/src/app-layout/__snapshots__/AppLayout.test.tsx.snap
app-layout: Fixed small issue in `AppLayoutSidebar` where the text color wasn't being applied correctly to text list items in dark mode 
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1408/storybook/index.html?path=/story/testing-kitchen-sink--application-layout&globals=palette:dark)
**Preflight**
**Testing**
=> app-layout: Fix small dark mode issue

.changeset/tall-zebras-watch.md, packages/react/src/file-upload/index.ts
file-upload: Exported `formatFileSize` utility function. Example usage:
```tsx
import { formatFileSize } from '@ag.ds-next/react/file-upload';
```
**Preflight**
=> file-upload: export `formatFileSize` util function

.changeset/plenty-shrimps-smell.md, packages/react/src/app-layout/AppLayoutSidebar.stories.tsx, packages/react/src/app-layout/AppLayoutSidebar.tsx, packages/react/src/app-layout/AppLayoutSidebarNav.tsx, packages/react/src/app-layout/__snapshots__/AppLayout.test.tsx.snap, packages/react/src/app-layout/test-utils.tsx
Extended the `items` prop in `AppLayoutSidebar` to accept an object with `options` and `items`. This allows consumers to control the padding between sidebar navigation groups.
```tsx
<AppLayoutSidebar
activePath="/"
items={[
// pass an object with `options` and `items`
{
options: { disableGroupPadding: true },
items: [{ label: 'Item A' }],
},
// or pass an array of items (current syntax)
[
{ label: 'Item B', href: '/b' },
{ label: 'Item C', href: '/c' },
{ label: 'Item D', href: '/c' },
],
]}
/>
```
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1410/components/app-layout)
**Preflight**
**Testing**
=> app-layout: Fixed incorrect padding between sidebar navigation groups

.changeset/pretty-plants-explain.md, packages/react/src/file-upload/index.ts
Export the `formatFileSize` utility from FileUpload. We attempted this change recently, but mistakingly exported it as a type.
**Preflight**
=> file-upload: Export formatFileSize utility

.storybook/stories/SelectableTableBatchActions/SelectableTableBatchActions.tsx, docs/content/patterns/selectable-table-with-batch-actions/index.mdx, packages/react/src/table/docs/overview.mdx
Improved code snippets on the "Selectable tables with batch actions" to be more realistic examples, as per feedback from @adhamdannawayaff.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1422/patterns/selectable-table-with-batch-actions)
**Preflight**
=> docs: Update table batch actions examples

.changeset/brave-bobcats-sip.md, packages/react/src/status-badge/StatusBadge.tsx, packages/react/src/status-badge/__snapshots__/StatusBadge.test.tsx.snap
Made each icon in the `StatusBadge` component announceable by screen readers
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1383/components/status-badge)
**Preflight**
**Testing**
=> status-badge: Announce SVG

.changeset/large-pumpkins-greet.md, packages/react/src/core/boxPalette.ts, packages/react/src/main-nav/NavContainer.tsx, packages/react/src/main-nav/NavList.tsx, packages/react/src/main-nav/__snapshots__/MainNav.test.tsx.snap, packages/react/src/main-nav/utils.ts
This PR updates the mobile variant of Main nav to always render in the light palette, which matches other modals such as App Layout Mobile, Modal, Drawer etc.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1416)
**Preflight**
**Testing**
=> main-nav: Use light palette for mobile version

.changeset/grumpy-flowers-pull.md, packages/react/src/file-upload/FileUploadFileThumbnail.tsx, packages/react/src/file-upload/__snapshots__/FileUpload.test.tsx.snap
Remove the grey border around the outside of the FileUploadThumbnail
| <img width="376" alt="image" src="https://github.com/steelthreads/agds-next/assets/12689383/1d6b3242-3fb3-4f33-8721-63a8a803be36"> | <img width="302" alt="image" src="https://github.com/steelthreads/agds-next/assets/12689383/2279c925-fc4a-4571-bda9-9338bab3fc73"> |
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1426/storybook/index.html?path=/story/forms-fileupload-primitives-fileuploadfilelist--mixed-files)
**Preflight**
**Testing**
=> file-upload: Remove border from thumbnail

.github/pull_request_template.md
Add a 'preflight' item to the PR checklist template to add a Changeset file. This was removed in #1337.
=> Add changeset item to PR checklist

.changeset/pretty-plants-explain.md, .changeset/pretty-terms-tan.md, packages/react/src/file-upload/FileUpload.stories.tsx, packages/react/src/file-upload/FileUpload.test.tsx, packages/react/src/file-upload/FileUpload.tsx, packages/react/src/file-upload/FileUploadExistingFile.stories.tsx, packages/react/src/file-upload/FileUploadExistingFile.tsx, packages/react/src/file-upload/FileUploadExistingFileList.stories.tsx, packages/react/src/file-upload/FileUploadExistingFileList.tsx, packages/react/src/file-upload/FileUploadFile.tsx, packages/react/src/file-upload/FileUploadFileList.tsx, packages/react/src/file-upload/FileUploadFileThumbnail.tsx, packages/react/src/file-upload/FileUploadRejectedFile.tsx, packages/react/src/file-upload/FileUploadRejectedFileList.tsx, packages/react/src/file-upload/__snapshots__/FileUpload.test.tsx.snap, packages/react/src/file-upload/docs/overview.mdx, packages/react/src/file-upload/utils.tsx
Add support for FileUpload to show previously uploaded files, with the new `existingFiles` prop.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1415/storybook/?path=/story/forms-fileupload--existing-files)
**Preflight**
**Testing**
=> file-upload: Show previously uploaded files

.changeset/tame-cups-tickle.md, packages/react/src/checkbox/Checkbox.tsx, packages/react/src/radio/Radio.tsx
If supplied, the `invalid` prop will now override the value of the `invalid` prop set in `ControlGroup`.
Compare how this works [in this pr preview](https://design-system.agriculture.gov.au/pr-preview/pr-1433/playroom/index.html#?code=N4Igxg9gJgpiBcIA8AlGA7WAnAfAHXQAJDgAKASkIF4cSDjjJ0BnAF0IG0wALGMAaxhQAjABpCzGKwDCvAUOEBdaoTQBDMKwB0AV0kBlVmtYxSAMzUAbSeQDc9BkzacefQVABM4yTLnuPylSqMBraejCGxqasWDowdg6MECzsXH5CAMzeUrJumYHBoboGRibmVjb2RAxYUjpYRKSJDEjSyTEQlgDiWBA6AA7NDISWagBGMJZUeCAAInyjWMYAlskzQwzL6ABuVstQVMAAhK7yIoQAPheEJ%2Bmel9e3eVAZAL4bxAC2MMzMagDmMGmIAAgpZLIRTvwxhAAB4-QhqWqEWoARx0y1qUHW1WGxDRGKxH0IY0sEAEG3wuLxrT8MNhxMYd0OUIU72peMIyVkanQgMOFGotB8uTOwlITzF5HZnOGW12ln2h0l7mEMtlVNlDAAkoj-rUYIRWBAjdxlsxCGZMc4mFBlqxVuhiUgAPSi6FwzWy2luemMyHM4CszzqrXc7i8-lkSg0CQ5O4eCXBjzS-3yvYHY7J0N4r1a3UAg1Gk2sM0WyS …
=> checkbox: `invalid` prop should override control group

packages/react/src/file-upload/docs/overview.mdx
Fixing a mistake in the docs of the new FileUpload enhancements, where the example of existing files wasn't made to be a live preview.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1434/components/file-upload#existing-files)
**Preflight**
**Testing**
=> file-upload: Make existing file example a live preview

.changeset/wet-ways-dance.md, packages/react/src/dropdown-menu/reducer.tsx
Some minor changes to the reducer for the dropdown menu:
- Sort keys for `State` and `initialState` alphabetically
- Improved JSDoc comments with default values
- Wrap cases in curly braces to prevent accidental leaking of scope
- Treat `descendantCount` as a count and not an index
- Use a ternary instead of mutating a let variable for `ACTIVATE_LAST_DESCENDANT` and `ACTIVATE_NEXT_DESCENDANT` cases
- Throw error if an unexpected case is ever reached
**Preflight**
=> dropdown: Minor updates to state reducer

.changeset/strong-actors-dress.md, packages/react/src/button/Button.tsx, packages/react/src/button/__snapshots__/Button.test.tsx.snap, packages/react/src/button/styles.ts, packages/react/src/date-picker/__snapshots__/DatePicker.test.tsx.snap, packages/react/src/date-range-picker/__snapshots__/DateRangePicker.test.tsx.snap, packages/react/src/drawer/__snapshots__/Drawer.test.tsx.snap, packages/react/src/dropdown-menu/__snapshots__/DropdownMenu.test.tsx.snap, packages/react/src/file-input/__snapshots__/FileInput.test.tsx.snap, packages/react/src/file-upload/__snapshots__/FileUpload.test.tsx.snap, packages/react/src/global-alert/__snapshots__/GlobalAlert.test.tsx.snap, packages/react/src/hero-banner/HeroBanner/__snapshots__/HeroBanner.test.tsx.snap, packages/react/src/modal/__snapshots__/Modal.test.tsx.snap, packages/react/src/page-alert/__snapshots__/PageAlert.test.tsx.snap, packages/react/src/search-box/__snapshots__/Search.test.tsx.snap, packages/react/src/section-alert/__snapshots__/SectionAlert.test.tsx.snap, packages/react/src/skip-link/__snapshots__/SkipLinks.test.tsx.snap
- Added flex-shrinking to icons to prevent from shrinking when the button label spans multiple lines
- Updated text alignment for the `text` button variant
| [Before playroom](https://design-system.agriculture.gov.au/playroom/index.html#?code=N4Igxg9gJgpiBcIA8AFAhgcxgYQgOwBcZCA%2BAHTwAJKkAVNAIwBsYB1AJzQAcuZ3yq1GvWYwBQoXUYsAEjDRRxEySJYAlCAHclyldJhyFfSpoCWUAgAsAvGRABWAAwBSO5QDOkXrfAQmdnV0hABkIMDQCU3wKIMkAelUDeVh%2BGNjhfUMUyiIADwIAQSZTDDwfdhLLAjdPCG87SH8QQNiUOoBXJgiovDTYpATM5L4W5SlRLOM8wuLS8srqkA8vGB9GgL707Es0PCxKCAA3Yy52GEOo9vdKAE95dkpXQX7BieHU56Dx2XecmHyiiUynYKhgqjUVms-BtPrFtrt9kcTmcLhArpRYOFYI9NroBolJh8XokNNpcTRXj8FKNvjAAELQG6jai00nMvSibAwJhMEhIOntAgEfCUQ5oCq7Ag%2BaZuUyQPAFABmRHY1mAABEtHgmBAFABJeUAXxIVlM7gAtGbzWhzWc0DybuadXtzYrTCw8GgALYwc1WCLmjAQGAWtB …
=> button: Fix icon shrinking

.changeset/famous-parrots-perform.md, packages/react/src/button/__snapshots__/Button.test.tsx.snap, packages/react/src/button/styles.ts, packages/react/src/date-picker/__snapshots__/DatePicker.test.tsx.snap, packages/react/src/date-range-picker/__snapshots__/DateRangePicker.test.tsx.snap, packages/react/src/drawer/__snapshots__/Drawer.test.tsx.snap, packages/react/src/dropdown-menu/__snapshots__/DropdownMenu.test.tsx.snap, packages/react/src/file-input/__snapshots__/FileInput.test.tsx.snap, packages/react/src/file-upload/__snapshots__/FileUpload.test.tsx.snap, packages/react/src/global-alert/__snapshots__/GlobalAlert.test.tsx.snap, packages/react/src/hero-banner/HeroBanner/__snapshots__/HeroBanner.test.tsx.snap, packages/react/src/modal/__snapshots__/Modal.test.tsx.snap, packages/react/src/page-alert/__snapshots__/PageAlert.test.tsx.snap, packages/react/src/search-box/__snapshots__/Search.test.tsx.snap, packages/react/src/section-alert/__snapshots__/SectionAlert.test.tsx.snap, packages/react/src/skip-link/__snapshots__/SkipLinks.test.tsx.snap
This pull request updates our "Button" component to use `min-height` instead of `height`. This adjustment ensures that buttons with multi-line labels are better accommodated.
| [View before playroom](https://design-system.agriculture.gov.au/playroom/index.html#?code=N4Igxg9gJgpiBcIA8AFAhgcxgYQgOwBcZCA%2BAHTwAJKkBlAtMAa0ozQAcBeYAZgF9yVajXqMWbLsACMfSmgA2ASwx4AkkQC2AZ05kQAM3kwAHgFotDAE4E9g4cKQAhAK4EC%2BSgDc0lxWkK6IOy%2BGj4AnnqUipB4AIL6RJbcACIQAO548hBoUKoxAhT29igh4ZQARq7ueIVFSAD0Lm74dnVN1V4%2BfgF6WjAxUOGR0fjxiSnpmdm5%2Ba1FlLT9%2BIOWYRVV%2BLX2De0tWw67VN6%2B-gSBiQR%2Bq8MxYzBJwKkZWTl5%2BAVC8wAq95dllc0qPI0OUYPJ9tQdhs8HMDtDOiceiAiMYbCAorcEvcJs9pm88B95tQfqj1oDKMDQeDPg5GtDYQ1RMwGclFJ5FLBLJR6gymeIONwZHIlCp1DBtIFDCZzFY0bDIYcEd0znpgopQtd0SM4liHk8pq9ZhDhAQABaKLSmC2m …
=> button: use min height

docs/content/foundations/tokens/spacing.mdx, docs/content/patterns/search-filters/index.mdx
- Tweak spacing within list of cards, in the example published on the [search-filters pattern page](https://design-system.agriculture.gov.au/pr-preview/pr-1457/patterns/search-filters) (was 24px, now 16px)
- Add documentation to [spacing tokens page](https://design-system.agriculture.gov.au/pr-preview/pr-1457/foundations/tokens/spacing) about card list/grid gaps
=> Adjust card spacing in search-filters example

example-form/components/ErrorBoundary.tsx, example-form/components/Layout/AppLayout.tsx, example-form/pages/app/businesses/index.tsx
Added a [React Error Boundary](https://react.dev/reference/react/Component#catching-rendering-errors-with-an-error-boundary) around the application layout main content area, which will stop the whole page from crashing if an error occurred in that part of the page (e.g. hydrating the form state from session storage). This will most likely never occur but it's good to have just in case.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1449/example-form/)
**Preflight**
=> example-form: Add error boundary

.changeset/happy-trees-serve.md, packages/react/src/file-upload/FileUpload.stories.tsx, packages/react/src/file-upload/FileUploadFile.stories.tsx, packages/react/src/file-upload/FileUploadFile.tsx, packages/react/src/file-upload/test-utils.ts, packages/react/src/file-upload/utils.tsx
Add support for href attributes on files, so they can link to a view/download page.
Requested by Anand.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1460/storybook/?path=/story/forms-fileupload--instant-upload)
**Preflight**
**Testing**
=> file-upload: Support `href` attribute on files

packages/react/src/control-group/docs/overview.mdx
Fixed broken links on the Control group documentation page.
=> docs: Fix broken link on control group page

.changeset/metal-donkeys-live.md, packages/react/src/file-input/FileInput.tsx, packages/react/src/file-input/__snapshots__/FileInput.test.tsx.snap
Fixed hover styles in the `FileInput` component. These hover styles are currently broken because `&:not(:disabled):hover` is not supported by the `::file-selector-button` selector.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1475/components/file-input)
| <img width="821" alt="Screenshot 2023-11-02 at 2 01 17 pm" src="https://github.com/steelthreads/agds-next/assets/6265154/4cadb413-3ef2-4b49-ad30-d886eaaabe4e"> | <img width="822" alt="Screenshot 2023-11-02 at 2 01 04 pm" src="https://github.com/steelthreads/agds-next/assets/6265154/a4bb05a6-2f70-4421-bd80-6d3ccb140da6"> | 
**Preflight**
**Testing**
=> file-input: Fix hover states

.changeset/moody-games-think.md, packages/react/src/combobox/ComboboxRenderItem.stories.tsx, packages/react/src/combobox/ComboboxRenderItem.tsx
A consuming team of AgDS needs to support 4 lines of text in the Combobox component. We currently have support for `secondaryText` and `tertiaryText`, but we don't allow a 4th line of text.
Rather than adding in a new prop `quaternaryText` (lol), I've added support for react nodes in the `secondaryText` and `tertiaryText` props in the `ComboboxRenderItem` component.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1476/storybook/index.html?path=/story/forms-combobox-primitives-comboboxrenderitem--with-four-lines-text)
**Preflight**
**Testing**
=> combobox: Support 4 lines of text

packages/react/src/app-layout/AppLayoutHeaderAccount.tsx, packages/react/src/box/styles.ts, packages/react/src/file-upload/FileUpload.tsx, packages/react/src/file-upload/__snapshots__/FileUpload.test.tsx.snap, packages/react/src/loading/LoadingBlanketContent.tsx, packages/react/src/table/TableCaption.tsx, packages/react/src/table/TableCell.tsx, packages/react/src/table/TableHeader.tsx, packages/react/src/table/TableHeaderSortable.tsx, packages/react/src/table/__snapshots__/Table.test.tsx.snap, packages/react/src/table/__snapshots__/TableHeaderSortable.test.tsx.snap
Added `text-align` prop to `BoxProps
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1485/playroom/index.html#?code=N4Igxg9gJgpiBcIA8AhCAPABAFxu7AggDYCWA5gHYC8wA2gDrgwW4BOjANJo6%2BQBbZO3EERgAzQSC49%2BkgLoBfAHwAJGEQ0RMAdwisiUJAHo06JfQogFQA)
**Preflight**
=> box: Add new `textAlign` prop

.changeset/funny-students-happen.md, packages/react/src/combobox/Combobox.tsx
Fixed a bug in the `Combobox` component where changing the value of the `options` prop would not immediately update the list of options.
This is because in the `Combobox` component, we keep track of the list of options with internal `useState`, using the `options` prop as an initial value. But if that list of option prop ever changes, the options don't update until the component re-renders for whatever reason.
To view the current bug, [use this playroom link](https://design-system.agriculture.gov.au/playroom/index.html#?code=N4Igxg9gJgpiBcIA8AlGA7WAnAfAHXQAJDgAKASkIF4cSDjjJ0BnAF0IG0IAHVgSwgsANIWYxWAeV4CWAXWqE0AQzCsAdAFcxAZVZLWMUh1nkA3AXoNlqzWICiAMwcxVpCtVrBLDUeIAqfAC2MBAarG6UNHREPgxiktKCzKQAwhIAqgByfigAmgD6EgAKfgCSEpnaZt4MAL4iAMwADC3VMcT1nCbm6DVY4hpYREgpEIEARhCTAB6EADZK4zBzVHgg2ssu7Dz8gmuE …
=> combobox: Fixed stale options bug

.changeset/large-melons-drive.md, packages/react/src/combobox/Combobox.stories.tsx, packages/react/src/combobox/Combobox.tsx, packages/react/src/combobox/ComboboxAsync.stories.tsx, packages/react/src/combobox/ComboboxAsync.tsx, packages/react/src/combobox/ComboboxBase/ComboboxBase.tsx, packages/react/src/combobox/docs/overview.mdx
Added new `clearable` prop to `Combobox`. If true, the clear button ("x") will be rendered when there is a selected option. `clearable` is already a prop in `ComboboxAsync`, but it didn't have docs or stories, and the ordering of the buttons was incorrect.
- [Preview clearable documentation](https://design-system.agriculture.gov.au/pr-preview/pr-1489/components/combobox#clearable)
- [Preview clearable storybook](https://design-system.agriculture.gov.au/pr-preview/pr-1489/storybook/index.html?path=/story/forms-combobox-combobox--clearable)
- [Preview async storybook](https://design-system.agriculture.gov.au/pr-preview/pr-1489/storybook/index.html?path=/story/forms-combobox-comboboxasync--clearable)
**Preflight**
**Testing**
=> combobox: Document `clearable` prop

docs/content/patterns/loading-error-empty-states/index.mdx
- Component level error state
- Component level empty state
- Current gap: 0
- Should be: 0.5rem (8px)
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1494/patterns/loading-error-empty-states)
=> docs: Loading, empty and error states space

.changeset/proud-jars-complain.md, packages/react/src/progress-indicator/ProgressIndicatorItem.tsx, packages/react/src/progress-indicator/__snapshots__/ProgressIndicator.test.tsx.snap
Tweaked padding and spacing values of list item elements in the [Progress Indicator](https://design-system.agriculture.gov.au/components/progress-indicator) component to more closely match designs.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1500/components/progress-indicator)
**Preflight**
**Testing**
=> progress-indicator: Fix spacing bugs

packages/react/src/control-group/docs/overview.mdx
Fixed broken link to the Radio component from the Control Group page.
=> control-group: Fix broken links

.changeset/dull-houses-return.md, packages/react/src/combobox/Combobox.test.tsx, packages/react/src/combobox/Combobox.tsx, packages/react/src/combobox/ComboboxAsync.test.tsx, packages/react/src/combobox/ComboboxAsync.tsx, packages/react/src/combobox/ComboboxAsyncMulti.test.tsx, packages/react/src/combobox/ComboboxAsyncMulti.tsx, packages/react/src/combobox/ComboboxBase/ComboboxBase.tsx, packages/react/src/combobox/ComboboxBase/ComboboxMultiBase.tsx, packages/react/src/combobox/ComboboxMulti.test.tsx, packages/react/src/combobox/ComboboxMulti.tsx
Added support for `onBlur` and `onFocus` props to all Combobox component variants (`Combobox`, `ComboboxAsync`, `ComboboxMulti`, `ComboboxAsyncMulti`).
- [View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1498/components/combobox)
- [View preview in Playroom](https://design-system.agriculture.gov.au/pr-preview/pr-1498/playroom/index.html#?code=N4Igxg9gJgpiBcIA8BlALgQzAawAQHMMAHAXmAGYBfXIjKKASwDt8yBGagWwwA8B1BlDQALEgB0QAVgAMAJxicJAPjFNcuJAGEInAEYR9PVevUAbDLpinxIbXoMQjIYyYhE0DCEwDOZANouJrjAuABuGKYArjDwuBIYEgA0uOaWprESAPLunmoAghK4lImBJiHhUTFxILpJKRZWGSDZHl64AEKFxaXq5RHRTWB1qY3VLbm4ml0laiYAupSluqYQOKVeAGKrkb7AABQwoTBMaACUuCRKuJA%2BEKYwAHQr%2BHsSm9vekzr6hnWHx2dFrN1F52lFZGQDkcTudLtcvN47o9nq8QKDwV97L8QMl-jCgeoAPQqJguLTfBw8ACykVMHlKI2sEjsP0cNLpDAk6xyCP8PWCYX6VXiwwa6TGPPy035fUqTV …
=> combobox: Add `onBlur` and `onFocus` events

.changeset/modern-bats-raise.md, packages/react/src/table/TableWrapper.tsx, packages/react/src/table/__snapshots__/Table.test.tsx.snap
Allow focus on tableWrapper to fix accessibility for keyboard users
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1517)
**Preflight**
**Testing**
=> table: Allow focus on TableWrapper to fix a11y for keyboard users

docs/playroom/snippets.ts
Adds the `accountDetails` prop to `AppLayoutHeader` in `boilerplateAppTemplate`.
Makes all whitespace consistent to use tabs, and not a mixture of tabs and spaces.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1525/playroom)
**Preflight**
=> playroom: Add accountDetails to AppLayoutHeader. Fix whitespace

.changeset/dull-keys-tap.md, packages/react/src/date-range-picker/DateRangePicker.stories.tsx, packages/react/src/date-range-picker/DateRangePicker.tsx
The error message wasn't associated to the inputs, so this fixes that.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1534)
**Preflight**
**Testing**
=> date-range-picker: Correctly associate error message to appropriate date inputs

.github/workflows/deploy-docs.yml, .github/workflows/preview.yml, .github/workflows/release.yml, .github/workflows/test.yml
Follow up to PR #1505.
This PR ensures that all of our github actions run in the same version of node. I've also ensured that we're using the latest versions of certain actions like `actions/checkout` etc.
=> Update github actions

.changeset/heavy-badgers-sit.md, packages/react/src/progress-indicator/ProgressIndicator.stories.tsx, packages/react/src/progress-indicator/ProgressIndicator.test.tsx, packages/react/src/progress-indicator/ProgressIndicatorItem.tsx, packages/react/src/progress-indicator/docs/overview.mdx
Added two new statuses for items: `saved` and `error`.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1548/components/progress-indicator)
**Preflight**
**Testing**
=> progress-indicator: Add new `saved` and `error` status

.changeset/tall-gifts-heal.md, packages/react/src/date-picker/Calendar.tsx, packages/react/src/date-picker/__snapshots__/Calendar.test.tsx.snap
- Update calendar days to be standard, not toggle buttons
- Manually prefix "Selected" to selected days
- Make days within selected region not selected, but manually announce that they're within the selected range.
**Preflight**
**Testing**
=> date-picker: Days are standard buttons. Selected and range dates announced

packages/react/src/file-upload/docs/overview.mdx
Our File upload component doesn't the best working examples of the component on the docs site. This is mainly because the File upload component relies on the `value` and `onChange` prop, which are absent from all of the examples.
In this PR, I have updated the examples to include these missing props which results in a better live code example.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1560/components/file-upload)
=> file-upload: Update examples in documentation site

.changeset/cuddly-steaks-add.md, packages/react/src/autocomplete/__snapshots__/Autocomplete.test.tsx.snap, packages/react/src/combobox/ComboboxBase/ComboboxBase.tsx, packages/react/src/combobox/ComboboxBase/ComboboxMultiBase.tsx, packages/react/src/combobox/__snapshots__/Combobox.test.tsx.snap, packages/react/src/combobox/__snapshots__/ComboboxAsync.test.tsx.snap, packages/react/src/combobox/__snapshots__/ComboboxAsyncMulti.test.tsx.snap, packages/react/src/combobox/__snapshots__/ComboboxMulti.test.tsx.snap, packages/react/src/date-picker/DatePickerInput.tsx, packages/react/src/date-picker/__snapshots__/DatePicker.test.tsx.snap, packages/react/src/date-range-picker/__snapshots__/DateRangePicker.test.tsx.snap, packages/react/src/field/Field.tsx, packages/react/src/field/FieldContainer.tsx, packages/react/src/fieldset/__snapshots__/Fieldset.test.tsx.snap, packages/react/src/password-input/__snapshots__/PasswordInput.test.tsx.snap, packages/react/src/search-input/SearchInput.tsx, packages/react/src/search-input/__snapshots__/SearchInput.test.tsx.snap, packages/react/src/select/Select.tsx, packages/react/src/select/__snapshots__/Select.test.tsx.snap, packages/react/src/text-input/TextInput.tsx, packages/react/src/text-input/__snapshots__/TextInput.test.tsx.snap, packages/react/src/textarea/Textarea.tsx, packages/react/src/textarea/__snapshots__/Textarea.test.tsx.snap
This fixes a bug where standard form inputs didn't try to use their `maxWidth` as soon as they were put in a `Flex` container.
The requirements for the fix are:
1. Inputs will always try to be as wide as their `maxWidth` but will shrink if there is not enough space.
2. The label (and hint text) will be as long as they need to be, which may be longer than the input.
3. Any flex siblings must sit immediately beside the input/label (whichever is largest)
You can see a comparison in Playroom here: [**Before**](https://design-system.agriculture.gov.au/playroom/index.html#?code=N4Igxg9gJgpiBcIA8AhCAPABABwIZSgEsA7AcwF5gBmAXwD4AdYzTJAZQBdcwBrTU3NkoAmekxYskACRj4SpTBwCe2GOQYgAFsI10Aks1w4ANrhKZO3HkgD0MuWUbMJ7Lr36DKARjHOJrABUYdA4DbABXDkxTACMYY3UQdABnTBIIjg1MAFtcdAB1QigOTUSUrIAnGABHcMIqqEwbJ39JIJCwyOjc …
=> field: Ensure all form inputs always try to achieve their maxWidth

package.json, yarn.lock
This previous Dependabot PR (https://github.com/agriculturegovau/agds-next/pull/1559) updated Vite from 4.2.3 to 4.5.2, however, Storybook no longer worked in Dev. It seems 4.4.7 (before the transient dependency, esbuild updated) is the last version to get Storybook functioning without changes.
Effort will be spent in future to update Vite, but in the meantime, we just need to get Storybook running again.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1567)
**Preflight**
=> deps: Pin Vite@4.4.7 as it's the last known working Storybook

.changeset/poor-dots-juggle.md, packages/react/src/icon/__snapshots__/Icon.test.tsx.snap, packages/react/src/icon/utils.tsx
`CalendarIcon` was missing from the list of all icons that gets shown in the docs and storybook.
Also ordered them the same as they're rendered.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1570)
**Preflight**
**Testing**
=> icon: Add CalendarIcon to list of all icons.

.changeset/nice-peaches-press.md, packages/react/src/section-alert/SectionAlertDismissButton.tsx, packages/react/src/section-alert/__snapshots__/SectionAlert.test.tsx.snap
Changed SectionAlert "Dismiss" button text to say "Close" instead. This was to align with Global Alert and Modal.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1575)
**Preflight**
=> section-alert: replace "Dismiss" with "Close"

docs/content/updates/2024-03-19.mdx
AgDS Beta v1.20.0 release notes.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1587)
=> Release notes v1.20.0

.changeset/silver-ravens-confess.md, packages/react/src/grouped-fields/docs/overview.mdx
The grouped fields docs didn't allow the selects to change, and the options were incorrect.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1592)
**Preflight**
=> docs: grouped-fields - Update select options. Allow appropriate ones to be changed

.changeset/yellow-snakes-eat.md, packages/react/src/status-badge/StatusBadge.tsx, packages/react/src/status-badge/__snapshots__/StatusBadge.test.tsx.snap
In the enhancements of https://github.com/agriculturegovau/agds-next/pull/1579/, subtle appearance status badges were incorrectly given the `body` background color, which made them visible in zebra striped tables etc.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1601)
**Preflight**
**Testing**
=> status-badge: Remove background colour for subtle appearance

.changeset/lazy-cherries-greet.md, packages/react/src/time-input/docs/overview.mdx, packages/react/src/time-picker/docs/overview.mdx
The Figma links were broken after the revert.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1664)
=> time-input, time-picker: Fix Figma links

.changeset/metal-cheetahs-roll.md, docs/components/ComponentPropsTable.tsx, packages/react/src/box/styles.ts
None of the props in Box were documented. This fixes that for website and TypeScript users.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1670/components/box/code)
**Preflight**
=> box: Document all style props

.changeset/stale-baboons-allow.md, packages/react/src/table/docs/overview.mdx
The header cells should have been right-aligned
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1671)
**Preflight**
=> table: Fix example header alignment

.changeset/five-melons-tease.md, packages/react/src/task-list/TaskList.tsx, packages/react/src/task-list/docs/overview.mdx
`doneRecently` was counting towards the `stepsCompleted` count. Whoops!
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1673)
**Preflight**
**Testing**
=> task-list: Make `doneRecently` status count towards `stepsCompleted`

.changeset/breezy-rockets-agree.md, packages/react/src/table/TableRow.tsx, packages/react/src/table/__snapshots__/Table.test.tsx.snap, packages/react/src/table/__snapshots__/TableHeaderSortable.test.tsx.snap, packages/react/src/table/docs/overview.mdx
Introducing `hasRowError` prop to enable a visual indicator via background colour for table rows containing an error. Updated the docs with an example and direction to incorporate a section alert.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1672)
**Preflight**
**Testing**
=> table-row: Allow error background indicator

.changeset/wet-windows-shout.md, docs/components/LinkComponent.tsx, packages/react/src/box/styles.ts, packages/react/src/button/Button.tsx, packages/react/src/button/docs/overview.mdx, packages/react/src/button/styles.ts
This PR adds the `focusRingFor` prop to the `Button` component on the back of its establishment in the [custom element focus on close work recently completed in the Drawer](https://github.com/agriculturegovau/agds-next/pull/1669). This allows programmatic focusing via `.focus()`, and links, to render the focus ring. Our current use-case is for when a `SectionAlert` drives focus to a table with an action column full of the same named buttons.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1675)
**Preflight**
**Testing**
=> button: Add focusRingFor prop to Button component

.changeset/selfish-bobcats-decide.md, packages/react/src/app-layout/AppLayoutSidebarNav.tsx
Fixes a bug where the sidebar does not close on mobile when a nav item (link or button) is pressed.
Video of closing on press now working:
https://github.com/agriculturegovau/agds-next/assets/43688949/a96d5bf1-17e2-4a11-be28-6d568f62c20c
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1677)
**Preflight**
**Testing**
=> app-layout: Fix app layout mobile side bar not closing on press of nav item

.changeset/smart-peas-wash.md, .storybook/components/PageTemplate.tsx, docs/.env.production, example-site/components/SiteFooter.tsx, packages/react/src/app-layout/AppLayout.stories.tsx, packages/react/src/app-layout/AppLayoutFooter.stories.tsx, packages/react/src/text-link/docs/overview.mdx
This fixes broken production Playroom links such as this one from Drawer:
https://design-system.agriculture.gov.au/playroom/index.html/#?code=N4Igxg9gJgpiBcIA8AxANjAHgAgOYEMAHAXmAEYBfbAMw0wBEBLAJxjABdGIA7YgHRDMIAdwEA+Ptz7tUdSdOm0sTVhy68BkNAFcAtlJDz2iugHEhw0pSPTC+DO3Yx+INI1wALY4anH2dqChGblwrCht2ACN8MABrXCFtbigXSOgATwEjCV9pJABhfGYobABnD3woEWwwNzj8SIwchT8CoqgASW5uGGZmvxakAGV2GNi8IjD+lsGACRhK4NxsfFKXDwBmAWx2dMJnAQ8AFnEImdbC4oAZYPGPVmoXAGJxS5K3blikAHo3m8-pgNWt95osQoDzkgACpYdgQoHSK4QVi6bCMQilPTYKpoZFlRjsFa6GDsAA0NR4pTYTnY2mYKyChEYpTAS2wMDc7AAdNh8sxVthuDwzgj2NRgoxItpStgMBAuSLBt8YZg4YqZN8RmN4T83l0en0Irr2v0fugsKbzZgIkoGCxqeoXFo9AYbWYLGEInYHE4XFAirEsrl-JUgiFPcHonEEhAkikBGkoJkfNJAW1ijU6rEGk0RenOt1evC8lq4hMSOQKMXWqCw8tVustiAdnsDiBjqdg+c8n9bth7jBHgIXiAxG9ZbdjddbtW8iCFnXZzIVWqu6KkSi0RisTi8aUCUSSeTINwqRw …
=> docs: Fix playroom links returning 404

.changeset/four-rats-hear.md, packages/react/src/summary-list/SummaryList.tsx, packages/react/src/summary-list/__snapshots__/SummaryList.test.tsx.snap
Adds extra gap for clearer separation between term and description.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1678)
**Preflight**
**Testing**
=> summary-list: increase horizontal gap in list item

.changeset/smart-fireants-sniff.md, packages/react/src/box/styles.ts, packages/react/src/drawer/docs/overview.mdx
Fixes an omission from the docs for Drawer's `elementToFocusOnClose` that prevented focus being returned to the trigger button when there was no alert to focus. Also cleaned up a typo in a JSDoc from Box.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1681)
**Preflight**
**Testing**
=> drawer: fix elementToFocusOnClose docs

.changeset/purple-geese-raise.md, packages/react/src/combobox/ComboboxBase/ComboboxMultiBase.tsx
This PR turns off `downshift`'s `preventKeyAction` in order to allow deleting a selected item on press of backspace. As a byproduct, it allows navigating from the menu to the input without pressing "escape".
[More detail in the downshift docs](https://www.downshift-js.com/use-multiple-selection/#props-used-in-examples)
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1690)
**Preflight**
**Testing**
=> combobox-multi: Allow backspace to remove selected items when the popover is open

.changeset/blue-oranges-allow.md, packages/react/src/footer/Footer.stories.tsx, packages/react/src/footer/Footer.tsx, packages/react/src/footer/FooterDivider.tsx, packages/react/src/footer/__snapshots__/Footer.test.tsx.snap, packages/react/src/footer/docs/code.mdx, packages/react/src/main-nav/MainNav.tsx, packages/react/src/main-nav/MainNavBottomBar.tsx, packages/react/src/main-nav/MainNavContainer.tsx
We recently added palette and borderColor support to AppLayout, but the standard MainNav and Footer also needs borderColor.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1694)
**Preflight**
**Testing**
=> footer, main-nav: Add borderColor props

.changeset/giant-books-raise.md, packages/react/src/table/TableHeaderSortable.tsx, packages/react/src/table/__snapshots__/TableHeaderSortable.test.tsx.snap, packages/react/src/table/docs/overview.mdx
This fixes `textAlign` which wasn't being respected in `TableHeaderSortable`
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1693)
**Preflight**
**Testing**
=> table: Fix textAlign support in TableHeaderSortable

.changeset/dirty-dryers-yawn.md, .changeset/sixty-swans-tie.md, .storybook/components/PageTemplate.tsx, docs/content/templates/__shared/SiteLayout.tsx, example-site/components/SiteHeader.tsx, packages/react/src/main-nav/MainNav.stories.tsx, packages/react/src/main-nav/MainNav.tsx, packages/react/src/main-nav/MainNavBottomBar.tsx, packages/react/src/main-nav/MainNavContainer.tsx, packages/react/src/main-nav/docs/code.mdx, packages/react/src/main-nav/docs/overview.mdx, yourgov/components/Layout/SiteLayout.tsx
`AppLayout` supports `focusMode`, as does Main nav in Figma, yet weirdly, `MainNav` in code required consumers to manually render either the main nav or the bottom bar depending on whether it should be in focus mode.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1698)
**Preflight**
**Testing**
=> main-nav: `Add focusMode` prop. Deprecate `MainNavBottomBar`.

.changeset/quiet-apricots-dance.md, packages/react/src/button/BaseButton.tsx, packages/react/src/drawer/Drawer.stories.tsx, packages/react/src/drawer/docs/overview.mdx
Associating a form's submit button with a form is typically done by nesting the button within the form. The main advantage of this is the common pattern of submitting a form by pressing "enter" when focused on a form input. The drawer's `action` prop and content composition prevents this nesting. This PR adds examples of how to create the association via the button's `form="<form-id>"` and `type="submit"` props.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1697)
**Preflight**
**Testing**
=> drawer: Add support for form tag

.changeset/metal-tables-smoke.md, packages/react/src/checkbox/Checkbox.stories.tsx, packages/react/src/checkbox/Checkbox.tsx, packages/react/src/control-group/ControlGroup.test.tsx, packages/react/src/control-group/ControlGroup.tsx, packages/react/src/control-group/ControlGroupProvider.tsx, packages/react/src/control-group/__snapshots__/ControlGroup.test.tsx.snap, packages/react/src/radio/Radio.stories.tsx, packages/react/src/radio/Radio.tsx
We discovered that Radios and Checkboxes didn't actually have a required state when used in a ControlGroup, and when used without, incorrectly set the `required` attribute instead of `aria-required` like all other form controls.
Also noticed that without state management, Radios in ControlGroups weren't related and didn't function correctly because they had no `name`. Checkboxes were the same, but it doesn't have a visible effect like Radios.
`name` is now auto-generated, but can be overridden at both the ControlGroup and Radio/Checkbox level (which you'd care about if sending the values in a classic server-side form post).
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1699)
**Preflight**
**Testing**
=> checbox, control-group, radio: Fix required. Add/fix name

.changeset/chilly-singers-sip.md, packages/react/src/main-nav/MainNavDialog.tsx, packages/react/src/main-nav/MainNavMenuButtons.tsx, packages/react/src/main-nav/__snapshots__/MainNav.test.tsx.snap, packages/react/src/main-nav/utils.ts, packages/react/src/modal/ModalDialog.tsx, packages/react/src/modal/__snapshots__/Modal.test.tsx.snap
The mobile nav menu button/dialog have a few issues:
1. The button's accessible label doesn't begin with what's on screen (Menu)
1. The dialog isn't labelled.
1. Both have an incorrect aria-controls to an element that doesn't exists
1. Both an incorrect aria-expanded attribute (it doesn't expand like a classic menu button)
1. Modal Close button is first in visual order but last in reading order.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1705)
**Preflight**
**Testing**
=> main-nav: Use correct ARIA in button & dialog

.changeset/shiny-pots-do.md, packages/react/src/main-nav/MainNavDialog.tsx, packages/react/src/main-nav/MainNavDialogNavList.tsx
In the mobile menu, if you were on the active page, pressing the link would not close the menu.
This PR fixes that, but only closes the menu if you press the active link and not always. I have done this, because, in dev, a route change is slow so I don't want to see the focus ring move to the button, and then move off it.
The route change is still announced when you press the same link, so a screen reader user is told they go to Components or whatever. The only weirdness is that when you are in a sub-page (like a component detail), the nav will close and then the route change will happen, but there's no way around that…?
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1706)
**Preflight**
**Testing**
=> main-nav: Fix mobile dialog menu not closing when you press the active link

.changeset/brown-suns-end.md, packages/react/src/app-layout/AppLayoutHeader.stories.tsx, packages/react/src/app-layout/AppLayoutHeader.tsx, packages/react/src/app-layout/AppLayoutHeaderBrand.tsx, packages/react/src/app-layout/__snapshots__/AppLayout.test.tsx.snap, packages/react/src/app-layout/docs/overview.mdx, packages/react/src/header/Header.tsx, packages/react/src/header/HeaderBrand.tsx
Matching the co-branding (second href, second logo) implementation from the `Header` component. This one is slightly different so as to fit the structure + styles of the app layout. Also fixed a bug I noticed on the `Header` where a `calc` wasn't working.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1704)
---
**AppLayoutHeader**
Desktop:
Tablet:
Mobile:
---
**Header bug** (gap after second logo in first image, divider visible on wrapping in second image)
Before:
After:
---
**Preflight**
**Testing**
=> app-layout-header: Add co-branding

.changeset/few-brooms-hide.md, packages/react/src/progress-indicator/docs/overview.mdx, packages/react/src/side-nav/SideNav.stories.tsx, packages/react/src/side-nav/SideNav.test.tsx, packages/react/src/side-nav/SideNav.tsx, packages/react/src/side-nav/SideNavGroup.tsx, packages/react/src/side-nav/SideNavLink.tsx, packages/react/src/side-nav/SideNavLinkList.tsx, packages/react/src/side-nav/SideNavListItem.tsx, packages/react/src/side-nav/SideNavUnorderedList.tsx, packages/react/src/side-nav/__snapshots__/SideNav.test.tsx.snap, packages/react/src/side-nav/docs/overview.mdx, packages/react/src/side-nav/test-utils.ts, packages/react/src/side-nav/utils.test.ts, packages/react/src/side-nav/utils.ts
Adding a new variant for nested items that only opens one nested list at a time, the currently active one. This is designed to be the new default (current default keeps all items open), though this may need to be reverted, pending discussion. Additionally, only revealing nested items after navigating could be inaccessible to users who are never made aware of this pattern and contextual change.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1702)
**Preflight**
**Testing**
=> side-nav: new variants for nested items

.changeset/friendly-jobs-float.md, packages/react/src/date-picker/DatePicker.stories.tsx, packages/react/src/date-picker/DatePicker.test.tsx, packages/react/src/date-picker/DatePicker.tsx, packages/react/src/date-picker/docs/overview.mdx, packages/react/src/date-picker/utils.test.ts, packages/react/src/date-picker/utils.ts, packages/react/src/date-range-picker/DateRangePicker.stories.tsx, packages/react/src/date-range-picker/DateRangePicker.test.tsx, packages/react/src/date-range-picker/DateRangePicker.tsx, packages/react/src/date-range-picker/docs/overview.mdx, packages/react/src/date-range-picker/utils.test.ts, packages/react/src/date-range-picker/utils.ts
Some consumers of the date pickers complained that their apps which only wanted AU date support were causing confusion for users when they accidentally entered an invalid AU date, but a valid US one, and thus formatting to US.
The solution was to add an `allowedDateFormats` prop so consumers can customise which they support.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1708)
**Preflight**
**Testing**
=> date-picker: Add allowedDateFormats prop

.changeset/real-pets-sort.md, .storybook/stories/DataFiltering/components/DataTable.tsx, .storybook/stories/DataFiltering/components/DataTableRow.tsx, .storybook/stories/KitchenSink/KitchenSink.stories.tsx, docs/content/patterns/multi-task-form/index.mdx, docs/content/templates/content/ContentWithSideNav.tsx, docs/content/templates/multi-page-form/MultiPageFormStep.tsx, docs/content/templates/multi-page-form/MultiPageFormSummary.tsx, example-site/components/FormExampleMultiStep/FormExampleMultiStep.tsx, example-site/components/FormStepTitle.tsx, packages/react/src/button/Button.stories.tsx, packages/react/src/card/Card.stories.tsx, packages/react/src/drawer/Drawer.stories.tsx, packages/react/src/global-alert/GlobalAlert.stories.tsx, packages/react/src/page-alert/PageAlert.stories.tsx, packages/react/src/section-alert/SectionAlert.stories.tsx, packages/react/src/table/Table.stories.tsx, yourgov/components/FormMobileFoodVendorPermit/FormTask1Step1ChangeDetails.tsx, yourgov/components/FormRegisterPetPersonalDetails/FormRegisterPetPersonalDetailsStep0.tsx, yourgov/components/FormRegisterPetPersonalDetails/FormRegisterPetPersonalDetailsStep1.tsx, yourgov/components/FormStepTitle.tsx
There have been quite a few deprecations of props etc recently, but many examples weren't updated.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1721)
**Preflight**
**Testing**
=> Update deprecated component and prop uses through examples

.changeset/neat-months-hang.md, example-site/pages/audit/app-layout.tsx, example-site/pages/audit/checkbox.tsx, example-site/pages/audit/date-picker.tsx, example-site/pages/audit/date-range-picker.tsx, example-site/pages/audit/details.tsx, example-site/pages/audit/dropdown-menu.tsx, example-site/pages/audit/file-upload.tsx, example-site/pages/audit/filter-sidebar.tsx, example-site/pages/audit/pagination.tsx, example-site/pages/audit/progress-indicator.tsx, example-site/pages/audit/side-nav.tsx, example-site/pages/audit/table.tsx
This adds all of the redirects for the audit urls. They will work after all PRs are merged to the audit-2024 branch.
An example url: https://design-system.agriculture.gov.au/pr-preview/pr-1722/example-site/audit/app-layout
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1722)
**Preflight**
**Testing**
=> Audit: Temporary audit redirects

.changeset/chatty-mugs-bathe.md, docs/playroom/snippets.ts
The snippet for one of the AppLayoutSidebar items didn't render the icon because it wasn't a link. Also made all the icons unique.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1738)
**Preflight**
**Testing**
=> playroom: Fix AppLayout boilerplate sidebar links & icons

.changeset/cold-spoons-drop.md, packages/react/src/table/TableScroller.tsx, packages/react/src/table/__snapshots__/Table.test.tsx.snap
Various things were raised about scrolling tables in the a11y audit:
1. Non-scrolling tables shouldn't have a tabstop
2. Scrolling tables should be announced as a labelled region
3. Scrollbar border didn't have enough contrast
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1744)
**Preflight**
**Testing**
=> table: TableScroller a11y fixes

.changeset/tidy-swans-argue.md, docs/components/AllIconsPlayground.tsx
The audit reported that our list of icons in the docs wasn't correctly marked up as an `ol`.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1748)
**Preflight**
**Testing**
- [ x] Create or update documentation on the website
=> docs: Icons - markup as ordered list

.changeset/silly-games-drop.md, packages/react/src/tags/Tag.tsx, packages/react/src/tags/__snapshots__/Tags.test.tsx.snap
The audit highlighted that our removable tag touch target was too small and they need to be 24 x 24.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1750)
**Preflight**
**Testing**
=> tags: Make remove button hit target 24x24

.changeset/silent-radios-hug.md, packages/react/src/table/TableHeaderSortable.tsx, packages/react/src/table/__snapshots__/TableHeaderSortable.test.tsx.snap
table: Add `display` support to `TableHeaderSortable`.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1732)
**Preflight**
**Testing**
=> table: Add `display` support to `TableHeaderSortable`.

.changeset/chatty-pumpkins-flash.md, packages/react/src/_collapsing-side-bar/CollapsingSideBar.tsx, packages/react/src/_collapsing-side-bar/__snapshots__/CollapsingSideBar.test.tsx.snap, packages/react/src/filter-sidebar/FilterSidebar.tsx, packages/react/src/filter-sidebar/__snapshots__/FilterSidebar.test.tsx.snap, packages/react/src/progress-indicator/__snapshots__/ProgressIndicator.test.tsx.snap, packages/react/src/side-nav/SideNav.test.tsx, packages/react/src/side-nav/SideNav.tsx, packages/react/src/side-nav/__snapshots__/SideNav.test.tsx.snap, packages/react/src/side-nav/utils.ts
The a11y audit found the the components that used collapsing sidebar were very verbose in their descriptions of the collapsible versions. This makes it so much better.
Recommendations:
* Remove the “(Expand/Collapse)" text from the button's aria-label. The expanded/collapsed state is already being communicated via the aria-expanded attribute.
* Consider removing the <section> landmark. The side nav region is already adequately identified via the heading and label for the <nav> landmark.
* Alternatively, name the <nav> by what type of navigation it is, e.g. Sub-categories or In-page navigation, rather than by the name of the page or section it belongs to.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1762)
**Preflight**
**Testing**
=> collapsing-sidebar: Reduce verbosity of collapsible announcements for screen readers

.changeset/thin-forks-own.md, packages/react/src/details/Details.tsx, packages/react/src/details/__snapshots__/Details.test.tsx.snap
The expanded state of the `<summary>` element in our `Details` component on iOS was not being announced due to it being an inline element. This PR moves back to a block level element with updated CSS approach, `fit-content`.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1773)
**Preflight**
**Testing**
=> details: Fix iOS VO announcement of expanded state

.changeset/calm-cougars-scream.md, packages/react/src/checkbox/CheckboxInput.tsx, packages/react/src/checkbox/__snapshots__/Checkbox.test.tsx.snap, packages/react/src/control-group/__snapshots__/ControlGroup.test.tsx.snap, packages/react/src/field/useScrollToField.ts, packages/react/src/password-input/__snapshots__/PasswordInput.test.tsx.snap, packages/react/src/radio/RadioInput.tsx, packages/react/src/radio/__snapshots__/Radio.test.tsx.snap
radios and checkboxes didn't display focus rings when focused programatically. Since all other form inputs display focus rings always, radios and checkboxes should to.
The programmatic focusing also didn't work because react hook form doesn't actually give us a reference to the radio/checkbox ids
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1743)
**Preflight**
**Testing**
=> checkbox radio: Use :focus for focus rings

.changeset/thin-colts-appear.md, packages/react/src/combobox/ComboboxBase/ComboboxListError.tsx, packages/react/src/combobox/ComboboxBase/ComboboxListLoading.tsx, packages/react/src/time-picker/__snapshots__/TimePicker.test.tsx.snap
The audit found that we weren't announcing the loading and error states, and to do this with `role="status"`
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1746)
**Preflight**
**Testing**
=> combobox: Announce loading and error states to screen readers

.changeset/smart-gifts-bathe.md, packages/react/src/date-picker/__snapshots__/Calendar.test.tsx.snap, packages/react/src/date-picker/reactDayPickerStyles.ts
The accessibility audit found that the selected, hover and today's date weren't visible in WHCM or `forced-colors: active`
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1747)
**Preflight**
**Testing**
=> date-picker: Make hover, selected and today cells visible in high contrast mode

.changeset/nervous-kangaroos-admire.md, jest.config.js, jest.setup.js, packages/react/src/combobox/Combobox.test.tsx, packages/react/src/combobox/ComboboxAsyncMulti.test.tsx, packages/react/src/combobox/ComboboxBase/ComboboxBase.tsx, packages/react/src/combobox/ComboboxBase/ComboboxListItem.tsx, packages/react/src/combobox/ComboboxBase/ComboboxMultiBase.tsx, packages/react/src/combobox/ComboboxRenderItem.tsx, packages/react/src/combobox/utils.test.ts, packages/react/src/combobox/utils.ts, packages/react/src/time-picker/__snapshots__/TimePicker.test.tsx.snap
The a11y audit and our own testing found:
1. The options were being announced as indivdual letters in iOS VoiceOver.
2. The options weren't reachable at all in Android TalkBack
3. The Done button on the iOS keyboard should not close the dropdown
4. We could further improve perf by using case-insensitive attribute selectors
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1783)
**Preflight**
**Testing**
=> combobox: iOS a11y & UX fixes

.changeset/quiet-chairs-lick.md, docs/content/templates/multi-page-form/MultiPageFormSuccess.tsx, docs/content/templates/single-page-form/SinglePageFormSuccess.tsx, docs/content/templates/single-page-form/index.mdx, example-site/pages/category/subcategory/multi-page-form/success.tsx, example-site/pages/category/subcategory/single-page-form-success.tsx, packages/react/src/badge/docs/overview.mdx, packages/react/src/control-input/docs/overview.mdx, packages/react/src/filter-drawer/docs/overview.mdx, packages/react/src/global-alert/docs/overview.mdx, packages/react/src/page-alert/PageAlert.stories.tsx, packages/react/src/page-alert/PageAlert.test.tsx, packages/react/src/page-alert/PageAlertTitle.tsx, packages/react/src/page-alert/__snapshots__/PageAlert.test.tsx.snap, packages/react/src/page-alert/docs/overview.mdx, packages/react/src/section-alert/docs/overview.mdx, yourgov/components/FormMobileFoodVendorPermit/FormTask1Step3.tsx, yourgov/components/FormMobileFoodVendorPermit/FormTask1Step5.tsx
The a11y audit highlighted that PageAlert should be used after the H1, but it's heading by default was an H2. This PR updates that so we only need to use the simple `title` throughout.
They also told us that we need to managed user's focus when all alerts are dismissed, but I questioned that, and they are happy with a paragraph describing the importance of focus management.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1793)
**Preflight**
**Testing**
=> page-alert: Make title default to H2 instead of H3. Add focus docs

.changeset/heavy-elephants-swim.md, docs/content/patterns/focus-mode/index.mdx
=> DAFF-131 focus mode content changes

.changeset/blue-shirts-push.md, docs/content/patterns/search-filters/index.mdx
The a11y audit highlighted that our example should have been using an H2 for the search results heading
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1800)
**Preflight**
**Testing**
=> docs - patterns: Fix heading hierarchy in Search filters page

.changeset/heavy-sheep-visit.md, .storybook/stories/DataFiltering/components/DashboardPagination.tsx, packages/react/src/pagination/Pagination.tsx, packages/react/src/pagination/PaginationButtons.tsx, packages/react/src/pagination/PaginationItemPage.tsx, packages/react/src/pagination/usePagination.ts
Fix the focus issues when the "Previous" button is added/removed. When the "Previous" button is pressed and the component unmounts it we return focus to the `1` button rather than leaving the focus stranded. This is only for the buttons version of Pagination as the links version focus management should be handled by consuming apps.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1804)
**Preflight**
**Testing**
=> pagination: fix focus not returning to correct button when Previous button is added/removed

.changeset/eleven-pugs-search.md, docs/content/content/content-styles.mdx, docs/content/guides/how-to-write-guidance/how-to-present-guidance.mdx
The a11y audit complained that we had uncontrolled checkboxes and radio buttons that didn't function because their `checked` prop was hardcoded.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1797)
**Preflight**
**Testing**
=> content: Make uncontrolled checkboxes & radio buttons function

.changeset/rude-cobras-suffer.md, .storybook/stories/DataFiltering/ListFiltering.tsx, .storybook/stories/DataFiltering/components/DataTable.tsx, docs/content/patterns/search-filters/index.mdx, packages/react/src/pagination/Pagination.tsx, packages/react/src/pagination/PaginationButtons.tsx, packages/react/src/pagination/utils.test.ts, packages/react/src/pagination/utils.ts
The a11y audit highlighted that we weren't announcing changes from filters etc.
This PR:
1. Announces pangination's `itemRangeText` to screen readers.
2. Also announces "Audits loading" text for storybook examples
3. Updates the search filter pattern to use `role="status"` on the heading since it has no `itemRangeText`
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1809)
**Preflight**
**Testing**
=> pagination/filters: Announce changes to screen readers

.changeset/good-penguins-breathe.md, packages/react/src/callout/docs/overview.mdx
Add the title section to Callout
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1811)
**Preflight**
**Testing**
=> callout: Add title section with link to semantic headings

.changeset/large-bottles-explode.md, packages/react/src/prose/Prose.tsx
I noticed that Prose restricted paragraphs, but didn't restrict lists. Since markdown doesn't produce paragraphs in list
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1824)
**Preflight**
**Testing**
=> prose: Apply bodyText maxWidth token to lists.

.changeset/loud-suns-notice.md, docs/components/designSystemComponents.tsx, packages/react/src/tags/Tag.tsx, packages/react/src/tags/Tags.tsx, packages/react/src/tags/TagsContainer.tsx, packages/react/src/tags/docs/overview.mdx
The a11y audit found that we should manage focus when removing tags.
**Preflight**
**Testing**
=> tags: focus management of removed tags. Improve docs

.changeset/tall-toys-kneel.md, .storybook/stories/DataFiltering/components/FilterSearchInput.tsx, docs/content/patterns/search-filters/index.mdx, packages/react/src/search-input/docs/overview.mdx
The a11y audit recommended that we wrap search inputs in a landmark
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1812)
**Preflight**
**Testing**
=> search-input: Improve guidance/examples to include a search landmark

.changeset/fluffy-beers-roll.md, packages/react/src/table/docs/overview.mdx
The a11y audit wanted changes and fixes to our docs.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1828)
**Preflight**
=> table: Improve usage guidance in docs

.changeset/two-colts-kick.md, packages/react/src/app-layout/AppLayoutHeaderNav.tsx, packages/react/src/main-nav/MainNav.tsx, packages/react/src/main-nav/MainNavContainer.tsx, packages/react/src/main-nav/MainNavMenuButtons.tsx
The a11y audit (incorrectly) told us to set the mobile menu button to `aria-expanded="true"` even though a user can never get to or hear it.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1836)
**Preflight**
**Testing**
=> app-layout, main-nav: Set aria-expanded to mobile menu's state

.changeset/brown-ways-speak.md, packages/react/src/button/styles.ts, packages/react/src/checkbox/CheckboxIndicator.tsx, packages/react/src/columns/docs/overview.mdx, packages/react/src/control-group/__snapshots__/ControlGroup.test.tsx.snap, packages/react/src/date-picker/__snapshots__/DatePicker.test.tsx.snap, packages/react/src/date-range-picker/__snapshots__/DateRangePicker.test.tsx.snap, packages/react/src/drawer/DrawerDialog.tsx, packages/react/src/drawer/__snapshots__/Drawer.test.tsx.snap, packages/react/src/dropdown-menu/__snapshots__/DropdownMenu.test.tsx.snap, packages/react/src/file-input/__snapshots__/FileInput.test.tsx.snap, packages/react/src/file-upload/__snapshots__/FileUpload.test.tsx.snap, packages/react/src/global-alert/GlobalAlert.tsx, packages/react/src/global-alert/__snapshots__/GlobalAlert.test.tsx.snap, packages/react/src/modal/ModalDialog.tsx, packages/react/src/modal/__snapshots__/Modal.test.tsx.snap, packages/react/src/notification-badge/NotificationBadge.tsx, packages/react/src/notification-badge/__snapshots__/NotificationBadge.test.tsx.snap, packages/react/src/progress-indicator/ProgressIndicatorItem.tsx, packages/react/src/progress-indicator/__snapshots__/ProgressIndicator.test.tsx.snap, packages/react/src/radio/RadioIndicator.tsx, packages/react/src/radio/__snapshots__/Radio.test.tsx.snap, packages/react/src/stack/docs/overview.mdx, packages/react/src/sub-nav/SubNavListItem.tsx, packages/react/src/sub-nav/__snapshots__/SubNav.test.tsx.snap, packages/react/src/tabs/TabButton.tsx, packages/react/src/tabs/__snapshots__/Tabs.test.tsx.snap
My testing in high contrast mode found multiple issues with various components
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1829)
Before:
**Preflight**
**Testing**
=> many: Improve appearance & experience for high contrast users

.changeset/selfish-ravens-rest.md, packages/react/src/core/utils/useFocus.ts, packages/react/src/modal/Modal.tsx, packages/react/src/modal/ModalDialog.tsx, yourgov/components/Staff/DataTable.tsx, yourgov/components/Staff/DataTableBatchActionsBar.tsx, yourgov/components/Staff/DataTableRow.tsx, yourgov/components/Staff/ModalConfirmChangeRole.tsx, yourgov/components/Staff/ModalConfirmPauseAccess.tsx, yourgov/components/Staff/ModalConfirmRemoveAccess.tsx, yourgov/components/Staff/StaffMembersTable.tsx, yourgov/pages/app/licences-and-permits/manage-existing/index.tsx
modal: Add `elementToFocusOnClose` prop to allow for manual focus management.
page-alert: Update `focusOnUpdate` to not focus on any falsey value.
section-alert: Update `focusOnUpdate` to not focus on any falsey value.
yourgov: Fix focus issues with Staff table.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1858)
**Preflight**
**Testing**
=> yourgov: Fix focus issues with Staff table

.changeset/thick-pans-give.md, yourgov/components/Staff/AccessRequestsTable/AccessRequestsTable.tsx, yourgov/components/Staff/AccessRequestsTable/ModalConfirmApproveAccess.tsx, yourgov/components/Staff/AccessRequestsTable/ModalConfirmRejectAccess.tsx, yourgov/components/Staff/StaffMembersTable.tsx
Works around the focus management issues in staff members and access requests tables.
Tested all scenarios in VO with Safari & Chrome, VO on iOS, NVDA in Edge and TalkBack on Android.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1865/yourgov)
**Preflight**
**Testing**
=> yourgov: Fix alert focus management in staff and access requests

.changeset/real-pets-argue.md, yourgov/components/Staff/AccessRequestsTable/AccessRequestsTable.tsx, yourgov/components/Staff/AccessRequestsTable/ModalConfirmApproveAccess.tsx, yourgov/components/Staff/AccessRequestsTable/ModalConfirmRejectAccess.tsx, yourgov/components/Staff/DataTable.tsx, yourgov/components/Staff/DataTableBatchActionsBar.tsx, yourgov/components/Staff/DataTableRow.tsx, yourgov/components/Staff/ModalConfirmChangeRole.tsx, yourgov/components/Staff/ModalConfirmPauseAccess.tsx, yourgov/components/Staff/ModalConfirmRemoveAccess.tsx, yourgov/components/Staff/StaffMembersTable.tsx
yourgov: Support focus management when cancelling staff & access modals
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1870/yourgov)
**Preflight**
**Testing**
=> yourgov: Fix focus when using staff/access modals

.changeset/happy-rabbits-wonder.md, yourgov/pages/_app.tsx
When the staff table loaded on mobile, everything was tiny. This fixes that
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1875)
**Preflight**
**Testing**
=> yourgov: Fix mobile by adding correct viewport meta tag

.changeset/great-snails-dress.md, packages/react/src/progress-indicator/ProgressIndicator.tsx
If a pathname matched the start of two separate steps, both would be the active step as indicated in the "Before" image below. This PR forces the check to be either an exact match or a sub-step, i.e. denoted with `'/'`.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1876)
**Before:**
**After:**
**Preflight**
**Testing**
=> progress-indicator: Only set active step when path matches exactly or has a sub-step

.changeset/tiny-emus-teach.md, packages/react/src/tags/Tag.tsx, packages/react/src/tags/__snapshots__/Tags.test.tsx.snap
It was flagged that tags should have the background set for when they're used in coloured components.
[Before](https://design-system.agriculture.gov.au/develop/playroom/#?code=N4Igxg9gJgpiBcIA8BlALgQzAawAQHMMAHAXmAEYBfAPgB0A7XXVGMNASwnoEEAbGAE5pcHNPxK0QAORgB3ERnwBnSSK4wJIWRgH129fJLqMmzACqKludmhgBbJWQDawXLwwAjGL3i5JAMQgIVUoAGlxXdy8fPxAAIR0Q8MjPb19JBIAvEIBdSlwAemMmJAKUVg4uPkE0YuY4iAAPXCgdbDqShuaPLGx8AQgAV3ooTQ9oAE9VIgwoKH18MioO0yQLZWtbB2cU6PSQQOCQXDCIt1SYjMTj09202Kzc-KKGU2YCrrrSz4ZX%2BqaWm0Vkgurgejh%2BkMRmNJtNZvMDEsaH83iw2JwePwhCIbOJJDJ5JhlKo0OpNNpdAsjCi3uZLDTaZt7I5gC5zntYockmcovcrgJuXdLvEMNkbnkGaYXiZUWUKhjqkJgR8ml8VY1jKV0L1jCBQlp2FA0AALJQIJwAVgA7AA2PJAA)
[After](https://design-system.agriculture.gov.au/pr-preview/pr-1879/playroom/#?code=N4Igxg9gJgpiBcIA8BlALgQzAawAQHMMAHAXmAEYBfAPgB0A7XXVGM …
=> tags: Set background to body

.changeset/six-poems-glow.md, packages/react/src/time-input/utils.test.ts, packages/react/src/time-input/utils.ts
We discovered that users tried to type "3 pm" which then incorrectly converted to "12:00 am". This fixes that.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1886)
**Preflight**
**Testing**
=> time-input: Handle am/pm when separated from times with a space

.changeset/kind-mayflies-suffer.md, docs/components/Code.tsx
The audit suggested that we add a unique label to live code editors
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1881)
**Preflight**
**Testing**
=> docs: Add role & unique aria-label to live code editors

.changeset/five-toys-change.md, packages/react/src/field/FieldLabel.tsx, packages/react/src/field/useSecondaryLabel.tsx, packages/react/src/file-input/FileInput.tsx, packages/react/src/file-input/__snapshots__/FileInput.test.tsx.snap, packages/react/src/file-input/docs/overview.mdx, packages/react/src/file-upload/FileUpload.tsx, packages/react/src/file-upload/__snapshots__/FileUpload.test.tsx.snap
Optional file inputs and file uploads were not being announced
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1891)
**Preflight**
**Testing**
=> file-input, file-upload: Announce optional in button label

.changeset/polite-flowers-exist.md, packages/react/src/modal/Modal.tsx, packages/react/src/modal/ModalDialog.tsx
During yourgov development, we added an `elementToFocusOnClose` prop which did not prove useful. Removing it so we consumers don't get and we later have to deprecate it.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1894)
**Preflight**
**Testing**
=> modal: Remove `elementToFocusOnClose` prop.

.changeset/gentle-socks-impress.md, packages/react/src/icon/Icon.tsx, packages/react/src/section-alert/SectionAlert.test.tsx, packages/react/src/section-alert/SectionAlert.tsx, packages/react/src/section-alert/__snapshots__/SectionAlert.test.tsx.snap, packages/react/src/section-alert/docs/overview.mdx, packages/react/src/section-alert/utils.tsx
The audt and my testing found that focusing the alert wasn't announcing it in JAWS and iOS 16.7.10 & 18 something, instead it just announced the graphic.
This change makes the alert a region, so not only does it appear in the landmarks menu (which is important since there is no heading to jump to), it improves the announcements across all screen readers. JAWS still doesn't announce it on the default setting, but changing to "high" does.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1893)
**Preflight**
**Testing**
=> section-alert: Improve announcements across screen readers

.changeset/neat-toes-hang.md, docs/package.json, yarn.lock
Discovered that react-simple-code-editor has been unused since Feb 2022 https://github.com/agriculturegovau/agds-next/pull/65/files
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1906)
**Preflight**
=> docs: Remove unused react-simple-code-editor

.changeset/large-eels-push.md, packages/react/src/button/docs/overview.mdx
button: Add guidance about customising `loadingLabel`.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1915)
**Preflight**
**Testing**
=> button: Add guidance about customising `loadingLabel`

.changeset/itchy-coats-argue.md, packages/react/src/loading/LoadingBlanket.tsx, packages/react/src/loading/LoadingBlanketLabel.tsx
We discovered that the fullscreen LoadingBlanket wasn't being announced in JAWS and NVDA in yourgov and other implementations. Making it `role="alert"` fixes it in these and makes no difference to the others.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1916)
**Preflight**
**Testing**
=> loading: Announce fullscreen LoadingBlanket assertively

.changeset/twelve-gifts-destroy.md, yourgov/pages/app/dashboard/index.tsx, yourgov/pages/app/index.tsx
Re-orders the ABN so it's not after the important info that defines it.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1937)
**Preflight**
**Testing**
=> yourgov: Reorder ABNs to appear after headings & before digits

.changeset/tall-forks-flash.md, packages/react/src/date-picker-next/DatePickerNext.test.tsx, packages/react/src/date-picker/DatePicker.test.tsx, packages/react/src/date-range-picker-next/DateRangePickerNext.test.tsx, packages/react/src/date-range-picker/DateRangePicker.test.tsx
The existing tests for date-picker and date-range-picker were full of state warnings, and these carried across into the next versions of these components, too.
There were so many and it was annoying, so I fixed them.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1940)
**Preflight**
**Testing**
=> date-pickers: Fix all act/state warnings in tests

.changeset/hungry-maps-crash.md, yourgov/components/FormMobileFoodVendorPermit/steps/FormState.ts, yourgov/components/FormMobileFoodVendorPermit/steps/StepTradingTimeForm.tsx, yourgov/components/FormMobileFoodVendorPermit/steps/StepUploadDocumentsForm.tsx, yourgov/components/Staff/DashboardFilterDrawer.tsx, yourgov/lib/zodUtils.ts
Updates all error messaging to be "Label" is Verb (Required/Invalid etc)
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1948)
**Preflight**
**Testing**
=> yourgov: Update all error messages to X is Y

.changeset/fifty-mirrors-collect.md, packages/react/src/date-picker-next/DatePickerNext.tsx, packages/react/src/date-picker/DatePicker.tsx, packages/react/src/date-range-picker-next/DateRangePickerNext.tsx, packages/react/src/date-range-picker/DateRangePicker.tsx, packages/react/src/drawer/docs/overview.mdx, yourgov/components/FormMobileFoodVendorPermit/steps/StepUploadDocumentsForm.tsx
Discovered that all Date Pickers in Drawers closed the Drawer instead of the Calendar when pressing Escape.
Also allowing PDFs in Upload Documents in yourgov.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1949)
**Preflight**
**Testing**
=> date-pickers: Fix Escape keydown to not close parent Drawer

.changeset/gentle-games-hug.md, packages/react/src/file-upload/FileUpload.stories.tsx, packages/react/src/file-upload/FileUpload.test.tsx, packages/react/src/file-upload/FileUploadExistingFile.stories.tsx, packages/react/src/file-upload/FileUploadExistingFile.tsx, packages/react/src/file-upload/FileUploadExistingFileList.stories.tsx, packages/react/src/file-upload/FileUploadFile.tsx, packages/react/src/file-upload/__snapshots__/FileUpload.test.tsx.snap, packages/react/src/file-upload/docs/overview.mdx, packages/react/src/file-upload/test-utils.ts, packages/react/src/file-upload/utils.test.tsx, packages/react/src/file-upload/utils.tsx
A team needed the option to make existing files downloadable (using the `download` attribute).
Also found that placeholder.com no longer works, so updated these to a different service.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1950)
**Preflight**
**Testing**
=> file-upload: Add download support for uploaded and existing files

.changeset/many-vans-wonder.md, packages/react/src/app-layout/AppLayoutSidebarNav.tsx, packages/react/src/button/BaseButton.tsx, packages/react/src/core/CoreProvider.tsx, packages/react/src/dropdown-menu/DropdownMenuItem.tsx, packages/react/src/main-nav/MainNavList.tsx, packages/react/src/table/TableHeaderSortable.tsx, yourgov/pages/app/index.tsx
We had requests to add support for `onMouse*` events to various components. This adds them to base links, buttons and `TableHeaderSortable`.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1962)
**Preflight**
**Testing**
=> button, link, table: Add mouse event support.

.changeset/forty-hats-learn.md, packages/react/src/status-badge/StatusBadge.tsx, packages/react/src/status-badge/__snapshots__/StatusBadge.test.tsx.snap
The StatusBadge wasn't quite right:
1. The non-legacy icon shouldn't have been 22px wide
2. The paddingX should have been 12px
3. It created whitespace underneath the badge in certain circumstance, especially visible in table cells.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1958)
You can see the whitespace fix here: https://design-system.agriculture.gov.au/pr-preview/pr-1958/components/table#actions and all status badge examples here for comparison: https://design-system.agriculture.gov.au/pr-preview/pr-1958/components/status-badge#high-emphasis
**Preflight**
**Testing**
=> status-badge: Update to match design & remove unnecessary whitespace

.changeset/pink-jokes-matter.md, docs/content/patterns/search-filters/index.mdx
Fixed the Cards link address on the Doc page patterns -> search-filters. Link was directing to incorrect address
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1963)
[Patterns > Search filters page](https://design-system.agriculture.gov.au/pr-preview/pr-1963/patterns/search-filters)
**Preflight**
=> docs: fixed Card link address in patterns, search-filters

.changeset/calm-cats-yell.md, packages/react/src/accordion/Accordion.test.tsx, packages/react/src/autocomplete/Autocomplete.test.tsx, packages/react/src/combobox/Combobox.test.tsx, packages/react/src/combobox/ComboboxAsync.test.tsx, packages/react/src/combobox/ComboboxAsyncMulti.test.tsx, packages/react/src/combobox/ComboboxMulti.test.tsx, packages/react/src/drawer/Drawer.test.tsx, packages/react/src/dropdown-menu/DropdownMenu.test.tsx, packages/react/src/modal/Modal.test.tsx, packages/react/src/password-input/PasswordInput.test.tsx, packages/react/src/search-input/SearchInput.test.tsx, packages/react/src/side-nav/SideNav.test.tsx, packages/react/src/tabs/Tabs.test.tsx, packages/react/src/time-input/TimeInput.test.tsx, packages/react/src/time-picker/TimePicker.test.tsx
When running tests, many components produced noisy warnings like so:
```
Warning: An update to ForwardRef(SearchInput) inside a test was not wrapped in act(...).
When testing, code that causes React state updates should be wrapped into act(...):
act(() => {
/* fire events that update state */
});
/* assert on the output */
This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
```
This PR fixes that.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1956)
**Preflight**
**Testing**
=> chore: Fix all act/state warnings in tests

.changeset/rare-yaks-type.md, packages/react/src/drawer/DrawerDialog.tsx, packages/react/src/modal/Modal.tsx, packages/react/src/modal/ModalDialog.tsx
Ages ago we deprecated the `onDismiss` prop in Drawer in favour of `onClose`. For some reason, we kept the `onDimiss` logic within in the internal `DrawerDialog` even though it's not available to consumers and we pass it through as `onClose`
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1969)
**Preflight**
- [ x] Create a changeset file by running `yarn changeset`. [Learn more about change management](https://design-system.agriculture.gov.au/guides/change-management).
**Testing**
=> drawer, modal: Remove deprecated internal onDismiss props on dialogs

.changeset/six-jars-share.md, packages/react/src/core/packs.ts
Using kebab case cause hydration warnings to appear where used. Changed to cammel case.  No functional or style changes. Added `const` type for `print` to fix Typescript error.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1971)
**Preflight**
**Testing**
=> core: fix print exactColor hydration error with kebab case

.changeset/rare-masks-love.md, packages/react/src/getCloseHandler.ts, packages/react/src/page-alert/PageAlertTitle.tsx
Loads of our deprecation warnings were only happening in non-prod environments, but these ones weren't… so now they're consistent.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1974)
**Preflight**
**Testing**
=> Change various deprecation warnings to not appear in prod envs

.changeset/heavy-moose-marry.md, docs/pages/components/[slug]/index.tsx, docs/playroom/snippets.ts, packages/react/src/icon/__snapshots__/Icon.test.tsx.snap, packages/react/src/icon/icons/WarningIcon.tsx, packages/react/src/section-alert/SectionAlert.stories.tsx, packages/react/src/section-alert/SectionAlert.test.tsx, packages/react/src/section-alert/SectionAlert.tsx, packages/react/src/section-alert/__snapshots__/SectionAlert.test.tsx.snap, packages/react/src/section-alert/docs/content.mdx, packages/react/src/section-alert/docs/overview.mdx, packages/react/src/section-alert/utils.tsx, packages/react/src/status-badge/__snapshots__/StatusBadge.test.tsx.snap
Added the `info` level tone to the section-alert components. This build also add level variants (`high`, `medium` and `low`) for each tone.
Refactor the component to differentiate the tone selection with the various options of levels from icon, border, border width, icon, icon fill colour and background. The new levels have compatibility with legacy tones `success`, `warning` and `error` which will fallback to `successHigh`, `warningHigh` and `errorHigh`.
This PR also contains two fixes:
- docs: components table-of-contents has `relatedComponents` and `relatedPatterns` in wrong order, [live example](https://design-system.agriculture.gov.au/components/section-alert)
- icon: `WarningIcon` reverted to pre [live icon](https://design-system.agriculture.gov.au/foundations/icons) and [PR …
=> section-alert: add `info` tone and level variants to tone

.changeset/new-papayas-help.md, packages/react/src/file-upload/test-utils.ts, packages/react/src/file-upload/utils.test.tsx, packages/react/src/file-upload/utils.tsx
In 1.26 we added `download` support as a boolean, but it that attribute also supports strings which will download the file as the name in the string.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-2000)
**Preflight**
**Testing**
=> file-upload: Update the download type to also support strings

.changeset/clean-pens-talk.md, packages/react/src/checkbox/Checkbox.tsx, packages/react/src/checkbox/CheckboxIndicator.tsx, packages/react/src/checkbox/CheckboxInput.tsx, packages/react/src/checkbox/__snapshots__/Checkbox.test.tsx.snap, packages/react/src/control-group/__snapshots__/ControlGroup.test.tsx.snap, packages/react/src/password-input/__snapshots__/PasswordInput.test.tsx.snap, packages/react/src/radio/Radio.tsx, packages/react/src/radio/RadioIndicator.tsx, packages/react/src/radio/RadioInput.tsx, packages/react/src/radio/__snapshots__/Radio.test.tsx.snap
I noticed in yourgov that tabbing through the items in the staff table didn't scroll the checkbox back into view. The visually hidden styles were the cause, so I'm now hiding them behind the custom indicator.
Also realised that the screen reader virtual cursor wasn't indicative (or visible at all), so this fixes that too.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-2006)
[broken behaviour on main](https://design-system.agriculture.gov.au/playroom/#?code=N4Igxg9gJgpiBcIA8BlALgQzAawAQHMMAHAXmAEYBfAPgB0A7XXJKASwDdcBnNATwBsYZYLgDurKGgAW8XACYADAoA0uCOxgAnAGb8Io2bRBcwmiP35HVoqazQwURLDEMh6%2BzcSO5KNBkyYkAGEIejQzfgBxMwBXIjpGAMC2Th4BIWARcUkZXHIlBR8-RKTAoKkYHAAjCAAPXHYMfhihIyIpUJgjagAFDvoYJAB6csrsGtqE0oDgiuq6hqaWkiNMKsE0boAVDHWYNGHR%2Bcn-aeYj8YXG5taQfmI0CCJugBkHp8O5y5OS0tmx …
=> checkbox, radio: Fix scrolling into view when focused

.changeset/angry-owls-stare.md, .github/workflows/preview.yml
On the 15 of April, the Ubuntu image version we were using for the job `deploy-preview` was depreciated (v20.04). This PR changes the targeted version to `ubuntu-latest` to match `build-and-deploy` jobs.
[Reference Github runner ticket](https://github.com/actions/runner-images/issues/11101)
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-2007)
**Preflight**
=> github: update ubuntu image for deploy-preview

.changeset/silly-falcons-switch.md, docs/components/Code.tsx, docs/components/PictogramCard.tsx, docs/components/mdxComponents.tsx, docs/lib/mdx/packages.ts, docs/pages/components/[slug]/legacy.tsx, docs/playroom/snippets.ts, packages/react/src/accordion/Accordion.stories.tsx, packages/react/src/accordion/docs/overview.mdx, packages/react/src/button/docs/overview.mdx, packages/react/src/card/Card.stories.tsx, packages/react/src/card/Card.test.tsx, packages/react/src/card/Card.tsx, packages/react/src/card/CardFooter.tsx, packages/react/src/card/CardInner.tsx, packages/react/src/card/CardLink.tsx, packages/react/src/card/__snapshots__/Card.test.tsx.snap, packages/react/src/card/docs/legacy.mdx, packages/react/src/card/docs/overview.mdx, packages/react/src/prose/Prose.stories.tsx, packages/react/src/prose/docs/overview.mdx, packages/react/src/toggle-button/docs/overview.mdx
Teams need to be able to have footer card actions that sit outside of a standard clickable card.
To be able to achieve all of the various configurations, I ended up needing to create `footer` and `footerOutside` props. I also created a `header` prop to be consistent, but realised this was also required with various configurations to have `footerOutside`.
Doing this also highlighted that cards with footers didn't flex to fill their space and that the `CardLink` hit area and focus states were always applied to the full card even when `clickable` was `false` plus other bugs.
Please compare the focus, mouse over and visual states of the first 9 cards in the demos below.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1990)
[Playroom card …
=> card: Add header, footer & footerOutside props. Improve layouts

.changeset/spotty-readers-relax.md, packages/react/src/tags/Tag.tsx, packages/react/src/tags/__snapshots__/Tags.test.tsx.snap
We previously used `999` borderRadius, but when tag text wrapped, it scaled and looked super weird. This PR changes it to be 12px.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-2018)
**Preflight**
**Testing**
=> tag: Prevent border radius from scaling when tag label wraps

.changeset/tall-months-repair.md, docs/content/guides/custom-theme.mdx, docs/content/patterns/conditional-reveal/index.mdx, docs/content/patterns/selectable-table-with-batch-actions/index.mdx, packages/react/src/a11y/docs/overview.mdx, packages/react/src/conditional-field-container/docs/overview.mdx, packages/react/src/section-alert/SectionAlert.stories.tsx, yourgov/components/Staff/lib/getDisplayData.ts
While testing everything in React 19, I came across a few small errors.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-2021)
**Preflight**
**Testing**
=> docs: Fix various React and deprecation warnings throughout examples

.changeset/lucky-radios-behave.md, packages/react/src/button/Button.tsx, packages/react/src/button/__snapshots__/Button.test.tsx.snap, packages/react/src/button/docs/overview.mdx, packages/react/src/drawer/__snapshots__/Drawer.test.tsx.snap, packages/react/src/dropdown-menu/__snapshots__/DropdownMenu.test.tsx.snap, packages/react/src/file-upload/__snapshots__/FileUpload.test.tsx.snap, packages/react/src/global-alert/__snapshots__/GlobalAlert.test.tsx.snap, packages/react/src/modal/__snapshots__/Modal.test.tsx.snap, packages/react/src/page-alert/__snapshots__/PageAlert.test.tsx.snap, packages/react/src/section-alert/__snapshots__/SectionAlert.test.tsx.snap, packages/react/src/toggle-button/__snapshots__/ToggleButton.test.tsx.snap
When button's were `loading`, the dots overlapped any icons. We have decided to hide any icons when loading now.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-2028)
**Preflight**
**Testing**
=> button: Hide icons when loading

.changeset/lucky-bikes-buy.md, packages/react/src/app-layout/AppLayoutSidebarDialog.tsx, packages/react/src/core/utils/useIsMounted.ts, packages/react/src/drawer/Drawer.tsx
It was discovered that the Drawer changes to support React 19 caused hydration match issues when using Next's App Router. They do not surface in the pages router. Or is it a strict mode issue?
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-2035)
**Preflight**
**Testing**
=> app-layout, drawer: Fix hydration mismatch when using App Router

.changeset/khaki-balloons-brush.md, packages/react/src/combobox/utils.ts
After working on the hydration mismatch issue, I discovered that comboboxes removed those warnings. That didn't feel right, and it turned out it wasn't. The `useIsIos` hook shouldn't have been allowed to run in non-DOM environments (like the server), so it was causing re-rendering issues.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-2037)
**Preflight**
**Testing**
=> combobox: Prevent useIsIos from attempting to run on the server

.changeset/pink-cheetahs-report.md, packages/react/src/table/TableRow.test.tsx, packages/react/src/table/TableRow.tsx, packages/react/src/table/__snapshots__/TableRow.test.tsx.snap
There was a bug where if the `tableLayout` prop on `<Table>` component was not exactly `auto` or `fixed`, no hover styles would be applied. Change checking logic to default to `auto`. Additionally the hover mouse cursor was missing from the onHover row for fixed table styled.
There was a bug where clicking on a `<Checkbox>` component would fire the row event. This was because the `input` was not a parent of the clicked target. Added `label` to selection.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-2048)
**Preflight**
**Testing**
=> table: fix TableRow onHover not applying any styles, update onClick on TableRow when clicking Checkbox

.changeset/plenty-pens-perform.md, packages/react/src/core/Core.tsx, packages/react/src/core/CoreProvider.tsx, packages/react/src/core/boxPalette.ts, packages/react/src/core/index.ts, packages/react/src/core/packs.ts, packages/react/src/core/utils/fontGrid.ts, packages/react/src/core/utils/useAriaModalPolyfill.ts, packages/react/src/core/utils/useClickOutside.ts, packages/react/src/core/utils/useElementSize.ts, packages/react/src/core/utils/useFocus.ts, packages/react/src/core/utils/useId/useId.ts, packages/react/src/core/utils/useId/useIsomorphicLayoutEffect.ts, packages/react/src/core/utils/useIsMounted.ts, packages/react/src/core/utils/usePrefersReducedMotion.ts, packages/react/src/core/utils/useTernaryState.ts, packages/react/src/core/utils/useToggleState.ts, packages/react/src/core/utils/useTransitionHeight.ts, packages/react/src/core/utils/useWindowSize.ts
When adding things to the new starter kit, I discovered that any time you wanted to use `tokens`, it had to be a client component.
So, instead of adding 1 `'use client'` to main Core export, all of the files that need it have them added and are exported individually so the build works.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-2052)
**Preflight**
**Testing**
=> core: Apply use client directive to only the files that need it

.changeset/new-eyes-care.md, packages/react/src/summary-list/docs/overview.mdx, packages/react/src/table/docs/overview.mdx
A consumer had trouble locating where to import  the `VisuallyHidden` component, added in a comment to the code snippet and paragraph above with reference to `a11y`.
This PR also fixes a few lint errors and format in code snippets on the Table documentation page.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-2061)
[View preview Table](https://design-system.agriculture.gov.au/pr-preview/pr-2061/components/table)
[View preview Summary List](https://design-system.agriculture.gov.au/pr-preview/pr-2061/components/summary-list)
**Preflight**
=> docs: update summary-list and table documentation

.changeset/strange-lobsters-enjoy.md, docs/playroom/snippets.ts, packages/react/src/accordion/Accordion.stories.tsx, packages/react/src/accordion/Accordion.tsx, packages/react/src/accordion/AccordionBody.tsx, packages/react/src/accordion/AccordionTitle.tsx, packages/react/src/accordion/__snapshots__/Accordion.test.tsx.snap, packages/react/src/accordion/docs/overview.mdx
This adds an indent prop to inset the title and body content of accordions.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-2068)
**Preflight**
**Testing**
=> accordion: Add indent prop to apply horizontal padding to Accordion els

.changeset/wicked-grapes-hammer.md, yourgov/lib/useAuth.tsx, yourgov/lib/useLinkedBusinesses.tsx
To allow our new pattern demos to link to sections, set auth and the selected business by default. Login and logout still work should you want to use them and test those flows. Reloading the page would immediately log back in
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-2069/yourgov)
**Preflight**
**Testing**
=> yourgov: Bypass auth to allow navigating through the app

.changeset/few-apples-breathe.md, docs/content/patterns/conditional-reveal/index.mdx, packages/react/src/autocomplete/__snapshots__/Autocomplete.test.tsx.snap, packages/react/src/combobox/__snapshots__/Combobox.test.tsx.snap, packages/react/src/combobox/__snapshots__/ComboboxAsync.test.tsx.snap, packages/react/src/combobox/__snapshots__/ComboboxAsyncMulti.test.tsx.snap, packages/react/src/combobox/__snapshots__/ComboboxMulti.test.tsx.snap, packages/react/src/conditional-field-container/ConditionalFieldContainer.tsx, packages/react/src/conditional-field-container/__snapshots__/ConditionalFieldContainer.test.tsx.snap, packages/react/src/conditional-field-container/docs/overview.mdx, packages/react/src/control-group/__snapshots__/ControlGroup.test.tsx.snap, packages/react/src/field/FieldContainer.tsx, packages/react/src/field/__snapshots__/Field.test.tsx.snap, packages/react/src/fieldset/__snapshots__/Fieldset.test.tsx.snap, packages/react/src/file-input/__snapshots__/FileInput.test.tsx.snap, packages/react/src/file-upload/__snapshots__/FileUpload.test.tsx.snap, packages/react/src/grouped-fields/GroupedFields.tsx, packages/react/src/grouped-fields/__snapshots__/GroupedFields.test.tsx.snap, packages/react/src/password-input/__snapshots__/PasswordInput.test.tsx.snap, packages/react/src/search-input/__snapshots__/SearchInput.test.tsx.snap, packages/react/src/select/__snapshots__/Select.test.tsx.snap, packages/react/src/text-input/__snapshots__/TextInput.test.tsx.snap, packages/react/src/textarea/__snapshots__/Textarea.test.tsx.snap, packages/react/src/time-input/__snapshots__/TimeInput.test.tsx.snap, packages/react/src/time-picker/__snapshots__/TimePicker.test.tsx.snap
This changes the conditional field containe to use a thick left border instead of the a horizontal divider.
To support this, we now negatively offset any invalid fields within the CFC
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-2075)
**Preflight**
**Testing**
=> conditional-field-container: Update to use left border. Modify Field

.changeset/brown-moose-destroy.md, packages/react/src/drawer/DrawerDialog.tsx, packages/react/src/drawer/__snapshots__/Drawer.test.tsx.snap
I discovered that long Drawer content wasn't keyboard accessible, because it wasn't focusable. Had to add a label to it and inset the focus ring.
Also made Drawers consistent across breakpoints, so mobile now has a sticky footer.
We also had a bug where the title could overlap into the absolutely positioned Close button. The Close button is last in the DOM order, so have created a non-functioning clone in the title.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-2076)
**Preflight**
**Testing**
=> drawer: Make the content area keyboard-accessible

.changeset/dull-steaks-do.md, packages/react/src/app-layout/AppLayoutSidebarNav.test.tsx, packages/react/src/app-layout/AppLayoutSidebarNav.tsx, packages/react/src/app-layout/__snapshots__/AppLayout.test.tsx.snap, packages/react/src/app-layout/__snapshots__/AppLayoutSidebarNav.test.tsx.snap, packages/react/src/side-nav/SideNav.test.tsx, packages/react/src/side-nav/SideNavLink.tsx, packages/react/src/side-nav/SideNavLinkList.tsx, packages/react/src/side-nav/__snapshots__/SideNav.test.tsx.snap
Our a11y user testing found the announcements of our parent chevrons weird. They were on a different element, so could be reached twice, and the full stop would be read as "dot". NVDA was particularly annoying.
This PR changes them so that the SVG is hidden, and `aria-label` is used. This has the benefit of announcing the change to the label when you activate the link so users now know it's been expanded (tested in NVDA)
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-2072)
**Preflight**
**Testing**
=> app-layout, side-nav: Simplify announcements of parent links

.changeset/quiet-kids-help.md, packages/react/src/_collapsing-side-bar/CollapsingSideBar.tsx, packages/react/src/_collapsing-side-bar/__snapshots__/CollapsingSideBar.test.tsx.snap, packages/react/src/filter-sidebar/__snapshots__/FilterSidebar.test.tsx.snap, packages/react/src/progress-indicator/__snapshots__/ProgressIndicator.test.tsx.snap, packages/react/src/side-nav/__snapshots__/SideNav.test.tsx.snap
The Chevron on the `CollapsingSideBar` component had issues with the colour on a `dark` background. Updated the Chevron to match the `Accordion` component with `action` colour.
Affected components:
- filter-sidebar:
- [before](https://design-system.agriculture.gov.au/playroom/#?code=N4Igxg9gJgpiBcIA8AlGA7WAnAfAHXQAJjDgAKASkIF4dSCTC8AXLGZgVyyLIZJZZIAwhAA2HALboAzoQDmAQwAO1YMEIAPafEIBGADSEJUHQGZCAXwv4i-ZgObCxkopHFSAykoXpV6rTq6AEyGxjoALJbWfMQODkgAYgCWoswwWB5JsABGCliECmDMSQBuMMmp6dIiHOjMqqbRtrH2rfEJEFgSHsyFANY2jHFtrUgAKjAazACS6EoczITZohBgfYSiCtkwotR4IACiGgoSSqIwhElzC3r7hAD0g3bD8RNTs-OLy6vrm9u7%2ByOJzOFyun0IQTujxiTBGw3Gkxm1y%2BKzWGy2Oz2h2Op3Ol2RhFMUKeLReozeSPB3zRf0xgJxIPx4PCxJhZME9w6XR6-RJsPhnJSaQyWRguVwMMYUqlSAAQhANIQoHkBpLperGIkhelMjk8gUiqVytqsNUILV6sBGnz2Y4ud1emsbXCRgj3gTqb8MQDscC8WCbrpWc1%2B …
=> filter-sidebar, process-indicator, side-nav: update colour on chevron to `action`

.changeset/five-months-agree.md, docs/playroom/snippets.ts, packages/react/src/app-layout/AppLayout.test.tsx, packages/react/src/app-layout/__snapshots__/AppLayout.test.tsx.snap, packages/react/src/footer/Footer.test.tsx, packages/react/src/footer/__snapshots__/Footer.test.tsx.snap, packages/react/src/footer/docs/overview.mdx
Update copyright from year `2024` to `2025`. Only in docs and tests.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-2081)
**Preflight**
**Testing**
=> docs, footer, app-layout: update copyright from 2024 to 2025

.changeset/strange-turkeys-punch.md, packages/react/src/filter-sidebar/docs/overview.mdx
Expanded on existing content.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-1918)
**Preflight**
**Testing**
=> filter-sidebar: Enhanced documentation and guidance around mobile usage.

.changeset/young-penguins-press.md, packages/react/src/checkbox/CheckboxInput.tsx, packages/react/src/checkbox/__snapshots__/Checkbox.test.tsx.snap, packages/react/src/control-group/__snapshots__/ControlGroup.test.tsx.snap, packages/react/src/password-input/__snapshots__/PasswordInput.test.tsx.snap, packages/react/src/radio/RadioInput.tsx, packages/react/src/radio/__snapshots__/Radio.test.tsx.snap, packages/react/src/table/__snapshots__/TableRow.test.tsx.snap
The a11y fix for checkboxes in 1.27 accidentally added space beneath when they're not in Stacks etc.
Also added the same fix to radios to make them consistent, but they're never used that way anyway.
[View preview](https://design-system.agriculture.gov.au/pr-preview/pr-2084)
**Preflight**
**Testing**
=> checkbox: Remove space beneath when in the normal document flow
